### ISSUE TITLE
New error I've never received before

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1048]
2015-06-07 08:29:06 WARNING [Warning] ComicID: 80455 is incomplete - Removing from DB. You should try to re-add the series.
2015-06-07 08:28:50 ERROR   Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 451, in addComictoDB
shutil.copy(coverfile, comiclocal)
File "/usr/local/python/lib/python2.7/shutil.py", line 120, in copy
copymode(src, dst)
File "/usr/local/python/lib/python2.7/shutil.py", line 91, in copymode
os.chmod(dst, mode)
OSError: [Errno 1] Operation not permitted: '/volume1/Comics/Marvel/Princess Leia (2015)/cover.jpg'

**Comment by evilhero** [comment]
The user running mylar doesn't have the proper permissions to change the ownership of the cover file within the series directory for some reason (it has to have at least level 7, as in 775 - but odds are thr perms are 755)
