### ISSUE TITLE
SABNZBD - Issues stuck with error message below

### ISSUE THREAD

**Issue by markerstadt** [evilhero/mylar#1060]
"WAIT 23 SEC Trying to fetch NZB from http://0.0.0.0:8090/api
apikey=62cNOTIMPORTANT67&cmd=downloadNZB&nzbname=Wolverines.018.2015.c2c.Digi-Hybrid.TLK-EMPIRE-HD.nzb"

I apologize if this error has already been reported - I did read through "issues" and didn't see the same problem that I'm having.  This happened out of nowhere -- the apikey that it lists is not attached to anything that I use however it is the same error for every issue I have tried to download.  I'm using DOGnzb.

Any help would be greatly appreciated.  Thank you kindly.

**Comment by evilhero** [comment]
Probably similar to #1055 - try setting the mylar host address within the mylar configuration to the actual ip of the machine running mylar (instead of localhost).  If mylar and sabnzbd are on the same machine, setting it to 0.0.0.0 seems to work as well. Otherwise, different machines for sab and mylar means ip specification within mylar. 

Mylar uses an internal apikey that's not stored anywhere and is regenerated on each send. It internally sends the downloaded nzb to sab via this api.

**Comment by markerstadt** [comment]
That seems to have done the trick.  Thanks very much for your help.  Made my day!

**Comment by erickgrau** [comment]
I have a similar issue, but the IP address is 172.20.8.2 not 0.0.0.0

Help please - total n00b... So forgive any improper posts here.

**Comment by evilhero** [comment]
0.0.0.0 is used to tell mylar to listen to all network interfaces on the local machine. There's no need to put in the actual ip unless you have some unique configuration on your system.

**Comment by erickgrau** [comment]
Thanks for responding quickly evilhero - I originally had 0.0.0.0 then changed it to the LAN ip of 10.0.1.19... Either way I get the same message when Mylar snatches a comic from NZBgeek... Trying to fetch NZB from http://172.20.8.2:8090/api.....

I have Librarian, CouchPotato and SIckRage successfully talking to SABnzbd... For the life of me I can't figure out why it won't with Mylar.

Any help here would be appreciated...

Erick

**Comment by erickgrau** [comment]
Here are the debug logs:

2016-08-18 16:19:43	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1217, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 2296, in searcher
notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 2301, in notify_snatch
snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects
2016-08-18 16:19:42	INFO	setting the alternate nzbname for this download grabbed by https://api.nzbgeek.info/ (newznab) in the nzblog to : .Batman.003..2016...2.covers...Digital...Zone-Empire.
2016-08-18 16:19:42	INFO	setting the nzbid for this download grabbed by https://api.nzbgeek.info/ (newznab) in the nzblog to : 04b74a29a4be3c120bf187483a460103
2016-08-18 16:19:42	DEBUG	Found matching comic...preparing to send to Updater with IssueID: 540047 and nzbname: Batman.003.2016.2.covers.Digital.Zone-Empire [.Batman.003..2016...2.covers...Digital...Zone-Empire.]
2016-08-18 16:19:42	INFO	Successfully sent nzb file to SABnzbd
2016-08-18 16:19:42	DEBUG	Completed send-to-SAB link: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=http%3A%2F%2F172.20.8.2%3A8090%2Fapi%3Fapikey%3D4f5da58d991d619cac03fadca8b7e187%26cmd%3DdownloadNZB%26nzbname%3DBatman.003.2016.2.covers.Digital.Zone-Empire.nzb&priority=0&cat=comicbooks&script=ComicRN.py
2016-08-18 16:19:42	DEBUG	...attaching rename script: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=http%3A%2F%2F172.20.8.2%3A8090%2Fapi%3Fapikey%3D4f5da58d991d619cac03fadca8b7e187%26cmd%3DdownloadNZB%26nzbname%3DBatman.003.2016.2.covers.Digital.Zone-Empire.nzb&priority=0&cat=comicbooks&script=ComicRN.py
2016-08-18 16:19:42	DEBUG	...attaching category: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=http%3A%2F%2F172.20.8.2%3A8090%2Fapi%3Fapikey%3D4f5da58d991d619cac03fadca8b7e187%26cmd%3DdownloadNZB%26nzbname%3DBatman.003.2016.2.covers.Digital.Zone-Empire.nzb&priority=0&cat=comicbooks
2016-08-18 16:19:42	DEBUG	...setting priority: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=http%3A%2F%2F172.20.8.2%3A8090%2Fapi%3Fapikey%3D4f5da58d991d619cac03fadca8b7e187%26cmd%3DdownloadNZB%26nzbname%3DBatman.003.2016.2.covers.Digital.Zone-Empire.nzb&priority=0
2016-08-18 16:19:42	DEBUG	...attaching nzb via internal Mylar API: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=http%3A%2F%2F172.20.8.2%3A8090%2Fapi%3Fapikey%3D4f5da58d991d619cac03fadca8b7e187%26cmd%3DdownloadNZB%26nzbname%3DBatman.003.2016.2.covers.Digital.Zone-Empire.nzb
2016-08-18 16:19:42	DEBUG	...selecting API type: http://10.0.1.19:8080/api?apikey=0b5a80802149cdb870d8f9dc03d7bfcc&mode=addurl&name=
2016-08-18 16:19:42	DEBUG	send-to-SAB host &api initiation string : http://10.0.1.19:8080/api?apikey=xUDONTNEEDTOKNOWTHISx
2016-08-18 16:19:42	DEBUG	link given by: newznab
2016-08-18 16:19:42	INFO	Found Batman (None) issue: 3 using https://api.nzbgeek.info/ (newznab)
2016-08-18 16:19:42	DEBUG	issues match!
2016-08-18 16:19:42	DEBUG	[FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
2016-08-18 16:19:42	INFO	[FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2016-08-18 16:19:42	INFO	prov : https://api.nzbgeek.info/ (newznab)[04b74a29a4be3c120bf187483a460103]
2016-08-18 16:19:42	DEBUG	Successfully changed permissions [0777 / 0660]
2016-08-18 16:19:42	DEBUG	Cache Directory successfully found at : /usr/local/mylar/var/cache. Ensuring proper permissions.
2016-08-18 16:19:42	INFO	filen: .Batman.003..2016...2.covers...Digital...Zone-Empire. -- nzbname: Batman.003.2016.2.covers.Digital.Zone-Empire are not identical. Storing extra value as : .Batman.003..2016...2.covers...Digital...Zone-Empire.
2016-08-18 16:19:42	DEBUG	[FILENAME] end nzbname: .Batman.003..2016...2.covers...Digital...Zone-Empire..nzb
2016-08-18 16:19:42	DEBUG	[FILENAME] nzbname (\s): .Batman.003. 2016 . 2.covers . Digital . Zone-Empire .nzb
2016-08-18 16:19:42	DEBUG	[FILENAME] filename (remove chars): .Batman.003. 2016 . 2.covers . Digital . Zone-Empire .nzb
2016-08-18 16:19:41	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-18 16:19:41	DEBUG	comicid: 35257
2016-08-18 16:19:41	DEBUG	nzbprov: newznab
2016-08-18 16:19:41	DEBUG	RSS Check: None
2016-08-18 16:19:41	DEBUG	calpha/cnumber: None / None
2016-08-18 16:19:41	INFO	Shhh be very quiet...I'm looking for Batman-Grendel issue: 1 (2008) using drunkenslug.com (newznab)
2016-08-18 16:19:41	DEBUG	using Newznab host of : drunkenslug.com
2016-08-18 16:19:41	INFO	Alternate Search pattern detected...re-adjusting to : Batman-Grendel 2008
2016-08-18 16:19:40	INFO	Download URL: https://api.nzbgeek.info/api?apikey=eea5db8c7eccfb47e28762cf5978ccdb&t=get&id=04b74a29a4be3c120bf187483a460103 [VerifySSL:True]
2016-08-18 16:19:40	INFO	link : https://api.nzbgeek.info/getnzb/04b74a29a4be3c120bf187483a460103.nzb&i=&r=eea5db8c7eccfb47e28762cf5978ccdb
2016-08-18 16:19:40	INFO	newznab detected as : https://api.nzbgeek.info/ @ https://api.nzbgeek.info/
2016-08-18 16:19:40	INFO	fetched via newnzab. Retrying the send.
2016-08-18 16:19:40	INFO	--Referencing : newznab @ 2016-08-17 23:02:53
2016-08-18 16:19:40	INFO	Located snatched download:
2016-08-18 16:19:40	INFO	Retrying : 540047
2016-08-18 16:19:40	INFO	ComicID:91273
2016-08-18 16:19:39	DEBUG	[SSL: False] Search URL: http://drunkenslug.com/api?t=search&q=batman%20grendel%201&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-18 16:18:38	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-18 16:18:38	DEBUG	comicid: 35257
2016-08-18 16:18:38	DEBUG	nzbprov: newznab
2016-08-18 16:18:38	DEBUG	RSS Check: None
2016-08-18 16:18:38	DEBUG	[SSL: False] Search URL: http://drunkenslug.com/api?t=search&q=batman%20grendel%2001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-18 16:18:27	DEBUG	If you read this message, debug logging is available
2016-08-18 16:18:27	INFO	Verbose toggled, set to True
2016-08-18 16:18:26	INFO	Web logs cleared

**Comment by erickgrau** [comment]
![sabnzbd screenshot for mylar](https://cloud.githubusercontent.com/assets/12092672/17789307/b0c13efc-655f-11e6-8d8c-5f403d8bfe16.jpg)

**Comment by erickgrau** [comment]
Ok, I think I got somewhere.. That machine has a permanent VPN with NOT that IP address in the "Trying to fetch NZB..." But I found it in the logs:
Successfully discovered local IP and locking it in as : 172.20.8.2

I turned off the VPN and restarted Mylar...

Now it correctly captures its local IP BUT now I have another error...

 Empty NZB file api?apikey=533fbb271c0dd47ee283ede0141859e2&cmd=downloadNZB&nzbname=Batman.003.2016.2.covers.Digital.Zone-Empire.nzb.nzb [http://10.0.1.14:8090/api?apikey=533fbb271c0dd47ee283ede0141859e2&cmd=downloadNZB&nzbname=Batman.003.2016.2.covers.Digital.Zone-Empire.nzb]

Ideas?

**Comment by evilhero** [comment]
What's the 172.20.82.2 ip if theres a different LAN ip? 
Do mylar and sab reside on different machines? 

Depending in your answer, the simplest solution might be to probably make use of the host_return value in the config.ini. Make sure mylar isn't running, edit the config.ini and find the value for host_return and set it to the ip of the machine.

**Comment by erickgrau** [comment]
Yes both on Synology Boxes

10.0.1.14 is Mylar (DSM 5)
10.0.1.19 is SABnzbd (DSM 6 - wish I never upgraded that machine)

**Comment by evilhero** [comment]
OK so in the configuration GUI in the downloaded section for sabnzbd theres an option for different machines (this is necessary if you plan to use post-processing and the mylar has to be able to access the download directory on the sab machine). 

Set the mylar host to 0.0.0.0 and change the host_return value in the config.ini to host_return = http://10.0.1.14:8090/

It should then start to work

The notification error at the end though I'm just going to look into

**Comment by erickgrau** [comment]
Ok, let me terminal in and try to change that config... Restart and see.. I"ll report back

**Comment by erickgrau** [comment]
Ok,  I think that fixed it... It now shows up as the comic title in SABnzbd - its in the queue so I'll know if it actually downloads soon. 

THANKS!!!

Erick
