### ISSUE TITLE
Can't Add "Born Again" story arc

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1107]
I get this error on the screen:
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/xxx/Mylar/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Users/xxx/Mylar/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/xxx/Mylar/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/xxx/Mylar/mylar/mylar/webserve.py", line 446, in addStoryArc
    readingorder = int(re.sub('[\,\|]','', rosre).strip())
ValueError: invalid literal for int() with base 10: ''
```

And here is the log entry (no error there though):
```
15-Aug-2015 23:01:49 - DEBUG   :: CP Server Thread-6 : there are 8 search results...
15-Aug-2015 23:01:49 - DEBUG   :: CP Server Thread-6 : querying 0
15-Aug-2015 23:01:49 - DEBUG   :: CP Server Thread-6 : [STORY ARC] Arcresults: {'issuechoice': [{'Store_Date': '0000-00-00', 'Issue_Date': u'1986-02-01', 'ComicName': u'Daredevil', 'IssueID': u'26500', 'Issue_Name': u'Apocalypse', 'ArcID': u'55638', 'Issue_Number': u'227', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-03-01', 'ComicName': u'Daredevil', 'IssueID': u'26597', 'Issue_Name': u'Purgatory', 'ArcID': u'55638', 'Issue_Number': u'228', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-04-01', 'ComicName': u'Daredevil', 'IssueID': u'26695', 'Issue_Name': u'Pariah', 'ArcID': u'55638', 'Issue_Number': u'229', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-05-01', 'ComicName': u'Daredevil', 'IssueID': u'26789', 'Issue_Name': u'Born Again', 'ArcID': u'55638', 'Issue_Number': u'230', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-06-01', 'ComicName': u'The Amazing Spider-Man', 'IssueID': u'26884', 'Issue_Name': u'The Rules of the Game', 'ArcID': u'55638', 'Issue_Number': u'277', 'ComicID': u'2127'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-06-01', 'ComicName': u'Daredevil', 'IssueID': u'26919', 'Issue_Name': u'Saved', 'ArcID': u'55638', 'Issue_Number': u'231', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-07-01', 'ComicName': u'Daredevil', 'IssueID': u'26987', 'Issue_Name': u'God and Country', 'ArcID': u'55638', 'Issue_Number': u'232', 'ComicID': u'2190'}, {'Store_Date': '0000-00-00', 'Issue_Date': u'1986-08-01', 'ComicName': u'Daredevil', 'IssueID': u'27079', 'Issue_Name': u'Armageddon', 'ArcID': u'55638', 'Issue_Number': u'233', 'ComicID': u'2190'}], 'firstdate': u'1986-02-01'}
15-Aug-2015 23:01:49 - DEBUG   :: CP Server Thread-6 : arclist: 26500,1|26597,2|26695,3|26789,4|26919,5|26884,6|26987,7|27079,8
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [1] issueid:26500 - findorder#:0
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [2] issueid:26597 - findorder#:8
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [3] issueid:26695 - findorder#:16
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [4] issueid:26789 - findorder#:24
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [6] issueid:26884 - findorder#:40
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [5] issueid:26919 - findorder#:32
15-Aug-2015 23:01:49 - INFO    :: CP Server Thread-6 : [7] issueid:26987 - findorder#:48
```

Reproduction Steps:
* Search for story arc: "Born Again"
* Click "Add this Story Arc"
* BOOM

**Comment by evilhero** [comment]
Weird, i can see where it's happening and the cause, but not sure why it's only happening now. 

I'll check into this in the a.m, it's an easy fix but I'm curious as to why it only is happening for this arc thus far (testing ones all worked fine).

**Comment by weidercs** [comment]
Fixed, thanks!
