### ISSUE TITLE
Mylar Post Processing

### ISSUE THREAD

**Issue by devestator05** [evilhero/mylar#1116]
I get this error in my log when trying to post process torrent downloads

ERROR  Uncaught exception: Traceback (most recent call last):
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\logger.py", line 159, in new_run
 old_run(_args, *_kwargs)
 File "C:\Python27\lib\threading.py", line 763, in run
 self.**target(_self.__args, *_self.__kwargs)
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\PostProcessor.py", line 898, in Process
 self.Process_next(comicid, issueid, issuenumOG, ml, stat)
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\PostProcessor.py", line 1133, in Process_next
 pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml['ComicLocation'])
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\cmtagmylar.py", line 327, in run
 ctversion = subprocess.check_output([comictagger_cmd, "--version"])
 File "C:\Python27\lib\subprocess.py", line 566, in check_output
 process = Popen(stdout=PIPE, _popenargs, *_kwargs)
 File "C:\Python27\lib\subprocess.py", line 710, in __init**
 errread, errwrite)
 File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
 startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by evilhero** [comment]
This is probably similar to #1114 - where you have 2 or more series in your watchlist that share the same title of sorts (ie. Secret Wars and Secret Wars Journal)

What series is it trying to scan in and failing?  In the mylar.log file it will indicate just prior to the error you pasted.

**Comment by devestator05** [comment]
[POST-PROCESSING] [1/15] Starting Post-Processing for Magneto issue: 18

**Comment by devestator05** [comment]
I made the changes above and here is the log error

2015-08-26 15:51:09 ERROR  Uncaught exception: Traceback (most recent call last):
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\logger.py", line 159, in new_run
 old_run(*args, **kwargs)
 File "C:\Python27\lib\threading.py", line 763, in run
 self.__target(*self.__args, **self.__kwargs)
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\PostProcessor.py", line 898, in Process
 self.Process_next(comicid, issueid, issuenumOG, ml, stat)
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\PostProcessor.py", line 1133, in Process_next
 pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml['ComicLocation'])
 File "C:\Users\MASTER\Downloads\mylar-development\mylar-development\mylar\cmtagmylar.py", line 327, in run
 ctversion = subprocess.check_output([comictagger_cmd, "--version"])
 File "C:\Python27\lib\subprocess.py", line 566, in check_output
 process = Popen(stdout=PIPE, *popenargs, **kwargs)
 File "C:\Python27\lib\subprocess.py", line 710, in __init__
 errread, errwrite)
 File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
 startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by evilhero** [comment]
Are you on the development or master branch of mylar?  The fix is currently in the development only.

**Comment by evilhero** [comment]
Actually that's a comictagger error - make sure you have the comictagger location specified within the mylar configuration (there's a FAQ on the forums related to setting up comictagger with mylar)

**Comment by devestator05** [comment]
I'm in development and I see the FAQ for SAB, but I am using torrent

**Comment by evilhero** [comment]
The FAQ is on the forums, not on the github pages.

Doesn't matter if you use torrents or not, you're using the manual postprocess / folder monitor method, both of which use the same work flow for nzbs (save that there is no automatic post-processing)
