### ISSUE TITLE
500 Internal Service Error when adding series, opening settings, or clicking Update

### ISSUE THREAD

**Issue by projektidiot** [evilhero/mylar#1118]
I get this error when I click "+add series", "+one-off", the Settings button, or Update:

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 3355, in config
    "br_version": mylar.versioncheck.getVersion()[0],
  File "C:\Mylar\mylar\versioncheck.py", line 132, in getVersion
    logger.info('Branch detected & set to : ' + mylar.GIT_BRANCH)
  File "C:\Python27\lib\logging\__init__.py", line 1165, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1284, in _log
    self.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 1294, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging\__init__.py", line 1334, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 757, in handle
    self.emit(record)
  File "C:\Mylar\mylar\logger.py", line 43, in emit
    mylar.LOG_LIST.insert(0, (helpers.now(), message, record.levelname, record.threadName))
MemoryError

**Comment by evilhero** [comment]
What branch / commit are you running of Mylar ? 

Are you running Mylar via a 3rd party-app of some kind?

Does restarting Mylar resolve the issue ?

**Comment by projektidiot** [comment]
Restarting my PC fixed it. Thanks.
