### ISSUE TITLE
error: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by Gungnir999** [evilhero/mylar#1140]
After looking through past issues, I beleive this is due to a temp ban from comicvine but I want confirm with you before I jump to conclusions.

Uncaught exception: Traceback (most recent call last):
File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/Applications/Mylar/mylar/webserve.py", line 3056, in preSearchit
sresults, explicit = mb.findComic(displaycomic, mode, issue=numissues, limityear=yearRANGE, explicit='all') #ogcname, mode, issue=numissues, limityear=yearRANGE, explicit='all') #ComicName, mode, issue=numissues, limityear=yearRANGE)
File "/Applications/Mylar/mylar/mb.py", line 129, in findComic
searched = pullsearch(comicapi, comicquery, 0, explicit, type)
File "/Applications/Mylar/mylar/mb.py", line 68, in pullsearch
file = urllib2.urlopen(PULLURL)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
result = self._call_chain(_args)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(_args)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
r = h.getresponse(buffering=True)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
data = self._sock.recv(self._rbufsize)
error: [Errno 54] Connection reset by peer

**Comment by mnbf9rca** [comment]
I also have this error: 
2015-10-02 15:42:28	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/updater.py", line 274, in dbUpdate
cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload)
File "/opt/mylar/mylar/importer.py", line 95, in addComictoDB
comic = cv.getComic(comicid, 'comic')
File "/opt/mylar/mylar/cv.py", line 151, in getComic
dom = pulldetails(comicid, 'comic', None, 1)
File "/opt/mylar/mylar/cv.py", line 85, in pulldetails
file = urllib2.urlopen(PULLURL)
File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
return _opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 410, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 442, in error
result = self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "/usr/lib/python2.7/urllib2.py", line 404, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 422, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
r = h.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
response.begin()
File "/usr/lib/python2.7/httplib.py", line 415, in begin
version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 476, in readline
data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

**Comment by mnbf9rca** [comment]
logging in to https://auth.comicvine.com/login/ gives a really badly formatted page - i assume they are having issues

**Comment by evilhero** [comment]
See #1139 - CV are enforcing some type of ip ban for excessive api usage, although they don't indicate what excessive is. They haven't answered any questions on their forums of others being affected from other apps having exactly the same problem. 

At this point it's just a wait and see what happens kind of deal unfortunately. I can't do anything on this end - especially if I don't know why it is that they're doing what they're doing.

**Comment by mnbf9rca** [comment]
i have my own API key entered in to mylar - so not sure how much i could have used it in reality!

**Comment by evilhero** [comment]
According to one of the forum mods over there it was an issue with their data center blocking api requests as being malicious - so everything should be working again (for the time being at least)
