### ISSUE TITLE
Post-Processing Failing

### ISSUE THREAD

**Issue by razambon** [evilhero/mylar#1148]
Not sure what has happened, but all of a sudden SABnzbd is getting stuck on running ComicRN.py for any comic.  No errors on the Sab side, but getting this in the mylar log:

2015-10-28 13:54:52 	ERROR 	Uncaught exception: Traceback (most recent call last):
File "C:\Program Files\mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 761, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Program Files\mylar\mylar\PostProcessor.py", line 911, in Process
return self.Process_next(comicid, issueid, issuenumOG)
File "C:\Program Files\mylar\mylar\PostProcessor.py", line 1134, in Process_next
pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion)
File "C:\Program Files\mylar\mylar\cmtagmylar.py", line 327, in run
ctversion = subprocess.check_output([comictagger_cmd, "--version"])
File "C:\Python27\lib\subprocess.py", line 568, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "C:\Python27\lib\subprocess.py", line 711, in __init__
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
2015-10-28 13:54:47 	INFO 	[POST-PROCESSING] [1/1] Starting Post-Processing for Deadpool vs. Thanos issue: 4

**Comment by razambon** [comment]
And...I solved this myself.  Seems with the most recent update, metatagging settings were changed and 'turned on' despite my not having it setup previously.  Finally figured it out from another issue...not sure how it updated.  This was after an update, so could be due to that.
