### ISSUE TITLE
Negative Number issue causes an uncaught exception

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1153]
Low priority, but wanted to save it here... Adding some old stuff and it barfed on Uncanny X-Men -1
Stupid negative number comics.

Log below:

```
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] cchk is : uncanny xmen
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] we should remove 9 characters
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] detected 1 special characters
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : i,j:0,17
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : 17 - subname: uncanny xmen -001
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : digitchk: 1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] 17 is >= 17 .End reached. ignoring remainder.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] nonocount [9] cchk [uncanny xmen] length [12]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] final jtd_len to prune [12]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] before title removed from FILENAME [The.Uncanny.X-Men.-001.(1997).cbr]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] after title removed from FILENAME [X-Men.-001.(1997).cbr]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] creating just the digits using SUBNAME, pruning first [12] chars from [uncanny xmen -001]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] after title removed from SUBNAME [-001]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] JUSTTHEDIGITS [-001]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : I've encountered a negative issue #: -001. Trying to accomodate.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] final justthedigits [-001]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] cchk = uncanny xmen
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] modwatchcomic = uncanny xmen
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] subname = uncanny xmen -001
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] SeriesYear: 1981
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] IssueTotal: 405
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Comic Volume: v1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] volume detected: None
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Latest date: 2011
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] 0 Bracket Word: The.Uncanny.X-Men.-001./23
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] 1 Bracket Word: 1997/4
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] year detected: 1997
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] 1997 is within the series range of 1981-2011
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Matched on year, not on version - continuing.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] yearmatch string is : true
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] poss_alpha: [u'-001']
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] lenalpha: 4
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] sub_removed: uncanny xmen -001
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] split_sub: [u'uncanny', u'xmen']
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] split_mod: ['uncanny', 'xmen']
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : xmen comparing to xmen
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] word match exact. 1/2
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : uncanny comparing to uncanny
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] word match exact. 2/2
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] scnt:2
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] split_mod length:2
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] we got 100 percent.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] this should be considered an exact match.Justthedigits:-001
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : ignoring os metadata for ._The.Uncanny.X-Men.-001.(1997).cbr
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] you have a total of 1 The Uncanny X-Men comics
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] comic: All-New X-Men
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Looking in: /mnt/Media/Comic_Stage
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : there are 4 files.
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : ignoring os metadata for ._.DS_Store
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] numberinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] decimalinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] bracketinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] subnm len : 3
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] subname no brackets: The.Uncanny.X-Men.-001.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [.] charpos: [3, 11, 17, 22]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Decimal check.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 3
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: e
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: U
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 11
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: y
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: X
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 17
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: n
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: -
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 22
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: 1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: 
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [-] charpos: [13, 18]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] possible negative issue detected.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] AS_Alt : ['127372873872871091383 abdkhjhskjhkjdhakajhf']
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] watchcomic:AllNew XMen ..comparing to found file: uncanny x-men -001
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : ignoring os metadata for ._The.Uncanny.X-Men.-001.(1997).cbr
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] you have a total of 0 All-New X-Men comics
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] comic: Uncanny X-Men
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Looking in: /mnt/Media/Comic_Stage
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : there are 4 files.
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : ignoring os metadata for ._.DS_Store
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] numberinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] decimalinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] bracketinseries: False
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] subnm len : 3
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] subname no brackets: The.Uncanny.X-Men.-001.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [.] charpos: [3, 11, 17, 22]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] Decimal check.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 3
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: e
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: U
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 11
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: y
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: X
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 17
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: n
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: -
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : fndit: 22
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit1: 1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : isdigit2: 
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [-] charpos: [13, 18]
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] possible negative issue detected.
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] AS_Alt : ['127372873872871091383 abdkhjhskjhkjdhakajhf']
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] watchcomic:Uncanny XMen ..comparing to found file: uncanny x-men -001
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : ignoring os metadata for ._The.Uncanny.X-Men.-001.(1997).cbr
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [FILECHECKER] you have a total of 0 Uncanny X-Men comics
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [POST-PROCESSING] There are 1 files found that match on your watchlist, 140 do not match anything and will be ignored.
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : [DUPECHECK] Duplicate check for /mnt/Media/Comic_Stage/The Uncanny X-Men Annuals & Giant Size Comics & Specials [25 of 26] 'Uncanny X-Men Flashback 01 (Universo Edits-DCP).cbr'/The.Uncanny.X-Men.-001.(1997).cbr
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
03-Nov-2015 11:40:54 - INFO    :: Thread-45 : [POST-PROCESSING] [1/1] Starting Post-Processing for The Uncanny X-Men issue: -1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [POST-PROCESSING] issueid: 43915
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [POST-PROCESSING] issuenumOG: -1
03-Nov-2015 11:40:54 - DEBUG   :: Thread-45 : [POST-PROCESSING] Zero Suppression set to : 00x
03-Nov-2015 11:40:54 - ERROR   :: Thread-45 : Uncaught exception: Traceback (most recent call last):
  File "/home/xxx/Apps/Mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 901, in Process
    self.Process_next(comicid, issueid, issuenumOG, ml, stat)
  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 1017, in Process_next
    prettycomiss = '-' + str(zeroadd) + str(abs(issueno))
TypeError: bad operand type for abs(): 'unicode'

```

**Comment by evilhero** [comment]
Ugh ok yeah that's a problem. Thanks for the detailed log,  I'll look into this tonight and get it working again.
