### ISSUE TITLE
NameError  global name 'pic_extensiosn' is not defined

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1156]
I got this error clicking on the info button next to a comic. Looks like a typo in there.

ERROR<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 
    <title>500 Internal Server Error</title>

<body><h2>500 Internal Server Error</h2>

<p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>

<pre id="traceback">Traceback (most recent call last):  
File "C:\~scripts\mylar-dev\cherrypy\_cprequest.py", line 645, in respond    response.body = self.handler()  File "C:\~scripts\mylar-dev\cherrypy\lib\encoding.py", line 188, in __call__    self.body = self.oldhandler(*args, **kwargs)  
File "C:\~scripts\mylar-dev\cherrypy\_cpdispatch.py", line 29, in __call__    return self.callable(*self.args, **self.kwargs)  
File "C:\~scripts\mylar-dev\mylar\webserve.py", line 4002, in IssueInfo    issuedetails = helpers.IssueDetails(filelocation)  
File "C:\~scripts\mylar-dev\mylar\helpers.py", line 1346, in IssueDetails    
elif any(['00a' in infile, '00b' in infile, '00c' in infile, '00d' in infile, '00e' in infile]) and **infile.endswith(pic_extensiosn):**
**NameError: global name 'pic_extensiosn' is not defined**</pre>

<div id="powered_by"><span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.0</a></span></div>

</body>
</html>

**Comment by evilhero** [comment]
Yups, definite typo ;)  Thanks for the catch - not quite sure how I missed that, but I'll get this fixed in the next dev commit
