### ISSUE TITLE
Exception in WEEKLYCHECK

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1162]
Just started happening with the latest development pull:

```
18-Nov-2015 07:39:54 - DEBUG   :: WEEKLYCHECK : Exception generated in thread WEEKLYCHECK: 'list' object has no attribute 'lower'
18-Nov-2015 07:39:54 - DEBUG   :: WEEKLYCHECK : 'Traceback (most recent call last):\n  File "/home/www/Apps/Mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/home/www/Apps/Mylar/mylar/weeklypullit.py", line 31, in run\n    mylar.weeklypull.future_check()\n  File "/home/www/Apps/Mylar/mylar/weeklypull.py", line 1104, in future_check\n    if split_match.lower().index(ss) == split_series.lower().index(ss):\nAttributeError: \'list\' object has no attribute \'lower\'\n'
```

**Comment by evilhero** [comment]
I can't seem to duplicate this at all atm.

Can you paste in what is occuring just prior to that error? It should indicate what it's trying to search for, which might possibly be the problem?

**Comment by weidercs** [comment]
It's the Duck's fault? Drax maybe?
Seems to kill WEEKLYCHECK when it error and goes on to the RSS/FOLDERMONITOR after that.

May have been happening prior to the release, but hadn't noticed before and my logs have rotated out already.

```
18-Nov-2015 09:41:50 - DEBUG   :: WEEKLYCHECK : cflist: [{'Status': u'Wanted', 'Publisher': u'MARVEL COMICS', 'ComicName': u'HOWARD THE DUCK', 'IssueDate': u'2015-11-04', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'MARVEL COMICS', 'ComicName': u'SPIDER-GWEN', 'IssueDate': u'2015-11-04', 'IssueNumber': u'0'}, {'Status': u'Wanted', 'Publisher': u'MARVEL COMICS', 'ComicName': u'HERCULES', 'IssueDate': u'2015-11-04', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'MARVEL COMICS', 'ComicName': u'DRAX', 'IssueDate': u'2015-11-04', 'IssueNumber': u'1'}, {'Status': u'Wanted', 'Publisher': u'MARVEL COMICS', 'ComicName': u'EXTRAORDINARY X-MEN', 'IssueDate': u'2015-11-04', 'IssueNumber': u'1'}]
18-Nov-2015 09:41:50 - INFO    :: WEEKLYCHECK : I will be looking to see if any information has been released for 5 series that are NEW series
18-Nov-2015 09:41:50 - INFO    :: WEEKLYCHECK : looking for new data for HOWARD THE DUCK[#1] (2015)
18-Nov-2015 09:41:50 - DEBUG   :: WEEKLYCHECK : Default search mode - this will match on ALL search words
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : there are 14 search results...
18-Nov-2015 09:41:51 - INFO    :: WEEKLYCHECK : More than one result returned - this may have to be a manual add, but I'm going to try to figure it out myself first.
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Publisher of series to be added: MARVEL COMICS
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing Howard the Duck - to - HOWARD THE DUCK
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing howard duck - to - howard duck
18-Nov-2015 09:41:51 - INFO    :: WEEKLYCHECK : Name matched successful: Howard the Duck
18-Nov-2015 09:41:51 - INFO    :: WEEKLYCHECK : Matched to : 2015
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing Howard the Duck - to - HOWARD THE DUCK
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing howard duck - to - howard duck
18-Nov-2015 09:41:51 - INFO    :: WEEKLYCHECK : Name matched successful: Howard the Duck
18-Nov-2015 09:41:51 - INFO    :: WEEKLYCHECK : Matched to : 2015
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing Howard the Duck: What the Duck - to - HOWARD THE DUCK
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing howard duck what duck - to - howard duck
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing Howard the Duck: The Complete Collection - to - HOWARD THE DUCK
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Comparing howard duck complete collection - to - howard duck
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : length match differential set for an allowance of 20%
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : actual differential in length between result and series title: 0%
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : Exception generated in thread WEEKLYCHECK: 'list' object has no attribute 'lower'
18-Nov-2015 09:41:51 - DEBUG   :: WEEKLYCHECK : 'Traceback (most recent call last):\n  File "/home/xxx/Apps/Mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/home/xxx/Apps/Mylar/mylar/weeklypullit.py", line 31, in run\n    mylar.weeklypull.future_check()\n  File "/home/xxx/Apps/Mylar/mylar/weeklypull.py", line 1104, in future_check\n    if split_match.lower().index(ss) == split_series.lower().index(ss):\nAttributeError: \'list\' object has no attribute \'lower\'\n'
18-Nov-2015 09:42:06 - INFO    :: RSSCHECK : RSS Feed Check was last run at : 2015-11-18 09:40:11
```

**Comment by evilhero** [comment]
I'm pretty sure that it's Howard the Duck that's causing the problem - just because it's looking for issue 1's and it's at issue 5...so it would never match properly at this point (it's meant to add it immediately as the issue data is put on CV). Since there's no delete option available for the auto-wants yet, I would manually add the Howard the Duck series, and then do a Force Check Availability in the Wanted tab/ Upcoming / upcoming nodata section. When it gets added successfully, upon the next Force Check Availability, if the series is already added - it should remove it.

**Comment by weidercs** [comment]
Tried your suggestion, no go... 

So I just went into the db and removed the entries in the futureupcoming table, all good now.  I'm guessing things are just a little weird with all the in-year marvel reboots and whatnot.  

Closing because it's unreproducible...

**Comment by evilhero** [comment]
Actually it is reproducible - once I figured out why it was happening, definite bug. Next commit coming up in a few minutes will have that part of the code commented out, so that it won't error. As well, there will be a 'X' beside each item in the auto-want list so that one can remove the title if necessary.

**Comment by weidercs** [comment]
teach me to close issues... :)

**Comment by evilhero** [comment]
haha - no worries, I honestly would not have found this one anytime soon - so thanks much for providing the headsup ;)
