### ISSUE TITLE
Error since update

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1163]
Since downloading today's update, I've been getting this from time to time

18-Nov-2015 17:17:00 - ERROR :: Thread-14 : Uncaught exception: Traceback (most recent call last):
  File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
    old_run(_args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 1321, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Applications/Mylar/mylar/search.py", line 264, in search_init
    findit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, semd_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
NameError: global name 'semd_prov_count' is not defined

Traceback (most recent call last):
  File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
    old_run(_args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 1321, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "/Applications/Mylar/mylar/search.py", line 264, in search_init
    findit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, semd_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
NameError: global name 'semd_prov_count' is not defined

**Comment by evilhero** [comment]
Thanks for the error log - stupid typos :( 

It's good to go in development branch now.

**Comment by thewindupboy** [comment]
Thank you kindly!
