### ISSUE TITLE
 Error in recreating weekly pull list 

### ISSUE THREAD

**Issue by max6166** [evilhero/mylar#1165]
I am still experiencing the error described in #1161. When I try to recreate the weekly pull list, I get the below 500 error. I am on the latest dev branch.  

The log entries stop at the Uncanny Avengers Annual as described in #1161 (Log at bottom). 

That issue is already downloaded. I also tried adding an alternate title of "Uncanny Avengers Annual" but it did not make a difference.
 
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/mkerr/.mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/mkerr/.mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/mkerr/.mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/mkerr/.mylar/mylar/webserve.py", line 1658, in pullrecreate
    weeklypull.pullit(forcecheck)
  File "/home/mkerr/.mylar/mylar/weeklypull.py", line 434, in pullit
    pullitcheck(forcecheck=forcecheck)
  File "/home/mkerr/.mylar/mylar/weeklypull.py", line 826, in pullitcheck
    updater.weekly_update(ComicName=week['COMIC'], IssueNumber=ComicIssue, CStatus=cstatus, CID=cstatusid, futurepull=fp, altissuenumber=altissuenum)
  File "/home/mkerr/.mylar/mylar/updater.py", line 546, in weekly_update
    newValue['ComicID'] = CID['ComicID']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
LOG:
```
20-Nov-2015 20:39:05 - DEBUG   :: CP Server Thread-2 : UpcomingcontrolValue: {'ComicID': u'84608'}
20-Nov-2015 20:39:05 - DEBUG   :: CP Server Thread-2 : updating Pull-list to reflect status change: Downloaded[Downloaded]
20-Nov-2015 20:39:05 - DEBUG   :: CP Server Thread-2 : weekly_update of table : TOKYO GHOST #:3 to a status of Downloaded
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : looking for : UNCANNY AVENGERS ANNUAL
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : comparingUNCANNY AVENGERS ANNUAL..to..UNCANNY AVENGERS ANNUAL
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : watchcomic : UncannyAvengersAnnual / mod :UncannyAvengersAnnual
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : comicnm : UNCANNYAVENGERSANNUAL / mod :UNCANNYAVENGERS
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : matched on:UNCANNYAVENGERSANNUAL...UNCANNYAVENGERSANNUAL
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : [Uncanny Avengers Annual] trying to locate annual issue 1 to do comparitive issue analysis for pull-list
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : No results matched for Issue number - either this is a NEW issue with no data yet, or something is wrong
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : Watchlist hit for : Uncanny Avengers Annual Annual ISSUE: 1
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : annual detected - adjusting name to : uncanny avengers
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : Annual detected, but annuals not enabled. Ignoring result.
20-Nov-2015 20:39:06 - DEBUG   :: CP Server Thread-2 : weekly_update of table : UNCANNY AVENGERS ANNUAL #:1 to a status of None
```

**Comment by evilhero** [comment]
Can y make sure you're running the latest development commit?

It's saying you don't have annuals enabled, so you're searching for the Uncanny Avengers Annual that's indicated as being in your watchlist?

**Comment by max6166** [comment]
Closed. Now that the data for this issue available in CV, I can no longer reproduce the problem.

I was running Version: a32264eacd4ddbb56123ee074a4836846e6b8abb (development).
