### ISSUE TITLE
Post processing fails on one off

### ISSUE THREAD

**Issue by cerinthus** [evilhero/mylar#1186]
As per title.  This happens with every one off I've tried.  Adding the series and downloading the comic works as expected.  Only happens with one offs.

2015-12-26 11:09:13 ERROR   Uncaught exception: Traceback (most recent call last):
File "/home/rick/src/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(_self.__args, *_self.__kwargs)
File "/home/rick/src/mylar/mylar/PostProcessor.py", line 727, in Process
if helpers.is_number(sandwich):
UnboundLocalError: local variable 'sandwich' referenced before assignment
2015-12-26 11:09:13 INFO    [POST-PROCESSING] issuenzb not found.
2015-12-26 11:09:13 INFO    [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
2015-12-26 11:09:13 INFO    Starting postprocessing for : Deadpool.004.2016.Digital-Empire
2015-12-26 11:09:13 INFO    ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
2015-12-26 11:08:59 INFO    Downloaded DEADPOOL 4
2015-12-26 11:08:59 INFO    setting the alternate nzbname for this download grabbed by NZBGeek(newznab) in the nzblog to : Deadpool.004..2016...Digital-Empire.
2015-12-26 11:08:59 INFO    setting the nzbid for this download grabbed by NZBGeek(newznab) in the nzblog to : 1c8c44220c38457a6be7c3355d9231d4
2015-12-26 11:08:59 INFO    Successfully sent nzb file to SABnzbd
2015-12-26 11:08:59 INFO    Found DEADPOOL (2015) issue: 4 using NZBGeek(newznab) [RSS]
2015-12-26 11:08:59 INFO    [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2015-12-26 11:08:59 INFO    prov : NZBGeek(newznab) [RSS][1c8c44220c38457a6be7c3355d9231d4]
2015-12-26 11:08:59 INFO    filen: Deadpool.004..2016...Digital-Empire. -- nzbname: Deadpool.004.2016.Digital-Empire are not identical. Storing extra value as : Deadpool.004..2016...Digital-Empire.

**Comment by evilhero** [comment]
Which branch/commit of mylar are you currently running?  I believe the was fixed in the development branch but I'm not sure about master as of yet (need to check)

**Comment by cerinthus** [comment]
Running Master.  I'll check out development and update accordingly
