### ISSUE TITLE
Unable to send NZB to downloader

### ISSUE THREAD

**Issue by Undeadhunter** [evilhero/mylar#1206]
I've been having the following issue:

```
  File "/opt/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1297, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, fi
lesafe=ComicName_Filesafe)
  File "/opt/mylar/mylar/search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID
, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/opt/mylar/mylar/search.py", line 1419, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/opt/mylar/mylar/search.py", line 2030, in searcher
    in_file = open(nzbpath, "r")
UnboundLocalError: local variable 'nzbpath' referenced before assignment

```

This happens when it search for a NZB through NZBHydra. I've tried all different types of sending NZB through hydra (direct link, caching, redirect) but none of them work. 

All other tools work however.

**Comment by evilhero** [comment]
It might be that nzbhydra doesn't currently work with mylar.  At the time,  only nzbmegasearch was available so that's what was programmed against. I'll have to look to see how nzbhydra sends the information back to the client. 

Can you post the debug logs showing the sequence of events leading up to that error?  Since I don't have nzbhydra installed,  mylar should be logging the response so I can at least see how things are coming back from nzbhydra.

**Comment by Undeadhunter** [comment]
```
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [SEARCHER] entry[title]: Grayson 016 (2016) (Digital) (BlackManta-Empire)
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [SEARCHER] nzbname (remove chars): Grayson 016  2016   Digital   BlackManta-Empire
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [SEARCHER] nzbname (\s): Grayson 016 2016 Digital BlackManta-Empire
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [SEARCHER] end nzbname: Grayson.016.2016.Digital.BlackManta-Empire
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : nzbname used for post-processing:Grayson.016.2016.Digital.BlackManta-Empire
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [newznab] link: http://raspberrypi:5075/api?apikey=xxxx&t=get&id=(guid:'589080c10a85eb0bd80de625581bb00c',indexer:Usenet-Crawler,searchid:488,title:'Grayson+016+(201
6)+(Digital)+(BlackManta-Empire)')
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : payload:{'apikey': 'xxxx', 't': 'get', 'id': "(guid:'589080c10a85eb0bd80de625581bb00c',indexer:Usenet-Crawler,searchid:488,title:'Grayson+016+(2016)+(Digital)+(Black
Manta-Empire)'"}
03-Feb-2016 14:48:06 - INFO    :: Thread-13 : Download URL: http://raspberrypi:5075/api?apikey=xxxx&t=get&id=%28guid%3A%27589080c10a85eb0bd80de625581bb00c%27%2Cindexer%3AUsenet-Crawler%2Csearchid%3A488%2Ctitle%3
A%27Grayson%2B016%2B%282016%29%2B%28Digital%29%2B%28BlackManta-Empire%29%27 [VerifySSL:False]
03-Feb-2016 14:48:06 - ERROR   :: Thread-13 : Unable to download nzb from link: http://raspberrypi:5075/api?apikey=xxxx&t=get&id=%28guid%3A%27589080c10a85eb0bd80de625581bb00c%27%2Cindexer%3AUsenet-Crawler%2Csear
chid%3A488%2Ctitle%3A%27Grayson%2B016%2B%282016%29%2B%28Digital%29%2B%28BlackManta-Empire%29%27 [http://raspberrypi:5075/api?apikey=xxxx&t=get&id=(guid:'589080c10a85eb0bd80de625581bb00c',indexer:Usenet-Crawler,s
earchid:488,title:'Grayson+016+(2016)+(Digital)+(BlackManta-Empire)')]
03-Feb-2016 14:48:06 - INFO    :: Thread-13 : prov  : Hydra (newznab)[(guid:'589080c10a85eb0bd80de625581bb00c',indexer:Usenet-Crawler,searchid:488,title:'Grayson+016+(2016)+(Digital)+(BlackManta-Empire)']
03-Feb-2016 14:48:06 - INFO    :: Thread-13 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : issues match!
03-Feb-2016 14:48:06 - INFO    :: Thread-13 : Found Grayson (2016) issue: 16 using Hydra (newznab)
03-Feb-2016 14:48:06 - DEBUG   :: Thread-13 : link given by: newznab
03-Feb-2016 14:48:06 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1297, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, fi
lesafe=ComicName_Filesafe)
  File "/opt/mylar/mylar/search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID
, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/opt/mylar/mylar/search.py", line 1419, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/opt/mylar/mylar/search.py", line 2030, in searcher
    in_file = open(nzbpath, "r")
UnboundLocalError: local variable 'nzbpath' referenced before assignment

```

**Comment by evilhero** [comment]
Yep, can confirm it's definitely not working with Mylar. I have it installed on my local machine so I can do some testing, but it looks like I'm going to have to manually patch in abunch of stuff to accept the way they have the responses multi-tiered to the GUID.

I'll start working on it, but it's probably gonna take me a few days + testing to get it working properly. Will update this issue post when it's available for testing in the development branch.

**Comment by Undeadhunter** [comment]
Many thanks @evilhero

**Comment by Undeadhunter** [comment]
Resolved in last update
