### ISSUE TITLE
Comics not moving from cache directory after post-processing

### ISSUE THREAD

**Issue by kurnalbert** [evilhero/mylar#1207]
Currently, with comics set to move after post processing, the comics will get moved to the cache directory, tagged and then be unable to move to the correct directory.

When copy is selected, a copy of the comic will be made in the cache directory, tagged and then a copy will be placed in the correct comic directory.

Whichever method is selected, a copy of the comic will still remain in the cache directory, it does not appear to get deleted.

**Comment by kurnalbert** [comment]
Logs for move:

2016-02-03 15:52:03 INFO [FOLDER-CHECK] Finished checking for newly snatched downloads
2016-02-03 15:52:02 WARNING [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
2016-02-03 15:52:02 INFO [POST-PROCESSING] moveing Amazing Spider-Man Super Special 001 (1995).cbz into directory : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/001-Amazing Spider-Man Super Special 1 (1995).cbz
2016-02-03 15:52:02 DEBUG [POST-PROCESSING] Source Path : /users/tv/downloads/Amazing Spider-Man Super Special 001 (1995).cbz
2016-02-03 15:52:02 DEBUG [POST-PROCESSING] Destination Path : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/001-Amazing Spider-Man Super Special 1 (1995).cbz
2016-02-03 15:52:02 DEBUG [POST-PROCESSING] readingorder#: 1
2016-02-03 15:52:02 DEBUG [POST-PROCESSING] Renaming file to conform to configuration: Amazing Spider-Man Super Special 001 (1995).cbz
2016-02-03 15:52:02 DEBUG Destination: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/Amazing Spider-Man Super Special 1 (1995).cbz
2016-02-03 15:52:02 DEBUG Source: Amazing Spider-Man Super Special 001 (1995).cbz
2016-02-03 15:52:02 DEBUG New Filename: Amazing Spider-Man Super Special 1 (1995).cbz
2016-02-03 15:52:02 DEBUG new format: $Series $Issue ($Year)
2016-02-03 15:52:02 DEBUG not an annual - removing from filename paramaters
2016-02-03 15:52:02 DEBUG new format: $Series $Issue ($Year)
2016-02-03 15:52:02 DEBUG No version # found for series, removing from filename
2016-02-03 15:52:02 DEBUG Comic Location: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 15:52:02 DEBUG Year: 1995
2016-02-03 15:52:02 DEBUG Series: Amazing Spider-Man Super Special
2016-02-03 15:52:02 DEBUG Publisher: Marvel
2016-02-03 15:52:02 DEBUG Issue Year : 1995
2016-02-03 15:52:02 DEBUG Pretty Comic Issue is : 1
2016-02-03 15:52:02 DEBUG Zero level supplement set to none. Issue will be set as : 1
2016-02-03 15:52:02 DEBUG issue detected less than 10
2016-02-03 15:52:02 DEBUG Zero Suppression set to : none
2016-02-03 15:52:02 DEBUG issueno:1
2016-02-03 15:52:02 DEBUG iss:1
2016-02-03 15:52:02 DEBUG Story Arc Directory set to : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 15:52:02 DEBUG issueid is now : 110899
2016-02-03 15:52:02 DEBUG issueid:110899
2016-02-03 15:52:02 DEBUG issue#: 1
2016-02-03 15:52:02 DEBUG comicid: 18772
2016-02-03 15:52:02 INFO [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 15:52:02 INFO [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Amazing Spider-Man Super Special 001 (1995).cbz) - Continuing..
2016-02-03 15:52:02 INFO [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/Applications/mylar/cache/mylar_AUg3Hn/Amazing Spider-Man Super Special 001 (1995).cbz]
2016-02-03 15:52:02 DEBUG [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2016-02-03 15:52:02 DEBUG [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/mylar/comictagger.py', '-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'110899', '--type', 'cr', u'/Applications/mylar/cache/mylar_AUg3Hn/Amazing Spider-Man Super Special 001 (1995).cbz']
2016-02-03 15:52:02 DEBUG [META-TAGGER] Enabling ComicTagger script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Applications/mylar/comictagger.py with options: ['-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'110899', '--type', 'cr', u'/Applications/mylar/cache/mylar_AUg3Hn/Amazing Spider-Man Super Special 001 (1995).cbz']
2016-02-03 15:52:02 INFO [META-TAGGER] ComicRack tagging meta-tagging processing started.
2016-02-03 15:52:02 DEBUG [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2016-02-03 15:52:02 DEBUG [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/mylar/comictagger.py', '-e', '--delete-rar', u'/Applications/mylar/cache/mylar_AUg3Hn/Amazing Spider-Man Super Special 001 (1995).cbz']
2016-02-03 15:52:02 DEBUG [META-TAGGER] Enabling ComicTagger script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Applications/mylar/comictagger.py with options: ['-e', '--delete-rar', u'/Applications/mylar/cache/mylar_AUg3Hn/Amazing Spider-Man Super Special 001 (1995).cbz']
2016-02-03 15:52:02 DEBUG [META-TAGGER] Will NOT modify existing tag blocks even if they exist already.
2016-02-03 15:52:02 DEBUG [META-TAGGER] CR Tagging enabled.
2016-02-03 15:52:02 DEBUG [META-TAGGER] ComicTagger 1.1.15-beta being used - using personal ComicVine API key supplied via mylar.
2016-02-03 15:52:02 DEBUG [META-TAGGER] Running the ComicTagger Add-on for Mylar
2016-02-03 15:52:02 DEBUG [META-TAGGER] unrar_folder : /Applications/mylar/cache/mylar_AUg3Hn/unrard
2016-02-03 15:52:02 DEBUG [META-TAGGER] comicpath : /Applications/mylar/cache/mylar_AUg3Hn
2016-02-03 15:52:02 DEBUG [META-TAGGER] sabnzbdscriptpath : /Applications/mylar
2016-02-03 15:52:02 DEBUG [META-TAGGER] downloadpath : /users/tv/downloads
2016-02-03 15:52:02 DEBUG [META-TAGGER] scriptname : Mylar.py
2016-02-03 15:52:02 DEBUG [META-TAGGER] Paths / Locations:
2016-02-03 15:52:02 DEBUG [META-TAGGER] Filename is : /users/tv/downloads/Amazing Spider-Man Super Special 001 (1995).cbz
2016-02-03 15:52:02 DEBUG [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
2016-02-03 15:52:02 DEBUG ComicTagger Path location for internal comictagger.py set to : /Applications/mylar/comictagger.py
2016-02-03 15:52:02 DEBUG [META-TAGGER] dirName:/users/tv/downloads
2016-02-03 15:52:02 INFO [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
2016-02-03 15:52:02 DEBUG [POST-PROCESSING] Story Arc Directory set to : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 15:52:02 INFO [STORY-ARC POST-PROCESSING] Enabled for Planet of the Symbiotes
2016-02-03 15:52:02 INFO [STORY-ARC MANUAL POST-PROCESSING] I have found 3 issues that belong to Story Arcs. Flinging them into the correct directories.
2016-02-03 15:51:58 INFO [Spider-Man Super Special #1] MATCH: /users/tv/downloads/Spider-Man Super Special 001 (1995).cbz / 140411 / 140411
2016-02-03 15:51:58 INFO IssueDate: 1995-07-01
2016-02-03 15:51:58 INFO ReleaseDate: 0000-00-00
2016-02-03 15:51:58 DEBUG issuechk: 07
2016-02-03 15:51:58 DEBUG issuedate:1995-07-01
2016-02-03 15:51:58 DEBUG [FILECHECKER] I have found a total of 3 Spider-Man Super Special comics

**Comment by kurnalbert** [comment]
Logs for copy:

2016-02-03 16:00:59 INFO [POST-PROCESSING] Manual post-processing completed for 5 story-arc issues.
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] [Planet of the Symbiotes] Post-Processing completed for: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/002-Spider-Man Super Special 1 (1995).cbz
2016-02-03 16:00:59 DEBUG writing: {'Status': 'Downloaded', 'Location': u'/Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/002-Spider-Man Super Special 1 (1995).cbz'} -- {'IssueArcID': u'55738_2486'}
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] IssueArcID: 55738_2486
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] Removed temporary directory : /users/tv/downloads
2016-02-03 16:00:59 INFO [POST-PROCESSING] copying Spider-Man Super Special 001 (1995).cbz into directory : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/002-Spider-Man Super Special 1 (1995).cbz
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] Source Path : /users/tv/downloads/Spider-Man Super Special 001 (1995).cbz
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] Destination Path : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/002-Spider-Man Super Special 1 (1995).cbz
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] readingorder#: 2
2016-02-03 16:00:59 DEBUG [POST-PROCESSING] Renaming file to conform to configuration: Spider-Man Super Special 001 (1995).cbz
2016-02-03 16:00:59 DEBUG Destination: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes/Spider-Man Super Special 1 (1995).cbz
2016-02-03 16:00:59 DEBUG Source: Spider-Man Super Special 001 (1995).cbz
2016-02-03 16:00:59 DEBUG New Filename: Spider-Man Super Special 1 (1995).cbz
2016-02-03 16:00:59 DEBUG new format: $Series $Issue ($Year)
2016-02-03 16:00:59 DEBUG not an annual - removing from filename paramaters
2016-02-03 16:00:59 DEBUG new format: $Series $Issue ($Year)
2016-02-03 16:00:59 DEBUG No version # found for series, removing from filename
2016-02-03 16:00:59 DEBUG Comic Location: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 16:00:59 DEBUG Year: 1995
2016-02-03 16:00:59 DEBUG Series: Spider-Man Super Special
2016-02-03 16:00:59 DEBUG Publisher: Marvel
2016-02-03 16:00:59 DEBUG Issue Year : 1995
2016-02-03 16:00:59 DEBUG Pretty Comic Issue is : 1
2016-02-03 16:00:59 DEBUG Zero level supplement set to none. Issue will be set as : 1
2016-02-03 16:00:59 DEBUG issue detected less than 10
2016-02-03 16:00:59 DEBUG Zero Suppression set to : none
2016-02-03 16:00:59 DEBUG issueno:1
2016-02-03 16:00:59 DEBUG iss:1
2016-02-03 16:00:59 DEBUG Story Arc Directory set to : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 16:00:59 DEBUG issueid is now : 140411
2016-02-03 16:00:59 DEBUG issueid:140411
2016-02-03 16:00:59 DEBUG issue#: 1
2016-02-03 16:00:59 DEBUG comicid: 23406
2016-02-03 16:00:59 INFO [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 16:00:59 INFO [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Spider-Man Super Special 001 (1995).cbz) - Continuing..
2016-02-03 16:00:59 INFO [META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz]
2016-02-03 16:00:59 DEBUG [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2016-02-03 16:00:59 DEBUG [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/mylar/comictagger.py', '-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'140411', '--type', 'cbl', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:59 DEBUG [META-TAGGER] Enabling ComicTagger script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Applications/mylar/comictagger.py with options: ['-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'140411', '--type', 'cbl', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:59 INFO [META-TAGGER] Comicbooklover tagging meta-tagging processing started.
2016-02-03 16:00:59 INFO [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz]
2016-02-03 16:00:58 DEBUG [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2016-02-03 16:00:58 DEBUG [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/mylar/comictagger.py', '-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'140411', '--type', 'cr', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:58 DEBUG [META-TAGGER] Enabling ComicTagger script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Applications/mylar/comictagger.py with options: ['-s', '-m', 'volume=1', '--cv-api-key', u'17594b1206281a02b9d50073a48bf52bcc325986', '--nooverwrite', '-o', '--id', u'140411', '--type', 'cr', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:58 INFO [META-TAGGER] ComicRack tagging meta-tagging processing started.
2016-02-03 16:00:58 DEBUG [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2016-02-03 16:00:58 DEBUG [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/mylar/comictagger.py', '-e', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:58 DEBUG [META-TAGGER] Enabling ComicTagger script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Applications/mylar/comictagger.py with options: ['-e', u'/Applications/mylar/cache/mylar_8KUCmS/Spider-Man Super Special 001 (1995).cbz']
2016-02-03 16:00:58 DEBUG [META-TAGGER] Will NOT modify existing tag blocks even if they exist already.
2016-02-03 16:00:58 DEBUG [META-TAGGER] CBL Tagging enabled.
2016-02-03 16:00:58 DEBUG [META-TAGGER] CR Tagging enabled.
2016-02-03 16:00:58 DEBUG [META-TAGGER] ComicTagger 1.1.15-beta being used - using personal ComicVine API key supplied via mylar.
2016-02-03 16:00:57 DEBUG [META-TAGGER] Running the ComicTagger Add-on for Mylar
2016-02-03 16:00:57 DEBUG [META-TAGGER] unrar_folder : /Applications/mylar/cache/mylar_8KUCmS/unrard
2016-02-03 16:00:57 DEBUG [META-TAGGER] comicpath : /Applications/mylar/cache/mylar_8KUCmS
2016-02-03 16:00:57 DEBUG [META-TAGGER] sabnzbdscriptpath : /Applications/mylar
2016-02-03 16:00:57 DEBUG [META-TAGGER] downloadpath : /users/tv/downloads
2016-02-03 16:00:57 DEBUG [META-TAGGER] scriptname : Mylar.py
2016-02-03 16:00:57 DEBUG [META-TAGGER] Paths / Locations:
2016-02-03 16:00:57 DEBUG [META-TAGGER] Filename is : /users/tv/downloads/Spider-Man Super Special 001 (1995).cbz
2016-02-03 16:00:57 DEBUG [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
2016-02-03 16:00:57 DEBUG ComicTagger Path location for internal comictagger.py set to : /Applications/mylar/comictagger.py
2016-02-03 16:00:57 DEBUG [META-TAGGER] dirName:/users/tv/downloads
2016-02-03 16:00:57 INFO [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
2016-02-03 16:00:57 DEBUG [POST-PROCESSING] Story Arc Directory set to : /Volumes/OldMac/eBooks/Comics/StoryArcs/Planet of the Symbiotes
2016-02-03 16:00:57 INFO [STORY-ARC POST-PROCESSING] Enabled for Planet of the Symbiotes

**Comment by evilhero** [comment]
Ok, I think I may have this fixed for Story Arc processing now on my local build. I just want to make sure it's working as to what you were doing when it occured. Were you doing one-off downloads off the story-arc page or were you manually post-processing the issues ?

**Comment by kurnalbert** [comment]
I had added the story arc into Mylar. As I already had the comics, I added them to my watch directory and let Mylar find them and import them on the next scan.

Thanks for working on this!

**Comment by kurnalbert** [comment]
So after the last update, this issue has returned but this time for all comics, not just comics from story arcs.

The logs for a failed move is as follows:

26-Feb-2016 18:43:05 - INFO :: FOLDERMONITOR : [DUPECHECK] Duplicate check for /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - INFO :: FOLDERMONITOR : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Was downloaded from KAT. Enabling torrent manual post-processing completion notification.
26-Feb-2016 18:43:05 - INFO :: FOLDERMONITOR : [POST-PROCESSING] [1/1] Starting Post-Processing for All-New X-Men issue: 5
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] issueid: 516946
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] issuenumOG: 5
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Zero Suppression set to : 00x
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : issue detected less than 10
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : Zero level supplement set to 00x. Issue will be set as : 005
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Pretty Comic Issue is : 005
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Issue Year : 2016
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Publisher: Marvel
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Series: All-New X-Men
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Year: 2015
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Comic Location: /Volumes/OldMac/eBooks/Comics/All-New X-Men (2015)
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Comic Version: v2
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Not an annual - removing from filename parameters
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] New format: $Series $Issue ($Year)
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Metatagging enabled - proceeding...
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] dirName:/users/tv/downloads
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : ComicTagger Path location for internal comictagger.py set to : /Applications/mylar/comictagger.py
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] UNRAR path set to : /usr/local/bin/unrar
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] Filename is : /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] Paths / Locations:
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] scriptname : Mylar.py
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] downloadpath : /users/tv/downloads
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] sabnzbdscriptpath : /Applications/mylar
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] comicpath : /Applications/mylar/cache/mylar_EA80aH
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] unrar_folder : /Applications/mylar/cache/mylar_EA80aH/unrard
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [META-TAGGER] Running the ComicTagger Add-on for Mylar
26-Feb-2016 18:43:05 - WARNING :: FOLDERMONITOR : [META-TAGGER][WARNING] Make sure that you have configparser installed.
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without tagging...
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] ofilename:All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] odir: /users/tv/downloads
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] ofilename: All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] ext:.cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Original Filename: All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Original Extension: .cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] New Filename: All-New X-Men 005 (2016)
26-Feb-2016 18:43:05 - INFO :: FOLDERMONITOR : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/OldMac/eBooks/Comics/All-New X-Men (2015)
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Source: /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Destination: /Volumes/OldMac/eBooks/Comics/All-New X-Men (2015)/All-New X-Men 005 (2016).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Renaming /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] odir src : /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] moveing /users/tv/downloads/All-New X-Men 005 (2016) (Digital) (Zone-Empire).cbr ... to ... /Volumes/OldMac/eBooks/Comics/All-New X-Men (2015)/All-New X-Men 005 (2016).cbr
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
26-Feb-2016 18:43:05 - DEBUG :: FOLDERMONITOR : [POST-PROCESSING] Post-Processing ABORTED.
26-Feb-2016 18:43:05 - INFO :: FOLDERMONITOR : [POST-PROCESSING] Manual post-processing completed for 1 issues.

**Comment by evilhero** [comment]
It looks like you're missing configparser from your installation now -  there's an error in the log indicating that.

**Comment by kurnalbert** [comment]
That's what I thought it was saying but I haven't changed anything on my setup at all, just updated Mylar.

On OSX, when I run pip show configparser, it comes back with the following:

pip show configparser
---
Metadata-Version: 2.0
Name: configparser
Version: 3.3.0.post2
Summary: This library brings the updated configparser from Python 3.2+ to Python 2.6-2.7.
Home-page: http://docs.python.org/3/library/configparser.html
Author: Łukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: 

Which implies it is still installed so I'm not quite sure what is happening here!

**Comment by evilhero** [comment]
OK,  so that's an incorrect assumption on mylar that it's a configparser error. It tries to run a very basic version check on comictagger and normally it passes and it continues fine. Yours is failing the version check for some reason. 

If you're in the mylar directory in a clinical, can you type in 'python comictagger.py - - version'  and see what the output says?

**Comment by kurnalbert** [comment]
If I run that, it outputs the following:

python comictagger.py --version
Traceback (most recent call last):
  File "comictagger.py", line 2, in <module>
    from lib.comictaggerlib.main import ctmain
  File "/Applications/mylar/lib/comictaggerlib/main.py", line 28, in <module>
    import cli
  File "/Applications/mylar/lib/comictaggerlib/cli.py", line 38, in <module>
    from issueidentifier import IssueIdentifier
  File "/Applications/mylar/lib/comictaggerlib/issueidentifier.py", line 35, in <module>
    from comicvinetalker import ComicVineTalker, ComicVineTalkerException
  File "/Applications/mylar/lib/comictaggerlib/comicvinetalker.py", line 99
    <<<<<<< Updated upstream
     ^
SyntaxError: invalid syntax

**Comment by kurnalbert** [comment]
Update on this, I redownloaded mylar from github and replaced the ComicTagger folder and it seems to work for tagging regular comics. It still fails on moving comics that only exist in story arcs though.

**Comment by evilhero** [comment]
I'll have to do some more digging - I thought I had it fixed on my local build, but it's quite possible I got confused trying to go through all the iterations of possible workflows.

Just to confirm, these are all with manual post-processing and you're selecting them to download off the story-arc page? Or are you queuing them up from the actual series page (if you have it on your watchlist)?  

The reason I ask is that they use separate code for each workflow, so I would need to know for at least a better vantage of a starting point to the issue at hand.

**Comment by kurnalbert** [comment]
Sorry for the delay in replying.

These comics do not exist as normal series in my watchlist, they only exist in the Story Arcs page. The comics are either being downloaded by Mylar or outside of Mylar and going into the watched folder. Mylar then picks them up and scans them from there. It is at that point that they were going into the cache folder and then not being moved out into the correct place in the story arcs directory.

Thanks!

**Comment by evilhero** [comment]
Should be working as of late (especially since this is over a year-and-a-half old). I'll close this issue, but if it's still a problem, please create a new issue with the relevant details and I can look more into.
