### ISSUE TITLE
missing ',' error - not downloading NZB

### ISSUE THREAD

**Issue by kylerw** [evilhero/mylar#1222]
2016-03-03 13:16:11 ERROR   Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(_self.__args, *_self.__kwargs)
File "/app/mylar/mylar/webserve.py", line 1297, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/app/mylar/mylar/search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/app/mylar/mylar/search.py", line 1419, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/app/mylar/mylar/search.py", line 2030, in searcher
in_file = open(nzbpath, "r")
UnboundLocalError: local variable 'nzbpath' referenced before assignment
2016-03-03 13:16:11 INFO    Found Spider-Man/Deadpool (2016) issue: 1 using NZBHydra (newznab)
2016-03-03 13:16:11 INFO    [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2016-03-03 13:16:11 INFO    prov : NZBHydra (newznab)[(indexer:nzb.su,indexerguid:f6315d32c23c24a7ef2f29a9e4a3f920,searchid:5005,title:'Spider-Man-Deadpool+001+(2016)+(Digital)+(Zone-EMPIRE']
2016-03-03 13:16:11 ERROR   Unable to download nzb from link: http://kylerw.com/nzbhydra/api?apikey=APIKEYHERE&t=get&id=%28indexer%3Anzb.su%2Cindexerguid%3Af6315d32c23c24a7ef2f29a9e4a3f920%2Csearchid%3A5005%2Ctitle%3A%27Spider-Man-Deadpool%2B001%2B%282016%29%2B%28Digital%29%2B%28Zone-EMPIRE%27 [http://kylerw.com/nzbhydra/getnzb?apikey=APIKEYHERE&id=(indexer:nzb.su,indexerguid:f6315d32c23c24a7ef2f29a9e4a3f920,searchid:5005,title:'Spider-Man-Deadpool+001+(2016)+(Digital)+(Zone-EMPIRE')]

**Comment by evilhero** [comment]
Nzbhydra isn't currently supported. 

I'm working on adding it in, but it's taking a bit longer due to some other more pressing issues that had to be dealt with. Hopefully will be working sooner rather than later

**Comment by kylerw** [comment]
Ahh, interesting. It seemed to be working for a short time... But good to know!

Thanks!

**Comment by theotherp** [comment]
@evilhero  If there's any way I can help you please let me know. I had hoped that hydra would be compatible enough with newznab specs.

**Comment by evilhero** [comment]
@theotherp thanks for the offer to assist. 

I'm pretty sure the reason why it doesn't work with mylar is because mylar isn't expecting a tuple response for the getnzb request (the whole tuple is being stored in the id field in the url pasted above). 

Not anything wrong with your program at all - it's just a matter of parsing out the tuple if it's a nzbhydra response.
