### ISSUE TITLE
mylar tries to chmod/chown and can't +more

### ISSUE THREAD

**Issue by hakarune** [evilhero/mylar#1223]
<githubroot><githubroot>Keeping getting 2 errors when trying to import my comics...
#1. `ERROR Could not change permissions : /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003). Exiting...`      well yeah, it's a limited dummy user so of course if doesn't have permission to change things. Note I tried adding it to the exception /etc/sudoers to try and fix and even temporarily made part of the sudo group, but neither worked.

Can't leave permission changing our ownership boxes empty.
#2. During import attempt. `ERRORUncaught exception: Traceback (most recent call last):

File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 505, in run
self.**target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 587, in addComictoDB
moveit.movefiles(comicid, comlocation, ogcname)
File "/opt/Mylar/mylar/moveit.py", line 25, in movefiles
nfilename = renameit['nfilename']
TypeError: 'NoneType' object has no attribute '__getitem**'
2016-03-07 03:04:13`

Bonus:  `ERROR Invalid Issue_Number - please validate.`</githubroot></githubroot>

**Comment by evilhero** [comment]
Mylar has to have full rwx authority to your comics directory (comic location path in the gui), as well as wherever you download your comics to (sabnzbd download folder, torrents folder etc). This is because of all the copy /move /delete requirements that it needs - maybe not so high on the downloads portion but the comic location has to be full. If mylar can't chmod/chown during post-processing then you need to ensure that user running mylar has the correct permissions, and that you're using the correct owner /group within the permissions of the mylar GUI. 

Note that if you're running this using a third party pkg (synopkg, docker) the problem may lie with the pkg - synopkg users have had nothing  it permissions problems until they moved to a git version of mylar. 

The second error, I'd need to see the lead up in the log files (toggle verbose before running the import) to see exactly what's happening - although it might be related to a permissions problem as well.

**Comment by hakarune** [comment]
It does have full authority of both download and comic location (775) and added mylar user to the "users" group too.

`drwxrwsr-x   4 hakarune users   4.0K Mar  7 03:03 Comics/`

It creates directories, but is failing on the chmod part for some reason. Pretty sure only root/admin can chmod though.

`drwxrwxr-x 2 mylar    users 4.0K Mar  7 03:14 Invincible (2003)/`

Here is the user info for mylar (tried to add it to sudo again even:
 `uid=1006(mylar) gid=1006(mylar) groups=1006(mylar),27(sudo),100(users),115(debian-transmission)`

**Comment by evilhero** [comment]
What do you have the owner &  group set to within mylar for files and directories? 

You might have to make the user mylar the owner of the comics directory, I see the group at that level has a rws, not quite sure what the status implies.

**Comment by hakarune** [comment]
Here is the full debug from the PY error.

2016-03-07 15:33:00ERRORUncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 587, in addComictoDB
moveit.movefiles(comicid, comlocation, ogcname)
File "/opt/Mylar/mylar/moveit.py", line 25, in movefiles
nfilename = renameit['nfilename']
TypeError: 'NoneType' object has no attribute '__getitem__'
2016-03-07 15:33:00ERRORInvalid Issue_Number - please validate.2016-03-07 15:33:00INFOmoving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - Vol.V2003 092.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible - Vol.V2003 092.cbz2016-03-07 15:33:00INFOmoving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - Vol.V2003 108.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible - Vol.V2003 108.cbz2016-03-07 15:33:00INFOmoving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - Vol.V2003 120.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible - Vol.V2003 120.cbz2016-03-07 15:33:00INFOmoving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - Vol.V2003 091.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible - Vol.V2003 091.cbz2016-03-07 15:33:00INFOmoving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - Vol.V2003 093.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible - Vol.V2003 093.cbz2016-03-07 15:33:00INFOMass import - Move files2016-03-07 15:33:00INFOimported is : yes2016-03-07 15:33:00INFOUpdating complete for: Invincible2016-03-07 15:32:41INFONow adding/updating issues for Invincible2016-03-07 15:32:38INFOSucessfully retrieved issue details for Invincible2016-03-07 15:32:32INFONo series have been marked as being on auto-watch.2016-03-07 15:32:32INFOFinished checking for comics on my watchlist.2016-03-07 15:32:32INFOChecking the Weekly Releases list for comics I'm watching...2016-03-07 15:32:32INFOWeekly Pull List successfully loaded.2016-03-07 15:32:31INFOprevious version detected as None - seeing if update required2016-03-07 15:32:31INFOAttempting to retrieve the comic image for series2016-03-07 15:32:29INFODirectory (/media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)) already exists! Continuing...2016-03-07 15:32:29INFOSucessfully retrieved details for Invincible2016-03-07 15:32:29INFONow adding/updating: Invincible2016-03-07 15:32:24INFOSuccessfully imported :Invincible2016-03-07 15:32:24INFOAttempting to add directly by ComicVineID: 179932016-03-07 15:32:24INFOIssues found with valid ComicID information for : Invincible [17993]2016-03-07 15:32:24INFO17993
2016-03-07 15:26:42	INFO	There is an import already running. Please wait for it to finish, and then you can resubmit this import.
2016-03-07 15:26:42	DEBUG	Mass importing the following series: [u'Invincible', u'Invincible: The War At Home']
2016-03-07 15:26:42	INFO	2 series will be attempted to be imported.
2016-03-07 15:26:42	INFO	initiating mass import.
2016-03-07 15:26:08	INFO	Successfully scanned in directory. Enabling the importResults button now.

**Comment by hakarune** [comment]
I'll see if changing the Comic folder owner does anything

**Comment by evilhero** [comment]
I see from the import that it might be coughing on the 'Vol.V2003' portion that you have in the filenames (Invincible - Vol.V2003 092.cbz) .

Mylar parses out the Vol but then normally it's a numeric after the word vol not another volume indicator - so when it removes the Vol. 2003 from the parsing, it's left with an issue number of V 93 (or something along those lines). 

I can code in a fix/exception but I'm not near a pc atm. I have a feeling if you removed the wording of 'Vol.' from the filename, or the 'V' in the 2003 it would be able to pick it up just fine.

**Comment by hakarune** [comment]
Oh. Oddly that is the Mylar that is naming them that way. On my rename scheme I set it to `Vol.$Volume` because I wanted it to read Vol.2003, but instead it's doing Vol.V2003. 

I'll change the filenames back and change my naming setup and see if it fixes it.

**Comment by evilhero** [comment]
Ah yeah that would do it. Mylar doesn't append the word 'Vol.', if you used $VolumeY without the wording at the front, it would put it as V2003.

**Comment by hakarune** [comment]
So making mylar the Comic directory owner fixed chmod issues it appears, but the PY error is still persistent.

There are multiple file naming conventions in the folder... 

Invincible (2003) V2003 #119 -.cbz
Invincible (V2003) - 093.cbz
Invincible - V2003 116.cbz

Could one of them be breaking it?

`07-Mar-2016 15:54:45 - INFO    :: Thread-12 : moving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - V2003 117.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible ($Volume) - 117.cbz
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Issue :93
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Renaming files according to configuration details : $Series ($Volume) - $Issue
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : comicid: 17993
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issue#: 93
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issueid:None
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : annualize is None
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issueid is now : 344118
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : iss:93
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issueno:93
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Zero Suppression set to : 00x
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issue detected greater than 10, but less than 100
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Zero level supplement set to 00x.Issue will be set as : 093
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Pretty Comic Issue is : 093
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Issue Year : 2012
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Publisher: Skybound
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Series: Invincible
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Year: 2003
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Comic Location: /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : No version # found for series, removing from filename
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : new format: $Series ($Volume) - $Issue
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : not an annual - removing from filename paramaters
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : new format: $Series ($Volume) - $Issue
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : New Filename: Invincible ($Volume) - 093.cbz
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Source: Invincible - V2003 093.cbz
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Destination: /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible ($Volume) - 093.cbz
07-Mar-2016 15:54:45 - INFO    :: Thread-12 : moving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - V2003 093.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible ($Volume) - 093.cbz
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Issue :999999
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : Renaming files according to configuration details : $Series ($Volume) - $Issue
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : comicid: 17993
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issue#: 999999
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : issueid:None
07-Mar-2016 15:54:45 - DEBUG   :: Thread-12 : annualize is None
07-Mar-2016 15:54:45 - ERROR   :: Thread-12 : Invalid Issue_Number - please validate.
07-Mar-2016 15:54:45 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/opt/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Mylar/mylar/importer.py", line 587, in addComictoDB
    moveit.movefiles(comicid, comlocation, ogcname)
  File "/opt/Mylar/mylar/moveit.py", line 25, in movefiles
    nfilename = renameit['nfilename']
TypeError: 'NoneType' object has no attribute '__getitem__'
`

**Comment by evilhero** [comment]
I think it might be due to having '$Volume' in your file format - the valid options are only '$VolumeY' or '$VolumeN' - having $Volume seems to be leaving it intact during the actual move/rename as you can see from the log
```
moving /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible/Invincible 2003/Invincible - V2003 093.cbz ... to /media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Invincible (2003)/Invincible ($Volume) - 093.cbz```

Try changing the $Volume to either $VolumeY or $VolumeN, save the config and restart Mylar and try that again. I've honestly never seen that happen so far, so if that doesn't solve the issue I'll have to start digging through the code even more...

**Comment by hakarune** [comment]
I made a mistake in my comment. It was `Vol.$VolumeY` and then I changed it to just $Volume without thinking. And now it's $VolumeY, but still giving me that error.  And just realized looking at the logs it's saying issue #9999 before glitching. I'm going to remove the #from my Comic names and see if that fixes it.

**Comment by hakarune** [comment]
Nope. Still has issues and glitches

**Comment by evilhero** [comment]
OK, let's start at the beginning again (or mostly), cause I might be a bit confused atm. 

And they aren't getting renamed properly on an import attempt, correct? 

What is you folder format and file string as you have it now? 

Also, have you restarted mylar at all since doing the file formatting changes in the config?
