### ISSUE TITLE
log Error help

### ISSUE THREAD

**Issue by solspire** [evilhero/mylar#1225]
Hello,
Mylar on nas synology with package synocommunity 
Mylar Version: master
-- git build f0f9cda21ec15451b05c4e930595159540b19e8e.
Python Version : 2.7.11

I make : MANAGE / MANUAL POST PROCESSING
I have 2 folders : one is "fausse-bdtheque-test" (with 2 comics) and the other is "bd-mylar" (the same two comics add with search bar on mylar)

Timestamp   Level   Message
2016-03-07 13:11:22 ERROR   Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(_self.__args, *_self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 912, in Process
self.Process_next(comicid, issueid, issuenumOG, ml, stat)
File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1289, in Process_next
nfilename = helpers.replace_all(chunk_file_format, file_values)
File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 173, in replace_all
text = text.replace(i, j)
TypeError: coercing to Unicode: need string or buffer, NoneType found
2016-03-07 13:11:22 INFO    [POST-PROCESSING] [1/1] Starting Post-Processing for Thorgal issue: 34
2016-03-07 13:11:22 INFO    [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2016-03-07 13:11:22 INFO    [DUPECHECK] Duplicate check for /volume1/Mes-ebooks/fausse-bdtheque-test/Thorgal/Thorgal #34 - Kah Aniel.cbr
2016-03-07 13:11:22 INFO    [POST-PROCESSING] Found matching issue # 34000 for ComicID: 40719 / IssueID: 447745
2016-03-07 13:11:22 INFO    Starting postprocessing for : Manual Run
2016-03-07 13:11:07 INFO    RSS Feed Check was last run at : 2016-03-07 12:56:50
2016-03-07 13:10:47 INFO    No series have been marked as being on auto-watch.
2016-03-07 13:10:47 INFO    Finished checking for comics on my watchlist.
2016-03-07 13:10:47 INFO    Checking the Weekly Releases list for comics I'm watching...
2016-03-07 13:10:47 INFO    No new pull-list available - will re-check again in 24 hours.
2016-03-07 13:10:47 INFO    [PULL-LIST] Populating & Loading pull-list data from file
2016-03-07 13:10:47 INFO    Weekly pull list present - checking if it's up-to-date..
2016-03-07 13:10:47 INFO    [WEEKLY] Checking Weekly Pull-list for new releases/updates
2016-03-07 13:10:37 INFO    delaying startup thread for 60 seconds to avoid locks.
2016-03-07 13:10:37 INFO    Enabling folder monitor for : /volume1/Mes-ebooks/fausse-bdtheque-test every 1 minutes.
2016-03-07 13:10:37 INFO    delaying startup thread for 10 seconds to avoid locks.
2016-03-07 13:10:37 INFO    delaying startup thread for 30 seconds to avoid locks.
2016-03-07 13:10:37 INFO    Checking for existance of Weekly Comic listing...
2016-03-07 13:10:37 INFO    Initiating startup-RSS feed checks.
2016-03-07 13:10:37 INFO    Initializing the DB Updater.
2016-03-07 13:10:37 INFO    Starting Mylar on http://0.0.0.0:8090/
2016-03-07 13:10:37 INFO    Writing PID 19484 to /usr/local/mylar/var/mylar.pid
2016-03-07 13:10:36 INFO    Daemonized to PID: 19484
2016-03-07 13:10:36 INFO    Sucessfully ordered 3 series in your watchlist.
2016-03-07 13:10:36 INFO    Remapping the sorting to allow for new additions.
2016-03-07 13:10:36 INFO    Synology Parsing Fix already implemented. No changes required at this time.
2016-03-07 13:10:36 INFO    Mylar is up to date
2016-03-07 13:10:35 INFO    Retrieving latest version information from github
2016-03-07 13:10:35 INFO    Correcting Null entries that make the main page break on startup.
2016-03-07 13:10:35 INFO    Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2016-03-07 13:10:35 ERROR   Could not locate exceptions.csv file. Make sure it is in datadir: /usr/local/mylar/var/
2016-03-07 13:10:34 INFO    Checking to see if the database has all tables....
2016-03-07 13:10:34 INFO    [DB Module] Loading : sqlite3 as the database module to use.
2016-03-07 13:10:34 INFO    Branch detected & set to : master
2016-03-07 13:10:34 INFO    Successfully discovered local IP and locking it in as : 192.168.0.10

**Comment by evilhero** [comment]
Try running mylar in verbose mode (start it with the -v option, or toggle verbose on in the logs tab within mylar), then run the manual post-processing again and see what the logs say.
