### ISSUE TITLE
New install - can't add comics

### ISSUE THREAD

**Issue by andrzejstepien** [evilhero/mylar#1233]
I just installed Mylar and am having difficulty adding comics. It seems to get stuck at (Comic information is currently being loaded). I have tried it with various comics, to no avail. The directories are getting made no problem, so I'm not sure what's going on here. Any idea? 

2016-03-22 12:25:10	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 456, in addComictoDB
os.remove(coverfile)
OSError: [Errno 2] No such file or directory: '/opt/Mylar/cache/86696.jpg'
2016-03-22 12:25:10	INFO	Trying to grab an alternate cover due to problems trying to retrieve the main cover image.
2016-03-22 12:25:10	WARNING	Unable to download image from CV URL link: http://static5.comicvine.com/uploads/scale_large/6/67663/4955639-01.jpg [Status Code returned: 400]
2016-03-22 12:25:10	INFO	Attempting to retrieve the comic image for series
2016-03-22 12:25:08	INFO	[DIRECTORY-CHECK] Creating comic directory (0777) : /home/cuqui/Documents/Comics/Judge Dredd (2015)
2016-03-22 12:25:08	WARNING	[DIRECTORY-CHECK] Could not find comic directory: /home/cuqui/Documents/Comics/Judge Dredd (2015)
2016-03-22 12:25:08	INFO	Sucessfully retrieved details for Judge Dredd
2016-03-22 12:25:08	INFO	Now adding/updating: Judge Dredd

**Comment by evilhero** [comment]
The 400 indicates that it's a bad/malformed request, but the request URL is fine - I've just added the series to my local build with no errors, and it was able to pull down the initial cover (yours had failed, and was attempting to get an alternate cover). It might be related to the version of python you're currently running against mylar, or if you're running it through a 3rd-party type of plugin.

You could try running Mylar in verbose mode on startup and in a non-daemon mode (-v on the command line will enable verbose logging). You'll be able to view the debugging logs thereafter. Then try adding another series and post the results back - there are times when the error messages get dropped into the console output, but if you're running it as a daemon you'll never see the messages since they get suppressed.

**Comment by andrzejstepien** [comment]
OK so I followed your instructions and tried with another series. Here are the logs:

2016-03-22 14:34:30	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 456, in addComictoDB
os.remove(coverfile)
OSError: [Errno 2] No such file or directory: '/opt/Mylar/cache/79542.jpg'
2016-03-22 14:34:30	DEBUG	invalid image link is here: http://static5.comicvine.com/uploads/scale_large/6/67663/4338449-01.jpg
2016-03-22 14:34:30	INFO	Trying to grab an alternate cover due to problems trying to retrieve the main cover image.
2016-03-22 14:34:30	WARNING	Unable to download image from CV URL link: http://static5.comicvine.com/uploads/scale_large/6/67663/4338449-01.jpg [Status Code returned: 400]
2016-03-22 14:34:30	DEBUG	comic image retrieval status code: 400
2016-03-22 14:34:30	INFO	Attempting to retrieve the comic image for series
2016-03-22 14:34:28	DEBUG	Successfully changed ownership and permissions [cuqui:cuqui] / [0777 / 0660]
2016-03-22 14:34:28	INFO	[DIRECTORY-CHECK] Creating comic directory (0777) : /home/cuqui/Documents/Comics/Akame ga Kill (2015)
2016-03-22 14:34:28	WARNING	[DIRECTORY-CHECK] Could not find comic directory: /home/cuqui/Documents/Comics/Akame ga Kill (2015)
2016-03-22 14:34:28	INFO	Sucessfully retrieved details for Akame ga Kill!
2016-03-22 14:34:28	INFO	Now adding/updating: Akame ga Kill!
2016-03-22 14:34:28	DEBUG	{'ComicIssues': '5', 'ComicName': u'Akame ga Kill!', 'ComicVersion': 'noversion', 'FirstIssueID': u'476667', 'ComicPublisher': u'Yen Press', 'ComicYear': u'2015', 'ComicImageALT': u'http://static4.comicvine.com/uploads/scale_small/6/67663/4338449-01.jpg', 'ComicURL': u'http://comicvine.gamespot.com/akame-ga-kill/4050-79542/', 'ComicImage': u'http://static5.comicvine.com/uploads/scale_large/6/67663/4338449-01.jpg', 'Aliases': 'None'}
2016-03-22 14:34:28	DEBUG	comic[ComicVersion]:noversion
2016-03-22 14:34:28	DEBUG	vari is set to: yes
2016-03-22 14:34:28	DEBUG	number of issues CV says it has: 4
2016-03-22 14:34:28	DEBUG	number of issues I counted: 5

**Comment by evilhero** [comment]
Does the user running Mylar have full authority to the /opt/Mylar/cache/ directory ? 

Which version of python are you running and which branch/commit of mylar ?

**Comment by andrzejstepien** [comment]
Mylar should have full authority in the opt dir. I even gave all users full permissions, but to no avail.

I am running python 2.7.6. I git cloned with this command:

sudo git clone https://github.com/evilhero/mylar -b development /opt/Mylar

So I guess the branch is 'development'. Should I be using something else?

**Comment by evilhero** [comment]
No that's the correct branch, however you're using an older version of python which isn't supported due to SNI/SSL certificate problems. At a minimum, mylar requires python 2.7.9 now, in order to allow it to properly verify against SSL certificates.

So in the one hand, you found a bug with the os.remove option (It will be fixed in the next development commit), but on the other once the bug is fixed, you'll encounter problems due to be on 2.7.6 - the problems could be being able to retrieve data from CV, or grabbing files from your nzb/torrent providers since most seem to be using SSL now.

If you upgrade to 2.7.9, and run mylar the os.remove error will go away on it's own (since it can then retrieve the data from CV without an error)

**Comment by ztaylor38** [comment]
Oddly enough I've been using the same install of mylar for over a year now and I'm starting to get the same errors:

2016-03-22 18:25:15	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 456, in addComictoDB
os.remove(coverfile)
OSError: [Errno 2] No such file or directory: '/opt/Mylar/cache/89163.jpg'
2016-03-22 18:25:15	INFO	Trying to grab an alternate cover due to problems trying to retrieve the main cover image.
2016-03-22 18:25:15	WARNING	Unable to download image from CV URL link: http://static5.comicvine.com/uploads/scale_large/6/67663/5109012-01.jpg [Status Code returned: 400]
2016-03-22 18:25:15	INFO	Attempting to retrieve the comic image for series
2016-03-22 18:25:13	INFO	Directory (/media/nas/Comics/Marvel/Hyperion (2016)) already exists! Continuing...
2016-03-22 18:25:13	INFO	Sucessfully retrieved details for Hyperion
2016-03-22 18:25:13	INFO	Now adding/updating: Hyperion

**Comment by andrzejstepien** [comment]
I'm running Ubuntu 14.04 on an Intel NUC, and I think updating python/OS would be more trouble than it's worth. I've installed Mylar on my Windows PC instead, however, and it seems to be working just fine. Thanks very much for your help!
