### ISSUE TITLE
Random Error on Import [Uncaught exception: Traceback (most recent call last)]

### ISSUE THREAD

**Issue by hakarune** [evilhero/mylar#1236]
i keep trying to import my comics and i keep getting a random error with no solution or reason to it. it happens for every folder i try to import. I was able to import one set of comics after deleting almost every comic in the series so it would add the series and then i had to manually have the app download every issue i deleted and it still have me this error on processing those new comics and took forever to finally get them.

2016-04-04 12:54:34 ERROR   Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 3022, in preSearchit
logger.info(comicinfo['ComicID'])
TypeError: string indices must be integers
2016-04-04 12:54:34 INFO    Checking for any valid metatagging already present.
2016-04-04 12:54:34 DEBUG   Mass importing the following series: [u'Superman: Earth One', u'Batman: Earth One']
2016-04-04 12:54:34 INFO    initiating mass import mode for Batman: Earth One
2016-04-04 12:54:34 INFO    initiating mass import mode for Superman: Earth One
2016-04-04 12:54:03 INFO    Successfully scanned in directory. Enabling the importResults button now.
2016-04-04 12:54:03 DEBUG   filename: Batman - Earth One V2012 #001 - Volume One.cbz
2016-04-04 12:54:03 DEBUG   comicname: Batman: Earth One
2016-04-04 12:54:03 DEBUG   issue_info: None
2016-04-04 12:54:03 DEBUG   soma_sl: {'volume': u'2012', 'comlocation': u'/media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Earth One/Batman 2012/Batman - Earth One V2012 #001 - Volume One.cbz', 'comfilename': 'Batman - Earth One V2012 #001 - Volume One.cbz', 'comicname': u'Batman: Earth One', 'displayname': 'batman: earth one', 'comicyear': u'2012', 'issueid': None, 'impid': u'Batman: Earth One-2012-1', 'watchmatch': None, 'comicid': None}
2016-04-04 12:54:03 DEBUG   filename: Superman - Earth One V2010 #001 - Volume One.cbz
2016-04-04 12:54:03 DEBUG   comicname: Superman: Earth One
2016-04-04 12:54:03 DEBUG   issue_info: None
2016-04-04 12:54:03 DEBUG   soma_sl: {'volume': u'2010', 'comlocation': u'/media/96e60511-62ca-48ba-bccc-9b365bfcc4e5/Comics/Earth One/Superman 2010/Superman - Earth One V2010 #001 - Volume One.cbz', 'comfilename': 'Superman - Earth One V2010 #001 - Volume One.cbz', 'comicname': u'Superman: Earth One', 'displayname': 'superman: earth one', 'comicyear': u'2010', 'issueid': None,

**Comment by hakarune** [comment]
also it wouldn't do anything with cbr, had to manually covert to cbz  fit Mylar to finally try and import them.

**Comment by evilhero** [comment]
The error you pasted will be fixed in the next development commit, as well as a huge backend improvement to the entire import work flow. 

It's actually failing to read a portion of the metadata in the cbz files (or its expecting a specific tag and it's not present for some reason).  If there is no metadata present in the cbz files, it would also throw that error.

**Comment by hakarune** [comment]
Okay, cool. Several of the cbz don't have data, but the ones that do are from ComicRack and they fail too
