### ISSUE TITLE
import_status: Now adding the completed results to the DB error

### ISSUE THREAD

**Issue by max6166** [evilhero/mylar#1239]
Just updated to 19bf048fbba6e3a12985a265de96a1254605d3fe (development). 

When importing, I receive the error message below followed by an infinitely repeating "import_status: Now adding the completed results to the DB" message.

I am importing comics with the following options enabled: Auto-add new series, Use existing Metadata, Move files into corresponding Series directory. Rename Files is not enabled.

If I disable "Use existing Metadata", the import process continues to the Import Results Management section, but many comics are not imported due to multiple search results.

```
09-Apr-2016 11:46:53 - INFO    :: LibraryScan : [IMPORT] Parsing/Reading of files completed!
09-Apr-2016 11:46:53 - ERROR   :: LibraryScan : Uncaught exception: Traceback (most recent call last):
  File "/home/xxxx/.mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxxx/.mylar/mylar/librarysync.py", line 595, in scanLibrary
    logger.info('[IMPORT] Attempting to import ' + str(int(soma['import_cv_ids'] + soma['import_count'])) + ' files into your watchlist.')
TypeError: 'NoneType' object has no attribute '__getitem__'

09-Apr-2016 11:46:54 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:46:59 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:04 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:09 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:14 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:19 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:24 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:29 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:34 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:39 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:44 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:49 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:54 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:47:59 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
09-Apr-2016 11:48:04 - INFO    :: CP Server Thread-6 : import_status: Now adding the completed results to the DB.
```

**Comment by evilhero** [comment]
Try running mylar in verbose mode ( - v option from a command line, or toggle verbose mode in the GUI log).  

Either the number of issues it discovered is 0, or the total amount of issues scanned is 0 (I'm going to guess the first one)  -  seeing the debug logs would help to see what's happening so I can fix things.

**Comment by max6166** [comment]
Below is the output in verbose mode on importing 1 comic. 

Don't know if it is relevant, but the log says, "0 files are in a cbz format" despite the file being a CBZ.

```
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : Scanning comic directory: /media/xxxx/Storage_01/Comics/_Incoming
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : I have successfully discovered & parsed a total of 1 files....analyzing now
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : I have not been able to determine what 0 files are
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : However, 0 files are in a cbz format, which may contain metadata.
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : loading in the watchlist to see if a series is being watched already...
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : Successfully loaded 4210 series from your watchlist.
09-Apr-2016 12:18:02 - INFO    :: LibraryScan : [IMPORT-CBZ} Attempting to read tags present in filename: /media/xxxx/Storage_01/Comics/_Incoming/The Punisher 007 (2014) (digital) (CompetentRipper-Empire).cbz
09-Apr-2016 12:18:03 - INFO    :: LibraryScan : issueinfo: [{'publisher': u'Marvel', 'letterer': u'Cory Petit', 'title': u'El Diablito Part One', 'webpage': u'http://comicvine.gamespot.com/the-punisher-7-el-diablito-part-one/4000-456553/', 'series': u'The Punisher', 'notes': u'Tagged with ComicTagger 1.1.15-beta using info from Comic Vine on 2016-04-09 11:40:03.  [Issue ID 456553]', 'writer': u'Kevin Maurer, Nathan Edmondson', 'summary': u'The international best-selling author of NOT A GOOD DAY TO DIE, KEVIN MAURER joins Nathan Edmondson to tell a story of Punisher in jungle warfare!\n\nA group of American soldiers are being held prisoner by a South American drug lord, and suddenly a new prisoner arrives\u2026Frank Castle!\n\nBut not all is as it seems on EITHER side of the bars in this jail tale!\n\nTagged with ComicTagger 1.1.15-beta using info from Comic Vine on 2016-04-09 11:40:03.  [Issue ID 456553]\n\nhttp://comicvine.gamespot.com/the-punisher-7-el-diablito-part-one/4000-456553/', 'volume': u'2014', 'penciller': u'Carmen Nunez Carnero, Carmen Nunez Carnero, Carmen Nunez Carnero', 'issue_number': u'7', 'pagecount': u'22', 'colorist': u'Antonio Fabela', 'year': u'2014', 'cover_artist': u'Mitch Gerads', 'IssueImage': 'cache/temp.jpg?1460218683.0', 'month': u'08', 'inker': u'Terry Pallot, Carmen Nunez Carnero, Carmen Nunez Carnero', 'day': u'31', 'editor': u'Jake Thomas'}]
09-Apr-2016 12:18:03 - INFO    :: LibraryScan : [IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
09-Apr-2016 12:18:03 - INFO    :: LibraryScan : tmpidlist: 456553
09-Apr-2016 12:18:07 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:07 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:07 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:12 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:12 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:12 - INFO    :: CP Server Thread-7 : import_status: Now Reverse looking up 1 IssueIDs to get the ComicIDs
09-Apr-2016 12:18:15 - INFO    :: LibraryScan : tempseries:{'Issue_Number': u'7', 'ComicName': u'The Punisher', 'Issue_Name': u'El Diablito Part One', 'IssueID': u'456553', 'ComicID': u'71435'}
09-Apr-2016 12:18:15 - INFO    :: LibraryScan : [IMPORT] Parsing/Reading of files completed!
09-Apr-2016 12:18:15 - ERROR   :: LibraryScan : Uncaught exception: Traceback (most recent call last):
  File "/home/xxxx/.mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxxx/.mylar/mylar/librarysync.py", line 595, in scanLibrary
    logger.info('[IMPORT] Attempting to import ' + str(int(soma['import_cv_ids'] + soma['import_count'])) + ' files into your watchlist.')
TypeError: 'NoneType' object has no attribute '__getitem__'

09-Apr-2016 12:18:17 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:17 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:17 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:22 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:22 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:22 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:27 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:27 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:27 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:32 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:32 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:32 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:37 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:37 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:37 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:42 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:42 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
09-Apr-2016 12:18:42 - INFO    :: CP Server Thread-7 : import_status: Now adding the completed results to the DB.
```

**Comment by evilhero** [comment]
Perfect log!

I was able to exactly duplicate that error and find/fix the problem ;) It was bombing out when the parsed filenames were 0, even though there were metatagged filenames successfully identified.

Will be coming in the next development commit. Cheers for that log!

**Comment by max6166** [comment]
Cheers! That's great!
