### ISSUE TITLE
Problem with # in filenames

### ISSUE THREAD

**Issue by dreadxero** [evilhero/mylar#1242]
I have noticed a new issue with the latest dev branch that seems to be related to #. This seems to occur with anything with a title that has a number in it or a period in the issue number. Here are some examples: 

`Ravage 2099 001 (1992)` works fine 
`Ravage 2099  #001 (1992)` archived

`Peter Parker Spider-Man 156.1 (2012)` works fine
`Peter Parker Spider-Man #156.1 (2012)` seems to crash when I recheck files with:

Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/updater.py", line 784, in forceRescan
tmpval = tval.listFiles()
File "/opt/mylar/mylar/filechecker.py", line 171, in listFiles
'sub': runresults['sub'],
KeyError: 'sub'

**Comment by evilhero** [comment]
Weird, the sub key is for tracking subdirectories - so not really sure why it would be erroring out off of that when it has the # in the filename. 

I'll check it out and see what is happening.

**Comment by dreadxero** [comment]
Here is a debug with another one. Looks like the "2 seperate numbers detected" isnt working with a # in filename

```
12-Apr-2016 16:11:41 - INFO    :: Thread-18 : [FILENAME]: Spider-Man 1602 #001 (2009).cbz
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : checking date : 2009
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : date: 2009
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : datecheck: [{'date': '2009', 'position': 3, 'mod_position': 21}]
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : sctd: 2016
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : year verified as : 2009
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : year verified as: 2009
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : highest_series_position: 3
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : possible_issuenumbers: [{'position': 1, 'validcountchk': False, 'number': '1602', 'mod_position': 11}]
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : issue verified as : 1602
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : series title possibly: Spider-Man
12-Apr-2016 16:11:41 - INFO    :: Thread-18 : Series_Name: spider-man --- WatchComic: spider-man 1602
12-Apr-2016 16:11:41 - DEBUG   :: Thread-18 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
12-Apr-2016 16:11:41 - INFO    :: Thread-18 : [NO MATCH] Spider-Man 1602 #001 (2009).cbz [WATCHLIST:Spider-Man 1602]
12-Apr-2016 16:11:41 - ERROR   :: Thread-18 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/updater.py", line 784, in forceRescan
    tmpval = tval.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 171, in listFiles
    'sub':            runresults['sub'],
KeyError: 'sub'
```

```
12-Apr-2016 16:12:23 - INFO    :: Thread-19 : [FILENAME]: Spider-Man 1602 001 (2009).cbz
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : 2 seperate numbers detected. Assuming 2nd number is the actual issue
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : checking date : 2009
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : date: 2009
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : datecheck: [{'date': '2009', 'position': 3, 'mod_position': 20}]
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : sctd: 2016
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : year verified as : 2009
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : year verified as: 2009
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : highest_series_position: 3
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : possible_issuenumbers: [{'position': 1, 'validcountchk': False, 'number': '1602', 'mod_position': 11}, {'position': 2, 'validcountchk': False, 'number': '001', 'mod_position': 16}, {'position': 2, 'validcountchk': False, 'number': '001', 'mod_position': 16}]
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : dash is in first word, not considering for determing issue number.
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : issue number :001
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : series title possibly: Spider-Man 1602
12-Apr-2016 16:12:23 - INFO    :: Thread-19 : Series_Name: spider-man 1602 --- WatchComic: spider-man 1602
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
12-Apr-2016 16:12:23 - DEBUG   :: Thread-19 : [MATCH: Spider-Man 1602] Spider-Man 1602 001 (2009).cbz
```

**Comment by evilhero** [comment]
Yep I was able to confirm this almost immediately when I tried it. I also have it fixed in my local branch (tested against the two filenames you posted initially). 

Just haven't been able to make it back to my machine to push it out, but should expect the fix for it in a few hrs...

**Comment by dreadxero** [comment]
Seems to be working now thanks
