### ISSUE TITLE
Error when Initiating manual search

### ISSUE THREAD

**Issue by cclick815** [evilhero/mylar#1243]
I keep getting the following error when doing a manual search.

2016-04-12 19:53:53 ERROR   Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1332, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/opt/Mylar/mylar/search.py", line 232, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/opt/Mylar/mylar/search.py", line 917, in NZB_SEARCH
cleantitle = re.sub(origvol, '', cleantitle).strip()
File "/usr/lib/python2.7/re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "/usr/lib/python2.7/re.py", line 247, in _compile
raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern
2016-04-12 19:53:52 INFO    Shhh be very quiet...I'm looking for Spider-Man issue: 3 (2016) using experimental [RSS]
2016-04-12 19:53:52 INFO    search provider order is ['Experimental', 'newznab:NZBgeek', 'newznab:Usenet-Crawler']
2016-04-12 19:53:52 INFO    Issue Title given as : None
2016-04-12 19:53:52 INFO    Initiating manual search for Spider-Man issue: 3

**Comment by evilhero** [comment]
Ugh I thought I had patched that yesterday, but I guess I didn't.  I'll commit out the fix in the next hr or two that will fix things up.
