### ISSUE TITLE
Traceback error after trying to recheck files.

### ISSUE THREAD

**Issue by Nobrumski** [evilhero/mylar#1249]
I was trying the latest update to see if it would find the files if I rechecked them. 

13-Apr-2016 21:42:43 - INFO :: Thread-14 : [FILE-RESCAN] Now checking files for 5 Ronin (2011) in Z:\Mylar\Marvel/5 Ronin (2011)
13-Apr-2016 21:42:43 - INFO :: Thread-14 : there are 5 files.
13-Apr-2016 21:42:43 - INFO :: Thread-14 : [FILENAME]: 5 Ronin 1 V2011 (2011).cbz
13-Apr-2016 21:42:43 - INFO :: Thread-14 : Series_Name: 5 --- WatchComic: 5 ronin
13-Apr-2016 21:42:43 - INFO :: Thread-14 : [NO MATCH] 5 Ronin 1 V2011 (2011).cbz [WATCHLIST:5 Ronin]
13-Apr-2016 21:42:43 - ERROR :: Thread-14 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar-development\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Mylar\mylar-development\mylar\updater.py", line 784, in forceRescan
    tmpval = tval.listFiles()
  File "C:\Mylar\mylar-development\mylar\filechecker.py", line 171, in listFiles
    'sub':            runresults['sub'],
KeyError: 'sub'

Traceback (most recent call last):
  File "C:\Mylar\mylar-development\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Mylar\mylar-development\mylar\updater.py", line 784, in forceRescan
    tmpval = tval.listFiles()
  File "C:\Mylar\mylar-development\mylar\filechecker.py", line 171, in listFiles
    'sub':            runresults['sub'],
KeyError: 'sub'

**Comment by evilhero** [comment]
Fix will be coming in a bit, just haven't had a chance to make it back to a machine to push it out. 

It's trying to log the fact that it can't parse the file properly and the sub key tracks the subdirectory in the path - it's just referencing it wrong.
