### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1252]
Below is an error that i have been getting, I'm on the latest development version

Any idea what this error means?

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/mylar/search.py", line 1658, in searchIssueIDList
foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/volume1/@appstore/mylar/mylar/search.py", line 254, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/volume1/@appstore/mylar/mylar/search.py", line 1461, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/volume1/@appstore/mylar/mylar/search.py", line 2073, in searcher
send_to_nzbget = server.append(nzbpath, str(mylar.NZBGET_CATEGORY), int(nzbgetpriority), True, nzbcontent64)
File "/usr/lib/python2.7/xmlrpclib.py", line 1240, in __call__
return self.__send(self.__name, args)
File "/usr/lib/python2.7/xmlrpclib.py", line 1599, in __request
verbose=self.__verbose
File "/usr/lib/python2.7/xmlrpclib.py", line 1280, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python2.7/xmlrpclib.py", line 1328, in single_request
response.msg,
ProtocolError:

**Comment by evilhero** [comment]
Try using either 0.0.0.0 or the ip itself of the machine instead of localhost for the nzbget host address within mylar.
