### ISSUE TITLE
Traceback exception when initiating a manual search

### ISSUE THREAD

**Issue by Silverwulf** [evilhero/mylar#1257]
Since about last week Mylar hasnt been downloading new issues and I have been getting this error whenever I initiate a manual search:

Uncaught exception: Traceback (most recent call last):
 File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\logger.py", line 158, in new_run
 old_run(_args, *_kwargs)
 File "C:\Python27\lib\threading.py", line 763, in run
 self.__target(_self.__args, *_self.__kwargs)
 File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\search.py", line 1580, in searchforissue
 foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
 File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\search.py", line 254, in search_init
 findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
 File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\search.py", line 540, in NZB_SEARCH
 findurl = findurl + "&apikey=" + str(apikey)
UnboundLocalError: local variable 'findurl' referenced before assignment

**Comment by evilhero** [comment]
Check your newznab configuration - either in the GUI or the config.ini 
You most likely have a blank newznab entry and it's causing it to error out, or you've made configuration changes without restarting Mylar (provider changes in most cases seem to require this restart). 

I've fixed this in the next development release now (if it's a blank entry), so it won't throw the above error but will indicate that there's a configuration problem.

**Comment by Silverwulf** [comment]
I've done a new re-clone and re-set up my entire configuration and I still seem to be getting this error. I have checked the GUI and there isn't a blank newsnab entry. I am only using nzb.su. I have also restarted Mylar.


________________________________

**Comment by evilhero** [comment]
Then you might need to check the provider_order field within your config.ini

Somewhere you have an entry that doesn't exist and its causing the error. With mylar shutdown, if you delete the entire provider_order line, save the config.ini and them start mylar it will regenerate a clean one on startup.

**Comment by Silverwulf** [comment]
It seems if I have Kat as a search provider I get the error but as soon as that is disabled it seems to work fine.

**Comment by evilhero** [comment]
Start mylar with verbose mode on (-v on startup), or toggle verbose on in the log tab within Mylar.  Then try to do a search and paste back the debug log leading up to the error (make sure to remove any api keys if they happen to come through) .

**Comment by lostkt87** [comment]
Ok, Here is my Traceback error with debug mode. i have double checked all of my providers api and uids.

ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/mylar/search.py", line 1658, in searchIssueIDList
foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/volume1/@appstore/mylar/mylar/search.py", line 254, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/volume1/@appstore/mylar/mylar/search.py", line 1290, in NZB_SEARCH
elif int(F_ComicVersion) == int(D_ComicVersion) or int(F_ComicVersion) == int(S_ComicVersion):
ValueError: invalid literal for int() with base 10: ''
2016-04-24 21:53:30	DEBUG	SCVersion: 2011
2016-04-24 21:53:30	DEBUG	DCVersion: 1
2016-04-24 21:53:30	DEBUG	FCVersion:
2016-04-24 21:53:30	DEBUG	vers4vol: v04
2016-04-24 21:53:30	DEBUG	vers4year: no
2016-04-24 21:53:30	DEBUG	version found: vol
2016-04-24 21:53:30	DEBUG	watch comicversion is None
2016-04-24 21:53:30	DEBUG	volume detection commencing - adjusting length.
2016-04-24 21:53:30	DEBUG	['wonder', 'woman'] watchlist word count: 2
2016-04-24 21:53:30	DEBUG	['wonder', 'woman', '051'] nzb series word count: 2
2016-04-24 21:53:30	DEBUG	adjusting from: wonder woman 051 to: 051
2016-04-24 21:53:30	DEBUG	adjusted nzb comic and issue: wonder woman 051
2016-04-24 21:53:30	DEBUG	original nzb comic and issue: wonder woman 051
2016-04-24 21:53:30	DEBUG	Scanner detected: thornn-empire
2016-04-24 21:53:30	DEBUG	7. Bracket Word: thornn-empire
2016-04-24 21:53:30	DEBUG	5. Bracket Word: hd
2016-04-24 21:53:30	DEBUG	digital edition detected
2016-04-24 21:53:30	DEBUG	3. Bracket Word: digital
2016-04-24 21:53:30	DEBUG	2016 - right years match baby!
2016-04-24 21:53:30	DEBUG	year looking for: 2016
2016-04-24 21:53:30	DEBUG	year detected: 2016
2016-04-24 21:53:30	DEBUG	1. Bracket Word: 2016
2016-04-24 21:53:30	DEBUG	Year not given properly formatted but Version detected.Bypassing Year Match.
2016-04-24 21:53:30	DEBUG	ComVersChk : 0
2016-04-24 21:53:30	DEBUG	UseFuzzy is : None
2016-04-24 21:53:30	DEBUG	Comic: wonder woman 051
2016-04-24 21:53:30	DEBUG	0. Bracket Word: wonder woman 051
2016-04-24 21:53:30	DEBUG	Cleantitle: wonder woman 051 (2016) (digital) (hd) (thornn-empire)
2016-04-24 21:53:30	DEBUG	Newly finished reformed cleantitle (with NO volume label): wonder woman 051 (2016) (digital) (hd) (thornn-empire)
2016-04-24 21:53:30	DEBUG	[Vxxx] Version detected as v04
2016-04-24 21:53:30	DEBUG	Newly finished reformed cleantitle (with NO volume label): wonder woman 051 (2016) (digital) (hd) (thornn-empire)
2016-04-24 21:53:30	INFO	[0, 1, 2, 3, 4, 5, 6, 7, 8]
2016-04-24 21:53:30	DEBUG	Split Volume label detected [04] - ie. Vol 4. Attempting to adust.
2016-04-24 21:53:30	DEBUG	volume detected - stripping and re-analzying for volume label.
2016-04-24 21:53:30	DEBUG	Cleantitle: wonder woman vol 04 051 (2016) (digital) (hd) (thornn-empire)
2016-04-24 21:53:30	DEBUG	Entry: Wonder Woman Vol 04 051 (2016) (Digital) (HD) (Thornn-Empire)
2016-04-24 21:53:30	DEBUG	Thu, 21 Apr 2016 15:02:25 -0400 is after store date of 2016-04-20
2016-04-24 21:53:30	DEBUG	size given as: 41.6 MB
2016-04-24 21:53:30	DEBUG	sub:Wonder Woman Vol 04 051 (2016) (Digital) (HD) (Thornn-Empire)
2016-04-24 21:53:30	DEBUG	checking search result: Wonder Woman Vol 04 051 (2016) (Digital) (HD) (Thornn-Empire)
2016-04-24 21:53:30	DEBUG	[SSL: False] Search URL: https://api.nzb.su/api?t=search&q=wonder%20woman%20051&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-04-24 21:52:30	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-04-24 21:52:30	DEBUG	comicid: 42953
2016-04-24 21:52:30	DEBUG	nzbprov: nzb.su
2016-04-24 21:52:30	DEBUG	RSS Check: None
2016-04-24 21:52:30	DEBUG	calpha/cnumber: None / None
2016-04-24 21:52:30	INFO	Shhh be very quiet...I'm looking for Wonder Woman issue: 51 (2016) using nzb.su
2016-04-24 21:52:30	DEBUG	Initiating Search via : api
2016-04-24 21:52:30	INFO	search provider order is ['nzb.su', 'dognzb', 'newznab:NZBGeek']
2016-04-24 21:52:30	DEBUG	provider order sequence is now to start with NZBGeek at spot #2
2016-04-24 21:52:30	DEBUG	sucessfully matched - appending to provider.order sequence
2016-04-24 21:52:30	DEBUG	newznab match against: newznab:NZBGeek
2016-04-24 21:52:30	DEBUG	checking against nzb provider: newznab:NZBGeek
2016-04-24 21:52:30	DEBUG	checking against nzb provider: dognzb
2016-04-24 21:52:30	DEBUG	checking against nzb provider: nzb.su
2016-04-24 21:52:30	DEBUG	found provider in existing enabled providers.
2016-04-24 21:52:30	DEBUG	provider order sequence is now to start with dognzb at spot #1
2016-04-24 21:52:30	DEBUG	checking against nzb provider: dognzb
2016-04-24 21:52:30	DEBUG	checking against nzb provider: nzb.su
2016-04-24 21:52:30	DEBUG	found provider in existing enabled providers.
2016-04-24 21:52:30	DEBUG	provider order sequence is now to start with nzb.su at spot #0
2016-04-24 21:52:30	DEBUG	checking against nzb provider: nzb.su
2016-04-24 21:52:30	DEBUG	found provider in existing enabled providers.
2016-04-24 21:52:30	DEBUG	Usenet Retention : 2000 days
2016-04-24 21:52:30	DEBUG	there are : 3 nzb providers you have selected.
2016-04-24 21:52:30	DEBUG	there are : 0 torrent providers you have selected.
2016-04-24 21:52:30	DEBUG	nzbprovider(s): ['nzb.su', 'dognzb', 'newznab:NZBGeek']
2016-04-24 21:52:30	DEBUG	newznab name:NZBGeek @ https://api.nzbgeek.info/
2016-04-24 21:52:30	DEBUG	Checking for torrent enabled.
2016-04-24 21:52:30	INFO	Issue Title given as : family ties
2016-04-24 21:52:30	DEBUG	Publisher is : DC Comics
2016-04-24 21:52:30	DEBUG	Marking issues: ['526033'] as Wanted
2016-04-24 21:52:30	DEBUG	updated...to Wanted
2016-04-24 21:52:30	DEBUG	Marking Wonder Woman 51 as Wanted
2016-04-24 21:52:23	DEBUG	Weekly pull list present - retrieving pull-list date.
2016-04-24 21:50:52	DEBUG	If you read this message, debug logging is available
2016-04-24 21:50:52	INFO	Verbose toggled, set to Tru
