### ISSUE TITLE
Something or some things are amiss. Can't download

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1260]
I realized this started a couple weeks ago. New issues not dl'ing. Other nzb apps fine.

Saw that it was looking for issue 2 of "one piece" for ages so deleted comic. Got an error. Now it looked for another comic and seemed to have stopped. 

Sorry, this is the webpage log. I'm traveling and this is my ipad.

```

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
2016-04-24 11:45:55
INFO
Shhh be very quiet...I'm looking for Iron Man: The Secret Origin of Tony Stark issue: 1 (2013) using dognzb [RSS]
2016-04-24 11:45:55
INFO
search provider order is ['dognzb', 'Experimental', 'newznab:nzbs.in', 'newznab:nzb.cat', 'newznab:http://']
2016-04-24 11:45:55
INFO
Issue Title given as : book 1
2016-04-24 11:45:55
INFO
[SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Iron Man The Secret Origin of Tony Stark
2016-04-24 11:45:55
INFO
Initiating Search Scan at scheduled interval of 20 minutes.
2016-04-24 11:45:55
INFO
[RSS] Watchlist Check for new Releases
2016-04-24 11:45:55
INFO
[RSS] RSS Feed Check/Update Complete
2016-04-24 11:45:54
INFO
[RSS] 25 entries have been indexed and are now going to be stored for caching.
2016-04-24 11:45:54
INFO
[RSS] (nzb.cat) 0 entries indexed.
2016-04-24 11:45:54
INFO
[RSS] (nzbs.in) 0 entries indexed.
2016-04-24 11:45:54
INFO
[RSS] (dognzb) 25 entries indexed.
2016-04-24 11:45:54
INFO
[RSS] (experimental) 0 entries indexed.
2016-04-24 11:45:54
WARNING
Error fetching RSS Feed Data from http://: Invalid URL u'http:///rss?t=7030&dl=1&i=1&num=100&r=': No host supplied
2016-04-24 11:45:52
INFO
[RSS] Initiating RSS Feed Check for NZB Providers.
2016-04-24 11:45:52
INFO
RSS Feed Check was last run at : 2016-04-24 11:19:43
2016-04-24 11:45:22
INFO
delaying thread for 30 seconds to avoid locks.
2016-04-24 11:43:36
ERROR
Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\search.py", line 1586, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "C:\Mylar\mylar\search.py", line 254, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Mylar\mylar\search.py", line 605, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-04-24 11:43:36
WARNING
Error fetching data from newznab: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
2016-04-24 11:42:34
INFO
pausing for 60 seconds before continuing to avoid hammering
2016-04-24 11:42:34
INFO
Shhh be very quiet...I'm looking for One Piece issue: 2 (2003) using http:// (newznab)
2016-04-24 11:42:34
INFO
Could not find Issue 2 of One Piece(2003) using nzb.cat [api]
2016-04-24 11:41:34
INFO
pausing for 60 seconds before continuing to avoid hammering
2016-04-24 11:40:33
INFO
pausing for 60 seconds before continuing to avoid hammering
2016-04-24 11:39:09
INFO
Deleting all traces of Comic: One Piece
Showing 1 to 25 of 120 lines
FirstPrevious12345NextLast
```

**Comment by AtariBaby** [comment]
Seemed to have fixed it by deleting 2nd comic. Are those other error messages normal?

**Comment by evilhero** [comment]
The r.status_code  error and other errors are all related to a blank newznab entry you have in either your provider_order line, or within the newznab section of the configuration ('newznab:http://') 

Just delete the entry from your configuration, save the config. Shutdown mylar and edit the config.ini and delete the entire provider_order line and then save it and start up mylar and you're back in the running again.
