### ISSUE TITLE
Error when getting info

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1263]
From the Pull List, clicking 'add series' on DOCTOR STRANGE LAST DAYS OF MAGIC, I get sent to this URL
`http://localhost:8090/searchit?name=DOCTOR+STRANGE+LAST+DAYS+OF+MAGIC&issue=1&mode=pullseries
`
With this error

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 221, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=issue)
  File "/Applications/Mylar/mylar/mb.py", line 293, in findComic
    possible_years = int(xmlYr) + tmpyearRange
ValueError: invalid literal for int() with base 10: '197-'

```

**Comment by partymike** [comment]
I get a similar error when preforming a search, since the last update:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 233, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=None, explicit=explicit)
  File "C:\Mylar\mylar\mb.py", line 293, in findComic
    possible_years = int(xmlYr) + tmpyearRange
ValueError: invalid literal for int() with base 10: '198-'

**Comment by evilhero** [comment]
Fix is up in the most recent development commit - was due to invalid dates being returned from CV (that actually had nothing to do with the series itself, but was causing the problem)
