### ISSUE TITLE
Post-Processing isn't doing anything.

### ISSUE THREAD

**Issue by Budlyte** [evilhero/mylar#1274]
My post-processing is finding the files, it should know where to put them since it is watching the series and downloaded the issues. 

The only thing I can think of that might be happening is that the files are stored on a NAS and there might be some permission issues.

Or maybe Ubooquity is keeping the files held in place?  Either way there doesn't appear to be any log of an error.
![capture](https://cloud.githubusercontent.com/assets/4451365/15052494/9d758e96-12c3-11e6-8c33-668eeca8458b.PNG)

**Comment by Budlyte** [comment]
Ok.  Found the Debug option in the Logs and it looks like it keeps getting hung up on the path for one item.

It looks like the system is duplicating the start of the path here for some reason.  Still though, everything else comes out okay in the logs, but still is not getting moved.


2016-05-05 13:53:23	DEBUG	'Traceback (most recent call last):\n File "C:\\Mylar\\mylar\\scheduler.py", line 78, in runAction\n self.action.run()\n File "C:\\Mylar\\mylar\\PostProcessor.py", line 1902, in run\n result = PostProcess.Process()\n File "C:\\Mylar\\mylar\\PostProcessor.py", line 1049, in Process\n dupthis = helpers.duplicate_filecheck(ml[\'ComicLocation\'], ComicID=comicid, IssueID=issueid)\n File "C:\\Mylar\\mylar\\helpers.py", line 1741, in duplicate_filecheck\n filesz = os.path.getsize(filename)\n File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\**'\\\\\\\\DISKSTATION1\\\\public\\\\DISKSTATION1\\\\public\\\**\Comics\\\\Polluted\\\\Detective.Comics.052.2016.2.covers.Digital.TLK-EMPIRE-HD\\\\Detective Comics 052(2016)(2 covers)(Digital)(TLK-EMPIRE-HD).cbr\'\n'

2016-05-05 13:53:23	DEBUG	Exception generated in thread FOLDERMONITOR: [Error 3] The system cannot find the path specified: u'\\**\\DISKSTATION1\\public\\DISKSTATION1\\public\**\Comics\\Polluted\\Detective.Comics.052.2016.2.covers.Digital.TLK-EMPIRE-HD\\Detective Comics 052(2016)(2 covers)(Digital)(TLK-EMPIRE-HD).cbr'

2016-05-05 13:45:49	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 1049, in Process
dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
File "C:\Mylar\mylar\helpers.py", line 1741, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "C:\Python27\lib\genericpath.py", line 57, in getsize
return os.stat(filename).st_size
WindowsError: [Error 3] The system cannot find the path specified: u'\\**\\DISKSTATION1\\public\\DISKSTATION1\\public\**\Comics\\Polluted\\Detective.Comics.052.2016.2.covers.Digital.TLK-EMPIRE-HD\\Detective Comics 052(2016)(2 covers)(Digital)(TLK-EMPIRE-HD).cbr'

**Comment by evilhero** [comment]
Are you on the master or development build of mylar?  The reason being that I rolled out a fix for this (which was basically anything in more than 1 level deep of subfolders)  in the development branch, that isn't in the master yet.

**Comment by Budlyte** [comment]
Development branch. But it just updated to a new build today. I'll let it run for the day and check again tomorrow morning.

**Comment by evilhero** [comment]
While you're at it, can you paste in what you're giving for the folder that's being monitored?

**Comment by Budlyte** [comment]
\\DISKSTATION1\public\Comics\Polluted

I guess it being in my public shared folder in the NAS rules out the permission issues.   I just checked again and still nothing has moved.  I'll set it to the manual IP and see if that makes a difference I guess.

**Comment by evilhero** [comment]
Well it could be permissions - I mean mylar is being rub from a windows machine and accessing the NAS share.  

It's actually failing at the very first part of the post-processing, the duplicate check where it tries to get the size of the file. 

Can you paste in the debug lines leading up to the error? If you're on the most recent development build, then this is a new type of error that's messing up the path for some reason.

**Comment by Budlyte** [comment]
Yep, you're right.


2016-05-05 22:30:30	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 1049, in Process
dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
File "C:\Mylar\mylar\helpers.py", line 1741, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "C:\Python27\lib\genericpath.py", line 57, in getsize
return os.stat(filename).st_size
WindowsError: [Error 3] The system cannot find the path specified: u'\\\\DISKSTATION1\\public\\DISKSTATION1\\public\\Comics\\Polluted\\Ultimates.006.2016.Digital.Zone-Empire\\Ultimates 006 (2016) (Digital) (Zone-Empire).cbr'

2016-05-05 22:30:30	INFO	[DUPECHECK] Duplicate check for \\DISKSTATION1\public\DISKSTATION1\public\Comics\Polluted\Ultimates.006.2016.Digital.Zone-Empire\Ultimates 006 (2016) (Digital) (Zone-Empire).cbr

2016-05-05 22:30:30	DEBUG	[POST-PROCESSING] Now Checking if the issue also resides in one of the storyarc's that I am watching.

2016-05-05 22:30:30	DEBUG	[POST-PROCESSING] There are 26 files found that match on your watchlist, 0 do not match anything and will be ignored.

**Comment by evilhero** [comment]
Gonna sound stupid, but can you add a trailing slash onto the end of the folder path you're submitting and try again? And also can you verify the branch/commit you're running?

**Comment by Budlyte** [comment]
That doesn't sound stupid, that's an oversight on my part.  I've updated and restarted Mylar, but now nothing is showing in the logs when I Go Manual Run.

Gonna have to try again tomorrow, spouse is whining about going to bed.


Configuration Options
Mylar Version: development
-- git build 09f6e32d603a818f3cba9d4f6161049457602eb0.
Python Version : 2.7.10

Thank you for your help so far.   :)

**Comment by Budlyte** [comment]
Alright, here's the error I'm getting now.


2016-05-06 09:01:55	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 248, in Process
filelist = flc.listFiles()
File "C:\Mylar\mylar\filechecker.py", line 133, in listFiles
runresults = self.parseit(self.dir, filename, filedir)
File "C:\Mylar\mylar\filechecker.py", line 206, in parseit
tmppath = re.sub(path, '', subpath).strip()
File "C:\Python27\lib\re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "C:\Python27\lib\re.py", line 251, in _compile
raise error, v # invalid expression
error: bogus escape (end of line)

2016-05-06 09:01:55	INFO	[FILENAME]: Ultimates 006 (2016) (Digital) (Zone-Empire).cbr

2016-05-06 09:01:55	INFO	there are 26 files.

2016-05-06 09:01:54	INFO	Starting postprocessing for : Manual Run

**Comment by evilhero** [comment]
Sorry, can you paste in the debug logs for that?  I need to see what the directory path is that its doing... Something is wrong somewhere, but I can't see where atm for some reason.

**Comment by Budlyte** [comment]
My fault. Didn't check that it was still on after a reboot.


2016-05-06 09:12:21	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 248, in Process
filelist = flc.listFiles()
File "C:\Mylar\mylar\filechecker.py", line 133, in listFiles
runresults = self.parseit(self.dir, filename, filedir)
File "C:\Mylar\mylar\filechecker.py", line 206, in parseit
tmppath = re.sub(path, '', subpath).strip()
File "C:\Python27\lib\re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "C:\Python27\lib\re.py", line 251, in _compile
raise error, v # invalid expression
error: bogus escape (end of line)

2016-05-06 09:12:21	DEBUG	[SUB-PATH] Sub-direcotry : 
\\DISKSTATION1\public\Comics\Polluted\Ultimates.006.2016.Digital.Zone-Empire

2016-05-06 09:12:21	DEBUG	[SUB-PATH] Original Path : \\DISKSTATION1\public\Comics\Polluted\

2016-05-06 09:12:21	DEBUG	[SUB-PATH] Checking Folder Name for more information.

2016-05-06 09:12:21	DEBUG	[CORRECTION] Sub-directory found. Altering path configuration.

2016-05-06 09:12:21	INFO	[FILENAME]: Ultimates 006 (2016) (Digital) (Zone-Empire).cbr

2016-05-06 09:12:21	INFO	there are 26 files.

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] Manual Run initiated

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] Manual Run Post-Processing enabled.

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] NZB name as passed from NZBGet: Manual Run

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] Not using SABnzbd

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] nzb folder: \\DISKSTATION1\public\Comics\Polluted\

2016-05-06 09:12:20	DEBUG	[POST-PROCESSING] nzb name: Manual Run

2016-05-06 09:12:20	INFO	Starting postprocessing for : Manual Run

**Comment by evilhero** [comment]
Ok, I was able to get onto a machine finally to see what's going on. The first way you had it is actually the correct way to submit the path (without the trailing slash), although Mylar should be able to account for either way, and will eventually.

In looking at this, it looks like Mylar is having problems determining the actual sub-directory from within the path - but it only affects Windows users due to the way the slash is (in python, it's an escape character). I'm running through abunch of tests now to see if I can figure out a way for Mylar to handle this properly without breaking it for other OS'

As soon as I figure it out, I'll post back in here and then (most likely) indicate it will be in the next development branch ;)

**Comment by evilhero** [comment]
Hopefully you can test this out for me to see if it works for you .If you could do the following it would be greatly appreciated.

First shutdown Mylar.
Backup the file mylar/filechecker.py to another location
Grab the new filechecker : https://gist.github.com/evilhero/6f93157f8d7ce3ebf7d7b4af37e2ec63
Start up mylar with the new-filechecker and see if you can manually post-process without any issues. If you do happen to have issues (I'm not 100% positive this will work), throw me a message back and I'll try another method.

**Comment by Budlyte** [comment]
Yep. It ran fine that time. I spot checked a few to make sure it did everything it should and all looks well now.  Thank you!
