### ISSUE TITLE
Error Adding New Volume

### ISSUE THREAD

**Issue by pardus79** [evilhero/mylar#1277]
Currently running 33a43262d286da4549a0419652dc63f290764e28

I'm unable to add new comics. Both adding from search and from comicvineID give the same error:

11-May-2016 10:05:40 - INFO    :: CP Server Thread-7 : Attempting to add directly by ComicVineID: 90125. I sure hope you know what you are doing.
11-May-2016 10:05:42 - INFO    :: Thread-12 : Now adding/updating: Thunderbolts
11-May-2016 10:05:42 - INFO    :: Thread-12 : Sucessfully retrieved details for Thunderbolts
11-May-2016 10:05:42 - INFO    :: Thread-12 : Directory (/comics/Thunderbolts (2016)) already exists! Continuing...
11-May-2016 10:05:44 - INFO    :: Thread-12 : Attempting to retrieve the comic image for series
11-May-2016 10:05:46 - INFO    :: Thread-12 : previous version detected as None - seeing if update required
11-May-2016 10:05:46 - INFO    :: Thread-12 : updated version to :v3
11-May-2016 10:05:46 - ERROR   :: Thread-12 : Database error executing UPDATE comics SET Status = ?, ComicName_Filesafe = ?, ComicName = ?, ComicImageURL = ?, ComicPublished = ?, ComicImageALTURL = ?, DynamicComicName = ?, ComicVersion = ?, ComicLocation = ?, DetailURL = ?, ComicPublisher = ?, ComicYear = ?, ComicSortName = ?, ComicImage = ?, DateAdded = ?, Total = ? WHERE ComicID = ? :: no such column: DynamicComicName
11-May-2016 10:05:46 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/importer.py", line 535, in addComictoDB
    myDB.upsert("comics", newValueDict, controlValueDict)
  File "/opt/mylar/mylar/db.py", line 170, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/mylar/mylar/db.py", line 129, in action
    sqlResult = self.connection.execute(query, args)
OperationalError: no such column: DynamicComicName

**Comment by evilhero** [comment]
For some reason you're missing that entry from your dB. Shutdown mylar and start it up again and hopefully it will add the entry on startup like it's supposed to. 

Are you running master / dev?

**Comment by pardus79** [comment]
Latest dev version.

Restarting. Reinstalling my mylar docker. None of those worked.

After getting that error, mylar will eventually say something about it removing that comic ID because it had no issues and that I should try to re-add it.

I'll see if I can manually remove it from the DB.

**Comment by evilhero** [comment]
Try running mylar in verbose mode (-v on startup or toggle Verbose on in the log tab within the GUI). It should then display all the debugging logs and maybe can see what's happening.

**Comment by pardus79** [comment]
2016-05-11 17:04:40	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/importer.py", line 535, in addComictoDB
myDB.upsert("comics", newValueDict, controlValueDict)
File "/opt/mylar/mylar/db.py", line 170, in upsert
self.action(query, valueDict.values() + keyDict.values())
File "/opt/mylar/mylar/db.py", line 129, in action
sqlResult = self.connection.execute(query, args)
OperationalError: no such column: DynamicComicName
2016-05-11 17:04:40	ERROR	Database error executing UPDATE comics SET Status = ?, ComicName_Filesafe = ?, ComicName = ?, ComicImageURL = ?, ComicPublished = ?, ComicImageALTURL = ?, DynamicComicName = ?, ComicVersion = ?, ComicLocation = ?, DetailURL = ?, ComicPublisher = ?, ComicYear = ?, ComicSortName = ?, ComicImage = ?, DateAdded = ?, Total = ? WHERE ComicID = ? :: no such column: DynamicComicName
2016-05-11 17:04:40	INFO	updated version to :v8
2016-05-11 17:04:40	INFO	previous version detected as None - seeing if update required
2016-05-11 17:04:40	DEBUG	comic image retrieval status code: 200
2016-05-11 17:04:39	INFO	Attempting to retrieve the comic image for series
2016-05-11 17:04:37	INFO	Directory (/comics/Punisher (2016)) already exists! Continuing...
2016-05-11 17:04:37	INFO	Sucessfully retrieved details for Punisher
2016-05-11 17:04:37	INFO	Now adding/updating: Punisher
2016-05-11 17:04:37	DEBUG	{'ComicIssues': '1', 'ComicName': u'Punisher', 'ComicVersion': u'8', 'FirstIssueID': u'528516', 'ComicPublisher': u'Marvel', 'ComicYear': u'2016', 'ComicImageALT': u'http://static4.comicvine.com/uploads/scale_small/6/67663/5187370-01.jpg', 'ComicURL': u'http://comicvine.gamespot.com/punisher/4050-90118/', 'ComicImage': u'http://static5.comicvine.com/uploads/scale_large/6/67663/5187370-01.jpg', 'Aliases': 'None'}
2016-05-11 17:04:37	DEBUG	Volume information found! Adding to series record : volume 8
2016-05-11 17:04:37	DEBUG	volume X format - 0: Volume 8.
2016-05-11 17:04:37	DEBUG	vari is set to: yes
2016-05-11 17:04:37	DEBUG	number of issues CV says it has: 0
2016-05-11 17:04:37	DEBUG	number of issues I counted: 1
2016-05-11 17:04:37	DEBUG	cv status code : 200
2016-05-11 17:04:35	INFO	Attempting to add directly by ComicVineID: 90118. I sure hope you know what you are doing.
2016-05-11 17:04:28	DEBUG	If you read this message, debug logging is available
2016-05-11 17:04:28	INFO	Verbose toggled, set to True

**Comment by evilhero** [comment]
Something's not right.. Your code is using the latest dev, but based on the dB error it's not using a recent mylar.db file - or its not updating the dB file when it's supposed to on startup. 

Are there any messages in the verbose logs during the startup sequence that say anything about failure to connect to the dB?

**Comment by pardus79** [comment]
Yes!

2016-05-12 13:31:56	INFO	Sucessfully ordered 270 series in your watchlist.
2016-05-12 13:31:56	INFO	Remapping the sorting to allow for new additions.
2016-05-12 13:31:56	INFO	New version is available. You are 2 commits behind
2016-05-12 13:31:55	INFO	Retrieving latest version information from github
2016-05-12 13:31:55	ERROR	Cannot connect to the database: line contains NULL byte
2016-05-12 13:31:55	INFO	Populating Base Exception listings into Mylar....
2016-05-12 13:31:55	INFO	Checking to see if the database has all tables....
2016-05-12 13:31:55	INFO	[Cache Check] Cache directory currently set to : /opt/mylar/cache/

**Comment by evilhero** [comment]
Have you been using the substitutes.csv file at all or changed / added anything to it? 

That error looks like it related to the csv importer which is for the substitutes.csv file that's located in your root directory (or is supposed to be)

**Comment by pardus79** [comment]
No, I have not messed with any of those files.

Any chance this can also be causing Mylar to also not post-process
downloaded issues?

**Comment by evilhero** [comment]
Yes it uses the DynamicComicName to match against during post-processing. If it can't find the column in the dB because it doesn't exist, it would never post-processes anything. 

Try shutting off mylar and then deleting the substitutes.csv file and then start it up again and see if that clears out the error.

**Comment by pardus79** [comment]
No substitutes.csv under /opt/mylar. Only substitutes_sample.csv. There is
exceptions.csv in there though.

**Comment by evilhero** [comment]
You shouldn't have to but try renaming the substitutes_sample.csv to substitutes.csv (with mylar shut off), and them try starting it up and see if you still get that dB error on startup.

**Comment by pardus79** [comment]
When I previously uninstalled, I left everything in my config folder. This time I deleted everything in it except for config.ini and mylar.db. Now it lets me post process and add volumes. Must have been something in there, not /opt/mylar.

**Comment by evilhero** [comment]
I guess the question is what was in the config folder that you deleted? Unless it was the .py files for mylar, it really shouldn't have made a difference (not knowing what the files are tho).
