### ISSUE TITLE
Exception being thrown: global name 'TORRENT_LOCAL' is not defined

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1278]
It's still processing the torrents but when mylar tries to add the torrent file to the watch directory it's throwing the following error:
```
11-May-2016 12:52:58 - DEBUG   :: Thread-13 : [KAT] Saved torrent file to : /var/nfs/torrent/watch/comic/Web_Warriors_7_2016.torrent
11-May-2016 12:52:58 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/home/xxx/Apps/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 1592, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 232, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 1467, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 2043, in searcher
    if TORRENT_LOCAL:
NameError: global name 'TORRENT_LOCAL' is not defined
```

**Comment by evilhero** [comment]
Ugh stupid mistake.. Thanks for the heads up, and fix is I'm development now.

**Comment by weidercs** [comment]
Grabbed several issues today without error, closing... Thanks!
