### ISSUE TITLE
Exception in folder monitor

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1298]
I'm getting an exception that stops processing in the folder monitor:
```
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [MATCH: Guardians of the Galaxy] Guardians of the Galaxy 009 (2016) (Digital) (Zone-Empire).cbr
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] Now checking against Guardians of the Galaxy-85290
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : {'LatestDate': u'2016-08-31', 'Publisher': u'Marvel', 'SeriesYear': u'2015', 'ComicVersion': u'v4', 'IsArc': False, 'Total': 9, 'ComicID': u'85290'}
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v4 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Issue Year of 2016 is a match to the year found in the filename of : 2016
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][SUCCESSFUL MATCH: Guardians of the Galaxy-85290] Match verified for Guardians of the Galaxy 009 (2016) (Digital) (Zone-Empire).cbr
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : Series_Name: new avengers --- WatchComic: new avengers
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [MATCH: New Avengers] New Avengers 012 (2016) (3 covers) (digital) (Minutemen-Midas).cbr
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] Now checking against New Avengers-55330
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] 2013-11-27 is before the issue year of 2016 that was discovered in the filename
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] IssueYear (issyr) is 2014
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] 2014 comparing to 2016 : rechecking by month-check versus year.
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][.:FAIL:.] Issue is before the modified issue year of 2014
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][NON-MATCH: New Avengers-55330] Incorrect series - not populating..continuing post-processing
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : Series_Name: new avengers --- WatchComic: new avengers
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [MATCH: New Avengers] New Avengers 012 (2016) (3 covers) (digital) (Minutemen-Midas).cbr
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] Now checking against New Avengers-85301
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : {'LatestDate': u'2016-08-31', 'Publisher': u'Marvel', 'SeriesYear': u'2015', 'ComicVersion': u'v4', 'IsArc': False, 'Total': 12, 'ComicID': u'85301'}
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v4 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Issue Year of 2016 is a match to the year found in the filename of : 2016
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][SUCCESSFUL MATCH: New Avengers-85301] Match verified for New Avengers 012 (2016) (3 covers) (digital) (Minutemen-Midas).cbr
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : Series_Name: darth vader --- WatchComic: darth vader
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [MATCH: Darth Vader] Darth Vader 021 (2016) (2 covers) (digital) (Minutemen-Midas).cbr
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] Now checking against Darth Vader-79990
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : {'LatestDate': u'2016-08-31', 'Publisher': u'Marvel', 'SeriesYear': u'2015', 'ComicVersion': None, 'IsArc': False, 'Total': 21, 'ComicID': u'79990'}
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][SUCCESSFUL MATCH: Darth Vader-79990] Match verified for Darth Vader 021 (2016) (2 covers) (digital) (Minutemen-Midas).cbr
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : Series_Name: friends forever --- WatchComic: my little pony: friends forever
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : Possible Alternate Names to match against (if necessary): [u'FriendsForever']
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [MATCH: Friends Forever] Friends Forever #29.cbz
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : loopchk: [u'FriendsForever']
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [FILECHECKER] FriendsForever - watchlist match on : Friends Forever #29.cbz
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 29000 for ComicID: 71074 / IssueID: 534079
08-Jun-2016 10:57:51 - INFO    :: FOLDERMONITOR : {'LatestDate': u'2016-06-30', 'Publisher': u'IDW Publishing', 'SeriesYear': u'2014', 'ComicVersion': u'None', 'IsArc': False, 'Total': 29, 'ComicID': u'71074'}
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : [POST-PROCESSING][ISSUE-VERIFY][NO VOLUME PRESENT] No Volume label present for series. Dropping down to Issue Year matching.
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : Exception generated in thread FOLDERMONITOR: int() argument must be a string or a number, not 'NoneType'
08-Jun-2016 10:57:51 - DEBUG   :: FOLDERMONITOR : 'Traceback (most recent call last):\n  File "/home/xxx/Apps/Mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 1969, in run\n    result = PostProcess.Process()\n  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 472, in Process\n    if int(watch_issueyear) == int(watchmatch[\'issue_year\']):\nTypeError: int() argument must be a string or a number, not \'NoneType\'\n'
```

**Comment by weidercs** [comment]
Moved the comic with a "#" in the title and it fixed the issue: "Friends Forever #29.cbz" seems to be a bug with handling the # symbol.

**Comment by weidercs** [comment]
wasn't the #, it's the lack of a date on that file.  When I renamed it to Friends.Forever.029.2016.cbz it processed correctly.  Hope that helps.

**Comment by evilhero** [comment]
As soon as you posted initially I knew exactly what the problem was based on the log. 

I'm not sure if I can make it back to a machine tonight to fix it, but I'll get a fix out tomorrow morning. And you're definitely right,  if there isn't a volume or a year present in the filename it doesn't know what to do and errors out (it should assume v1 and if anything isn't a v1 that matches it's not a match kinda logic).

**Comment by evilhero** [comment]
```
09-Jun-2016 10:33:37 - INFO :: Thread-13 : I have located 1 files that I should be able to post-process. Continuing...
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : Checking My Little Pony: Friends Forever [2014] -- 71074
09-Jun-2016 10:33:37 - INFO :: Thread-13 : Series_Name: friends forever --- WatchComic: my little pony: friends forever
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : Possible Alternate Names to match against (if necessary): [u'FriendsForever']
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [MATCH: Friends Forever] Friends Forever #29.cbz
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [FILECHECKER] This should be an alternate: [u'FriendsForever']
09-Jun-2016 10:33:37 - INFO :: Thread-13 : loopchk: [u'FriendsForever']
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [FILECHECKER] Complete matching list of names to this file [1] : [u'FriendsForever']
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [FILECHECKER] AS_Tuple : []
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [FILECHECKER] FriendsForever - watchlist match on : Friends Forever #29.cbz
09-Jun-2016 10:33:37 - INFO :: Thread-13 : [POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 29000 for ComicID: 71074 / IssueID: 534079
09-Jun-2016 10:33:37 - INFO :: Thread-13 : {'LatestDate': u'2016-06-30', 'Publisher': u'IDW Publishing', 'SeriesYear': u'2014', 'ComicVersion': u'None', 'IsArc': False, 'Total': 29, 'ComicID': u'71074'}
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [POST-PROCESSING][SUCCESSFUL MATCH: My Little Pony: Friends Forever-71074] Match verified for Friends Forever #29.cbz
09-Jun-2016 10:33:37 - DEBUG :: Thread-13 : [POST-PROCESSING] There are 1 files found that match on your watchlist, 0 do not match anything and will be ignored.
```
Good to go - will be up in the development branch shortly ;)

**Comment by weidercs** [comment]
Works!
