### ISSUE TITLE
Getting an Error when I Force Search a Comic

### ISSUE THREAD

**Issue by Shobetheprobe** [evilhero/mylar#1312]
```
2016-07-02 14:32:19 ERROR   Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 1341, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "C:\Mylar\mylar\search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Mylar\mylar\search.py", line 621, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-07-02 14:32:19 WARNING Error fetching data from newznab: ('Connection aborted.', gaierror(11002, 'getaddrinfo failed'))
2016-07-02 14:31:08 INFO    pausing for 60 seconds before continuing to avoid hammering
2016-07-02 14:31:08 INFO    Shhh be very quiet...I'm looking for The Flash issue: 1 (2016) using Freenzbs (newznab)
```

It was working pretty well about 3 weeks ago but atm it doesn't find any new comics

**Comment by evilhero** [comment]
The gaierror is a Getaddrinfo error which basically means that it can't connect to the given site.  It could be that the site doesn't exist, or you have no Internet connection when the attempt tries - all of which results in that error.

**Comment by Shobetheprobe** [comment]
The thing is i can connect to the indexer but for some reason it doesnt download anymore

**Comment by evilhero** [comment]
Because they turned off the api due to abuse (google search returned hits on reddit saying exactly this).

**Comment by Shobetheprobe** [comment]
Okay i removed that particular indexer i have another 4 in use and now im getting 

```
ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 1341, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "C:\Mylar\mylar\search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Mylar\mylar\search.py", line 1534, in NZB_SEARCH
if foundc == "yes":
UnboundLocalError: local variable 'foundc' referenced before assignment
```

**Comment by evilhero** [comment]
Make sure you shutdown and restart mylar after any configuration change regarding providers.

**Comment by Shobetheprobe** [comment]
Thank YOu :) :+1:
