### ISSUE TITLE
Failing on Manual run

### ISSUE THREAD

**Issue by SteadFast13** [evilhero/mylar#1318]
Attemping to manual post process and receiving this error, despite my best efforts. 

OS: Windows 10 Pro 64 bit
Mylar Version: development
-- source build ca8b7a80950703f3e325761283f4ab6dd7d8f034.
Python Version : 2.7.11

> 2016-07-12 11:33:02	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 446, in Process
logger.fdebuginfo('WATCH_VALUES:' + str(watch_values))
AttributeError: 'module' object has no attribute 'fdebuginfo'
2016-07-12 11:33:02	DEBUG	[POST-PROCESSING][ISSUE-VERIFY] Now checking against Raise the Dead-18440
2016-07-12 11:33:02	DEBUG	[MATCH: Raise The Dead] Raise The Dead 01 (2007) (Blasty-DCP).cbr
2016-07-12 11:33:02	DEBUG	Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
2016-07-12 11:33:02	INFO	Series_Name: Raise The Dead --- WatchComic: Raise the Dead
2016-07-12 11:33:02	INFO	I have located 394 files that I should be able to post-process. Continuing...

_
> 2016-07-12 11:42:44	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 446, in Process
logger.fdebuginfo('WATCH_VALUES:' + str(watch_values))
AttributeError: 'module' object has no attribute 'fdebuginfo'
2016-07-12 11:42:44	INFO	[POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 1000 for ComicID: 38239 / IssueID: 255947
2016-07-12 11:42:44	DEBUG	[MATCH: Assassin's Creed] Assassin's Creed 1 Desmond.cbr
2016-07-12 11:42:44	DEBUG	Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
2016-07-12 11:42:44	INFO	Series_Name: Assassin's Creed --- WatchComic: Assassin's Creed
2016-07-12 11:42:41	INFO	I have located 386 files that I should be able to post-process. Continuing...

_
> 2016-07-12 11:45:42	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\PostProcessor.py", line 446, in Process
logger.fdebuginfo('WATCH_VALUES:' + str(watch_values))
AttributeError: 'module' object has no attribute 'fdebuginfo'
2016-07-12 11:45:42	DEBUG	[POST-PROCESSING][ISSUE-VERIFY] Now checking against Back To the Future-85421
2016-07-12 11:45:42	DEBUG	[MATCH: Back to the Future] Back to the Future 01 (of 04) (2015) (Digital) (Kileko-Empire).cbr
2016-07-12 11:45:42	DEBUG	Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
2016-07-12 11:45:42	INFO	Series_Name: Back to the Future --- WatchComic: Back To the Future
2016-07-12 11:45:42	INFO	I have located 378 files that I should be able to post-process. Continuing...

**Comment by evilhero** [comment]
Crap typos on my part.  Hang on.. Will push fix in a few mins

**Comment by SteadFast13** [comment]
Success! All working pretty now. Thank you!
