### ISSUE TITLE
IndexError when importing more than 100 comics 

### ISSUE THREAD

**Issue by razorsliph** [evilhero/mylar#1325]
Traceback:

```
15-Jul-2016 18:58:05 - ERROR   :: LibraryScan : [IMPORT] Unable to complete the scan: list index out of range
15-Jul-2016 18:58:05 - ERROR   :: LibraryScan : Traceback: ['Traceback (most recent call last):', '  File "/opt/mylar/mylar/librarysync.py", line 596, in scanLibrary\n    soma = libraryScan(queue=queue)', '  File "/opt/mylar/mylar/librarysync.py", line 489, in libraryScan\n    vals = mylar.cv.getComic(None, \'import\', comicidlist=reverse_issueids)', '  File "/opt/mylar/mylar/cv.py", line 187, in getComic\n    tmpidlist += \'|\' + str(comicidlist[i])', 'IndexError: list index out of range']
```

Resolution:
endcnt += 100 without checking whether it exceeded the length of comicidlist was the issue. 
Fix/diff:

```
--- a/mylar/cv.py
+++ b/mylar/cv.py
@@ -167,11 +167,6 @@ def getComic(comicid, type, issueid=None, arc=None, arcid=None, arclist=None, co
         #within the tagging (with CT). This compiles all of the IssueID's during a scan (in 100's), and returns the corresponding CV data
         #related to the given IssueID's - namely ComicID, Name, Volume (more at some point, but those are the important ones).
         offset = 1
-        if len(comicidlist) <= 100:
-            endcnt = len(comicidlist)
-        else:
-            endcnt = 100
-
         id_count = 0
         import_list = []
         logger.fdebug('comicidlist:' + str(comicidlist))
@@ -180,6 +175,11 @@ def getComic(comicid, type, issueid=None, arc=None, arcid=None, arclist=None, co
             #break it up by 100 per api hit
             #do the first 100 regardless
             in_cnt = 0
+            if id_count + 100 <= len(comicidlist):
+                endcnt = id_count + 100
+            else:
+                endcnt = len(comicidlist)
+
             for i in range(id_count, endcnt):
                 if in_cnt == 0:
                     tmpidlist = str(comicidlist[i])
@@ -196,7 +196,6 @@ def getComic(comicid, type, issueid=None, arc=None, arcid=None, arclist=None, co
                 tGIL = GetImportList(searched)
                 import_list += tGIL

-            endcnt +=100
             id_count +=100

         return import_list
```

**Comment by evilhero** [comment]
Makes sense - I never tested against more than 100 cbz files that contained metadata (was maybe 20/30), so can definitely see the benefit/fix of this.

I'll try and incorporate this into the next development commit, otherwise I'll push it out separately into the subsequent one ;)  Thanks for the diff too, that helps alot!
