### ISSUE TITLE
Download generates error

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1329]
Clicking download from the The Week screen generates an error.  Looks like a problem in the SQL

```
Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 3088, in MassWeeklyDownload
    clist = myDB.select("SELECT * FROM Weekly AND weeknumber=? WHERE Status='Downloaded'", [pulldate['weeknumber']])
TypeError: string indices must be integers
```

**Comment by evilhero** [comment]
#1321 fixed I'm recent development commit
