### ISSUE TITLE
Search.py crashes with newly added Torznab entry

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1336]
Since KAT is gone and I don't have 32p access (yet) I've added a torznab entry (and jackett has been working for sonarr).  There's an exception on the verify variable being used before it's assigned when it goes to search:

```
27-Jul-2016 10:09:32 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/home/xxx/Apps/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/Apps/Mylar/mylar/webserve.py", line 1348, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
  File "/home/xxx/Apps/Mylar/mylar/search.py", line 604, in NZB_SEARCH
    elif findurl.startswith('http:') and verify == True:
UnboundLocalError: local variable 'verify' referenced before assignment

```

Tried to track it down but verify is used so much it's hard to make heads/tails, figured you could find the problem faster...

Let me know if you need more info

**Comment by evilhero** [comment]
Think I know where it's happening - just not carrying over the value into one of the submodules. 

Will try and get it fixed today at some point..

**Comment by weidercs** [comment]
Works now, thanks!
