### ISSUE TITLE
Mylar fails to load.

### ISSUE THREAD

**Issue by AustinYQM** [evilhero/mylar#1337]
```
`Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>C:\Python27\Python.exe C:\Mylar-Master\Mylar.py
27-Jul-2016 18:49:42 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: C:\Mylar-Master
27-Jul-2016 18:49:42 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar-Master\Mylar.py", line 268, in <module>
    main()
  File "C:\Mylar-Master\Mylar.py", line 195, in main
    mylar.CFG = ConfigObj(mylar.CONFIG_FILE, encoding='utf-8')
  File "C:\Mylar-Master\lib\configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "C:\Mylar-Master\lib\configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "1".

Traceback (most recent call last):
  File "C:\Mylar-Master\Mylar.py", line 268, in <module>
    main()
  File "C:\Mylar-Master\Mylar.py", line 195, in main
    mylar.CFG = ConfigObj(mylar.CONFIG_FILE, encoding='utf-8')
  File "C:\Mylar-Master\lib\configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "C:\Mylar-Master\lib\configobj.py", line 1332, in _load
    raise error
lib.configobj.ParseError: Invalid line at line "1".

C:\WINDOWS\system32>`
```

Just started happening randomly.  Attempted to update both python and Mylar (From master branch) to no avail. Thanks in advance for any help you can provide.

**Comment by evilhero** [comment]
Your config.ini file looks to be corrupted.  You probably need to wipe it out and let it recreate on startup and reenter the info again.

**Comment by AustinYQM** [comment]
That fixed it, thanks!
