### ISSUE TITLE
500 ISE on Wanted and This Week

### ISSUE THREAD

**Issue by psingley** [evilhero/mylar#1340]
Hey, so in searching around I've seen the general resolution to my error on wanted

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "Z:\2252014Mylar\mylar-development\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "Z:\2252014Mylar\mylar-development\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "Z:\2252014Mylar\mylar-development\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "Z:\2252014Mylar\mylar-development\mylar\webserve.py", line 1529, in pullist
    repoll = self.manualpull(weeknumber=weeknumber,year=year)
  File "Z:\2252014Mylar\mylar-development\mylar\webserve.py", line 1738, in manualpull
    mylar.locg.locg(weeknumber=weeknumber,year=year)
  File "Z:\2252014Mylar\mylar-development\mylar\locg.py", line 68, in locg
    data = r.json()
  File "Z:\2252014Mylar\mylar-development\lib\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

is to recreate pulllist

Unfortunately, my "This week" page also has an error as follows

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "Z:\2252014Mylar\mylar-development\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "Z:\2252014Mylar\mylar-development\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "Z:\2252014Mylar\mylar-development\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "Z:\2252014Mylar\mylar-development\mylar\webserve.py", line 1529, in pullist
    repoll = self.manualpull(weeknumber=weeknumber,year=year)
  File "Z:\2252014Mylar\mylar-development\mylar\webserve.py", line 1738, in manualpull
    mylar.locg.locg(weeknumber=weeknumber,year=year)
  File "Z:\2252014Mylar\mylar-development\mylar\locg.py", line 68, in locg
    data = r.json()
  File "Z:\2252014Mylar\mylar-development\lib\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

How do I recreate the pull list without access?

**Comment by evilhero** [comment]
It was a problem with the new site - the sql daemon wasn't running (it didn't come back up on a restart for some reason). 

It's back online now, so you should be able to just do a refresh on the the pullist (if a Refresh doens't work, do a Recreate Pullist), which will also fix the Upcoming/Wanted tab error.

**Comment by psingley** [comment]
Okay, so this just fixed itself but I'm not sure how -- The only way I know of to recreate the pull list is on the "This Week" page and I couldn't get in there due to the second 500 I documented. This was the case from at least yesterday until today as of my post.

Now, after unchecking dognzb and restarting, the pull list section loaded and is available again. I didn't do anything else and am not sure why that would have worked, but I wanted to add the info just in case.

I've gone ahead and recreated pull list anyway and things seem to be working just fine now.

Might be worth adding a recreate pull list functionality elsewhere if there's a chance like this for the page containing it to break and it is the immediate solution.
