### ISSUE TITLE
Check for New Version throws an error

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1341]
When I try to click Check for New Version, it throws an: "Error checking for update" box.
I went into logs and clicked Toggle Debug Log, and it threw a server exception error:
----------
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\webserve.py", line 2939, in toggleVerbose
    logger.info("Verbose toggled, set to %s", mylar.VERBOSE)
  File "C:\Python27\lib\logging\__init__.py", line 1159, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1278, in _log
    self.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging\__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 751, in handle
    self.emit(record)
  File "C:\Users\Bruce\Documents\GitHub\mylar\mylar\logger.py", line 43, in emit
    mylar.LOG_LIST.insert(0, (helpers.now(), message, record.levelname, record.threadName))

Is something hosed in my installation?

-Bruce

**Comment by evilhero** [comment]
Which version of mylar are you currently running and the branch? 

TBH I've never seen the error before, but it like it's a problem with the logging for some reason, moreso than the actual program activity. 

Have you restarted mylar since the error?

**Comment by bguidotti** [comment]
Yes, I've restarted.
It's weird.  I am on DEV branch - when I kill the python processes and restart, it seems to run ok for a little while, then go wonky again.

Exact version is: Version: 95b9b10786cf912a8af3611c0fd66d6218a5b90a (development)

**Comment by evilhero** [comment]
It might be that the actual logger is having problems rolling the log over - I've never seen an error message like the one youre having, but it's very possibke especially since you're in windows which is where the log rollover problems can occur. 

Mylar comes with a concurrent log rotator but you need to install an external item in order for things to work.  I believe it's ctypes, but I'll have to post back when I'm at home and can check

**Comment by bguidotti** [comment]
Bizarre.  Let me see if I rename the log files, if the problem stops.

**Comment by bguidotti** [comment]
So it is overrunning the logs with content like this:
2016-07-30 22:11:58	INFO	rss:yes
2016-07-30 22:11:58	INFO	experimental
2016-07-30 22:11:58	INFO	allow_packs:False
2016-07-30 22:11:58	INFO	rss:yes
2016-07-30 22:11:58	INFO	experimental
2016-07-30 22:11:58	INFO	allow_packs:False
2016-07-30 22:11:58	INFO	rss:yes
2016-07-30 22:11:58	INFO	experimental

I can't click the "last" button fast enough to see the end of the logs.
It created 5 log files within 1 minute.

What could be causing that?

**Comment by evilhero** [comment]
That's just the experimental search logging - but because you're only viewing the INFO level, and not the DEBUG level it only shows those lines. If it were showing the DEBUG, you would get a whack of loglines  inbetween those. Those 3 lines though will be removed in the next dev commit (just an FYI).

In order for Mylar to start using the built-in concurrent loghandler program, you need to install python for windows extensions (https://sourceforge.net/projects/pywin32/). Once it's installed, Mylar will auto-detect that it's installed when it startsup, and start using the concurrent loghandling and you shouldn't see that particular log error anylonger (nor have it crash after a few hours when it tries to rotate the logs)

**Comment by bguidotti** [comment]
OK - thanks!
I will try it out.

**Comment by bguidotti** [comment]
I will close this ticket now that I've installed pywin32.
