### ISSUE TITLE
Mass import - Uncaught exception

### ISSUE THREAD

**Issue by bebetech** [evilhero/mylar#1343]
`2016-08-04 11:57:03    ERROR   Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/importer.py", line 594, in addComictoDB
moveit.archivefiles(comicid, comlocation, imported)
File "/opt/Mylar/mylar/moveit.py", line 67, in archivefiles
result = myDB.select("SELECT * FROM importresults WHERE ComicName=?", [ogcname])
File "/opt/Mylar/mylar/db.py", line 145, in select
sqlResults = self.fetch(query, args).fetchall()
File "/opt/Mylar/mylar/db.py", line 94, in fetch
sqlResult = cursor.execute(query, args)
InterfaceError: Error binding parameter 0 - probably unsupported type.
2016-08-04 11:57:03 INFO    Mass import - Moving not Enabled. Setting Archived Status for import.
2016-08-04 11:57:03 INFO    imported is : {'Volume': u'None', 'filelisting': [{'import_id': u'89562495', 'issuenumber': u'025', 'comicfilename': u'Young Justice 025 (2013).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 025 (2013).cbr'}, {'import_id': u'43002044', 'issuenumber': u'001', 'comicfilename': u'Young Justice 001 (2011).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 001 (2011).cbr'}, {'import_id': u'55159775', 'issuenumber': u'012', 'comicfilename': u'Young Justice 012 (2012).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 012 (2012).cbz'}, {'import_id': u'44988217', 'issuenumber': u'015', 'comicfilename': u'Young Justice 015 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 015 (2012).cbr'}, {'import_id': u'96469028', 'issuenumber': u'000', 'comicfilename': u'Young Justice 000 (2011).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 000 (2011).cbr'}, {'import_id': u'86744672', 'issuenumber': u'005', 'comicfilename': u'Young Justice 005 (2011).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 005 (2011).cbr'}, {'import_id': u'46476049', 'issuenumber': u'015', 'comicfilename': u'Young Justice 015 (2012).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 015 (2012).cbz'}, {'import_id': u'60493557', 'issuenumber': u'003', 'comicfilename': u'Young Justice 003 (2011).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 003 (2011).cbr'}, {'import_id': u'91983653', 'issuenumber': u'024', 'comicfilename': u'Young Justice 024 (2013).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 024 (2013).cbr'}, {'import_id': u'49751888', 'issuenumber': u'007', 'comicfilename': u'Young Justice 007 (2011).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 007 (2011).cbz'}, {'import_id': u'18026826', 'issuenumber': u'023', 'comicfilename': u'Young Justice 023 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 023 (2012).cbr'}, {'import_id': u'45988134', 'issuenumber': u'002', 'comicfilename': u'Young Justice 002 (2011).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 002 (2011).cbz'}, {'import_id': u'88127020', 'issuenumber': u'013', 'comicfilename': u'Young Justice 013 (2012).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 013 (2012).cbz'}, {'import_id': u'2387444', 'issuenumber': u'010', 'comicfilename': u'Young Justice 010 (2012).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 010 (2012).cbz'}, {'import_id': u'81896034', 'issuenumber': u'019', 'comicfilename': u'Young Justice 019 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 019 (2012).cbr'}, {'import_id': u'20778718', 'issuenumber': u'016', 'comicfilename': u'Young Justice 016 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 016 (2012).cbr'}, {'import_id': u'46249971', 'issuenumber': u'020', 'comicfilename': u'Young Justice 020 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 020 (2012).cbr'}, {'import_id': u'64484616', 'issuenumber': u'017', 'comicfilename': u'Young Justice 017 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 017 (2012).cbr'}, {'import_id': u'2839813', 'issuenumber': u'011', 'comicfilename': u'Young Justice 011 (2011).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 011 (2011).cbz'}, {'import_id': u'58588689', 'issuenumber': u'008', 'comicfilename': u'Young Justice 008 (2011).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 008 (2011).cbr'}, {'import_id': u'21526250', 'issuenumber': u'021', 'comicfilename': u'Young Justice 021 (2012).cbr', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 021 (2012).cbr'}, {'import_id': u'58686303', 'issuenumber': u'004', 'comicfilename': u'Young Justice 004 (2011).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 004 (2011).cbz'}, {'import_id': u'46365560', 'issuenumber': u'009', 'comicfilename': u'Young Justice 009 (2011).cbz', 'comiclocation': u'/mnt/Comics/DC Comics/Young Justice (2011)/Young Justice 009 (2011).cbz'}], 'ComicName': u'Young Justice', 'srid': '430495', 'DynamicName': u'youngjustice'}
2016-08-04 11:57:03 INFO    Updating complete for: Young Justice
2016-08-04 11:57:03 INFO    Initiating mass import.`

**Comment by evilhero** [comment]
I believe the problem lies with the archive setting - not enabling the move option is causing the problem as I'm pretty sure the code hasn't been updated to accommodate the values that are now being returned by the importer. 

Will look into this as right now I think it's a a simple fix, but will flip back an update message when I can test and know more..
