### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by partymike** [evilhero/mylar#1345]
After the latest update i now see the following error and Mylar will not start, any ideas (I'm on master build):

C:\HTPC\Mylar>python mylar.py
Traceback (most recent call last):
  File "mylar.py", line 26, in <module>
    import mylar
  File "C:\HTPC\Mylar\mylar\__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "C:\HTPC\Mylar\mylar\rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "C:\HTPC\Mylar\mylar\rsscheck.py", line 15, in <module>
    import mylar.torrent.clients.transmission as transmission
  File "C:\HTPC\Mylar\mylar\torrent\clients\transmission.py", line 4, in <module>
    from lib.transmissionrpc import Client
  File "C:\HTPC\Mylar\lib\transmissionrpc\__init__.py", line 5, in <module>
    from constants import DEFAULT_PORT, DEFAULT_TIMEOUT, PRIORITY, RATIO_LIMIT, LOGGER
  File "C:\HTPC\Mylar\lib\transmissionrpc\constants.py", line 6, in <module>
    from six import iteritems
ImportError: No module named six

**Comment by partymike** [comment]
turns out i was on development...switched to master and all good :-)
