### ISSUE TITLE
mylar wont start since jun 23rd update

### ISSUE THREAD

**Issue by phairplay** [evilhero/mylar#1346]
hello 
i updated to the latest development 562a8a851204051c1a60a63d80f6b1beb1b499fa
and now i get the following error

```
C:\Users\david>python c:\mylar\mylar.py
Traceback (most recent call last):
  File "c:\mylar\mylar.py", line 26, in <module>
    import mylar
  File "c:\mylar\mylar\__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit
, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search,
PostProcessor, weeklypull, helpers, scheduler
  File "c:\mylar\mylar\rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "c:\mylar\mylar\rsscheck.py", line 15, in <module>
    import mylar.torrent.clients.transmission as transmission
  File "c:\mylar\mylar\torrent\clients\transmission.py", line 4, in <module>
    from lib.transmissionrpc import Client
  File "c:\mylar\lib\transmissionrpc\__init__.py", line 5, in <module>
    from constants import DEFAULT_PORT, DEFAULT_TIMEOUT, PRIORITY, RATIO_LIMIT,
LOGGER
  File "c:\mylar\lib\transmissionrpc\constants.py", line 6, in <module>
    from six import iteritems
ImportError: No module named six
```

**Comment by evilhero** [comment]
Sorry, it looks like if you don't have the six module installed (which is used by transmission) it causes the error.  The fix that just went up should fix the startup error.

**Comment by phairplay** [comment]
Hi thanks its back up and running.

I've started it up and now I'm unable to see my wanted list here is the error I see 

```
Traceback (most recent call last):
  File "c:\Mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 1824, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by evilhero** [comment]
Ugh that again... Do a recreate pullist from the weekly tab and it I'll line things up again.

**Comment by phairplay** [comment]
Cool thanks you for the quick response
