### ISSUE TITLE
Mass Import: ValueError: Malformed string

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1349]
I am seeing this error repeatedly during mass imports. From the log it looks to be related to titles with characters like `+` and `:`.

```
13-Aug-2016 03:59:12 - INFO :: Thread-35 : Mass import - Move files
13-Aug-2016 03:59:12 - ERROR :: Thread-35 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 591, in addComictoDB
    moveit.movefiles(comicid, comlocation, imported)
  File "C:\Users\jeremy\mylar\mylar\moveit.py", line 11, in movefiles
    imported = ast.literal_eval(imported)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 591, in addComictoDB
    moveit.movefiles(comicid, comlocation, imported)
  File "C:\Users\jeremy\mylar\mylar\moveit.py", line 11, in movefiles
    imported = ast.literal_eval(imported)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

```

**Comment by evilhero** [comment]
It looks like it's due to the improper usage of the ast module being called when it's not the expected string. I tested the ast against manual interventions, so it looks like a possible try/except catch might resolve this (seeing as how there is no interaction in the mass import until it's completed). 

Will try and push something out later tonight that will address this hopefully....
