### ISSUE TITLE
TypeError during duplicate_filecheck 

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1351]
This is during an import:

```
13-Aug-2016 21:12:06 - INFO :: Thread-12 : [DUPLICATE-CLEANUP][MOVE-MODE] New File will not be post-processed. Moving duplicate [X:\_work\proc\Batman 049 (2016) (2 covers) (Digital) (Zone-Empire).cbr] to Duplicate Dump Folder for manual intervention.
13-Aug-2016 21:12:06 - INFO :: Thread-12 : [DUPLICATE-CLEANUP][DIRECTORY-CHECK] Found comic directory: Z:\_work\comics.dupes
13-Aug-2016 21:12:06 - WARNING :: Thread-12 : [DUPLICATE-CLEANUP] Successfully moved X:\_work\proc\Batman 049 (2016) (2 covers) (Digital) (Zone-Empire).cbr ... to ... Z:\_work\comics.dupes\Batman 049 (2016) (2 covers) (Digital) (Zone-Empire).cbr
13-Aug-2016 21:12:06 - INFO :: Thread-12 : [DUPECHECK] Duplicate check for X:\_work\proc\Batman Annual 003 (2015) (Digital) (Zone-Empire).cbr
13-Aug-2016 21:12:06 - INFO :: Thread-12 : [DUPECHECK] Existing Status already set to Archived
13-Aug-2016 21:12:06 - INFO :: Thread-12 : [DUPECHECK] Existing filesize is 0 bytes as I cannot locate the orginal entry - it is probably archived.
13-Aug-2016 21:12:06 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\PostProcessor.py", line 1121, in Process
    dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
  File "C:\Users\jeremy\mylar\mylar\helpers.py", line 1792, in duplicate_filecheck
    'to_dupe': os.path.join(series['ComicLocation'], dupchk['Location'])})
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\PostProcessor.py", line 1121, in Process
    dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
  File "C:\Users\jeremy\mylar\mylar\helpers.py", line 1792, in duplicate_filecheck
    'to_dupe': os.path.join(series['ComicLocation'], dupchk['Location'])})
TypeError: 'NoneType' object has no attribute '__getitem__'
13-Aug-2016 21:12:49 - INFO :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
```

**Comment by evilhero** [comment]
Ahh OK the fact that the file is archived but mylar doesn't know the actual location of the file anymore (either due to manually marking it as archived or some other reason), is causing the problem. 

I'll have to look into this more to figure out exactly how to handle the files that aren't located anymore, but it shouldn't be too difficult to fix.

**Comment by jerblack** [comment]
I have Series-Annual Integration enabled here.
