### ISSUE TITLE
Mylar on Synology won't update - several commits behind

### ISSUE THREAD

**Issue by erickgrau** [evilhero/mylar#1353]
I'm still trying to configure Mylar for the first time and running into many issues with it scanning my 150GB+ library and I think it maybe be the version?  Anyway, I follow several posts on changing the GIT from Master to Development and now it states its 16 commits behind but no matter how many times I hit "update" it reboots into the same version.

How do I force a command line update?

**Comment by evilhero** [comment]
Shut down mylar and edit the config.ini variable git_branch so that it's git_branch = development 

Start up mylar and you're on the development  branch ;)

**Comment by erickgrau** [comment]
Thanks for your quick response, yes I did change over to development branch successfully as it now states that in the settings cog and also now tells me I'm 16 commits behind.  I click upgrade and it looks its doing something then it restarts... but its the same version.  Which is why I was asking if maybe there was a terminal git command to force the update?

I guess the bigger problem here that led me this path, is the scan library feature fails as some point and nothing shows up in Mylar.  its 150+GB so I thought that was the issue at first.

Thanks,

Erick

Thanks,

Erick

**Comment by JoshKastang** [comment]
The SynoCommunity Mylar package is really finicky - if you don't want to move to a Docker image, you should do the following to update Mylar:

1.  Shut down Mylar (in Package Center)
2. SSH into your Synology
3. Run `cd /usr/local/mylar/share/mylar; /volume1/@appstore/git/bin/git pull`
4. Start Mylar (in Package Center)

**Comment by erickgrau** [comment]
Thanks Josh.  

run /volume1/@appstore/git/bin/git pull
states 'Already Up-to-date'

but when I restart it, states 16 commits behind...

**Comment by evilhero** [comment]
I think it was the syno pkg that forced the branch to be master on startup regardless of what it's supposed to be in the config.ini. As your version is actually pointing to master still (which would men that the config.ini being set to development isn't being honoured for some reason). 

Like Josh had mentioned, it's really finicky on the pkg - and I can't really support the syno pkg as I don't have a syno and have nothing to do with the package. A lot of times I suggest  installing mylar via got instead and in almost every case the updating problems go away. 

Also 150gb+ of comics is going to cause problems just due to the size of importing. The files also have to be named in a proper format that Mylar can parse (or have metadata in the cbz) in order for the import to work properly.  I'd you can you're probably best to break up the import into 30-50gb chunks, so that it can at least get to the second stage of importing (and you can see the logs -  always run mylar in verbose mode when importing in case you get an error it saves you having to run the import against if you need to show the logs)

**Comment by JoshKastang** [comment]
@erickgrau you can force the branch to development - 

1. Stop Mylar
2. `cd /usr/local/mylar/share/mylar`
3. `/volume1/@appstore/git/bin/git checkout development`
4. `/volume1/@appstore/git/bin/git pull`
5. In `/volume1/@appstore/mylar/var/config.ini` make sure `git_branch = development`
6. Start Mylar

I seem to remember one additional (Synology specific) reference that needs to be updated to force the development branch, but I cant remember off the top of my head. Using the above method should preserve between restarts but not package upgrades.

**Comment by erickgrau** [comment]
@JoshKastang thanks for the advice and exact commands... I still get "Already Up To Date" BUT when I start Mylar, I know get:


Configuration Options
Mylar Version: development
-- git build "a850e386d41f3a88dfc8d04192f021a2081a27b6."
Python Version : 2.7.11

I think it upgraded... now to break the library into smaller chunks... :)

Erick

**Comment by erickgrau** [comment]
@evilhero - just I open a new issue on latest build or just leave the comment here?

It upgraded but when I click Wanted (top Menu) I get:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1845, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by evilhero** [comment]
No need to open a new ticket - easy fix.  Just go to the Weekly tab and then do a Recreate pullist. It will regenerate a clean pullist with the new fields (there was a change in fields in the dev branch). You  can then go to your Wanted tab with no further issues :)

**Comment by erickgrau** [comment]
BINGO! thanks

**Comment by erickgrau** [comment]
What can I do about not finding issues on that list?  If I manually search nzbgeek for instance I find them but even though Mylar is setup for nzbgeek, it says no issues found.

"Shhh be very quiet...I'm looking for Vertigo Essentials: Lucifer issue: 1 (2016) using https://api.nzbgeek.info/ (newznab)"

Could not find Issue 1 of Vertigo Essentials: Lucifer(2016

**Comment by evilhero** [comment]
It depends on how you're searching within mylar.. Are you letting the rss query fire off every 20 mins to poll the feeds, or are you doing an immediate search (magnifying glass), or a Force Search on the Wanted tab? 

If you're doing  just rss, if the issue wasn't posted to the rss feeds while mylar was watching them (meaning it was running) them odds are it might not be in a current feed so it can't find it. 

If it's the last 2 options, then it's possibly how the file is named on the indexer - I'd have to see what the name is in order to see what the problem might be.

**Comment by erickgrau** [comment]
Click Wanted and Force Check

2016-08-23 11:06:35	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-23 11:06:35	DEBUG	calpha/cnumber: None / None
2016-08-23 11:06:35	INFO	Shhh be very quiet...I'm looking for Vertigo Essentials: Lucifer issue: 1 (2016) using https://api.nzbgeek.info/ (newznab)
2016-08-23 11:06:35	DEBUG	using Newznab host of : https://api.nzbgeek.info/
2016-08-23 11:06:35	INFO	allow_packs set to :False
2016-08-23 11:06:35	DEBUG	Initiating Search via : api
2016-08-23 11:06:35	INFO	Finished searching via :rss. Issue not found - status kept as Wanted.
2016-08-23 11:06:35	INFO	Could not find Issue 1 of Vertigo Essentials: Lucifer(2016) using TPSE [rss]
2016-08-23 11:06:35	DEBUG	seriesname_alt:None
2016-08-23 11:06:35	DEBUG	tsearch : vertigo%essentials%%lucifer%
2016-08-23 11:06:35	DEBUG	ComicID: 87353
2016-08-23 11:06:35	DEBUG	Sending request to [TPSE] RSS for Vertigo Essentials Lucifer : 1
2016-08-23 11:06:35	DEBUG	seriesname_alt:None
2016-08-23 11:06:35	DEBUG	tsearch : vertigo%essentials%%lucifer%
2016-08-23 11:06:35	DEBUG	ComicID: 87353
2016-08-23 11:06:35	DEBUG	Sending request to [TPSE] RSS for Vertigo Essentials Lucifer : 01
2016-08-23 11:06:35	DEBUG	seriesname_alt:None
2016-08-23 11:06:35	DEBUG	tsearch : vertigo%essentials%%lucifer%
2016-08-23 11:06:35	DEBUG	ComicID: 87353
2016-08-23 11:06:35	DEBUG	Sending request to [TPSE] RSS for Vertigo Essentials Lucifer : 001
2016-08-23 11:06:35	DEBUG	calpha/cnumber: None / None
2016-08-23 11:06:35	INFO	Shhh be very quiet...I'm looking for Vertigo Essentials Lucifer issue: 1 (2016) using TPSE [RSS]
2016-08-23 11:06:35	INFO	allow_packs set to :False
2016-08-23 11:06:35	INFO	Alternate Search pattern detected...re-adjusting to : Vertigo Essentials Lucifer 2016
2016-08-23 11:06:35	DEBUG	seriesname_alt:None




Settings, RSS (force RSS check)

2016-08-23 11:08:52	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-23 11:08:52	DEBUG	calpha/cnumber: None / None
2016-08-23 11:08:52	INFO	Shhh be very quiet...I'm looking for Vertigo Essentials Lucifer issue: 1 (2016) using https://api.nzbgeek.info/ (newznab)
2016-08-23 11:08:52	DEBUG	using Newznab host of : https://api.nzbgeek.info/
2016-08-23 11:08:52	INFO	allow_packs set to :False
2016-08-23 11:08:52	INFO	Alternate Search pattern detected...re-adjusting to : Vertigo Essentials Lucifer 2016
2016-08-23 11:08:48	DEBUG	[SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=vertigo%20essentials%20lucifer%201&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-23 11:08:39	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-23 11:08:36	DEBUG	[SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=vertigo%20essentials%20lucifer%2001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-23 11:07:48	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-23 11:07:45	DEBUG	[SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=vertigo%20essentials%20lucifer%2001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-23 11:07:36	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-23 11:07:35	DEBUG	[SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=vertigo%20essentials%20lucifer%20001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-23 11:07:31	DEBUG	Git output: a850e386d41f3a88dfc8d04192f021a2081a27b6
2016-08-23 11:07:31	DEBUG	Trying to execute: ""/usr/local/git/bin/git" rev-parse HEAD" with shell in /usr/local/mylar/share/mylar
2016-08-23 11:07:29	DEBUG	ComicTagger Path enforced to use local library : /usr/local/mylar/share/mylar
2016-08-23 11:07:28	INFO	[RSS] Successfully ran a forced RSS Check.
2016-08-23 11:07:28	INFO	[RSS] Watchlist Check complete.
2016-08-23 11:07:28	INFO	Completed RSS Search scan
2016-08-23 11:07:28	INFO	Finished searching via :rss. Issue not found - status kept as Wanted.
2016-08-23 11:07:28	INFO	Could not find Issue 1 of Violent Cases(2013) using TPSE [rss]
2016-08-23 11:07:28	DEBUG	seriesname_alt:None
2016-08-23 11:07:28	DEBUG	tsearch : violent%cases%
2016-08-23 11:07:28	DEBUG	ComicID: 69343
2016-08-23 11:07:28	DEBUG	Sending request to [TPSE] RSS for Violent Cases : 1

**Comment by evilhero** [comment]
I'm not exactly sure what it is that you're searching for that's having the problems - the Vertigo issue you were searching for isn't on nzbgeek, nzbindex, or even tpse.

If you can provide an issue that it can't find that I can verify exists on a site somewhere then I have something to go from in regards to why it's not working. Right now, based on what you posted above, it's working as intended (meaning the issue doesn't exist on any indexer so the fact that it's reporting it can't find anything is correct)..

**Comment by Lasborg** [comment]
had a simmilar issue as Ericgrau. and got the latest development to run at long last.

My error on search can be seen from the log here.

`2016-08-23 22:32:35	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1368, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 291, in search_init
if searchprov == '32P' and mylar.MODE_32P == 0:
UnboundLocalError: local variable 'searchprov' referenced before assignment
2016-08-23 22:32:35	INFO	search provider order is []
2016-08-23 22:32:35	INFO	Issue Title given as : sour grapes part 1 of 5
2016-08-23 22:32:35	INFO	Initiating manual search for Chew issue: 56`

**Comment by evilhero** [comment]
@Lasborg : You have no search providers stated in your provider_order line, which usually means you made provider configuration changes and didn't restart mylar after the change save so that it could update the provider_order correctly. 

Now you need to shut down mylar. Edit the config.ini and find the provider_order line and delete the entire line. Save the config.ini and start mylar and it will the  generate a new provider_order on startup so that it can search properly again.

**Comment by Lasborg** [comment]
@evilhero got that fixed and it looks like it does something.
But it looks like it is trying to get aj nzb, and I am using torrents

2016-08-23 22:49:36	INFO	[UPDATER] Updated the status (Snatched) complete for Chew Issue: 56
2016-08-23 22:49:36	INFO	[UPDATER] Updating status to snatched
2016-08-23 22:49:36	INFO	passing to updater.
2016-08-23 22:49:35	INFO	setting the nzbid for this download grabbed by TPSE in the nzblog to : 75A1B04DD0138848C202404030F705571F7E34AB
2016-08-23 22:49:35	INFO	matched on Chew
2016-08-23 22:49:35	INFO	Found Chew (2016) issue: 56 using TPSE
2016-08-23 22:49:35	INFO	allow_packs:False
2016-08-23 22:49:35	INFO	rss:no
2016-08-23 22:49:35	INFO	TPSE
2016-08-23 22:49:35	INFO	allow_packs:False
2016-08-23 22:49:35	INFO	rss:no
2016-08-23 22:49:35	INFO	TPSE
2016-08-23 22:49:35	INFO	allow_packs:False
2016-08-23 22:49:35	INFO	rss:no
2016-08-23 22:49:35	INFO	TPSE
2016-08-23 22:49:35	INFO	allow_packs:False
2016-08-23 22:49:35	INFO	rss:no
2016-08-23 22:49:35	INFO	TPSE
2016-08-23 22:49:35	INFO	allow_packs:False
2016-08-23 22:49:35	INFO	rss:no
2016-08-23 22:49:35	INFO	TPSE
2016-08-23 22:49:35	INFO	[TPSE] there were 5 results..
2016-08-23 22:49:35	INFO	Shhh be very quiet...I'm looking for Chew issue: 56 (2016) using TPSE
2016-08-23 22:49:35	INFO	allow_packs set to :False
2016-08-23 22:49:35	INFO	search provider order is ['tpse']
2016-08-23 22:49:35	INFO	Issue Title given as : sour grapes part 1 of 5
2016-08-23 22:49:35	INFO	Initiating manual search for Chew issue: 56

**Comment by evilhero** [comment]
Tpse is torrentproject, so it's grabbing a torrent, but it doesn't say what your download client is set to.

**Comment by Lasborg** [comment]
Got it. there was a typo in the "watchdirectory" so now it works as it should.
but I think that O'd better get a 32p membership.

Thanks a lot

**Comment by erickgrau** [comment]
Hi @evilhero 

You are absolutely right, at least with the series called Lucifer, It was searching for Vertigo Essentials Lucifer (a reprint 2015) instead of the Lucifer from 2000 which is what I found in nzbgeek.

I'll do a few more tests and get back to you.. I have tried adding new series and still doesn't find, but I will report back specific comic searches with links to nzbgeek (if I find of course).

Thanks

Erick

**Comment by evilhero** [comment]
No worries - if the name it's searching for is different than what it is, you can use the Alternate Search Name option located on the Edit tab of the series detail page for a given series. Mylar will then search for both the normal name and the alternate name and you should be able to grab those types of issues (because CV tends to name the series whatever they want I think sometimes)...
