### ISSUE TITLE
Mylar won't start if newer html5lib is installed at the system level

### ISSUE THREAD

**Issue by tresni** [evilhero/mylar#1354]
```
software/mylar ●» pip freeze | grep html5lib                                                            « [development]
html5lib==0.999999999
software/mylar ●» python Mylar.py                                                                       « [development]
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/opt/software/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "/opt/software/mylar/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/opt/software/mylar/mylar/rsscheck.py", line 15, in <module>
    from mylar import db, logger, ftpsshup, helpers, auth32p, utorrent
  File "/opt/software/mylar/mylar/auth32p.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/opt/software/mylar/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/opt/software/mylar/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/opt/software/mylar/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
software/mylar ●» pip uninstall html5lib                                                                « [development]
Uninstalling html5lib-0.999999999:
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/html5lib-0.999999999.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/html5lib/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_ihatexml.py
  /usr/local/lib/python2.7/site-packages/html5lib/_ihatexml.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_inputstream.py
  /usr/local/lib/python2.7/site-packages/html5lib/_inputstream.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_tokenizer.py
  /usr/local/lib/python2.7/site-packages/html5lib/_tokenizer.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/_base.py
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/_base.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/datrie.py
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/datrie.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/py.py
  /usr/local/lib/python2.7/site-packages/html5lib/_trie/py.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/_utils.py
  /usr/local/lib/python2.7/site-packages/html5lib/_utils.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/constants.py
  /usr/local/lib/python2.7/site-packages/html5lib/constants.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/alphabeticalattributes.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/alphabeticalattributes.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/base.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/base.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/inject_meta_charset.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/inject_meta_charset.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/lint.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/lint.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/optionaltags.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/optionaltags.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/sanitizer.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/sanitizer.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/filters/whitespace.py
  /usr/local/lib/python2.7/site-packages/html5lib/filters/whitespace.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/html5parser.py
  /usr/local/lib/python2.7/site-packages/html5lib/html5parser.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/serializer.py
  /usr/local/lib/python2.7/site-packages/html5lib/serializer.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/genshi.py
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/genshi.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/sax.py
  /usr/local/lib/python2.7/site-packages/html5lib/treeadapters/sax.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/base.py
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/base.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/dom.py
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/dom.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/etree.py
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/etree.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/etree_lxml.py
  /usr/local/lib/python2.7/site-packages/html5lib/treebuilders/etree_lxml.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/__init__.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/__init__.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/base.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/base.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/dom.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/dom.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/etree.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/etree.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/etree_lxml.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/etree_lxml.pyc
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/genshi.py
  /usr/local/lib/python2.7/site-packages/html5lib/treewalkers/genshi.pyc
Proceed (y/n)? y
  Successfully uninstalled html5lib-0.999999999
software/mylar ●» python Mylar.py                                                                       « [development]
22-Aug-2016 14:58:37 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: /opt/software/mylar
22-Aug-2016 14:58:37 - INFO :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.16
22-Aug-2016 14:58:37 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
22-Aug-2016 14:58:37 - INFO :: MAIN : [Cache Check] Cache directory currently set to : /opt/software/mylar/cache/
22-Aug-2016 14:58:37 - INFO :: MAIN : Checking to see if the database has all tables....
22-Aug-2016 14:58:37 - INFO :: MAIN : Populating Base Exception listings into Mylar....
22-Aug-2016 14:58:37 - INFO :: MAIN : Populating Custom Exception listings into Mylar....
22-Aug-2016 14:58:37 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
22-Aug-2016 14:58:37 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
22-Aug-2016 14:58:37 - INFO :: MAIN : Retrieving latest version information from github
22-Aug-2016 14:58:38 - INFO :: MAIN : Mylar is up to date
22-Aug-2016 14:58:38 - INFO :: MAIN : Remapping the sorting to allow for new additions.
22-Aug-2016 14:58:38 - INFO :: MAIN : Starting Mylar on http://0.0.0.0:8090/
software/mylar ●»                                                                                       « [development]

```

I think this is partially due to how libs are included anyway.  Instead of the hard includes, it's likely better to set (`PYTHONPATH`)[https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH] when the script starts up to source from the `/libs` directory first and system second.

**Comment by PCurd** [comment]
I'm experiencing this issue and can't uninstall html5lib - any other way to work around?

**Comment by tresni** [comment]
@PCurd are you on the latest version?  The way things are setup now, it should (iirc) use the version in lib first, then default to sys.path if nothing is in lib.

**Comment by PCurd** [comment]
@Tresni I pulled from Development and I get the same error (pretty much) as you. Only started happening after installing html5lib with pip last week.

**Comment by tresni** [comment]
You are right, I double checked and html5lib isn't installed in /lib by default.  I've changed my setup so I don't recall exactly how I ended up dealing with this.  iirc, upgrading beautifulsoup (`pip install --upgrade --target=lib beautifulsoup4`) should do the trick.  Or installing an older version of html5lib into the lib folder (`pip install --target=lib html5lib=0.99999999` -- keep removing 9's from the end until it works ;-) )

**Comment by evilhero** [comment]
Can we not just include html5lib in the lib folder or is there an os-dependency on it being locally installed?

**Comment by tresni** [comment]
You can.  The issue is a mismatch between html5lib and beautifulsoup4.  By default bs4 doesn't need html5lib and works just fine without it.  Upgrading bs4 is the cleaner fix as you aren't introducing a new dependancy.  Using html5lib is very slow, better to use lxml (which does have an OS dependancy.)  See https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser for the tradeoffs.

**Comment by evilhero** [comment]
Mylar is currently using 4.5.1, which is the most recent version of bs4 - so if it's not working, then we'll have to implement a different fix aside from upgrading bs4.

From what I can recall, when bs4 is called it attempts to use the best possible parser on the system to use - I'm guessing because html5lib is installed on the OS that it figures that it's a better choice than the native html parser and that's causing the problem. I know I can specify the parser to use whenever bs4 is called within Mylar (ie. line 78 of auth32p.py is one instance that's actually in place atm) and have it default to the native html parser - but would that cause any other issues that anyone can think of ?

**Comment by tresni** [comment]
@evilhero I don't think there is anything to do here..  I just did a virtual environment with completely clean python 2.7, Mylar, and html5lib.  I'm using [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io)

```
Projects/mylar-test ●» mkvirtualenv mylar-test                                                                   «
New python executable in /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/python2.7
Also creating executable in /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/python
Please make sure you remove any previous custom paths from your /Volumes/Home/bhartvigsen/.pydistutils.cfg file.
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/predeactivate
virtualenvwrapper.user_scripts creating /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/preactivate
virtualenvwrapper.user_scripts creating /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/postactivate
virtualenvwrapper.user_scripts creating /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/get_env_details
Projects/mylar-test ●» workon mylar-test                                                                         «
Projects/mylar-test ●» which python                                                                              «
/Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/python
Projects/mylar-test ●» python --version                                                                          «
Python 2.7.13
Projects/mylar-test ●» which pip                                                                                 «
/Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/bin/pip
Projects/mylar-test ●» pip --version                                                                             «
pip 9.0.1 from /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/lib/python2.7/site-packages (python 2.7)
Projects/mylar-test ●» git clone https://github.com/evilhero/mylar.git .                                         «
Cloning into '.'...
remote: Counting objects: 8850, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 8850 (delta 29), reused 0 (delta 0), pack-reused 8748
Receiving objects: 100% (8850/8850), 12.40 MiB | 1.67 MiB/s, done.
Resolving deltas: 100% (5005/5005), done.
Projects/mylar-test ●» pip install html5lib                                                             « [master]
Collecting html5lib
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Collecting webencodings (from html5lib)
Requirement already satisfied: setuptools>=18.5 in /Volumes/Home/bhartvigsen/.virtualenvs/mylar-test/lib/python2.7/site-packages (from html5lib)
Collecting six (from html5lib)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: webencodings, six, html5lib
Successfully installed html5lib-0.999999999 six-1.10.0 webencodings-0.5
Projects/mylar-test ●» pip freeze                                                                       « [master]
html5lib==0.999999999
six==1.10.0
webencodings==0.5
Projects/mylar-test ●» python Mylar.py                                                                  « [master]
lib/js2py/constructors/time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
/Volumes/Home/bhartvigsen/Projects/mylar-test/lib/js2py/constructors/time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
19-Dec-2016 17:43:36 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: /Volumes/Home/bhartvigsen/Projects/mylar-test
19-Dec-2016 17:43:36 - INFO :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.16
19-Dec-2016 17:43:36 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
19-Dec-2016 17:43:36 - INFO :: MAIN : [Cache Check] Cache directory currently set to :
19-Dec-2016 17:43:36 - INFO :: MAIN : [Cache Check] Cache directory not found in configuration. Defaulting location to : /Volumes/Home/bhartvigsen/Projects/mylar-test/cache
19-Dec-2016 17:43:36 - ERROR :: MAIN : No User Comicvine API key specified. I will not work very well due to api limits - http://api.comicvine.com/ and get your own free key.
19-Dec-2016 17:43:36 - INFO :: MAIN : Checking to see if the database has all tables....
19-Dec-2016 17:43:36 - INFO :: MAIN : Populating Base Exception listings into Mylar....
19-Dec-2016 17:43:36 - INFO :: MAIN : No Custom Exceptions found - Using base exceptions only. Creating blank custom_exceptions for your personal use.
19-Dec-2016 17:43:36 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
19-Dec-2016 17:43:36 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
19-Dec-2016 17:43:36 - INFO :: MAIN : Updating db to include some important changes.
19-Dec-2016 17:43:36 - INFO :: MAIN : Finshed updating 0 / 0 entries within the db.
19-Dec-2016 17:43:36 - INFO :: MAIN : Retrieving latest version information from github
19-Dec-2016 17:43:38 - INFO :: MAIN : Mylar is up to date
19-Dec-2016 17:43:38 - INFO :: MAIN : Remapping the sorting to allow for new additions.
19-Dec-2016 17:43:38 - INFO :: MAIN : Sucessfully ordered -1 series in your watchlist.
19-Dec-2016 17:43:38 - INFO :: MAIN : Starting Mylar on http://0.0.0.0:8090/
19-Dec-2016 17:43:38 - INFO :: MAIN : Initializing the DB Updater.
19-Dec-2016 17:43:38 - INFO :: RSSCHECK : delaying thread for 30 seconds to avoid locks.
19-Dec-2016 17:43:38 - INFO :: MAIN : Initiating startup-RSS feed checks.
19-Dec-2016 17:43:38 - INFO :: MAIN : Checking for existance of Weekly Comic listing...
19-Dec-2016 17:43:38 - INFO :: WEEKLYCHECK : delaying thread for 10 seconds to avoid locks.
19-Dec-2016 17:43:48 - INFO :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
19-Dec-2016 17:43:48 - INFO :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..
19-Dec-2016 17:43:48 - INFO :: WEEKLYCHECK : [PULL-LIST] Populating & Loading pull-list data from file
lib/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
19-Dec-2016 17:43:48 - INFO :: WEEKLYCHECK : Preparing to update to the new listing.
19-Dec-2016 17:43:48 - INFO :: WEEKLYCHECK : Populating the NEW Weekly Pull list into Mylar for week 51
19-Dec-2016 17:43:49 - INFO :: WEEKLYCHECK : Weekly Pull List successfully loaded.
19-Dec-2016 17:43:49 - INFO :: WEEKLYCHECK : Checking the Weekly Releases list for comics I'm watching...
19-Dec-2016 17:43:49 - INFO :: WEEKLYCHECK : No series have been marked as being on auto-watch.
19-Dec-2016 17:43:55 - INFO :: MAIN : Received signal: shutdown
19-Dec-2016 17:43:55 - INFO :: MAIN : Aborting all threads
19-Dec-2016 17:43:55 - INFO :: MAIN : Waiting for the DB UPDATE thread to exit
19-Dec-2016 17:43:56 - INFO :: MAIN : Waiting for the SEARCH thread to exit
19-Dec-2016 17:43:57 - INFO :: MAIN : Waiting for the RSS CHECK thread to exit
19-Dec-2016 17:44:07 - INFO :: MAIN : Waiting for the WEEKLY CHECK thread to exit
19-Dec-2016 17:44:07 - INFO :: MAIN : Waiting for the VERSION CHECK thread to exit
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : RSS Feed Check was last run at :
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : RSS Feed Check First Ever Run.
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : [RSS] Initiating RSS Feed Check for NZB Providers.
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : [RSS] RSS Feed Check/Update Complete
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : [RSS] Watchlist Check for new Releases
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : Initiating RSS Search Scan at the scheduled interval of 20 minutes.
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : Completed RSS Search scan
19-Dec-2016 17:44:08 - INFO :: RSSCHECK : [RSS] Watchlist Check complete.
19-Dec-2016 17:44:08 - INFO :: MAIN : Waiting for the FOLDER MONITOR thread to exit
19-Dec-2016 17:44:08 - INFO :: MAIN : Mylar is shutting down...
Projects/mylar-test ●» git checkout development                                                         « [master]
Branch development set up to track remote branch development from origin.
Switched to a new branch 'development'
Projects/mylar-test ●» python Mylar.py                                                             « [development]
lib/js2py/constructors/time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
/Volumes/Home/bhartvigsen/Projects/mylar-test/lib/js2py/constructors/time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
19-Dec-2016 17:45:00 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: /Volumes/Home/bhartvigsen/Projects/mylar-test
19-Dec-2016 17:45:00 - INFO :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.16
19-Dec-2016 17:45:00 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
19-Dec-2016 17:45:00 - INFO :: MAIN : [Cache Check] Cache directory currently set to : /Volumes/Home/bhartvigsen/Projects/mylar-test/cache
19-Dec-2016 17:45:00 - INFO :: MAIN : Checking to see if the database has all tables....
19-Dec-2016 17:45:00 - INFO :: MAIN : Populating Base Exception listings into Mylar....
19-Dec-2016 17:45:00 - INFO :: MAIN : Populating Custom Exception listings into Mylar....
19-Dec-2016 17:45:00 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
19-Dec-2016 17:45:00 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
19-Dec-2016 17:45:00 - INFO :: MAIN : Retrieving latest version information from github
19-Dec-2016 17:45:02 - INFO :: MAIN : New version is available. You are 45 commits behind
19-Dec-2016 17:45:02 - INFO :: MAIN : Remapping the sorting to allow for new additions.
19-Dec-2016 17:45:02 - INFO :: MAIN : Sucessfully ordered -1 series in your watchlist.
19-Dec-2016 17:45:02 - INFO :: MAIN : Starting Mylar on http://0.0.0.0:8090/
19-Dec-2016 17:45:02 - INFO :: MAIN : Initializing the DB Updater.
19-Dec-2016 17:45:02 - INFO :: RSSCHECK : delaying thread for 30 seconds to avoid locks.
19-Dec-2016 17:45:02 - INFO :: MAIN : Initiating startup-RSS feed checks.
19-Dec-2016 17:45:02 - INFO :: MAIN : Checking for existance of Weekly Comic listing...
19-Dec-2016 17:45:02 - INFO :: WEEKLYCHECK : delaying thread for 10 seconds to avoid locks.
19-Dec-2016 17:45:05 - INFO :: MAIN : Received signal: shutdown
19-Dec-2016 17:45:05 - INFO :: MAIN : Aborting all threads
19-Dec-2016 17:45:05 - INFO :: MAIN : Waiting for the DB UPDATE thread to exit
19-Dec-2016 17:45:06 - INFO :: MAIN : Waiting for the SEARCH thread to exit
19-Dec-2016 17:45:07 - INFO :: MAIN : Waiting for the RSS CHECK thread to exit
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : [PULL-LIST] Populating & Loading pull-list data from file
lib/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : No new pull-list available - will re-check again in 24 hours.
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : Checking the Weekly Releases list for comics I'm watching...
19-Dec-2016 17:45:12 - INFO :: WEEKLYCHECK : No series have been marked as being on auto-watch.
19-Dec-2016 17:45:17 - INFO :: MAIN : Waiting for the WEEKLY CHECK thread to exit
19-Dec-2016 17:45:18 - INFO :: MAIN : Waiting for the VERSION CHECK thread to exit
19-Dec-2016 17:45:18 - INFO :: MAIN : Waiting for the FOLDER MONITOR thread to exit
19-Dec-2016 17:45:18 - INFO :: MAIN : Mylar is shutting down...
```

@PCurd - Double check you are using the latest master (or development).

**Comment by PCurd** [comment]
@tresni I have been updating with git pull before each try, looks like I was up to date when I last tried. Here is my most recent attempt. Note I am on Windows 10 if this makes a difference (looks like your environment is *nix?)


D:\Mylar\mylar>dir .\lib
 Volume in drive D has no label.
 Volume Serial Number is 3xxx

 Directory of D:\Mylar\mylar\lib

19/12/2016  19:20    <DIR>          .
19/12/2016  19:20    <DIR>          ..
25/10/2016  11:44    <DIR>          apscheduler
28/08/2013  11:28            91,939 argparse.py
25/10/2016  11:44            65,294 argparse.pyc
25/10/2016  11:44    <DIR>          bs4
02/02/2015  18:22             2,974 certgen.py
25/10/2016  11:44    <DIR>          cfscrape
25/10/2016  11:44    <DIR>          cherrypy
25/10/2016  11:44    <DIR>          comictaggerlib
02/02/2015  18:22    <DIR>          ConcurrentLogHandler
28/08/2013  11:28            90,631 configobj.py
28/08/2013  11:29            64,696 configobj.pyc
19/12/2016  19:20    <DIR>          deluge_client
28/08/2013  11:28           171,986 feedparser.py
28/08/2013  11:29           142,290 feedparser.pyc
25/10/2016  11:44    <DIR>          httplib2
25/10/2016  11:44    <DIR>          js2py
19/12/2016  19:20    <DIR>          mako
25/10/2016  11:44    <DIR>          markupsafe
28/08/2013  11:28             3,642 MultipartPostHandler.py
25/10/2016  11:44    <DIR>          requests
15/12/2016  21:04    <DIR>          rtorrent
25/10/2016  11:44    <DIR>          simplejson
25/10/2016  11:44            30,966 six.py
25/10/2016  11:44            29,010 six.pyc
25/10/2016  11:44    <DIR>          stun
25/10/2016  11:44    <DIR>          tests
25/10/2016  11:44    <DIR>          transmissionrpc
17/04/2016  17:10    <DIR>          utorrent
28/08/2013  11:28                 2 __init__.py
28/08/2013  11:29               117 __init__.pyc
              12 File(s)        693,547 bytes
              20 Dir(s)  134,231,392,256 bytes free

D:\Mylar\mylar>python --version
Python 2.7.11

D:\Mylar\mylar>c:\Python27\Scripts\pip.exe freeze
cffi==1.5.0
Cheetah==2.4.0
cryptography==1.2.1
enum34==1.1.2
html5lib==0.999999999
humblebundle==0.1.1
idna==2.0
ipaddress==1.0.16
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
pytz==2016.7
pywin32==220
requests==2.10.0
six==1.10.0
tzlocal==1.3
webencodings==0.5

D:\Mylar\mylar>git status
# On branch development
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       RunMylar.bat
#       debug.log
#       sabnzbd/
nothing added to commit but untracked files present (use "git add" to track)

D:\Mylar\mylar>git rev-parse head
9340cf8cf587b9c9f084b72d097d0412f25f9740

D:\Mylar\mylar>git pull
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 22 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
From https://github.com/evilhero/mylar
   9340cf8..64658f2  development -> origin/development
Updating 9340cf8..64658f2
Fast-forward
 data/interfaces/default/css/style.css |  6 ++++--
 data/interfaces/default/index.html    | 13 ++++++++++---
 mylar/__init__.py                     | 12 +++++++++++-
 mylar/cv.py                           | 14 +++++++++++++-
 mylar/helpers.py                      |  3 ++-
 mylar/importer.py                     |  8 ++++++--
 6 files changed, 46 insertions(+), 10 deletions(-)

D:\Mylar\mylar>git rev-parse head
64658f220109ae2dc7a0e4f696dded115a4b9bcf

D:\Mylar\mylar>python mylar.py
Traceback (most recent call last):
  File "mylar.py", line 26, in <module>
    import mylar
  File "D:\Mylar\mylar\mylar\__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "D:\Mylar\mylar\mylar\rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "D:\Mylar\mylar\mylar\rsscheck.py", line 16, in <module>
    from mylar import db, logger, ftpsshup, helpers, auth32p, utorrent
  File "D:\Mylar\mylar\mylar\auth32p.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "D:\Mylar\mylar\bs4\__init__.py", line 29, in <module>

  File "D:\Mylar\mylar\bs4\builder\__init__.py", line 306, in <module>

  File "D:\Mylar\mylar\bs4\builder\_html5lib.py", line 57, in <module>
AttributeError: 'module' object has no attribute '_base'

**Comment by evilhero** [comment]
Have you tried removing the .pyc files for bs4 (and probably the mylar subdirectory too)?  It might be having problems if the pyc files are trying to import from an incorrect location as it looks like it's looking for bs4 in mylar\bs4 (the old location) as opposed to the new location of mylar\lib\bs4

**Comment by PCurd** [comment]
@EvilHero that did it - I removed the bs4 folder (mylar\bs4) which only had .pyc files in it and Mylar started.. One error but probably unrelated:

`lib\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html`

Then after 1-2 minutes I got:
```

lib\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 774 of the file c:\python27\lib\threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
```

Thank you, and thank you @tresni - sorry to cause trouble. Should I delete all the .pyc files in the entire folder tree?

**Comment by evilhero** [comment]
You can delete the pyc files if you want to - as long as mylar isn't running when you do it, they'll get regenerated on the next startup. 

The 1st warning relates to your python and having an incompatible openssl so it can't make secure certificate requests and verify the certificates properly. The fix, if you're already on python 2.7.9+ for most is to do a 'pip install requests[cryptography]' in order to install the necessary modules for ssl. Note that in some cases this doesn't work, but usually it's been pretty reliable.

**Comment by PCurd** [comment]
Thanks for the advice! When I try to run the pip command it doesn't seem to
think anything is wrong:


D:\Mylar\mylar>c:\Python27\Scripts\pip.exe install requests[cryptography]
Requirement already satisfied: requests[cryptography] in
c:\python27\lib\site-packages
  requests 2.10.0 does not provide the extra 'cryptography'

I wondered if removing the rest of the pyc files would help, so I stopped
Mylar, deleted them, and started Mylar again - I still get the warning :(

**Comment by evilhero** [comment]
hm, ok if you can since you're on windows can you try the following (with Mylar not running):

- open up mylar/weeklypull.py
- on roughly line 1241 you should see:
```
r = requests.get(PULLURL, verify=False, headers=PULL_AGENT, stream=True)
```
change it to
```
r = requests.get(PULLURL, verify=True, headers=PULL_AGENT, stream=True)
```
save the file, delete the pyc file and then start Mylar - and hopefully you shouldn't get that message any longer.

**Comment by PCurd** [comment]
No message! I also did an update inside Mylar and it still works after a restart, but of course git status shows a modified file now.

**Comment by evilhero** [comment]
Yep, that's good - I figured that was it since the site mylar pulls against with the alt_pull 0 method changed their site and went ssl only.

Will be fixed in the next dev commit going up shortly so you shouldn't have to worry about the git status for long ;)

**Comment by PCurd** [comment]
Excellent! Thanks! Does someone want to close this issue?
