### ISSUE TITLE
Kickasstorrents Outage issues

### ISSUE THREAD

**Issue by the-Dakta** [evilhero/mylar#1355]
So I know that it's not really your issue that kat.ph is has been taken down, but it was my primary method for getting comics. Now that it's down, my other tracker either simply doesn't have any books, or can only find packs, which Mylar doesn't necessarily like. That's ok.

What I ask is if we can somehow impliment the ability to search one of the many kickasstorrents mirrors that are out there. This site seems to do a good job at collecting them in one place:
http://www.torrentmirror.net/

Thanks for all of your hard work!

**Comment by evilhero** [comment]
Well actually the last commit in the development branch that went up a few days ago has public torrent support again. KAT was removed from Mylar (due to all the other sites being scams / fakes that just mirror TPB but with the KAT template),  and 3 different public torrent sites were added. 

For backlog searches, Torrentproject is being used now.  TP is a meta-search engine that queries against 5/6 different big torrent sites. 

For RSS feeds, both Demonoid and WorldwideTorrents are used mainly because DEM has a good backlog of stuff and WWT is where the old comic posters from KAT are now posting on.  

So as long as you have RSS enabled and the public Torrent option you should be able to get pretty good coverage ;) 

I do plan on implementing backlog support for both DEM and WWT, but atm they both require page parsing to get done so it's more involved a d will take alot of testing.

**Comment by the-Dakta** [comment]
Holy shit you are the man. Thanks for the great response!

**Comment by the-Dakta** [comment]
I don't know if I just read obscure shit or what, but I still can't find my comics with these enabled. It says it's searching and the logs look ok with no apparent errors, but it won't download anything.

**Comment by evilhero** [comment]
It depends on what you're searching for... Do you have the log lines showing what you're searching for - and are you sure they exist on those sites? (keeping in mind that only TP has support for directly searching)

**Comment by the-Dakta** [comment]
So far I've only refreshed my list, so I'm sure it's having some issues with these few items and I should probably give it some time to finish looking.

2016-08-22 16:17:52	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 16:17:52	INFO	Shhh be very quiet...I'm looking for Moon Girl and Devil Dinosaur issue: 9 (2016) using Torznab
2016-08-22 16:17:52	INFO	allow_packs set to :False
2016-08-22 16:17:52	INFO	Finished searching via :rss. Issue not found - status kept as Wanted.
2016-08-22 16:17:52	INFO	Could not find Issue 9 of Moon Girl and Devil Dinosaur(2015) using Torznab [rss]
2016-08-22 16:17:52	INFO	Shhh be very quiet...I'm looking for Moon Girl and Devil Dinosaur issue: 9 (2016) using Torznab [RSS]
2016-08-22 16:17:52	INFO	allow_packs set to :False
2016-08-22 16:17:52	INFO	search provider order is ['torznab']
2016-08-22 16:17:52	INFO	Issue Title given as : cosmic cooties part three: moon and stars
2016-08-22 16:17:52	INFO	Finished searching via :api. Issue not found - status kept as Wanted.
2016-08-22 16:17:52	INFO	Could not find Issue 8 of Moon Girl and Devil Dinosaur(2015) using Torznab [api]
2016-08-22 16:16:52	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 16:16:41	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2016-08-22 16:16:41	WARNING	There were no files located - check the debugging logs if you think this is in error.
2016-08-22 16:16:41	INFO	there are 0 files.
2016-08-22 16:16:41	INFO	[FOLDER-CHECK] Checking folder V:\Downloading\Done for newly snatched downloads

Looking at TP, it seems all of them are marked 2016, so I've removed the date and added some alternative search for this particular comic. I'm going to give this a few hours I guess (I'm not sure how long it should take to search 200 issues) and report back with some more logs.

**Comment by evilhero** [comment]
Well torznab is dependent on the trackers that you're using - I only tested against IPT, so the results might be hit or miss depending on how they're named on the tracker. 

200 issue would take a fair bit of time, but if you want to search for one particular issue you can use the magnifying glass icon on each series page beside a given issue to check immediately for the issue (rss + api). 

To use the public torrents, just enable the public torrent option and restart mylar after you save the config

**Comment by the-Dakta** [comment]
Yeah IPT isn't great for comics, but I've left it on there anyways. It's all I've got for torznab.

I've got public torrents on now as well, so it should be searching there as well. When you say it only has support for directly searching, how direct are we talking about? For example, here is a relatively more popular comic search, and it appears to be all of the lines relevant to this particular search:


2016-08-22 16:26:56	INFO	Finished searching via :rss. Issue not found - status kept as Wanted.
2016-08-22 16:26:56	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [rss]
2016-08-22 16:26:56	DEBUG	Sending request to RSS for Civil War II : 2 (2016)
2016-08-22 16:26:56	DEBUG	Sending request to RSS for Civil War II : 02 (2016)
2016-08-22 16:26:56	DEBUG	Sending request to RSS for Civil War II : 002 (2016)
2016-08-22 16:26:56	DEBUG	calpha/cnumber: None / None
2016-08-22 16:26:56	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using Torznab [RSS]
2016-08-22 16:26:56	INFO	allow_packs set to :False
2016-08-22 16:26:56	DEBUG	Initiating Search via : rss
2016-08-22 16:26:56	INFO	search provider order is ['torznab']
2016-08-22 16:26:56	DEBUG	provider order sequence is now to start with Torznab at spot #1
2016-08-22 16:26:56	DEBUG	torrent provider found: torznab
2016-08-22 16:26:56	DEBUG	checking against torrent provider: torznab
2016-08-22 16:26:56	DEBUG	checking against torrent provider: tpse
2016-08-22 16:26:56	DEBUG	found provider in existing enabled providers.
2016-08-22 16:26:56	DEBUG	Usenet Retention : 1500 days
2016-08-22 16:26:56	DEBUG	there are : 0 nzb providers you have selected.
2016-08-22 16:26:56	DEBUG	there are : 2 torrent providers you have selected.
2016-08-22 16:26:56	DEBUG	nzbprovider(s): []
2016-08-22 16:26:56	DEBUG	Checking for torrent enabled.
2016-08-22 16:26:56	INFO	Issue Title given as : None
2016-08-22 16:26:56	DEBUG	Publisher is : Marvel

My question, is it "directly searching" for "Civil War II issue: 2 (2016)"? Because nothing even remotely to that shows up on TP: "Civil War II 002 (2016) Digital Zone Empire cbr"

**Comment by evilhero** [comment]
It's actually searching for all the numerical variations of the given issue (2,02,002) - it just displays the 'Civil War I issue :2' for display purposes.

Direct searching means that Mylar can query directly against the site (tpse in this case) for information. The RSS stuff will only monitors the feeds themselves and cache them, so if you don't have mylar running 24/7, or it's off for a period of time, you're going to have some empty spots in regards to coverage) 

Also, your search providers are only listing the torznab, you might want to restart mylar to make sure it picks up the tpse option (after a provider config change, it's necessary to restart mylar so it can update the provider_order properly as it only gets generated on startup). 

You can keep this ticket open if you want, it's related at least so it's easily follow able ;)

**Comment by the-Dakta** [comment]
I've restarted Mylar so many times since enabling that, and I've confirmed that it's enabled in the text config too.

![2016-08-22 16_45_04-mylar - settings](https://cloud.githubusercontent.com/assets/1900577/17875557/df11e5ec-6887-11e6-9fba-767804c2bb84.png)


I'm restarting it one more time for good measure.

**Comment by evilhero** [comment]
Check the provider_order line in the config.ini. Odds are it only has the one provider listed... If you delete the provider_order line from the config.ini (with mylar not running), then start up mylar again it will regenerate a new provider_order line on startup.

**Comment by the-Dakta** [comment]
It had "0, kat, 1, Torznab" in that line, so I deleted it anyways. I'll report back in a bit I suppose.

**Comment by the-Dakta** [comment]
2016-08-22 16:53:48	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Users\Josh\Desktop\servers\mylar-master\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Josh\Desktop\servers\mylar-master\mylar\webserve.py", line 1368, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "C:\Users\Josh\Desktop\servers\mylar-master\mylar\search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "C:\Users\Josh\Desktop\servers\mylar-master\mylar\search.py", line 669, in NZB_SEARCH
for entry in bb['entries']:
TypeError: 'NoneType' object has no attribute '__getitem__'

2016-08-22 16:53:48	WARNING	Error fetching RSS Feed Data from TPSE: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2016-08-22 16:53:48	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using TPSE
2016-08-22 16:53:48	INFO	allow_packs set to :False
2016-08-22 16:53:48	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [rss]
2016-08-22 16:53:48	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using Torznab [RSS]
2016-08-22 16:53:48	INFO	allow_packs set to :False
2016-08-22 16:53:48	INFO	Could not find Issue 2 of Civil War II(2016) using TPSE [rss]
2016-08-22 16:53:48	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using TPSE [RSS]
2016-08-22 16:53:48	INFO	allow_packs set to :False
2016-08-22 16:53:48	INFO	search provider order is ['tpse', 'torznab']
2016-08-22 16:53:48	INFO	Issue Title given as : None
2016-08-22 16:53:48	INFO	Initiating manual search for Civil War II issue: 2

Don't mind the directory names, that's just because I updated it in place. This is what I got when I searched for that same issue of Civil War II again. It seems it's at least searching TPSE, but I'm not sure what else is going on now.

**Comment by evilhero** [comment]
Same issue as someone on irc just a few moments ago.  They were using an older python version which was the problem. 

Is your version of python at least 2.7.9? SNI support for ssl is only working in that version up, although if you install/have 2.7.9+ and still get the error you might have to install the cryptography package too (pip install requests [security])

**Comment by the-Dakta** [comment]
I have 2.7.10 and 2.7.7 installed. Let me make sure that this is using the right version.

**Comment by the-Dakta** [comment]
I think that mostly everything is working, because while I was gathering these logs for the same issue of Civil War II, a completely unrelated comic was randomly found and downloaded.

2016-08-22 17:36:33	DEBUG	Could not find issue doing a manual search via : api
2016-08-22 17:36:33	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [api]
2016-08-22 17:36:33	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%202&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:36:02	DEBUG	Could not find issue doing a manual search via : api
2016-08-22 17:36:02	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [api]
2016-08-22 17:36:01	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%202&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:35:33	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:35:33	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%2002&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:35:18	DEBUG	Could not find issue doing a manual search via : api
2016-08-22 17:35:18	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [api]
2016-08-22 17:35:17	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%202&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:35:01	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:35:01	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%2002&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:34:33	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:34:32	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%20002&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:34:17	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:34:17	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%2002&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:34:01	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:34:00	DEBUG	[SSL: False] Search URL: http://127.0.0.1:9117/torznab/iptorrents?t=search&q=civil%20war%20ii%20002&o=xml&cat=8020&apikey=xUDONTNEEDTOKNOWTHISx
2016-08-22 17:33:32	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-08-22 17:33:32	DEBUG	calpha/cnumber: None / None
2016-08-22 17:33:32	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using Torznab
2016-08-22 17:33:32	INFO	allow_packs set to :False
2016-08-22 17:33:32	INFO	Could not find Issue 2 of Civil War II(2016) using TPSE [api]
2016-08-22 17:33:32	INFO	[TPSE] there were 0 results..
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] for civil war ii : 2
2016-08-22 17:33:32	INFO	[TPSE] there were 0 results..
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] for civil war ii : 02
2016-08-22 17:33:32	INFO	[TPSE] there were 0 results..
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] for civil war ii : 002
2016-08-22 17:33:32	DEBUG	calpha/cnumber: None / None
2016-08-22 17:33:32	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using TPSE
2016-08-22 17:33:32	INFO	allow_packs set to :False
2016-08-22 17:33:32	DEBUG	Initiating Search via : api
2016-08-22 17:33:32	DEBUG	Could not find issue doing a manual search via : rss
2016-08-22 17:33:32	INFO	Could not find Issue 2 of Civil War II(2016) using Torznab [rss]
2016-08-22 17:33:32	DEBUG	Sending request to RSS for Civil War II : 2 (2016)
2016-08-22 17:33:32	DEBUG	Sending request to RSS for Civil War II : 02 (2016)
2016-08-22 17:33:32	DEBUG	Sending request to RSS for Civil War II : 002 (2016)
2016-08-22 17:33:32	DEBUG	calpha/cnumber: None / None
2016-08-22 17:33:32	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using Torznab [RSS]
2016-08-22 17:33:32	INFO	allow_packs set to :False
2016-08-22 17:33:32	INFO	Could not find Issue 2 of Civil War II(2016) using TPSE [rss]
2016-08-22 17:33:32	DEBUG	seriesname_alt:None
2016-08-22 17:33:32	DEBUG	tsearch : civil%war%ii%
2016-08-22 17:33:32	DEBUG	ComicID: 90521
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] RSS for Civil War II : 2
2016-08-22 17:33:32	DEBUG	seriesname_alt:None
2016-08-22 17:33:32	DEBUG	tsearch : civil%war%ii%
2016-08-22 17:33:32	DEBUG	ComicID: 90521
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] RSS for Civil War II : 02
2016-08-22 17:33:32	DEBUG	seriesname_alt:None
2016-08-22 17:33:32	DEBUG	tsearch : civil%war%ii%
2016-08-22 17:33:32	DEBUG	ComicID: 90521
2016-08-22 17:33:32	DEBUG	Sending request to [TPSE] RSS for Civil War II : 002
2016-08-22 17:33:32	DEBUG	calpha/cnumber: None / None
2016-08-22 17:33:32	INFO	Shhh be very quiet...I'm looking for Civil War II issue: 2 (2016) using TPSE [RSS]
2016-08-22 17:33:32	INFO	allow_packs set to :False
2016-08-22 17:33:32	DEBUG	Initiating Search via : rss
2016-08-22 17:33:32	INFO	search provider order is ['tpse', 'torznab']
2016-08-22 17:33:32	DEBUG	provider order sequence is now to start with Torznab at spot #1
2016-08-22 17:33:32	DEBUG	torrent provider found: torznab
2016-08-22 17:33:32	DEBUG	checking against torrent provider: torznab
2016-08-22 17:33:32	DEBUG	checking against torrent provider: tpse
2016-08-22 17:33:32	DEBUG	found provider in existing enabled providers.
2016-08-22 17:33:32	DEBUG	provider order sequence is now to start with tpse at spot #0
2016-08-22 17:33:32	DEBUG	torrent provider found: tpse
2016-08-22 17:33:32	DEBUG	checking against torrent provider: tpse
2016-08-22 17:33:32	DEBUG	found provider in existing enabled providers.
2016-08-22 17:33:32	DEBUG	Usenet Retention : 1500 days
2016-08-22 17:33:32	DEBUG	there are : 0 nzb providers you have selected.
2016-08-22 17:33:32	DEBUG	there are : 2 torrent providers you have selected.
2016-08-22 17:33:32	DEBUG	nzbprovider(s): []
2016-08-22 17:33:32	DEBUG	Checking for torrent enabled.
2016-08-22 17:33:32	INFO	Issue Title given as : None
2016-08-22 17:33:32	DEBUG	Publisher is : Marvel
2016-08-22 17:33:32	INFO	Initiating manual search for Civil War II issue: 2
2016-08-22 17:33:32	DEBUG	mode:want
2016-08-22 17:33:32	DEBUG	ComicID:90521

**Comment by evilhero** [comment]
The torznab uses a non-https connection tho, so the tpse might not be working if you're running it with 2.7.7 (you can easily check which version mylar is using by going to the very first tab of the configuration in the GUI)

**Comment by the-Dakta** [comment]
It can't seem to find them, despite the fact that I can see good results when searching for many of the same things on TPSE.

I've actually just updated to 2.7.10 and uninstalled all other versions prior.

**Comment by evilhero** [comment]
It looks like TPSE has cloud flare protection now, which might be causing an issue (or they're in protection mode of some kind). 

If you're not getting the ssl errors anymore, then there's something wrong with the way mylar is trying to reach TPSE now. 

I'll have to look into this more as you're the 2nd person now having problems related to that site so there's obviously something occurring.

**Comment by the-Dakta** [comment]
Yeah every time I visit TP it waits a few seconds for Cloudflare. If it's just searching with a URL query, I suspect that could definitely be the issue.

**Comment by the-Dakta** [comment]
So I haven't changed anything since my last comment, but last night a ton of comics downloaded out of the blue. I don't know if cloudflare is only on during certain times, or if the requests were made soon enough after one another that it worked or what, but it was working for a while last night.

**Comment by evilhero** [comment]
Yeah it looks like it's their anti-ddos protection was kicking in - the cloudfare protection is gone now, so it's working as per normal (as it was when I was coding it - the anti-ddos never kicked in).

I'll look into trying to figure out a way to handle the ddos protection flare going up, but until then it's just a matter of waiting out the lock ;)

Glad you got it working tho!

**Comment by thorinmesser** [comment]
TPSE's cloudflare DDOS seems to be on pretty much constantly for about the last two weeks. I've turned torrents off.

**Comment by evilhero** [comment]
Even with the cloudflare up, it should be working in the latest development commit, unless they've gone to captcha now.

**Comment by thorinmesser** [comment]
Oh, man, once again, you are the BEST. You've got it fixed before I even know it's broke! Thank you.
