### ISSUE TITLE
Exception in WEEKLYCHECK

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1357]
I hadn't noticed this before but today when I did a restart and went to the pull list this popped up in the logs, let me know if you need more of the log:

```
23-Aug-2016 09:18:55 - INFO    :: WEEKLYCHECK : controlValue:{'COMIC': 'Extraordinary X-Men', 'ISSUE': '13', 'WEEKNUMBER': '34', 'YEAR': '2016'}
23-Aug-2016 09:18:55 - INFO    :: WEEKLYCHECK : CStatus:None
23-Aug-2016 09:18:55 - INFO    :: WEEKLYCHECK : newValue:{'STATUS': 'Wanted', 'IssueID': None, 'ComicID': u'85756'}
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : looking for : DOCTOR STRANGE
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : searchsql: %doctorstrange%
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : comparingMARVELS DOCTOR STRANGE PRELUDE..to..DOCTOR STRANGE
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : watchcomic : Doctor Strange
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : comicnm : MARVELS DOCTOR STRANGE PRELUDE
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : comparingMarvelâs Doctor Strange Prelude..to..DOCTOR STRANGE
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : watchcomic : Doctor Strange
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : Exception generated in thread WEEKLYCHECK: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)
23-Aug-2016 09:18:55 - DEBUG   :: WEEKLYCHECK : 'Traceback (most recent call last):\n  File "/home/xxx/Apps/Mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/home/xxx/Apps/Mylar/mylar/weeklypullit.py", line 30, in run\n    mylar.weeklypull.pullit()\n  File "/home/xxx/Apps/Mylar/mylar/weeklypull.py", line 203, in pullit\n    pullitcheck()\n  File "/home/xxx/Apps/Mylar/mylar/weeklypull.py", line 670, in pullitcheck\n    logger.fdebug("comicnm : " + str(comicnm)) # / mod :" + str(modcomicnm))\nUnicodeEncodeError: \'ascii\' codec can\'t encode characters in position 6-8: ordinal not in range(128)\n'
```

**Comment by evilhero** [comment]
are you on the development branch ? 

I'm guessing your using the alt_pull method of either 0/1  (meaning you haven't changed it specifically)

**Comment by weidercs** [comment]
yeah on the development branch
atl_pull is 0
```
usenet_retention = 2500
alt_pull = 0
search_interval = 360
```

**Comment by evilhero** [comment]
That's some weird Unicode going on.. I'll have to look into it when I can get to a machine later today. 

Until then you can either remove it from your pull temporarily, or you can set alt_pull = 2 (with mylar not running). Either of these methods would remove the error so that you can continue monitoring the pullist properly.

**Comment by weidercs** [comment]
Don't know if they cleaned up the feed or we had a glitch in the matrix but I just refreshed the pull-list and the unicode is gone now...  I'll close it if you want.

```
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : Weekly Update for week 34-2016 : EXTRAORDINARY X-MEN #13 to a status of Wanted
23-Aug-2016 09:58:41 - INFO    :: Thread-12 : controlValue:{'COMIC': 'EXTRAORDINARY X-MEN', 'ISSUE': '13', 'WEEKNUMBER': '34', 'YEAR': '2016'}
23-Aug-2016 09:58:41 - INFO    :: Thread-12 : CStatus:Wanted
23-Aug-2016 09:58:41 - INFO    :: Thread-12 : newValue:{'STATUS': 'Wanted', 'IssueID': u'546057', 'ComicID': u'85756'}
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : looking for : DOCTOR STRANGE
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : searchsql: %doctorstrange%
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : comparingMARVELS DOCTOR STRANGE PRELUDE..to..DOCTOR STRANGE
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : watchcomic : Doctor Strange
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : comicnm : MARVELS DOCTOR STRANGE PRELUDE
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : looking for : CONTEST OF CHAMPIONS
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : searchsql: %contestofchampions%
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : looking for : SPIDER-GWEN
23-Aug-2016 09:58:41 - DEBUG   :: Thread-12 : searchsql: %spidergwen%
```

**Comment by evilhero** [comment]
That's weird.. If you're on the alt_pull 0 method then there shouldn't be in Unicode in there as it's just a plain text file that's get pulled down. 

I'll remove the str conversion that it does anyways in case it happens again, plus the str conversion shouldnt be there anyways ;) 

Thanks for reporting back with the update!!
