### ISSUE TITLE
KeyError: 'ComicPublisher' on import

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1366]
The comic I am trying to import at the moment is "Hotline Miami - Wildlife 001 (2016).cbr".

```
28-Aug-2016 13:24:22 - INFO :: LibraryScan : Successfully loaded 2048 series from your watchlist.
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT] Parsing/Reading of files completed!
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT] Attempting to import 1 files into your watchlist.
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT-BREAKDOWN] Files with ComicIDs successfully extracted: 0
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT-BREAKDOWN] Files that had to be parsed: 1
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT-BREAKDOWN] Files that were unable to be parsed: 0
28-Aug-2016 13:24:22 - INFO :: LibraryScan : [IMPORT-BREAKDOWN] Failure Files: []
28-Aug-2016 13:24:22 - INFO :: CP Server Thread-11 : Successfully scanned in directory. Enabling the importResults button now.
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : here
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : Checking for any valid ComicID's already present within filenames.
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : {'Volume': u'None', 'ComicName': u'Hotline Miami - Wildlife', 'DynamicName': u'hotlinemiamiwildlife', 'ComicID': u'None'}
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : [Hotline Miami - Wildlife] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : [none] dynamicname: hotlinemiamiwildlife
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : [none] volume: None
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : yearTOP: 2016
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : yearRANGE: ['2016']
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : 1000
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : there
28-Aug-2016 13:24:27 - INFO :: CP Server Thread-11 : numissues: 1
28-Aug-2016 13:24:32 - INFO :: CP Server Thread-11 : [IMPORT MATCH] HotlineMiamiWildlife (92086)
28-Aug-2016 13:24:32 - INFO :: CP Server Thread-11 : There is only one result...automagik-mode enabled for Hotline Miami Wildlife :: 92086
28-Aug-2016 13:24:32 - INFO :: CP Server Thread-11 : now adding...
28-Aug-2016 13:24:32 - INFO :: CP Server Thread-11 : Attempting to add directly by ComicVineID: 92086
28-Aug-2016 13:24:32 - INFO :: CP Server Thread-11 : [IMPORT] Initial Import complete (I might still be populating the series data).
28-Aug-2016 13:24:35 - INFO :: Thread-36 : Now adding/updating: Hotline Miami Wildlife
28-Aug-2016 13:24:35 - INFO :: Thread-36 : Uh-oh. I cannot find a Series Year for this series. I am going to try analyzing deeper.
28-Aug-2016 13:24:37 - INFO :: Thread-36 : Ok - I could not find a Series Year at all. Loading in the issue data now and will figure out the Series Year.
28-Aug-2016 13:24:39 - INFO :: Thread-36 : Sucessfully retrieved details for Hotline Miami Wildlife
28-Aug-2016 13:24:39 - ERROR :: Thread-36 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 333, in addComictoDB
    publisher = re.sub('!', '', comic['ComicPublisher']) # thanks Boom!
KeyError: 'ComicPublisher'

Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 333, in addComictoDB
    publisher = re.sub('!', '', comic['ComicPublisher']) # thanks Boom!
KeyError: 'ComicPublisher'
```

When this happens, entry in the import results screen gets stuck at "Importing" under status. This is a separate problem because I see many series that stay on "Importing" forever and that process never completes, with no indication of an error or outcome. 

When I click the select button under options, I see a single entry in Import Search Results for "Hotline Miami ...", and under publisher it shows unknown and year shows 0000. (This information is also missing from the [comic entry on ComicVine](http://comicvine.gamespot.com/hotline-miami-wildlife/4050-92086/)).

Clicking on "Add this comic" gives another error in the log and takes me back to the main import results page, where Status is still on "Importing" (which to me implies work is still being done and I should keep waiting for it to finish). Here's the log error though:

```
28-Aug-2016 13:34:14 - ERROR :: Thread-38 : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 89, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "C:\Users\jeremy\mylar\mylar\filechecker.py", line 1151, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "C:\Python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Traceback (most recent call last):
  File "C:\Users\jeremy\mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\jeremy\mylar\mylar\importer.py", line 89, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "C:\Users\jeremy\mylar\mylar\filechecker.py", line 1151, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "C:\Python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by evilhero** [comment]
Yes that's generally what happens when tracebacks occur that aren't handled - the process stops entirely. The importer successfully determined the series, tried to auto-add it and the add failed due to the invalid data retrieved from CV. It would fail on a normal add as well in this case (not just import). 

The comic publisher error is a problem with CV not putting in valid data (yet again), and under normal circumstances there would always be a publisher. I'll have to add in a check for publisher being nom-existant because up until this point it hasn't come up.
