### ISSUE TITLE
no search providers with newsnab & trackback issue.

### ISSUE THREAD

**Issue by merlosus** [evilhero/mylar#1376]
Hi I am getting 0 search providers error using newsnab providers and then this:
so far mylar has failed to find a single comic even though I have manually found titles on the websites.

Traceback (most recent call last):
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\logger.py", line 158, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 1642, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 824, in NZB_SEARCH
    issuedate_int = int(time.mktime(tm.timetuple()))
OverflowError: mktime argument out of range

**Comment by evilhero** [comment]
See my response to your duplicate post in #1155.

Once you get rid of the 0 providers error, if you're still getting the mktime error then please respond back with a debug log showing the lead up to said error.
