### ISSUE TITLE
Public Torrent Search

### ISSUE THREAD

**Issue by joshnat** [evilhero/mylar#1380]
I've got  git build 742e5d380b547305e4081c003aa0e3e4f08ed8ba with Python 2.7.12.  When I initiate a search I get: 

2016-09-08 17:30:13	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/Mylar/mylar/search.py", line 291, in search_init
if searchprov == '32P' and mylar.MODE_32P == 0:
UnboundLocalError: local variable 'searchprov' referenced before assignment
2016-09-08 17:30:13	INFO	search provider order is []
2016-09-08 17:30:13	INFO	Issue Title given as : the death and life of oliver queen part three: the ninth circle
2016-09-08 17:30:13	INFO	Initiating manual search for Green Arrow issue: 3

Any idea what's going wrong?  I've got RSS and TPSE checked.  Nothing's being found and no torrents are ending up in my watch folder.

**Comment by evilhero** [comment]
It's basically the 0 provider error that you get when you make a provider change of some kind (enable / disable)  and don't restart mylar after the config save. 

You'll need to shutdown mylar and edit the config.ini. Find the provider_order line and delete the entire provider_order line from the config.ini. Save it and start mylar up and you should be OK.

**Comment by joshnat** [comment]
Thanks for that!  I got a little further this time:

2016-09-08 18:07:49	ERROR	Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/Mylar/mylar/search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/Mylar/mylar/search.py", line 669, in NZB_SEARCH
for entry in bb['entries']:
TypeError: 'NoneType' object has no attribute '__getitem__'
2016-09-08 18:07:49	WARNING	Error fetching RSS Feed Data from TPSE: No module named js2py.pyjs
2016-09-08 18:07:44	INFO	Shhh be very quiet...I'm looking for Batman issue: 3 (2016) using TPSE
2016-09-08 18:07:44	INFO	allow_packs set to :False
2016-09-08 18:07:44	INFO	Could not find Issue 3 of Batman(2016) using TPSE [rss]
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	allow_packs:False
2016-09-08 18:07:44	INFO	rss:yes
2016-09-08 18:07:44	INFO	WWT
2016-09-08 18:07:44	INFO	Shhh be very quiet...I'm looking for Batman issue: 3 (2016) using TPSE [RSS]

It appears to be looking for js2py.pyjs but I'm not sure how to install via pip.

**Comment by evilhero** [comment]
I dont recognize that commit - as long as you're running the most recent development commit you won't have to install any libraries.  Can you confirm that you're up to date on the dev branch? 

You can install it via pip (if you want to, but you really shouldn't have to) by doing a 'pip install js2py'  (with mylar not running just to be safe). 
The js2py module is used by the cfscape module, which allows mylar to get by the cloudflare protection when it's enabled on WWT.

**Comment by joshnat** [comment]
I backed up my config.ini, mylar.db and cache folder and recloned from git.  Now it seems to be working.  On my Settings page it says git build 1481c4ac928af8833fe9595875e634db79d1857b and Master, but I did request the development branch when cloning.  

Anyway, it seems to be working without python errors now and comics are downloading.  Thank you so much for your super fast help and for your fantastic work!

**Comment by evilhero** [comment]
Well if it says master you're going to have some upgrade problems at some point (meaning you won't be able to grab the latest  dev).  What you can do, is after the downloadinh is finished, shutdown mylar and edit the config.ini and find the value for git_branch and set it to development.  That will force mylar to run on that branch. 

I still don't recognize that build (I can't find it on the git list), so I'm unsure as to where you are, but tpse was only added a little while ago, with the fixes for tpse + cloudflare happening shortly thereafter. 

If you have any further problems feel free to shout back, and glad I could help ;)

**Comment by joshnat** [comment]
OK I'm on development now but the build is the same.  It's not asking for updates.  Thanks again!
