### ISSUE TITLE
Error message references lazylibrarian?

### ISSUE THREAD

**Issue by sukhysall** [evilhero/mylar#1404]
Hi

So I just tried to add "Eden's Fall" after doing a search for it and happened to look at the debug enabled log file:

Saw the following and can't understand the reference in the last line to lazylibrarian:

Error log:

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1770, in searchIssueIDList
foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 252, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1530, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 2089, in searcher
filechecker.setperms(mylar.CACHE_DIR, True)
File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 1190, in setperms
chowner = getpwnam(mylar.CHOWNER)[2]
KeyError: 'getpwnam(): name not found: lazylibrarian'

**Comment by evilhero** [comment]
I think you set the owner in the owner /group options within mylar to be 'lazylibrarian'.  

Either that or the file it's trying to access has an owner permission set to 'lazylibrarian' .
