### ISSUE TITLE
500 error clicking on upcoming

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1406]
My mylar updated, and when I click on wanted I get 

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/brian/mylar/cherrypy/_cprequest.py", line 645, in respond
  File "/home/brian/mylar/cherrypy/lib/encoding.py", line 188, in __call__
  File "/home/brian/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/home/brian/mylar/mylar/webserve.py", line 1853, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'
Powered by CherryPy 3.2.0
'''
```

**Comment by evilhero** [comment]
See #1405
