### ISSUE TITLE
Error searching for StoryArc files?

### ISSUE THREAD

**Issue by darknessgp** [evilhero/mylar#1411]
I've got 32P and a Torznab setup... but whenever I go into a StoryArc and tell it to grab an issue. The issue is marked wanted but then never found... Noticed this in the logs. Searching for normal issues works fine however.

2016-10-12 16:55:31 ERROR   Uncaught exception: Traceback (most recent call last):
File "/software/mylar/mylar/logger.py", line 158, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 504, in run
self.__target(_self.__args, *_self.__kwargs)
File "/software/mylar/mylar/webserve.py", line 1288, in queueissue
foundcom, prov = search.search_init(ComicName=ComicName, IssueNumber=ComicIssue, ComicYear=ComicYear, SeriesYear=None, Publisher=None, IssueDate=IssueDate, StoreDate=StoreDate, IssueID=None, AlternateSearch=None, UseFuzzy=None, ComicVersion=None, SARC=SARC, IssueArcID=IssueArcID)
File "/software/mylar/mylar/search.py", line 252, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/software/mylar/mylar/search.py", line 532, in NZB_SEARCH
bb = a.searchit()
File "/software/mylar/mylar/auth32p.py", line 163, in searchit
spl = [x for x in self.publisher_list if x in publisher_search]
TypeError: argument of type 'NoneType' is not iterable
2016-10-12 16:55:31 INFO    [32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
2016-10-12 16:55:31 INFO    Shhh be very quiet...I'm looking for Civil War II issue: 1 (2016) using 32P
2016-10-12 16:55:31 INFO    allow_packs set to :False
2016-10-12 16:55:31 INFO    Finished searching via :rss. Issue not found - status kept as Wanted.
2016-10-12 16:55:31 INFO    Could not find Issue 1 of Civil War II(None) using Torznab [rss]
2016-10-12 16:55:31 INFO    Shhh be very quiet...I'm looking for Civil War II issue: 1 (2016) using Torznab [RSS]
2016-10-12 16:55:31 INFO    allow_packs set to :False
2016-10-12 16:55:31 INFO    Could not find Issue 1 of Civil War II(None) using 32P [rss]
2016-10-12 16:55:31 INFO    Shhh be very quiet...I'm looking for Civil War II issue: 1 (2016) using 32P [RSS]
2016-10-12 16:55:31 INFO    allow_packs set to :False
2016-10-12 16:55:31 INFO    search provider order is ['32p', 'torznab']
2016-10-12 16:55:31 INFO    Marking Civil War II 1 as wanted...
2016-10-12 16:55:31 INFO    IssueArcID : 58879_5875
2016-10-12 16:55:31 INFO    Story Arc : Civil War II queueing selected issue...

**Comment by evilhero** [comment]
Ugh yeah - that's because searching on 32P is different than other providers, and then adding in story arcs adds another level to the mix. When Mylar adds the issues of an arc, it doesn't pay attention to the publisher of said arc (from my recollection anyways), and on 32p there are quite a few series that are only differentiated by the publisher, and Mylar has to gather all titles that match against a query.

I think if I can populate the publisher when the arc gets refreshed/added, it should fix that particular problem with a lack of publisher in the arcs currently. Note that this should only apply to 32p due to how it searches, using torznab shouldn't cause any errors - although the results would be hit or miss, but that's just due to how things are named on various torrent sites (some are good at naming, others just make you shake your head)...

**Comment by darknessgp** [comment]
I can confirm that the error goes away when I disable 32P and only rely on torznab, It searches without throwing an error.
