### ISSUE TITLE
Error during Mass Import

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1427]
Hello,

Im getting an error while running Import on about 9000+ comics. It gets to the same comic and give me an error of  ERROR    [IMPORT] Unable to complete the scan: [Error 2] The system cannot find the file specified

any ideas?

**Comment by jimbojnr81** [comment]
2016-10-26 17:39:43	ERROR	[IMPORT] Unable to complete the scan: [Error 2] The system cannot find the file specified
2016-10-26 17:39:42	INFO	[IMPORT-CBZ} Attempting to read tags present in filename: D:\Comics 2\DC Comics\Batman (1940)\Batman 021 (1940).cbz
2016-10-26 17:39:42	INFO	[IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
2016-10-26 17:39:42	INFO	issueinfo: [{'publisher': u'DC Comics', 'letterer': u'George Roussos', 'title': 'None', 'webpage': u'http://comicvine.gamespot.com/batman-20-bruce-wayne-loses-the-guardianship-of-di/4000-109705/', 'series': u'Batman', 'notes': u'Scraped metadata from ComicVine [CVDB109705].', 'writer': u'Bill Finger', 'summary': u'Stories included:The Centuries Of CrimeThe Trial Of Titus KeyesThe Lawmen Of The SeaBruce Wayne Loses The Gardianship Of Dick Grayson', 'volume': u'1940', 'penciller': u'Bob Kane, Dick Sprang', 'issue_number': u'20', 'pagecount': u'60', 'colorist': 'None', 'year': u'1943', 'cover_artist': 'None', 'IssueImage': 'cache/temp.jpg?1477463982.77', 'month': u'12', 'inker': u'Dick Sprang, George Roussos, Jerry Robinson', 'day': 'None', 'editor': 'None'}]

**Comment by evilhero** [comment]
When you double-check on the indicated file for issue 021,does it open without any errors? Is there anything weird character wise in the metadata within if it does open ok?

**Comment by jimbojnr81** [comment]
Yeah, the file opens no problem. The meta data looks normal to me, no weird characters in it etc. Ill try taking that file out and running the import again and see how i go.

**Comment by jimbojnr81** [comment]
So far so good..

**Comment by jimbojnr81** [comment]
It now gets through all the comics but now Im getting this error.

[IMPORT] Unable to complete the scan: [Errno 13] Permission denied: u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache\\temp.zip'

**Comment by evilhero** [comment]
The use running mylar has to have complete permissions to it's own cache directory. 

When mylar extracts the metadata from the cbz file during an import, it copies the file to temp.zip in the cache in order to extract it, and analyze it. It has to do this for each cbz with metadata that exist in the import directory.

**Comment by jimbojnr81** [comment]
I had a feeling  that was the issue. Im running mylar on windows 10. Any ideas how to fix the permissions? Ive got the directory chmod set at 0777 and file chmod at 0660 but that could be wrong.

**Comment by evilhero** [comment]
I'm not 100% sure if mylar even attempts to do file permission changes on windows machines. You would want file chmod to be at least 0770 (meaning full for owner and group, no access for everyone else - typically 0775 would be good).

You can check the perms in windows by just right-clicking over the temp.zip file using file explorer and viewing the properties.

**Comment by jimbojnr81** [comment]
Changing the permission in windows seems to have worked but I'm now getting a traceback error

2016-10-28 11:00:30	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Users\Jimmy\Documents\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Jimmy\Documents\Mylar\mylar\librarysync.py", line 632, in scanLibrary
"ComicLocation": helpres.conversion(ghi['comlocation']),
NameError: global name 'helpres' is not defined
2016-10-28 11:00:30	INFO	[IMPORT-BREAKDOWN] Failure Files: []
2016-10-28 11:00:30	INFO	[IMPORT-BREAKDOWN] Files that were unable to be parsed: 0
2016-10-28 11:00:30	INFO	[IMPORT-BREAKDOWN] Files that had to be parsed: 27
2016-10-28 11:00:30	INFO	[IMPORT-BREAKDOWN] Files with ComicIDs successfully extracted: 6
2016-10-28 11:00:30	INFO	[IMPORT] Attempting to import 33 files into your watchlist.
2016-10-28 11:00:30	INFO	[IMPORT] Parsing/Reading of files completed!

**Comment by jimbojnr81** [comment]
weird thing is, folders with only 1 or 2 series seem to work fine, anything more than that and the above error shows up.

**Comment by jimbojnr81** [comment]
oh, no, now its giving me the traceback error every time.

**Comment by evilhero** [comment]
That's a typo in the code that never got tracked until now for some reason. It should be 'helpers.conversion' not 'helpres.conversion'. Stupid typos. It should pop up with the error if you're importing cbz files, cbr shouldn't hit that error. 

I'll fix it when I can get to a machine later tonight :/
