### ISSUE TITLE
Error post processing comics

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1438]
I'm getting this error on post processing

```
2016-11-02 11:45:51	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 526, in Process
if int(watch_issueyear) == int(watchmatch['issue_year']):
TypeError: int() argument must be a string or a number, not 'NoneType'
2016-11-02 11:45:51	INFO	[POST-PROCESSING][ISSUE-VERIFY] Found matching issue # 10000 for ComicID: 91273 / IssueID: 556441
2016-11-02 11:45:51	INFO	Series_Name: Batman --- WatchComic: Batman
2016-11-02 11:45:51	INFO	I have located 4 files that I should be able to post-process. Continuing...
2016-11-02 11:45:51	INFO	[FILENAME]: Justice League 008 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz
2016-11-02 11:45:51	INFO	[FILENAME]: Green Lanterns 010 (2016) (2 covers) (digital) (Minutemen-Thoth).cbz
2016-11-02 11:45:51	INFO	[FILENAME]: Superman 010 (2016) (Webrip) (The Last Kryptonian-DCP).cbr
2016-11-02 11:45:51	INFO	[FILENAME]: Batman 010 (2017) (2 covers) (digital) (Minutemen-Faessla).cbz
```

Seems that 'issue_year' field is coming with "NoneType" string value instead of a int value.

**Comment by evilhero** [comment]
Does the Batman series page show the correct pub date for the given  issue you're trying to post-process,  or even if that issue is listed on the series detail page?

**Comment by WedgeSparda** [comment]
I'm not sure is the pub date is correct, here's a screenshot:
![batman](https://cloud.githubusercontent.com/assets/48375/19927136/b2b25622-a0f8-11e6-9767-d7387f7a76b2.png)

I clicked on "Refresh Comic" button but nothing changed after the refresh.

**Comment by evilhero** [comment]
Yep that's correct - you can check store dare /pub dates as mylar has them by going to the Manage tab / Manage Issues and then changing the dropdown status to Snatched. Sort the pub date from newest to oldest and you can then see the store date for the given issue (mylar uses store date for comparisons if it's available, but displays pub date for everything due to it being used as the 'norm' for decades)

**Comment by WedgeSparda** [comment]
Here. It seems is ok, right?

![batman2](https://cloud.githubusercontent.com/assets/48375/19927372/be4a2194-a0f9-11e6-86d7-85f785eee4fe.png)

**Comment by evilhero** [comment]
Yup exactly as mine. 

OK give me abit and I'll hook into mylar and try to run through the process on my end since I should be able to duplicate the error given that the issue data is correct.

**Comment by adamiltone** [comment]
I had the same error only with Batman this week

**Comment by evilhero** [comment]
Figured it out - was actually due to the filechecker not parsing the '2017' from the filename properly as it assumed it was in the future (rightly so, but it should ignore dates like that when it's nearer to the end of the given year). 

Fix up shortly along with a whack of others ;)
