### ISSUE TITLE
New error when selecting "Grab it" on Story Arc issue

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1458]
Hi

Now, when selecting "Grab it" on an issue on the Story Arc management I get this error.

```
2016-11-14 11:10:06	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1296, in queueissue
logger.fdebug('publisher: ' + Publisher)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2016-11-14 11:10:06	INFO	Marking Prowler #1 as wanted...
2016-11-14 11:10:06	INFO	IssueArcID : None
2016-11-14 11:10:06	INFO	Story Arc : The Clone Conspiracy queueing selected issue...
2016-11-14 11:10:06	DEBUG	mode:readlist
2016-11-14 11:10:06	DEBUG	ComicID:None
```

Is a slightly different error form the last time.

**Comment by evilhero** [comment]
Try refreshing the arc - the publisher field wasn't initially populated within mylar, so you need to refresh the arc in order for it to grab the information now. 

If that doesn't work, I'll have to look into it more so again...as it was working for me after doing an arc refresh.

**Comment by WedgeSparda** [comment]
It worked. Thanks :)
