### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by warrenonline** [evilhero/mylar#1465]
Just installed Mylar and I'm getting the following error when I hit the "This Week" button. This is on my Linux server and I was able to do this prior to moving to the dev branch. 

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/warren/mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/warren/mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/warren/mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/warren/mylar/mylar/webserve.py", line 1568, in pullist
    repoll = self.manualpull(weeknumber=weeknumber,year=year)
  File "/home/warren/mylar/mylar/webserve.py", line 1791, in manualpull
    weeklypull.pullit()
  File "/home/warren/mylar/mylar/weeklypull.py", line 83, in pullit
    urllib.urlretrieve(PULLURL, newrl)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 673, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 642, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 669, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by evilhero** [comment]
Ahh crap - they forced it from http to https, so now it's trying to verify the certificate but it's not using the proper library.

I'll have to get a fix out but can't atm (on the phone) - I would shut off Mylar, edit the config.ini and set the alt_pull to 2. Save the config, start up Mylar and you should be actually better off than it was previously (the  2 method uses an improved method for polling, less api hits, more accurate matching and everything is properly formatted to boot)

**Comment by warrenonline** [comment]
Done and fixed. Thanks for your time !
