### ISSUE TITLE
"This Week" Button results in 500 internal server error

### ISSUE THREAD

**Issue by GTSlayer** [evilhero/mylar#1467]
Running on ubuntu 16.04, latest development branch. 

Starting today, 11/20/16, if I hit the "This Week" button, I get a 500 internal server error. I assume its trying to create a pulllist and failing.

> Traceback (most recent call last):
  File "/opt/Mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/Mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 1568, in pullist
    repoll = self.manualpull(weeknumber=weeknumber,year=year)
  File "/opt/Mylar/mylar/webserve.py", line 1791, in manualpull
    weeklypull.pullit()
  File "/opt/Mylar/mylar/weeklypull.py", line 83, in pullit
    urllib.urlretrieve(PULLURL, newrl)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 673, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 642, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 669, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by evilhero** [comment]
Yep see #1465.. They changed the url to https and now mylar can't handle the request because that part of code wasn't updated.  

I have a fix going into dev, but setting alt_pull = 2 in the config.ini will fix + improve things in general.
