### ISSUE TITLE
Error on This Week Tab

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1468]
Hello, I'm getting the following error when navigating to the "This Week" tab.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 645, in respond
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
  File "C:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
  File "C:\Mylar\mylar\webserve.py", line 1568, in pullist
    repoll = self.manualpull(weeknumber=weeknumber,year=year)
  File "C:\Mylar\mylar\webserve.py", line 1791, in manualpull
    weeklypull.pullit()
  File "C:\Mylar\mylar\weeklypull.py", line 83, in pullit
    urllib.urlretrieve(PULLURL, newrl)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 671, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "C:\Python27\lib\urllib.py", line 641, in http_error_302
    data)
  File "C:\Python27\lib\urllib.py", line 667, in redirect_internal
    return self.open(newurl)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by evilhero** [comment]
Set your alt_pull =2 in the config.ini with mylar shutdown. Same as #1465 - fix will be in next dev commit.

**Comment by wraith1385** [comment]
Thanks, sorry I missed the other thread.

**Comment by Warborg71** [comment]
I'm getting the same error, I've tried changing the alt_pull as you stated above, but when I restart Mylar it automatically changes it back to alt_pull=1.  Seems like I am dead in the water as far as Mylar goes at the moment.  Any other suggestions?  I'm running it as a service on a Windows Home Server 2011.

**Comment by Warborg71** [comment]
Ok, well I couldn't make changes to the .ini file or it'd just change it back once I started the service up...  And every time I tried git pull from an elevated prompt it would say I was up to date, so I did what you mentioned in another thread and backed up the essentials and did a new git clone and restored the backed up files and seems to be good to go now.  So I guess my issue is now a non-issue.

**Comment by evilhero** [comment]
Yeah, you can't make changes to the .ini when Mylar is running as it writes to the .ini during a bootup/shutdown, so the moment you issue a restart (if you manually changed the .ini) it would blow away any changes with whatever is in the current configuration running.

**Comment by Warborg71** [comment]
See, that's the strange thing tho, I DID stop the service and make sure no other process to it was running (at least, that I could see), but as soon as I started the service back up it overwrote my changes.

**Comment by evilhero** [comment]
Are you using a config.ini that's specified on the command line when you issue the startup for mylar? Only thing I can think of is that there's another config it's pulling from for some reason. Mylar doesn't lock files unless they're in use (and even then it's not locked, just in use)

**Comment by Warborg71** [comment]
As far as I can tell that was the only one...  Just glad I got it up and running with the git clone, I gots to have my comics...  ;)
