### ISSUE TITLE
error fetching data from newzab

### ISSUE THREAD

**Issue by slavko07** [evilhero/mylar#1471]
I am a new user and tried using DogNZB for ~10days on a free trial with Mylar, SABnzdb. Everything worked. Now that my dog trial expired, I paid for NZBgeek and updated my search provider config. I now received the following error, need some help. I made sure I added a new Comic series (X Men 2013) after I removed dog and added nzbgeek.

Error fetching data from newznab: No connection adapters were found for ' https://api.nzbgeek.info/api?t=search&q=x-men%20025&o=xml&cat=7030&apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&maxage=5000

The newznab settings seem pretty straight forward, but just in case I added a screenshot below.

![image](https://cloud.githubusercontent.com/assets/23420200/20631595/7c4d014e-b305-11e6-8323-c65d0e355acb.png).

I hope you can help me out.

**Comment by slavko07** [comment]
I just tried a manual search on one of the issues, here is what the log looks like....

2016-11-25 11:59:37	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\mylar\mylar\webserve.py", line 1378, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "C:\mylar\mylar\search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "C:\mylar\mylar\search.py", line 642, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-11-25 11:59:37	WARNING	Error fetching data from newznab: No connection adapters were found for ' https://api.nzbgeek.info/api?t=search&q=x-men%20025&o=xml&cat=7030&apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&maxage=5000'
2016-11-25 11:58:37	INFO	pausing for 60 seconds before continuing to avoid hammering
2016-11-25 11:58:37	INFO	Shhh be very quiet...I'm looking for X-Men issue: 25 (2015) using NZBgeek (newznab)
2016-11-25 11:58:37	INFO	allow_packs set to :False
2016-11-25 11:58:37	INFO	Could not find Issue 25 of X-Men(2013) using NZBgeek [rss]
2016-11-25 11:58:37	INFO	Shhh be very quiet...I'm looking for X-Men issue: 25 (2015) using NZBgeek(newznab) [RSS]
2016-11-25 11:58:37	INFO	allow_packs set to :False
2016-11-25 11:58:37	INFO	search provider order is ['newznab:NZBgeek']
2016-11-25 11:58:37	INFO	Issue Title given as : the burning world part 3
2016-11-25 11:58:37	INFO	Initiating manual search for X-Men issue: 25

**Comment by evilhero** [comment]
You have a space at the beginning of your newznab host entry for nzbgeek. Remove the space, save the configuration and restart mylar and you'll be good to go ;)

**Comment by castertr0y357** [comment]
I'm hitting the same uncaught exception.  I see a few messages about SSL verification giving an issue in the debug logs though.

I think this started after the most recent version update as I haven't had any new issues grabbed for the past 2 weeks.

2016-11-30 01:11:37	ERROR	Uncaught exception: Traceback (most recent call last):
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 1378, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 642, in NZB_SEARCH
if str(r.status_code) != '200':
UnboundLocalError: local variable 'r' referenced before assignment
2016-11-30 01:11:37	WARNING	Error fetching data from newznab: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-11-30 01:11:36	DEBUG	[SSL: True] Search URL: https://www.usenet-crawler.com/api?t=search&q=star%20wars%20001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2016-11-30 01:11:36	INFO	pausing for 0 seconds before continuing to avoid hammering
2016-11-30 01:11:36	DEBUG	calpha/cnumber: None / None
2016-11-30 01:11:36	INFO	Shhh be very quiet...I'm looking for Star Wars issue: 1 (2016) using Usenet-Crawler (newznab)

I checked my newznab host entry for the provider shown in the logs and it doesn't have a space in front of the name.  I have tried turning SSL verify for the provider off and on, but it hasn't made a difference in the outcome, and the debug logs show the same thing.

Snap of my setting (with SSL verify turned off) is included below.  Any insight would be welcome.

![image](https://cloud.githubusercontent.com/assets/4755578/20756556/f75a36f2-b6c7-11e6-8d32-1dfc25cc8733.png)

**Comment by evilhero** [comment]
Different error than OP.  OP had connection issues, @castertr0y357 yours is related to ssl connectivity due to availability. 

Usenet-crawler has their api disabled due to some maintenance issues - I would suggest you keep an eye on their forum for updates as to when it will be enabled again (they mentioned it on their forums a few days ago)

**Comment by castertr0y357** [comment]
Ah, thanks.

I disabled usenet-crawler in mylar and left in my other search provider.  I was able to manually grab a comic.  I'll keep an eye on when usenet-crawler will be re-enabling their API.

Much appreciated!
