### ISSUE TITLE
Finding new issues but not downloading

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1484]
Today Mylar wasn't able to download any new release despite they were already released, for example on 32P.

Check this log for a specific example:

```
2016-12-14 17:21:50	INFO	Could not find Issue 946 of Detective Comics(2016) using 32P [api]
2016-12-14 17:21:50	ERROR	Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2016-12-14 17:21:50	ERROR	Query failed with result "invalid or corrupt torrent file".
2016-12-14 17:21:49	INFO	matched on Detective Comics
2016-12-14 17:21:49	INFO	Found Detective Comics (2017) issue: 946 using 32P
2016-12-14 17:21:49	INFO	allow_packs:False
2016-12-14 17:21:49	INFO	rss:no
2016-12-14 17:21:49	INFO	32P
2016-12-14 17:21:49	INFO	successfully retrieved 2 search results.
2016-12-14 17:21:49	INFO	{u'status': u'success', u'count': 2, u'details': [{u'seeders': u'33', u'scanner': u'The Last Kryptonian-DCP', u'language': u'English', u'format': u'cbr', u'upload_time': u'1481701580', u'volume': u'3', u'leechers': u'0', u'pack': u'0', u'id': u'45523', u'issues': u'946', u'size': u'34812241'}, {u'seeders': u'18', u'scanner': u'TLK-EMPIRE-HD', u'language': u'English', u'format': u'cbr', u'upload_time': u'1481730343', u'volume': u'3', u'leechers': u'2', u'pack': u'0', u'id': u'45558', u'issues': u'946', u'size': u'34721693'}]}
2016-12-14 17:21:47	INFO	payload: {'action': 'groupsearch', 'issue': u'946', 'id': u'47'}
2016-12-14 17:21:47	INFO	1 series match the title being search for
2016-12-14 17:21:47	INFO	Exact series ID already discovered previously. Setting to :Detective Comics[47]
2016-12-14 17:21:47	INFO	publisher search set to : DC
2016-12-14 17:21:47	INFO	[32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
2016-12-14 17:21:47	INFO	Shhh be very quiet...I'm looking for Detective Comics issue: 946 (2017) using 32P
```

With another issue I'm getting this result on the log

```
2016-12-14 17:27:06	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1700, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 540, in NZB_SEARCH
bb = a.searchit()
File "/volume1/@appstore/mylar/share/mylar/mylar/auth32p.py", line 288, in searchit
helpers.checkthe_id(comic_id, dataset)
UnboundLocalError: local variable 'dataset' referenced before assignment
2016-12-14 17:27:05	INFO	2 series listed for searching that match.
2016-12-14 17:27:05	INFO	searchresult: RedHoodOutlawsRebirth --- RedHoodOutlaws[DC]
2016-12-14 17:27:05	INFO	searchresult: RedHoodOutlawsFuturesEnd --- RedHoodOutlaws[DC]
2016-12-14 17:27:05	INFO	[MATCH] Red Hood and the Outlaws [3152]
2016-12-14 17:27:05	INFO	searchresult: RedHoodOutlaws --- RedHoodOutlaws[DC]
2016-12-14 17:27:05	INFO	[MATCH] Red Hood & the Outlaws [18879]
2016-12-14 17:27:05	INFO	searchresult: RedHoodOutlaws --- RedHoodOutlaws[DC]
2016-12-14 17:27:05	INFO	series_search: Red Hood & the Outlaws
2016-12-14 17:27:05	INFO	publisher search set to : DC
2016-12-14 17:27:05	INFO	[32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
2016-12-14 17:27:03	INFO	Shhh be very quiet...I'm looking for Red Hood & the Outlaws issue: 5 (2016) using 32P
```
I'm just using Torrents, not NZB.

Any clue about what's happening?

**Comment by evilhero** [comment]
For the first error, try restarting Mylar and try it again but with verbose mode enabled (-v on startup, or enable it in the Logs tab in the GUI).

As far as the 2nd error, I think it's because it trying to cache the results but because there's more than one match it's not sure which is the right one and which is the wrong one. I'll have to look into this one more as I haven't had it pop up as of yet myself.

**Comment by WedgeSparda** [comment]
Here is the debug log for the first error

```
2016-12-14 17:58:44	DEBUG	Could not find issue doing a manual search via : api
2016-12-14 17:58:44	INFO	Could not find Issue 946 of Detective Comics(2016) using 32P [api]
2016-12-14 17:58:44	ERROR	Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2016-12-14 17:58:44	ERROR	Query failed with result "invalid or corrupt torrent file".
2016-12-14 17:58:44	DEBUG	[32P] Saved torrent file to : /usr/local/mylar/share/mylar/cache/Detective_Comics_946_2017.torrent
2016-12-14 17:58:44	DEBUG	[32P-AUTHENTICATION] 32P (Auth Mode) Authentication already done. Attempting to use existing keys.
2016-12-14 17:58:44	DEBUG	[32P] Verify SSL set to : True
2016-12-14 17:58:44	DEBUG	filename for torrent set to : /usr/local/mylar/share/mylar/cache/Detective_Comics_946_2017.torrent
2016-12-14 17:58:44	INFO	matched on Detective Comics
2016-12-14 17:58:44	DEBUG	Torrent Provider:32P
2016-12-14 17:58:44	DEBUG	link:45523
2016-12-14 17:58:44	DEBUG	ComicName:Detective Comics
2016-12-14 17:58:44	DEBUG	link given by: 32P
2016-12-14 17:58:44	INFO	Found Detective Comics (2017) issue: 946 using 32P
2016-12-14 17:58:44	DEBUG	issues match!
2016-12-14 17:58:44	DEBUG	nzbname used for post-processing:Detective.Comics.v3.#946
2016-12-14 17:58:44	DEBUG	integer value of issue we have found : 946000
2016-12-14 17:58:44	DEBUG	issue we found for is : 946
2016-12-14 17:58:44	DEBUG	integer value of issue we are looking for : 946000
2016-12-14 17:58:44	DEBUG	issue we are looking for is : 946
2016-12-14 17:58:44	DEBUG	this should be a match!
2016-12-14 17:58:44	DEBUG	it's a go captain... - we matched 100.0%!
2016-12-14 17:58:43	DEBUG	Match to series : 100.0 %.
2016-12-14 17:58:43	DEBUG	splitit-len:2
2016-12-14 17:58:43	DEBUG	scount:2
2016-12-14 17:58:43	DEBUG	word matched on : comics
2016-12-14 17:58:43	DEBUG	1 Comparing: comics .to. comics
2016-12-14 17:58:43	DEBUG	scount : 1
2016-12-14 17:58:43	DEBUG	splitit: comics
2016-12-14 17:58:43	DEBUG	word matched on : detective
2016-12-14 17:58:43	DEBUG	0 Comparing: detective .to. detective
2016-12-14 17:58:43	DEBUG	scount : 0
2016-12-14 17:58:43	DEBUG	splitit: detective
2016-12-14 17:58:43	DEBUG	Watchlist-length: 2
2016-12-14 17:58:43	DEBUG	search-length: 2
2016-12-14 17:58:43	DEBUG	length match..proceeding
2016-12-14 17:58:43	DEBUG	len-watchcomic : 2
2016-12-14 17:58:43	DEBUG	splitst : 2
2016-12-14 17:58:43	DEBUG	['detective', 'comics'] watchlist word count: 2
2016-12-14 17:58:43	DEBUG	['detective', 'comics', '946'] nzb series word count: 2
2016-12-14 17:58:43	DEBUG	adjusting from: detective comics 946 to: 946
2016-12-14 17:58:43	DEBUG	adjusted nzb comic and issue: detective comics 946
2016-12-14 17:58:43	DEBUG	original nzb comic and issue: detective comics 946
2016-12-14 17:58:43	INFO	allow_packs:False
2016-12-14 17:58:43	INFO	rss:no
2016-12-14 17:58:43	INFO	32P
2016-12-14 17:58:43	DEBUG	We matched on versions...v3
2016-12-14 17:58:43	DEBUG	SCVersion: 2016
2016-12-14 17:58:43	DEBUG	DCVersion: 3
2016-12-14 17:58:43	DEBUG	FCVersion: 3
2016-12-14 17:58:43	DEBUG	vers4vol: v3
2016-12-14 17:58:43	DEBUG	vers4year: no
2016-12-14 17:58:43	DEBUG	version found: v3
2016-12-14 17:58:43	DEBUG	watch comicversion is v3
2016-12-14 17:58:43	DEBUG	volume detection commencing - adjusting length.
2016-12-14 17:58:43	DEBUG	Year not given properly formatted but Version detected.Bypassing Year Match.
2016-12-14 17:58:43	DEBUG	ComVersChk : 3
2016-12-14 17:58:43	DEBUG	UseFuzzy is : None
2016-12-14 17:58:43	DEBUG	Comic: detective comics 946
2016-12-14 17:58:43	DEBUG	0. Bracket Word: detective comics 946
2016-12-14 17:58:43	DEBUG	Cleantitle: detective comics 946
2016-12-14 17:58:43	DEBUG	Newly finished reformed cleantitle (with NO volume label): detective comics 946
2016-12-14 17:58:43	DEBUG	[Vx] Version detected as v3
2016-12-14 17:58:43	DEBUG	Cleantitle: detective comics v3 946
2016-12-14 17:58:43	DEBUG	Entry: Detective Comics v3 #946
2016-12-14 17:58:43	DEBUG	Wed Dec 14 08:46:20 2016 is after store date of 2016-12-14
2016-12-14 17:58:43	DEBUG	size given as: 33.2 MB
2016-12-14 17:58:43	DEBUG	sub:Detective Comics v3 #946
2016-12-14 17:58:43	DEBUG	checking search result: Detective Comics v3 #946
2016-12-14 17:58:43	DEBUG	32P direct match to issue # : 946
2016-12-14 17:58:43	INFO	successfully retrieved 2 search results.
2016-12-14 17:58:43	INFO	{u'status': u'success', u'count': 2, u'details': [{u'seeders': u'30', u'scanner': u'The Last Kryptonian-DCP', u'language': u'English', u'format': u'cbr', u'upload_time': u'1481701580', u'volume': u'3', u'leechers': u'3', u'pack': u'0', u'id': u'45523', u'issues': u'946', u'size': u'34812241'}, {u'seeders': u'19', u'scanner': u'TLK-EMPIRE-HD', u'language': u'English', u'format': u'cbr', u'upload_time': u'1481730343', u'volume': u'3', u'leechers': u'1', u'pack': u'0', u'id': u'45558', u'issues': u'946', u'size': u'34721693'}]}
2016-12-14 17:58:42	INFO	payload: {'action': 'groupsearch', 'issue': u'946', 'id': u'47'}
2016-12-14 17:58:42	INFO	1 series match the title being search for
2016-12-14 17:58:42	INFO	Exact series ID already discovered previously. Setting to :Detective Comics[47]
2016-12-14 17:58:42	INFO	publisher search set to : DC
2016-12-14 17:58:42	INFO	[32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
2016-12-14 17:58:42	DEBUG	[32P-AUTHENTICATION] Session key-based login was good.
2016-12-14 17:58:41	DEBUG	[32P-AUTHENTICATION] Session cookie found. Attempting to load...
2016-12-14 17:58:41	DEBUG	calpha/cnumber: None / None
2016-12-14 17:58:41	INFO	Shhh be very quiet...I'm looking for Detective Comics issue: 946 (2017) using 32P
2016-12-14 17:58:41	INFO	allow_packs set to :False
2016-12-14 17:58:41	INFO	Could not find Issue 946 of Detective Comics(2016) using TPSE [api]
2016-12-14 17:58:41	INFO	[TPSE] there were 0 results..
2016-12-14 17:58:34	DEBUG	Sending request to [TPSE] for detective comics : 946
2016-12-14 17:58:34	DEBUG	calpha/cnumber: None / None
2016-12-14 17:58:34	INFO	Shhh be very quiet...I'm looking for Detective Comics issue: 946 (2017) using TPSE
2016-12-14 17:58:34	INFO	allow_packs set to :False
2016-12-14 17:58:34	DEBUG	Initiating Search via : api
2016-12-14 17:58:34	DEBUG	Could not find issue doing a manual search via : rss
2016-12-14 17:58:34	INFO	Could not find Issue 946 of Detective Comics(2016) using 32P [rss]
2016-12-14 17:58:34	ERROR	Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2016-12-14 17:58:34	ERROR	Query failed with result "invalid or corrupt torrent file".
2016-12-14 17:58:34	DEBUG	[32P] Saved torrent file to : /usr/local/mylar/share/mylar/cache/Detective_Comics_946_2017.torrent
2016-12-14 17:58:33	DEBUG	[32P-AUTHENTICATION] 32P (Auth Mode) Authentication already done. Attempting to use existing keys.
2016-12-14 17:58:33	DEBUG	[32P] Verify SSL set to : True
2016-12-14 17:58:33	DEBUG	filename for torrent set to : /usr/local/mylar/share/mylar/cache/Detective_Comics_946_2017.torrent
2016-12-14 17:58:33	INFO	matched on Detective Comics
2016-12-14 17:58:33	DEBUG	Torrent Provider:32P
2016-12-14 17:58:33	DEBUG	link:45523
2016-12-14 17:58:33	DEBUG	filename for torrent set to : /usr/local/mylar/share/mylar/cache/Detective_Comics_946_2017.torrent
2016-12-14 17:58:33	INFO	matched on Detective Comics
2016-12-14 17:58:33	DEBUG	Torrent Provider:32P
2016-12-14 17:58:33	DEBUG	link:45523
2016-12-14 17:58:33	DEBUG	ComicName:Detective Comics
2016-12-14 17:58:33	DEBUG	link given by: 32P
2016-12-14 17:58:33	INFO	Found Detective Comics (2017) issue: 946 using 32P [RSS]
2016-12-14 17:58:33	DEBUG	issues match!
2016-12-14 17:58:33	DEBUG	nzbname used for post-processing:Detective.Comics.vol3.#946.(The.Last.Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	integer value of issue we have found : 946000
2016-12-14 17:58:33	DEBUG	issue we found for is : 946
2016-12-14 17:58:33	DEBUG	integer value of issue we are looking for : 946000
2016-12-14 17:58:33	DEBUG	issue we are looking for is : 946
2016-12-14 17:58:33	DEBUG	this should be a match!
2016-12-14 17:58:33	DEBUG	it's a go captain... - we matched 100.0%!
2016-12-14 17:58:33	DEBUG	Match to series : 100.0 %.
2016-12-14 17:58:33	DEBUG	splitit-len:2
2016-12-14 17:58:33	DEBUG	scount:2
2016-12-14 17:58:33	DEBUG	word matched on : comics
2016-12-14 17:58:33	DEBUG	1 Comparing: comics .to. comics
2016-12-14 17:58:33	DEBUG	scount : 1
2016-12-14 17:58:33	DEBUG	splitit: comics
2016-12-14 17:58:33	DEBUG	word matched on : detective
2016-12-14 17:58:33	DEBUG	0 Comparing: detective .to. detective
2016-12-14 17:58:33	DEBUG	scount : 0
2016-12-14 17:58:33	DEBUG	splitit: detective
2016-12-14 17:58:33	DEBUG	Watchlist-length: 2
2016-12-14 17:58:33	DEBUG	search-length: 2
2016-12-14 17:58:33	DEBUG	length match..proceeding
2016-12-14 17:58:33	DEBUG	len-watchcomic : 2
2016-12-14 17:58:33	DEBUG	splitst : 2
2016-12-14 17:58:33	DEBUG	['detective', 'comics'] watchlist word count: 2
2016-12-14 17:58:33	DEBUG	['detective', 'comics', '946'] nzb series word count: 2
2016-12-14 17:58:33	DEBUG	adjusting from: detective comics 946 to: 946
2016-12-14 17:58:33	DEBUG	adjusted nzb comic and issue: detective comics 946
2016-12-14 17:58:33	DEBUG	original nzb comic and issue: detective comics 946
2016-12-14 17:58:33	INFO	allow_packs:False
2016-12-14 17:58:33	INFO	rss:yes
2016-12-14 17:58:33	INFO	32P
2016-12-14 17:58:33	DEBUG	We matched on versions...3
2016-12-14 17:58:33	DEBUG	SCVersion: 2016
2016-12-14 17:58:33	DEBUG	DCVersion: 3
2016-12-14 17:58:33	DEBUG	FCVersion: 3
2016-12-14 17:58:33	DEBUG	vers4vol: 3
2016-12-14 17:58:33	DEBUG	vers4year: no
2016-12-14 17:58:33	DEBUG	version found: 3
2016-12-14 17:58:33	DEBUG	watch comicversion is v3
2016-12-14 17:58:33	DEBUG	volume detection commencing - adjusting length.
2016-12-14 17:58:33	DEBUG	Year not given properly formatted but Version detected.Bypassing Year Match.
2016-12-14 17:58:33	DEBUG	ComVersChk : 3
2016-12-14 17:58:33	DEBUG	UseFuzzy is : None
2016-12-14 17:58:33	DEBUG	Comic: detective comics 946
2016-12-14 17:58:33	DEBUG	0. Bracket Word: detective comics 946
2016-12-14 17:58:33	DEBUG	blank brackets removed: detective comics 946
2016-12-14 17:58:33	DEBUG	pubremoved : detective comics 946 ()
2016-12-14 17:58:33	DEBUG	removing publisher from title
2016-12-14 17:58:33	DEBUG	cnt is : 1 --- Publisher is: DC Comics
2016-12-14 17:58:33	DEBUG	Publisher detected within title : the last kryptonian-dcp
2016-12-14 17:58:33	DEBUG	1. Bracket Word: the last kryptonian-dcp
2016-12-14 17:58:33	DEBUG	Year not given properly formatted but Version detected.Bypassing Year Match.
2016-12-14 17:58:33	DEBUG	ComVersChk : 3
2016-12-14 17:58:33	DEBUG	UseFuzzy is : None
2016-12-14 17:58:33	DEBUG	Comic: detective comics 946
2016-12-14 17:58:33	DEBUG	0. Bracket Word: detective comics 946
2016-12-14 17:58:33	DEBUG	Cleantitle: detective comics 946 (the last kryptonian-dcp)
2016-12-14 17:58:33	DEBUG	Newly finished reformed cleantitle (with NO volume label): detective comics 946 (the last kryptonian-dcp)
2016-12-14 17:58:33	DEBUG	volume detected - stripping and re-analzying for volume label.
2016-12-14 17:58:33	DEBUG	Cleantitle: detective comics vol3 946 (the last kryptonian-dcp)
2016-12-14 17:58:33	DEBUG	Entry: Detective Comics vol3 #946 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	Wed, 14 Dec 2016 07:46:20 +0000 is after store date of 2016-12-14
2016-12-14 17:58:33	DEBUG	size given as: 33.2 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #946 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #946 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	Fri, 25 Nov 2016 09:56:45 +0000 is before store date of 2016-12-14. Ignoring search result as this is not the right issue.
2016-12-14 17:58:33	DEBUG	size given as: 31.2 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #945 (Minutemen-Drunk Monk)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #945 (Minutemen-Drunk Monk)
2016-12-14 17:58:33	DEBUG	Fri, 25 Nov 2016 09:28:47 +0000 is before store date of 2016-12-14. Ignoring search result as this is not the right issue.
2016-12-14 17:58:33	DEBUG	size given as: 31.3 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #945 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #945 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	Wed, 09 Nov 2016 23:45:42 +0000 is before store date of 2016-12-14. Ignoring search result as this is not the right issue.
2016-12-14 17:58:33	DEBUG	size given as: 37.1 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #944 (Minutemen-Drunk Monk)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #944 (Minutemen-Drunk Monk)
2016-12-14 17:58:33	DEBUG	Wed, 09 Nov 2016 14:48:32 +0000 is before store date of 2016-12-14. Ignoring search result as this is not the right issue.
2016-12-14 17:58:33	DEBUG	size given as: 37.1 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #944 (TLK-EMPIRE-HD)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #944 (TLK-EMPIRE-HD)
2016-12-14 17:58:33	DEBUG	Wed, 09 Nov 2016 08:01:02 +0000 is before store date of 2016-12-14. Ignoring search result as this is not the right issue.
2016-12-14 17:58:33	DEBUG	size given as: 37.2 MB
2016-12-14 17:58:33	DEBUG	sub:Detective Comics vol3 #944 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	checking search result: Detective Comics vol3 #944 (The Last Kryptonian-DCP)
2016-12-14 17:58:33	DEBUG	titleend: vol3 946 (tlk empire hd)
2016-12-14 17:58:33	DEBUG	matched on series title: Detective Comics
2016-12-14 17:58:33	DEBUG	matched to : Detective Comics vol3 #946 (TLK-EMPIRE-HD)
2016-12-14 17:58:33	DEBUG	16 - formatrem_seriesname :detective comics
2016-12-14 17:58:33	DEBUG	41 - formatrem_torsplit : detective comics vol3 946 (tlk empire hd)
2016-12-14 17:58:33	DEBUG	tor-Title: Detective Comics vol3 #946 (TLK-EMPIRE-HD)
2016-12-14 17:58:33	DEBUG	titleend: vol3 946 ( last kryptonian dcp)
```

**Comment by evilhero** [comment]
Are you on master / dev and up-to-date? There was an update yesterday that fixed a problem with rss grabs when you have 32p + TPSE enabled (if the id number existed on TPSE and 32P was being searched, it would wrongly grab from TPSE).

32P changed their cert key a few days ago as well, you might have to blow away your existing .32p_session.dat file in the cache directory (with mylar not running) and try to grab stuff again - this came up yesterday with someone else who was getting errors, and deleting the .dat so it could be cleanly regenerated solved things.

**Comment by WedgeSparda** [comment]
Ok, I deleted the `.32p_cookies.dat` file inside `share/mylar/cache` folder and now is downloading the issues from 32P. Thanks. :)

But I'm still getting the second error for that specific issue. :(

**Comment by WedgeSparda** [comment]
The other issue finally was downloaded :)

**Comment by evilhero** [comment]
2nd error will be fixed in next dev commit going forward, I had to add in some functionality for it to update items after the search process finished and matched. Just running thru some tests and will get it up soon hopefully.
