### ISSUE TITLE
Post Processor crash on annual

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1491]
I can't figure out why it's crashing on this Star Wars annual but not on other comics.

```
18-Dec-2016 01:17:35 - INFO    :: CP Server Thread-7 : Starting postprocessing for : Star.Wars.Annual.002.2017.Digital.BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: Star.Wars.Annual.002.2017.Digital.BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /home/xxx/.sabnzbd/Downloads/complete/Star.Wars.Annual.002.2017.Digital.BlackManta-Empire.2
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [NZBNAME]: Star.Wars.Annual.002.2017.Digital.BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): Star.Wars.Annual.002.2017.Digital.BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Star Wars Annual 002 2017 Digital BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : Star.Wars.Annual.002.2017.Digital.BlackManta-Empire
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: 562604
18-Dec-2016 01:17:35 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb found.
18-Dec-2016 01:17:35 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for /home/xxx/.sabnzbd/Downloads/complete/Star.Wars.Annual.002.2017.Digital.BlackManta-Empire.2
18-Dec-2016 01:17:35 - INFO    :: Post-Processing : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
18-Dec-2016 01:17:35 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for Star Wars Annual issue: 2
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] issueid: 562604
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] issuenumOG: 2
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] Zero Suppression set to : 00x
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : issue detected less than 10
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : Zero level supplement set to 00x. Issue will be set as : 002
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] Pretty Comic Issue is : 002
18-Dec-2016 01:17:35 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issue Year : 2017
18-Dec-2016 01:17:35 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/home/xxx/Apps/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 1191, in Process
    return self.Process_next(comicid, issueid, issuenumOG)
  File "/home/xxx/Apps/Mylar/mylar/PostProcessor.py", line 1437, in Process_next
    publisher = comicnzb['ComicPublisher']
TypeError: 'NoneType' object has no attribute '__getitem__'

```

Let me know if you need more logs.

**Comment by evilhero** [comment]
Looks like it's erroring out because the annual doesn't have a publisher for some reason. Do you have annual integration enabled or disabled?

**Comment by weidercs** [comment]
Enabled

**Comment by evilhero** [comment]
Weird, it should be working (tested myself and pp'd just fine with the publisher field being populated). Can you try to Refresh the series and then do the download again to see if it works?

**Comment by weidercs** [comment]
I tried refreshing and also tried deleting Star Wars and re-adding and it always craps out adding the annuals (both for me).  It's the only series that it errors out on and I've read them now so I'm going to let it go.  If there is anything you want me to try and diagnose let me know, but this can be considered a one off oddity and closed if you want.
