### ISSUE TITLE
Can't add series from pullist

### ISSUE THREAD

**Issue by amalafrozalam** [evilhero/mylar#1502]
Not exactly sure what the issue is here, but here is the code that is presented:
`Traceback (most recent call last):
  File "/opt/Mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/Mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 230, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=issue)
  File "/opt/Mylar/mylar/mb.py", line 135, in findComic
    searched = pullsearch(comicapi, comicquery, 0, explicit, type)
  File "/opt/Mylar/mylar/mb.py", line 52, in pullsearch
    PULLURL = mylar.CVURL + 'search?api_key=' + str(comicapi) + '&resources=' + str(type) + '&query=' + u_comicquery + '&field_list=id,name,start_year,first_issue,site_detail_url,count_of_issues,image,publisher,deck,description,last_issue&format=xml&limit=100&page=' + str(offset)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-81: ordinal not in range(128)`

This returns a 500 internal server error.
System is Ubuntu 16.04, Mylar is on the development branch.

**Comment by amalafrozalam** [comment]
Figured it out. For some reason when copying and pasting the ComicVine API, the paste command inserts a whole bunch of random characters at the end of the API.
