### ISSUE TITLE
error searching for new comics

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1511]
i'm on the dev branch getting the following error 

2016-12-28 19:50:41	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Users\User\Desktop\mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\User\Desktop\mylar\mylar\webserve.py", line 1415, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "C:\Users\User\Desktop\mylar\mylar\search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "C:\Users\User\Desktop\mylar\mylar\search.py", line 544, in NZB_SEARCH
a = auth32p.info32p(searchterm=searchterm)
File "C:\Users\User\Desktop\mylar\mylar\auth32p.py", line 30, in __init__
if not lses.login():
File "C:\Users\User\Desktop\mylar\mylar\auth32p.py", line 539, in login
if (self.test_skey_valid()):
File "C:\Users\User\Desktop\mylar\mylar\auth32p.py", line 498, in test_skey_valid
self.ses.cookies.save(ignore_discard=true)
NameError: global name 'true' is not defined
2016-12-28 19:50:41	ERROR	Got bad status code in the POST-ajax action=login GET:503

whats going on? i have no idea :(

**Comment by evilhero** [comment]
32p has cloudflare ddos protection up for the holidays, so it's no playing nicely with mylar.  A few have been trying to help out and fix things so it works, but atm we haven't been able to get it working. 

Worst case is on e the holidays are over, the ddos protection will be removed and mylar will resume working again.

**Comment by evilhero** [comment]
CF has been taken down now, so things should be back to normal as far as Mylar and 32P. Hopefully we'll be able to get the CF patch up before the next time it goes live again there, but without it being actually up it's difficult to test properly ;)
