### ISSUE TITLE
Other unusual "numbering"s

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1519]
2017-01-02 11:06:19	INFO	FAILED FILES: [{'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Black', 'comicfilename': 'Deathmate - Black (1993).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Blue', 'comicfilename': 'Deathmate - Blue (1993).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1994', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Epilogue', 'comicfilename': 'Deathmate - Epilogue (1994).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Preview', 'comicfilename': 'Deathmate - Preview (1993).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Prologue', 'comicfilename': 'Deathmate - Prologue (1993).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Red', 'comicfilename': 'Deathmate - Red (1993).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': '1993', 'comiclocation': u'D:/Comics/Valiant/Deathmate (1993)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Deathmate - Yellow', 'comicfilename': 'Deathmate - Yellow (1993).cbz', 'series_volume': None}]
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Yellow (1993).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Red (1993).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Prologue (1993).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Preview (1993).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Epilogue (1994).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Blue (1993).cbz
2017-01-02 11:06:19	INFO	[FILENAME]: Deathmate - Black (1993).cbz
2017-01-02 11:06:19	INFO	there are 7 files.

2017-01-02 11:06:14	WARNING	[FILE-RESCAN] you should either Refresh the series, and/or submit an issue on github in regards to the series and the error.
2017-01-02 11:06:14	WARNING	[FILE-RESCAN] An error occured trying to get the relevant issue data. This is probably due to the series not having proper issue data.
2017-01-02 11:06:14	INFO	Starting update for 1 active comics
2017-01-02 11:06:11	INFO	Series_Name: Aspen Seasons - Winter --- WatchComic: Aspen Seasons
2017-01-02 11:06:11	INFO	[FILENAME]: Aspen Seasons - Winter 2009 (2009).cbz
2017-01-02 11:06:11	INFO	Series_Name: Aspen Seasons - Summer --- WatchComic: Aspen Seasons
2017-01-02 11:06:11	INFO	[FILENAME]: Aspen Seasons - Summer 2006 (2006).cbz
2017-01-02 11:06:11	INFO	Series_Name: Aspen Seasons - Spring --- WatchComic: Aspen Seasons
2017-01-02 11:06:11	INFO	[FILENAME]: Aspen Seasons - Spring 2005 (2005).cbz
2017-01-02 11:06:11	INFO	Series_Name: Aspen Seasons - Fall --- WatchComic: Aspen Seasons
2017-01-02 11:06:10	INFO	[FILENAME]: Aspen Seasons - Fall 2005 (2005).cbz
2017-01-02 11:06:10	INFO	there are 4 files.

**Comment by evilhero** [comment]
Wow ok those are weird.. I'm not sure if I can build all of those in - I mean I can, but because of common words being used as issue numbers it'll take a bit of testing to figure things out.

**Comment by F688** [comment]
No problem, just noting it. Maybe some sort of manual entry.

**Comment by F688** [comment]
Volume Issue

Most of the ones with "Volume" in title worked except this one.

2017-01-03 13:55:48	INFO	Update complete
2017-01-03 13:55:33	INFO	[FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 5 ]
2017-01-03 13:55:33	DEBUG	[FILE-RESCAN] Ensuring permissions/ownership enforced for series: Mice Templar, Volume V: Night's End
2017-01-03 13:55:33	DEBUG	[FILE-RESCAN] I have changed the status of 0 issues to a status of Archived, as I now cannot locate them in the series directory.
2017-01-03 13:55:32	INFO	[FILE-RESCAN] Total files located: 0
2017-01-03 13:55:32	INFO	[FILE-RESCAN] Updated the status of 5 issues for Mice Templar, Volume V: Night's End (2015) that were not found.
2017-01-03 13:55:30	DEBUG	mc_issue:[]
2017-01-03 13:55:30	DEBUG	No issues with identical issue numbering were detected for this series
2017-01-03 13:55:28	DEBUG	[FILE-RESCAN]comiccnt is:0
2017-01-03 13:55:28	INFO	FAILED FILES: [{'issue_number': None, 'sub': None, 'issue_year': None, 'comiclocation': u'D:/Comics/Image/Mice Templar Volume V Nights End (2015)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mice Templar Volume V Nights End - 001 (2015)', 'comicfilename': 'Mice Templar Volume V Nights End - 001 (2015).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': None, 'comiclocation': u'D:/Comics/Image/Mice Templar Volume V Nights End (2015)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mice Templar Volume V Nights End - 002 (2015)', 'comicfilename': 'Mice Templar Volume V Nights End - 002 (2015).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': None, 'comiclocation': u'D:/Comics/Image/Mice Templar Volume V Nights End (2015)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mice Templar Volume V Nights End - 003 (2015)', 'comicfilename': 'Mice Templar Volume V Nights End - 003 (2015).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': None, 'comiclocation': u'D:/Comics/Image/Mice Templar Volume V Nights End (2015)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mice Templar Volume V Nights End - 004 (2015)', 'comicfilename': 'Mice Templar Volume V Nights End - 004 (2015).cbz', 'series_volume': None}, {'issue_number': None, 'sub': None, 'issue_year': None, 'comiclocation': u'D:/Comics/Image/Mice Templar Volume V Nights End (2015)', 'scangroup': None, 'parse_status': 'failure', 'series_name': 'Mice Templar Volume V Nights End - 005 (2015)', 'comicfilename': 'Mice Templar Volume V Nights End - 005 (2015).cbz', 'series_volume': None}]
2017-01-03 13:55:28	DEBUG	Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
2017-01-03 13:55:28	DEBUG	series title possibly: Mice Templar Volume V Nights End - 005 (2015)
2017-01-03 13:55:28	DEBUG	No issue number present in filename.
2017-01-03 13:55:28	DEBUG	issue_position: 0
2017-01-03 13:55:28	DEBUG	highest_series_position: 9
2017-01-03 13:55:28	DEBUG	No year present within title - ignoring as a variable.
2017-01-03 13:55:28	DEBUG	datecheck: []
2017-01-03 13:55:28	INFO	[FILENAME]: Mice Templar Volume V Nights End - 005 (2015).cbz
2017-01-03 13:55:28	DEBUG	Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
2017-01-03 13:55:28	DEBUG	series title possibly: Mice Templar Volume V Nights End - 004 (2015)
2017-01-03 13:55:28	DEBUG	No issue number present in filename.
2017-01-03 13:55:28	DEBUG	issue_position: 0
2017-01-03 13:55:28	DEBUG	highest_series_position: 9
2017-01-03 13:55:28	DEBUG	No year present within title - ignoring as a variable.
2017-01-03 13:55:28	DEBUG	datecheck: []
2017-01-03 13:55:28	INFO	[FILENAME]: Mice Templar Volume V Nights End - 004 (2015).cbz
2017-01-03 13:55:28	DEBUG	Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
2017-01-03 13:55:28	DEBUG	series title possibly: Mice Templar Volume V Nights End - 003 (2015)
2017-01-03 13:55:28	DEBUG	No issue number present in filename.
2017-01-03 13:55:28	DEBUG	issue_position: 0
2017-01-03 13:55:28	DEBUG	highest_series_position: 9
2017-01-03 13:55:28	DEBUG	No year present within title - ignoring as a variable.
2017-01-03 13:55:28	DEBUG	datecheck: []
2017-01-03 13:55:28	INFO	[FILENAME]: Mice Templar Volume V Nights End - 003 (2015).cbz
2017-01-03 13:55:28	DEBUG	Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
2017-01-03 13:55:28	DEBUG	series title possibly: Mice Templar Volume V Nights End - 002 (2015)
2017-01-03 13:55:28	DEBUG	No issue number present in filename.
2017-01-03 13:55:28	DEBUG	issue_position: 0
2017-01-03 13:55:28	DEBUG	highest_series_position: 9
2017-01-03 13:55:28	DEBUG	No year present within title - ignoring as a variable.
2017-01-03 13:55:28	DEBUG	datecheck: []
2017-01-03 13:55:28	INFO	[FILENAME]: Mice Templar Volume V Nights End - 002 (2015).cbz
2017-01-03 13:55:28	DEBUG	Cannot parse the filename properly. I'm going to make note of this filename so that my evil ruler can make it work.
2017-01-03 13:55:28	DEBUG	series title possibly: Mice Templar Volume V Nights End - 001 (2015)
2017-01-03 13:55:28	DEBUG	No issue number present in filename.
2017-01-03 13:55:28	DEBUG	issue_position: 0
2017-01-03 13:55:28	DEBUG	highest_series_position: 9
2017-01-03 13:55:28	DEBUG	No year present within title - ignoring as a variable.

**Comment by evilhero** [comment]
That's an easy fix, one cause when I did the previous PR for the roman numerals, I stopped at IV.  Should be ae to just add V to the subset list and it'll pick it up.

**Comment by F688** [comment]
Awesome

**Comment by miko3ed** [comment]
I don't suppose there's any new ideas on how to get [Aspen Seasons](https://comicvine.gamespot.com/aspen-seasons/4050-19696/) able to be imported? Getting the following error when trying to add it:
> 2019-01-16 09:44:06 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/importer.py", line 339, in addComictoDBissuedata = updateddata['issuedata']TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
> 2019-01-16 09:44:06 | DEBUG | this does not have an issue # that I can parse properly.
> 2019-01-16 09:44:06 | DEBUG | [] invalid numeric for issue - cannot be found. Ignoring.
> 2019-01-16 09:44:06 | INFO | Now adding/updating issues for Aspen Seasons

**Comment by evilhero** [comment]
@miko3ed : Fix is in development now. You will be able to Add the series, as well as perform a Recheck Files/Refresh in order to pick up issues - however search will not work (I don't forsee this working, it will search but probably won't match anything relevant). Note however that the files must be named in accordance with the issue number being preceded by a # as in ```Aspen Seasons #Winter 2009.cbr``` or ```Aspen Seasons #Summer 2005``` In these particular cases, the year is required as well (even though it will show in Mylar as the issues being just the season name without the year present.
