### ISSUE TITLE
Post Processing not importing from monitor folder.

### ISSUE THREAD

**Issue by ucmeflyby** [evilhero/mylar#1528]
Development Branch

Since the latest batch of updates I've noticed that new comics are not being imported from my monitor folder.  If I goto the Manage tab and initiate a Manual Run then I see the following errors:

2017-01-05 09:11:55	DEBUG	'Traceback (most recent call last):\n File "J:\\usr\\Mylar\\mylar-development\\mylar\\scheduler.py", line 78, in runAction\n self.action.run()\n File "J:\\usr\\Mylar\\mylar-development\\mylar\\PostProcessor.py", line 1998, in run\n result = PostProcess.Process()\n File "J:\\usr\\Mylar\\mylar-development\\mylar\\PostProcessor.py", line 788, in Process\n checkdirectory = filechecker.validateAndCreateDirectory(grdst, True, module=module)\n File "J:\\usr\\Mylar\\mylar-development\\mylar\\filechecker.py", line 1162, in validateAndCreateDirectory\n if os.path.exists(dir):\n File "C:\\Python27\\lib\\genericpath.py", line 26, in exists\n os.stat(path)\nTypeError: coercing to Unicode: need string or buffer, NoneType found\n'

---------------------------   Later in the Log  --------------------------------------------

2017-01-05 09:11:35	ERROR	Uncaught exception: Traceback (most recent call last):
File "J:\usr\Mylar\mylar-development\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "J:\usr\Mylar\mylar-development\mylar\PostProcessor.py", line 788, in Process
checkdirectory = filechecker.validateAndCreateDirectory(grdst, True, module=module)
File "J:\usr\Mylar\mylar-development\mylar\filechecker.py", line 1162, in validateAndCreateDirectory
if os.path.exists(dir):
File "C:\Python27\lib\genericpath.py", line 26, in exists
os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I am not using any torrent software, just dropping downloaded comics into the monitor folder and let Mylar import/track/organize them.

Thank you for all the time you spend working on Mylar.

**Comment by ucmeflyby** [comment]
I also had the issue that my Pull List was blank/empty.  I changed to Alt Pull = 2 and my Pull List is no longer blank/empty.

**Comment by evilhero** [comment]
It looks like you might have an extra character in your path that's being monitored - is there a space at the beginning/end of the path within mylar? What is the actual path you're entering in for the manual run to post-process?

**Comment by ucmeflyby** [comment]
The path I'm using for manual check is the same that is monitored, no spaces in path, "J:\usr\Mylar\Import".   Since you asked, I've checked in config.ini and see a difference, it's been this way for quite a long time:
...
comic_dir = J:\usr\Mylar\Import\
...
check_folder = J:\usr\Mylar\Import
....

I don't normaly initiate the manual, post-processing checks every 5 minutes.

**Comment by evilhero** [comment]
Actually I just realized it's erroring on trying to create & validate a directory  - what is your comic location set to within mylar? (it's called destintion_location within the .ini)

So it's either having problems checking that directory for existence (ie. Spaces leading/trailing), or one of the directories it's trying to post-process into has an invalid character in the title. If you enable verbose logging, you should be able to see what it's trying to check exactly just prior to the error.

**Comment by ucmeflyby** [comment]
There is a cvinfo file in my main dir that should not be there.  It contains a comicvine link to a storyarc.  Immediatly before the error I am seeing is a reference to processing story arcs.  I'll chase this for a minute and see where it goes.

**Comment by ucmeflyby** [comment]
Is the "Arcs in StoryArc Directory" option something new?

**Comment by evilhero** [comment]
No that's been around for a very long time - if its not enabled mylar will dump the arc issues into the grabbag_dir location which is normally the root of your comic location path. The cvinfo file isn't used by mylar except during an import, otherwise its just something mylar writes to for other programs to use.

**Comment by evilhero** [comment]
Can you paste the debug log for the few lines just prior to the error?

**Comment by ucmeflyby** [comment]
Here are a few lines of the debug log:

2017-01-05 15:43:51	ERROR	Uncaught exception: Traceback (most recent call last):
File "J:\usr\Mylar\mylar-development\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "J:\usr\Mylar\mylar-development\mylar\PostProcessor.py", line 835, in Process
logger.fdebug(module + '[ONE-OFF MODE][' + mylar.ARC_FILEOPS.upper() + '] Failure ' + src + ' - check directories and manually re-run.')
NameError: global name 'src' is not defined
2017-01-05 15:43:51	INFO	[POST-PROCESSING][ONE-OFF MODE][COPY] J:\usr\Mylar\Import\The Transformers More Than Meets the Eye Revolution 001 (2016) (Digital) (Knight Ripper-Empire).cbr into directory : J:\usr\Mylar\Import\The Transformers More Than Meets the Eye Revolution 001 (2016) (Digital) (Knight Ripper-Empire).cbr
2017-01-05 15:43:51	DEBUG	[POST-PROCESSING] Source Path : J:\usr\Mylar\Import\The Transformers More Than Meets the Eye Revolution 001 (2016) (Digital) (Knight Ripper-Empire).cbr
2017-01-05 15:43:51	DEBUG	[POST-PROCESSING] Destination Path : J:\usr\Mylar\Import\The Transformers More Than Meets the Eye Revolution 001 (2016) (Digital) (Knight Ripper-Empire).cbr
2017-01-05 15:43:51	INFO	[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: J:\usr\Mylar\Comics\StoryArcs\Revolution (2016)
2017-01-05 15:43:51	INFO	Revolution (2016)
2017-01-05 15:43:51	INFO	StoryArcs
2017-01-05 15:43:51	INFO	J:\usr\Mylar\Comics
2017-01-05 15:43:51	INFO	[STORY-ARC POST-PROCESSING] Enabled for Revolution
2017-01-05 15:43:51	INFO	[STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.


The previous error seems sorted, but now it has moved on to this.

**Comment by evilhero** [comment]
Weird source shouldn't be same as the destination, well that and the src is erroring out

**Comment by ucmeflyby** [comment]
I've deleted all my Story Arcs and it seems to be post processing on its own now.

**Comment by ucmeflyby** [comment]
Added back the Arc that was involved in the error.  We'll see if I have the errors again when I add another batch of downloaded comics.

Thank you for your help!

**Comment by evilhero** [comment]
No worries - this should be fixed in the next dev commit as well. It looks like it was due in part to not having a story arc directory enabled, and having multiple arcs all hit the same directory (the grab_bag but it wasn't properly associating it). It should now work by creating story arc subdirectories named after the arc, either in a separate story arc directory (if the option is enabled), or in your grab_bag directory location (the root of your comic location usually) with subsequent story arc subdirectories therein.

Cheers!
