### ISSUE TITLE
Mylar wont start

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#1549]
Mylar was working fine until yesterday that I restarted it. Now is showing the error below:

Starting Mylar
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/rsscheck.py", line 16, in <module>
    from mylar import db, logger, ftpsshup, helpers, auth32p, utorrent
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/auth32p.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/bs4/__init__.py", line 29, in <module>

  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/bs4/builder/__init__.py", line 306, in <module>

  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/bs4/builder/_html5lib.py", line 57, in <module>
AttributeError: 'module' object has no attribute '_base'

Didn't change anything as far as i know. Any assistance will be appreciated.

Thanks.

**Comment by evilhero** [comment]
Your bs4 is pointing to the wrong location with mylar - it has changed to be in lib/bs4 not bs4/ as you have it so the references are all wrong. 

You'll have to either delete the bs4 directory, and do a git pull to get back up to date - or move the bs4 directory from it's current location into the lib/ folder within mylar (with mylar not running).

**Comment by cesalo** [comment]
Thanks, it's up and running now. I removed the one in Mylar, I ended up having 2 bs4 directories one in Mylar and the other in Mylar/lib.
Why did this happen? A recent upgrade?
Thanks again.

**Comment by evilhero** [comment]
It's happened to some installations maybe due to permissions or how it was installed - it can't remove the directory, but ws able to copy it to the new location but the way mylar references libraries would make it hit the non-lib entry first. 

It happened awhile ago (the move to the /lib subfolder), so I'm guessing you installed html5lib at some point between mylar restarts and it caused the problem (the fix for having installed html5lib on your OS was in the lib move as it upgraded bs4)
