### ISSUE TITLE
Mylar not starting on OSX Sierra

### ISSUE THREAD

**Issue by WilliamKerridge** [evilhero/mylar#1555]
Hi

Looking for some help I have installed Mylar filling the installation guide on the below link

http://www.htpcguides.com/install-mylar-mac-osx-usenet-comics/

When i try to run it i get the below error 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/williamkerridge/Downloads/mylar-master/lib/cherrypy/_cprequest.py", line 645, in respond
  File "/Users/williamkerridge/Downloads/mylar-master/lib/cherrypy/lib/encoding.py", line 188, in __call__
  File "/Users/williamkerridge/Downloads/mylar-master/lib/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/Users/williamkerridge/Downloads/mylar-master/mylar/webserve.py", line 76, in home
  File "/Users/williamkerridge/Downloads/mylar-master/mylar/helpers.py", line 1253, in havetotals
  File "/Users/williamkerridge/Downloads/mylar-master/mylar/db.py", line 71, in __init__
OperationalError: unable to open database file

How do i fix this 

thank you

**Comment by evilhero** [comment]
Make sure the user running mylar has proper permissions to the entire mylar folder. Mylar needs to be able to read/write to the .db file and it's saying it can't.

**Comment by WilliamKerridge** [comment]
Hi

Thanks for the info but I have checked all the permissions and all users
have the full read write permissions.

I am going to try a reboot to see if that helps if you can think of any
other reason please let me know

Thank you

-- 
William Kerridge
Sent with Airmail

**Comment by WilliamKerridge** [comment]
Hi

I have rebooted and this has cured the permissions issue

Thank you for the help

-- 
William Kerridge
Sent with Airmail
