### ISSUE TITLE
Comics stuck in a refreshing state.

### ISSUE THREAD

**Issue by dsawejka** [evilhero/mylar#1560]

**Comment by dsawejka** [comment]
I have a few comics that are stuck in a refreshing state.
I have tried restarting, deleting and re-adding comic.

**Comment by evilhero** [comment]
post the debug logs (start Mylar with the -v switch, or toggle verbose to on  in the logs tab of the GUI) - without seeing what's going on I can't do much to assist.

**Comment by dsawejka** [comment]
2017-02-01 10:36:42	INFO	RSS Feed Check was last run at : 2017-02-01 10:33:33
2017-02-01 10:36:25	INFO	No series have been marked as being on auto-watch.
2017-02-01 10:36:25	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'The Woods', 'ISSUE': u'29', 'ComicID': u'73689'}
2017-02-01 10:36:25	INFO	cstatus:Wanted
2017-02-01 10:36:25	INFO	controlValue:{'rowid': 408}
2017-02-01 10:36:25	INFO	date_downloaded: None
2017-02-01 10:36:25	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579347', 'ComicID': u'73689'}
2017-02-01 10:36:25	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'The Walking Dead', 'ISSUE': u'163', 'ComicID': u'18166'}
2017-02-01 10:36:25	INFO	cstatus:Wanted
2017-02-01 10:36:25	INFO	controlValue:{'rowid': 446}
2017-02-01 10:36:25	INFO	date_downloaded: None
2017-02-01 10:36:25	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579339', 'ComicID': u'18166'}
2017-02-01 10:36:25	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'The Unstoppable Wasp', 'ISSUE': u'2', 'ComicID': u'97774'}
2017-02-01 10:36:25	INFO	cstatus:Wanted
2017-02-01 10:36:25	INFO	controlValue:{'rowid': 456}
2017-02-01 10:36:25	INFO	date_downloaded: None
2017-02-01 10:36:25	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579326', 'ComicID': u'97774'}
2017-02-01 10:36:25	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'The Transformers: Lost Light', 'ISSUE': u'2', 'ComicID': u'96642'}
2017-02-01 10:36:25	INFO	cstatus:Wanted
2017-02-01 10:36:25	INFO	controlValue:{'rowid': 300}
2017-02-01 10:36:25	INFO	date_downloaded: None
2017-02-01 10:36:25	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'578658', 'ComicID': u'96642'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Superman', 'ISSUE': u'16', 'ComicID': u'91298'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 419}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579298', 'ComicID': u'91298'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Old Man Logan', 'ISSUE': u'17', 'ComicID': u'87624'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 462}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579321', 'ComicID': u'87624'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Nova', 'ISSUE': u'3', 'ComicID': u'96300'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 463}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579320', 'ComicID': u'96300'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Nightwing', 'ISSUE': u'14', 'ComicID': u'92569'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 421}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579294', 'ComicID': u'92569'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Nailbiter', 'ISSUE': u'29', 'ComicID': u'73649'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 450}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579336', 'ComicID': u'73649'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Moon Knight', 'ISSUE': u'11', 'ComicID': u'89613'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 464}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579319', 'ComicID': u'89613'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Monsters Unleashed!', 'ISSUE': u'2', 'ComicID': u'98067'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 465}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579318', 'ComicID': u'98067'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Justice League', 'ISSUE': u'14', 'ComicID': u'92373'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 423}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579291', 'ComicID': u'92373'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Hawkeye', 'ISSUE': u'3', 'ComicID': u'96661'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 469}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579314', 'ComicID': u'96661'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Green Lanterns', 'ISSUE': u'16', 'ComicID': u'91285'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 426}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579288', 'ComicID': u'91285'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Green Arrow', 'ISSUE': u'16', 'ComicID': u'91284'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 427}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579287', 'ComicID': u'91284'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Deadpool', 'ISSUE': u'26', 'ComicID': u'85750'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 471}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579312', 'ComicID': u'85750'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Deadly Class', 'ISSUE': u'26', 'ComicID': u'71032'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 453}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579333', 'ComicID': u'71032'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Cyborg', 'ISSUE': u'9', 'ComicID': u'94266'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 431}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579281', 'ComicID': u'94266'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Champions', 'ISSUE': u'5', 'ComicID': u'94612'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 472}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579308', 'ComicID': u'94612'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Bullseye', 'ISSUE': u'1', 'ComicID': u'98512'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 473}

**Comment by dsawejka** [comment]
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579306', 'ComicID': u'98512'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Downloaded', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Batman', 'ISSUE': u'16', 'ComicID': u'91273'}
2017-02-01 10:36:24	INFO	cstatus:Downloaded
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 432}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Downloaded', 'IssueID': u'579279', 'ComicID': u'91273'}
2017-02-01 10:36:24	INFO	newValue:{'Status': u'Wanted', 'WEEKNUMBER': 5, 'YEAR': '2017', 'COMIC': u'Aquaman', 'ISSUE': u'16', 'ComicID': u'91738'}
2017-02-01 10:36:24	INFO	cstatus:Wanted
2017-02-01 10:36:24	INFO	controlValue:{'rowid': 433}
2017-02-01 10:36:24	INFO	date_downloaded: None
2017-02-01 10:36:24	INFO	statusupdate: {'Status': u'Wanted', 'IssueID': u'579278', 'ComicID': u'91738'}
2017-02-01 10:36:23	INFO	AlternateNames returned:{'Count': 1, 'AlternateName': [{'AlternateName': 'Outcast'}], 'ComicID': u'75114'}
2017-02-01 10:36:23	INFO	[PULL-LIST] Weekly Pull List successfully loaded with 90 issues.
2017-02-01 10:36:23	INFO	[PULL-LIST] Successfully populated pull-list into Mylar for the week of: 05
2017-02-01 10:36:23	INFO	[WEEKLY-PULL] There are 90 issues for the week of 05, 2017
2017-02-01 10:36:22	INFO	pulldate is : 00000000
2017-02-01 10:36:22	INFO	[PULL-LIST] Populating & Loading pull-list data directly from alternate website
2017-02-01 10:36:22	INFO	Weekly pull list present - checking if it's up-to-date..
2017-02-01 10:36:22	INFO	[WEEKLY] Checking Weekly Pull-list for new releases/updates
2017-02-01 10:36:12	INFO	delaying thread for 10 seconds to avoid locks.
2017-02-01 10:36:12	INFO	Checking for existance of Weekly Comic listing...
2017-02-01 10:36:12	INFO	Initiating startup-RSS feed checks.
2017-02-01 10:36:12	INFO	delaying thread for 30 seconds to avoid locks.
2017-02-01 10:36:12	INFO	Initializing the DB Updater.
2017-02-01 10:36:11	INFO	Starting Mylar on http://0.0.0.0:8085/
2017-02-01 10:36:11	INFO	Sucessfully ordered 154 series in your watchlist.
2017-02-01 10:36:11	INFO	Remapping the sorting to allow for new additions.
2017-02-01 10:36:11	INFO	Mylar is up to date
2017-02-01 10:36:09	INFO	Retrieving latest version information from github
2017-02-01 10:36:09	INFO	Correcting Null entries that make the main page break on startup.
2017-02-01 10:36:09	INFO	Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2017-02-01 10:36:09	INFO	Populating Custom Exception listings into Mylar....
2017-02-01 10:36:09	INFO	Populating Base Exception listings into Mylar....
2017-02-01 10:36:09	INFO	Checking to see if the database has all tables....
2017-02-01 10:36:09	INFO	[Cache Check] Cache directory currently set to : C:\Users\Dustin\Desktop\mylar-master\mylar-master\cache/
2017-02-01 10:36:09	INFO	[DB Module] Loading : sqlite3 as the database module to use.
2017-02-01 10:36:09	INFO	Branch detected & set to : master
2017-02-01 10:36:09	INFO	Successfully discovered local IP and locking it in as : 10.0.0.16
2017-02-01 10:36:09	INFO	[DIRECTORY-CHECK] Found comic directory: C:\Users\Dustin\Desktop\mylar-master\mylar-master

**Comment by dsawejka** [comment]
![image](https://cloud.githubusercontent.com/assets/22100564/22516663/1ad60608-e86c-11e6-954b-f3f06c17aa51.png)

**Comment by dsawejka** [comment]
Those 2 are stuck like that.

**Comment by evilhero** [comment]
Restart mylar, go into logs tab and enable verbose. Then go to one of those 2 series and do a refresh series. Then paste the resulting log in here so I can see what's happening. 

Note that if you're on dev, avengers probably won't refresh due to the .mu issue from last week (fix is in dev atm)

**Comment by dsawejka** [comment]
2017-02-01 12:17:44	INFO	[DIRECTORY-CHECK] Found comic directory: G:\Comics\Avengers\ (2016)
2017-02-01 12:17:44	DEBUG	Refreshing the series and pulling in new data using only CV.
2017-02-01 12:17:44	DEBUG	Deleting all issue data.
2017-02-01 12:17:44	DEBUG	checking annual db
2017-02-01 12:17:44	DEBUG	No issue data available. This is Whack.
2017-02-01 12:17:44	DEBUG	Gathering the status of all issues for the series.
2017-02-01 12:17:44	DEBUG	CV_OneTimer option enabled...
2017-02-01 12:17:44	DEBUG	Refreshing: Avengers (2016) [95402]
2017-02-01 12:17:44	INFO	Starting update for 1 active comics
2017-02-01 12:17:44	DEBUG	Refreshing comic: [u'95402']
2017-02-01 12:17:37	DEBUG	If you read this message, debug logging is available

**Comment by evilhero** [comment]
There's nothing else after the found comic directory line related to the refresh? 

Is your comicvine api key valid and not disabled /  rate limited?

**Comment by dsawejka** [comment]
2017-02-01 12:17:56	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Users\Dustin\Desktop\mylar-master\mylar-master\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Dustin\Desktop\mylar-master\mylar-master\mylar\updater.py", line 286, in dbUpdate
cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
File "C:\Users\Dustin\Desktop\mylar-master\mylar-master\mylar\importer.py", line 559, in addComictoDB
issuedata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
File "C:\Users\Dustin\Desktop\mylar-master\mylar-master\mylar\importer.py", line 1289, in updateissuedata
decisval = int(decis)
ValueError: invalid literal for int() with base 10: 'MU'
2017-02-01 12:17:56	INFO	Now adding/updating issues for Avengers
2017-02-01 12:17:56	DEBUG	Finshed Annual checking.
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 30632
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 39916
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 4219
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 3656
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 42683
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 18198
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 75140
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 73421
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 2350
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 69686
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 47942
2017-02-01 12:17:56	DEBUG	[IMPORTER-ANNUAL] - there are 23 results.
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers / Squadron Supreme '98 -- 1998 [Series years: [u'1998']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers 1999 -- 1999 [Series years: [u'1999']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers 2000 -- 2000 [Series years: [u'2000']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers 2001 -- 2001 [Series years: [u'2001']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avenging Spider-Man Annual -- 2012 [Series years: [u'2012']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers West Coast Annual -- 1989 [Series years: [u'1989']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers: The Initiative Annual -- 2008 [Series years: [u'2008']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers Assemble Annual -- 2013 [Series years: [u'2013']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:All-New, All-Different Avengers Annual -- 2016 [Series years: [u'2016']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers Annual #10 [Marvel Legends Reprint] -- 2005 [Series years: [u'2005']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:West Coast Avengers Annual -- 1986 [Series years: [u'1986']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:The New Avengers Annual -- 1976 [Series years: [u'1976']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:New Avengers Annual -- 2011 [Series years: [u'2011']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Dark Avengers Annual -- 2010 [Series years: [u'2010']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Uncanny Avengers Annual -- 2015 [Series years: [u'2015']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:New Avengers Annual -- 2006 [Series years: [u'2006']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:New Avengers Annual -- 2014 [Series years: [u'2014']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Uncanny Avengers Annual -- 2014 [Series years: [u'2014']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:The Avengers Annual -- 1967 [Series years: [u'1967']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers Annual -- 2012 [Series years: [u'2012']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:The Avengers Annual -- 1966 [Series years: [u'1966']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers Annual -- 2013 [Series years: [u'2013']]
2017-02-01 12:17:56	DEBUG	[RESULT][None] ComicName:Avengers Annual -- 1974 [Series years: [u'1974']]
2017-02-01 12:17:56	DEBUG	there are 23 search results...
2017-02-01 12:17:52	DEBUG	Default search mode - this will match on ALL search words
2017-02-01 12:17:52	DEBUG	[IMPORTER-ANNUAL] - Annual Year:2016
2017-02-01 12:17:52	DEBUG	checking annual db
2017-02-01 12:17:52	DEBUG	issuetype: None
2017-02-01 12:17:52	DEBUG	latestissueinfo: [{'latestiss': None, 'latestdate': u'Unknown-Unknow-01'}]
2017-02-01 12:17:52	DEBUG	issuechk: None
2017-02-01 12:17:52	DEBUG	calledfrom: None
2017-02-01 12:17:52	DEBUG	comicissues:8
2017-02-01 12:17:52	DEBUG	comicname:Avengers
2017-02-01 12:17:52	DEBUG	comicid:95402
2017-02-01 12:17:52	DEBUG	issuedata call references...
2017-02-01 12:17:52	INFO	Sucessfully retrieved issue details for Avengers
2017-02-01 12:17:52	DEBUG	querying range from 0 to 100
2017-02-01 12:17:52	DEBUG	there are 8 search results...
2017-02-01 12:17:49	DEBUG	comic image retrieval status code: 200
2017-02-01 12:17:49	INFO	Attempting to retrieve the comic image for series
2017-02-01 12:17:47	INFO	Directory (G:\Comics\Avengers\ (2016)) already exists! Continuing...
2017-02-01 12:17:47	INFO	Sucessfully retrieved details for Avengers
2017-02-01 12:17:47	INFO	2016
2017-02-01 12:17:47	INFO	Now adding/updating: Avengers
2017-02-01 12:17:47	DEBUG	{'ComicIssues': '8', 'ComicName': u'Avengers', 'ComicVersion': u'6', 'FirstIssueID': u'557355', 'ComicPublisher': u'Marvel', 'ComicYear': u'2016', 'ComicImageALT': u'http://comicvine.gamespot.com/api/image/scale_small/5511323-01.jpg', 'ComicURL': u'http://comicvine.gamespot.com/avengers/4050-95402/', 'Type': 'Print', 'ComicImage': u'http://comicvine.gamespot.com/api/image/scale_large/5511323-01.jpg', 'Aliases': 'None'}
2017-02-01 12:17:47	DEBUG	Volume information found! Adding to series record : volume 6
2017-02-01 12:17:47	DEBUG	volume X format - 0: Volume 6.
2017-02-01 12:17:47	DEBUG	vari is set to: yes
2017-02-01 12:17:47	DEBUG	number of issues CV says it has: 7
2017-02-01 12:17:47	DEBUG	number of issues I counted: 8
2017-02-01 12:17:44	INFO	[DIRECTORY-CHECK] Found comic directory: G:\Comics\Avengers\ (2016)
2017-02-01 12:17:44	DEBUG	Refreshing the series and pulling in new data using only CV.
2017-02-01 12:17:44	DEBUG	Deleting all issue data.
2017-02-01 12:17:44	DEBUG	checking annual db
2017-02-01 12:17:44	DEBUG	No issue data available. This is Whack.
2017-02-01 12:17:44	DEBUG	Gathering the status of all issues for the series.
2017-02-01 12:17:44	DEBUG	CV_OneTimer option enabled...
2017-02-01 12:17:44	DEBUG	Refreshing: Avengers (2016) [95402]
2017-02-01 12:17:44	INFO	Starting update for 1 active comics

**Comment by evilhero** [comment]
Yes avengers won't work due to the .mu issue from last week if you're on the master branch, which you are.  You need to wait for the dev to master merge for the fix. Until then you should pause the series or remove it so it doesn't cause furthef problems. 

Try refreshing the X-men one and see if it works (restart maybe) . It might be because of the error with the avengers it fails.

**Comment by dazzla76** [comment]
I've got what looks like the same but it complains about the MU issue when refreshing all new x-men.

`2017-02-09 19:40:31	ERROR	Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/updater.py", line 286, in dbUpdate
cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
File "/app/mylar/mylar/importer.py", line 559, in addComictoDB
issuedata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
File "/app/mylar/mylar/importer.py", line 1289, in updateissuedata
decisval = int(decis)
ValueError: invalid literal for int() with base 10: 'MU'
2017-02-09 19:40:31	INFO	Now adding/updating issues for All-New X-Men
2017-02-09 19:40:25	INFO	Sucessfully retrieved issue details for All-New X-Men
2017-02-09 19:40:21	INFO	Attempting to retrieve the comic image for series
2017-02-09 19:40:19	INFO	Directory (/comics/All-New_X-Men_(2015)) already exists! Continuing...
2017-02-09 19:40:19	INFO	Sucessfully retrieved details for All-New X-Men
2017-02-09 19:40:19	INFO	2015
2017-02-09 19:40:19	INFO	Now adding/updating: All-New X-Men
2017-02-09 19:40:16	INFO	[DIRECTORY-CHECK] Found comic directory: /comics/All-New_X-Men_(2015)
2017-02-09 19:40:16	INFO	Starting update for 1 active comics`

**Comment by evilhero** [comment]
You're running master, fix is in development to account for the .mu issues. If you can, switch to the dev branch other side you'll have to wait for the merge to happen, probably this weekend I'm hoping.

**Comment by dazzla76** [comment]
awesome, thanks for the super fast response as well.
