### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Finch106** [evilhero/mylar#1577]
2017-02-22 20:53:51	ERROR	Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\search.py", line 1730, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "c:\Mylar\mylar\search.py", line 257, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "c:\Mylar\mylar\search.py", line 1317, in NZB_SEARCH
if splitit[(len(splitit) -1)].isdigit():
IndexError: list index out of range
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	allow_packs:False
2017-02-22 20:53:51	INFO	rss:no
2017-02-22 20:53:51	INFO	TPSE
2017-02-22 20:53:51	INFO	[TPSE] there were 15 results..
2017-02-22 20:53:43	INFO	allow_packs:False
2017-02-22 20:53:43	INFO	rss:no
2017-02-22 20:53:43	INFO	TPSE
2017-02-22 20:53:43	INFO	[FAILED_DOWNLOAD_CHECKER] continuing search for another download.
2017-02-22 20:53:43	INFO	[FAILED_DOWNLOAD_CHECKER] result has a status of FAIL which indicates it is not a good choice to download.

Getting this on:

Mylar Version: development
-- git build e4098.
Python Version : 2.7.13

when force searching for all wanted.

**Comment by evilhero** [comment]
Try restarting Mylar and doing it again - you can turn on verbose logging by going into the Log tab and hit the 'Togger Verbose' option at the top of the page. Then when you run the search again it will be more information that might give some clues as to what's happening.

**Comment by Gamer106** [comment]
After a restart, so far so good. It is finding some..."odd" results through the logs though, not comics.
