### ISSUE TITLE
ExpatError: syntax error

### ISSUE THREAD

**Issue by gsemet** [evilhero/mylar#1606]
Here is an exception found in the log:
```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/webserve.py", line 423, in addStoryArc
arcinfo = mb.storyarcinfo(cvarcid)
File "/app/mylar/mylar/mb.py", line 433, in storyarcinfo
arcdom = parseString(r.content) #(arcdata)
File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
return expatbuilder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
return builder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
parser.Parse(string, True)
ExpatError: syntax error: line 1, column 0
```

**Comment by Warborg71** [comment]
I am getting the exact same problem every time I try to do a manual search for a comic title:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Mylar\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 242, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=None, explicit=explicit)
  File "C:\Mylar\mylar\mb.py", line 134, in findComic
    searched = pullsearch(comicapi, comicquery, 0, explicit, type)
  File "C:\Mylar\mylar\mb.py", line 78, in pullsearch
    dom = parseString(r.content) #(data)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: syntax error: line 1, column 0

**Comment by partymike** [comment]
me too, same error

**Comment by evilhero** [comment]
Comicvine is down atm. Try again in a bit and see them. It should handle the error more gracefully so I should be able to fix that, but I can't fix comicvine ;)

**Comment by evilhero** [comment]
You guys should be all good now - cv & their api have been back online most of the day. Can you all confirm it's working again without the above errors?

**Comment by partymike** [comment]
alls good, must have been the website down...problem happened after I updated mylar so must remember not to jump to conclusions! Thanks for great software :-)
