### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'MU'

### ISSUE THREAD

**Issue by johnmufc** [evilhero/mylar#1621]
2017-04-15 11:36:03	ERROR	Uncaught exception: Traceback (most recent call last):
File "/Applications/Mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/Applications/Mylar/mylar/updater.py", line 266, in dbUpdate
mylar.importer.addComictoDB(ComicID, mismatch, annload=annload)
File "/Applications/Mylar/mylar/importer.py", line 507, in addComictoDB
issuedata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
File "/Applications/Mylar/mylar/importer.py", line 1217, in updateissuedata
decisval = int(decis)
ValueError: invalid literal for int() with base 10: 'MU'
2017-04-15 11:36:03	INFO	Now adding/updating issues for Guardians of the Galaxy
2017-04-15 11:36:01	INFO	Sucessfully retrieved issue details for Guardians of the Galaxy
2017-04-15 11:35:59	INFO	Successfully retrieved cover for Guardians of the Galaxy
2017-04-15 11:35:59	INFO	Image header check: jpeg

Any idea how to fix this? I'm running a development build which won't update on a mac

**Comment by evilhero** [comment]
You gotta get it to to update to the latest version... Whatever version you're running hasgot to be pretty old. 

Easiest way usually is to backup your config.ini, mylar.db, and cache folder and then wipe the directory. Do a clean git clone to reinstall (```git clone https://github.com/evilhero/mylar -b development```), move the backed up files back and then you'll be on the latest build.

**Comment by johnmufc** [comment]
Sorted, thanks for the help
