### ISSUE TITLE
32p searches not really working error in logs

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1627]
```
i'm currently getting this error with a lot of comics:

2017-04-30 19:03:25	ERROR	Uncaught exception: Traceback (most recent call last):
File "D:\mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "D:\mylar\mylar\webserve.py", line 1450, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "D:\mylar\mylar\search.py", line 259, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "D:\mylar\mylar\search.py", line 1608, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "D:\mylar\mylar\search.py", line 2266, in searcher
t_hash = rcheck['hash']
TypeError: string indices must be integers, not str
2017-04-30 19:03:25	INFO	matched on Action Comics
2017-04-30 19:03:25	INFO	[FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2017-04-30 19:03:25	INFO	prov : 32P[50492]
```

i have no idea whats going on.

im on windows, on dev

**Comment by evilhero** [comment]
Are you doing a retry issue for those particular issues, or is it a manual search, or the normal 6hr background search? If I know the method that's causing that error I can then figure out the why and fix it ;)

**Comment by HypKin** [comment]
Manual search.

But the default 6hr search doesn't seem to work either

**Comment by evilhero** [comment]
What's the torrent method you're using with Mylar (rutorrent, deluge, transmission, qbittorrent, utorrent, or watchdir) ? It looks like it might be erroring out due to the client not passing back the proper values for some reason

**Comment by HypKin** [comment]
watchdir

**Comment by evilhero** [comment]
Ahh yeah, ok it's not setup to know the hash of the torrent file it snatches using the watchdir option.

I'm testing out a fix for that right now, hopefully will go live in a few for ya...

**Comment by HypKin** [comment]
after updating it i did a force check on the "wanted" page, now i'm getting this errors:


`2017-05-02 20:40:32	ERROR	Uncaught exception: Traceback (most recent call last):
File "D:\mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "D:\mylar\mylar\search.py", line 1764, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "D:\mylar\mylar\search.py", line 259, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "D:\mylar\mylar\search.py", line 1608, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "D:\mylar\mylar\search.py", line 2244, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
File "D:\mylar\mylar\rsscheck.py", line 1091, in torsend2client
torrent_info = helpers.get_the_hash(filepath)
File "D:\mylar\mylar\helpers.py", line 2856, in get_the_hash
metainfo = bencode.decode(torrent_file.read())
AttributeError: 'module' object has no attribute 'decode'
2017-05-02 20:40:32	INFO	[32P-AUTHENTICATION] Atttempting to integrate with all of your 32P Notification feeds.
2017-05-02 20:40:32	INFO	[32P] Successfully authenticated.
2017-05-02 20:40:31	INFO	matched on Detective Comics
2017-05-02 20:40:31	INFO	[FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2017-05-02 20:40:31	INFO	prov : 32P[50493]
2017-05-02 20:40:31	INFO	Found Detective Comics (2017) issue: 955 using 32P
2017-05-02 20:40:31	INFO	successfully retrieved 3 search results.`


:(

**Comment by evilhero** [comment]
There's probably a bencode.pyc file in the mylar subdirectory, delete it and then restart mylar. 

The bencode.py module got moved into the /lib subdirectory a few months ago, but the .pyc file has remained on some systems and mylar will use that instead of the file in the lib folder.

**Comment by HypKin** [comment]
ok its working now but i do not have a snatched status anymore. so its still red and wanted even though it (the torrent file) got sent to the watchdirectory.

**Comment by evilhero** [comment]
If it's been snatched successfully and sent to the watch directory, but the status hasn't changed to a Snatched status then it's erroring out somewhere after the snatch, and most likely there's an error somewhere in the logs thereafter pertaining to the problem. When I did a test snatch it worked fine on this end - marked it as Snatched and it was moved into the watch directory with no errors in the logs.

**Comment by HypKin** [comment]
again getting some errors:

```
2017-05-03 18:40:36	ERROR	Uncaught exception: Traceback (most recent call last):
File "D:\mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "D:\mylar\mylar\search.py", line 1764, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "D:\mylar\mylar\search.py", line 259, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "D:\mylar\mylar\search.py", line 1608, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "D:\mylar\mylar\search.py", line 2244, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
File "D:\mylar\mylar\rsscheck.py", line 1091, in torsend2client
torrent_info = helpers.get_the_hash(filepath)
File "D:\mylar\mylar\helpers.py", line 2856, in get_the_hash
metainfo = bencode.decode(torrent_file.read())
AttributeError: 'module' object has no attribute 'decode'
2017-05-03 18:40:36	INFO	matched on Star Wars: Darth Maul
2017-05-03 18:40:36	INFO	[FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2017-05-03 18:40:36	INFO	prov : 32P[11848]
```


:(((

**Comment by HypKin** [comment]
oh the bencode file is back again... i deleted it yesterday...

**Comment by evilhero** [comment]
Shutdown mylar and delete all the .pyc files in the mylar subdirectory. 

Is there a bencode.py file in the lib/ folder that's supposed to be there?
