### ISSUE TITLE
One-off not being post-processed, not respecting grab-bag directory

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1630]
One-off initiated from the This Week screen fails with the following: 

[POST-PROCESSING] Download not detected as being initiated via Mylar. Unable to continue post-processing said item. Either download the issue with Mylar, or use manual post-processing to post-process.
2017-05-04 21:46:03	INFO	[POST-PROCESSING] issuenzb not found.
2017-05-04 21:46:03	INFO	[POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
2017-05-04 21:46:03	INFO	Starting postprocessing for : Jean.Grey.001.2017.Digital.Zone-Empire
2017-05-04 21:46:03	INFO	ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0

Should one-offs be gracefully handled in either method at this time on dev branch? I'm on Version: f2cb786b69e9ac893479049430cc5e267663209b (development)

**Comment by evilhero** [comment]
That commit is from almost 4 months ago - you should probably update and then try the one-off again as at some point during that 4 month difference there were some fixes that should have fixed the one-off post-processing.

**Comment by ForumFerret** [comment]
updated to current version! 

Trying again with a one-off gets me the following (grabbing from the web UI for convenience' sake) 


2017-05-09 10:57:00	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/gitmylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/gitmylar/mylar/mylar/PostProcessor.py", line 1049, in Process
if all([mylar.ENABLE_META, sandwich is not None, 'S' in sandwich]):
TypeError: argument of type 'NoneType' is not iterable
2017-05-09 10:57:00	INFO	[POST-PROCESSING] One-off mode enabled for Post-Processing. Will move into Grab-bag directory.
2017-05-09 10:57:00	INFO	[POST-PROCESSING] [ONE-OFF POST-PROCESSING] One-off download detected. Post-processing as a non-watchlist item.
2017-05-09 10:57:00	INFO	[POST-PROCESSING] issuenzb not found.
2017-05-09 10:57:00	INFO	[POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
2017-05-09 10:57:00	INFO	Starting postprocessing for : Black.Bolt.001.2017.Digital.BlackManta-Empire

**Comment by ForumFerret** [comment]
seeing the following on 61d55907965e797e96f62809f49f41079dc2069e

(again grabbing from webUI logview)


-------
2017-06-02 16:47:42	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/gitmylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/gitmylar/mylar/mylar/PostProcessor.py", line 1128, in Process
renamed_file = helpers.rename_param(comicid, comicname, issuenumber, dfilename, issueid=issueid, arc=sarc)
File "/volume1/@appstore/gitmylar/mylar/mylar/helpers.py", line 261, in rename_param
logger.fdebug('issue#: ' + issue)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2017-06-02 16:47:42	INFO	[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /volume1/Diskstation/Media/Comics/OneOffs
2017-06-02 16:47:42	INFO	[POST-PROCESSING] Source Path : /volume1/Downloads/nzbget/dst/comics/Cable.001.2017.Digital.Zone-Empire/Cable 001 (2017) (Digital) (Zone-Empire).cbr
2017-06-02 16:47:42	INFO	[POST-PROCESSING] One-off mode enabled for Post-Processing. Will move into Grab-bag directory.
2017-06-02 16:47:42	INFO	[POST-PROCESSING] [ONE-OFF POST-PROCESSING] One-off download detected. Post-processing as a non-watchlist item.
2017-06-02 16:47:42	INFO	[POST-PROCESSING] issuenzb not found.
2017-06-02 16:47:42	INFO	[POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
2017-06-02 16:47:41	INFO	Starting postprocessing for : Cable.001.2017.Digital.Zone-Empire
2017-06-02 16:47:41	INFO	ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0

**Comment by evilhero** [comment]
How are you snatching the files - are you manually downloading them outside of Mylar and running the comicRN.py script on that ? Or are you snatching them using Mylar and your client is running the ComicRN.py script ?

**Comment by ForumFerret** [comment]
Initially snatched within Mylar but before the update to the latest commit
- however, processing failed so I updated to latest and then re-ran
post-processing on the new build (via nzbget's 'rerun post-processing'
feature).

**Comment by ForumFerret** [comment]
But I just tested it again with a new one-off issue snatched via the current build and hey presto it's working!

Thanks EH!

**Comment by evilhero** [comment]
yeah that's probably the problem - you can't use the rerun post-processing on one-off's in this case as mylar has to store the information of the snatch for the one-off so that it can access it during post-processing, and that was only added in the last commit. So in your case, it can't find the necessary information required to format the rename string (in this case it was the issue number it couldn't reference).

Try re-snatching the download again - it should run properly as it will then store the information for the one-off and be able to reference it correctly during post-processing.
