### ISSUE TITLE
Arc Management : Heroic Age issue

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1631]
Hello,

I have this bug with the Heroic Age arc, I'm not sure to understand what causes it but I've tryed refreshing several times, still the same issue.

OS : Synology 5.2 5644
Version : 32134e796e267cf7aa3004abe4626e4fd61c644a
Branch : Master

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 558, in addStoryArc
self.ArcWatchlist(storyarcid)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 2815, in ArcWatchlist
logger.fdebug('ARC-seriesyear: ' + str(int(arc['SeriesYear'])))
ValueError: invalid literal for int() with base 10: 'None'

**Comment by evilhero** [comment]
Yes can confirm - error due to a problem with the parser. Will try and get a fix out later today once I can make it to my machine.

**Comment by yongbi85** [comment]
exact same error with dark reign so i will let u work on it and refresh them when you push to master. Thanks again for all you do for comic fans

**Comment by evilhero** [comment]
Right so after a few tests and some code fixes, got it working on my local repo again. 

/long explanation/start
```The reason why it wasn't working was pretty unique - if a comicid of a series in the arc existed within the comicid of another series in the same arc (ie. 3092 in 33092) it would ignore the smaller value. Then when it was pulling down the series information, the record was present in the arc but no details, so it errored out when it was requesting the series year as that was the first request for data. ```
/long explanation/end

**Comment by yongbi85** [comment]
Thanks for your work. Sadly i cannot seem to be able to switch to dev branch (even after changing the config.ini and restarting, it just wouldnt update)
So im gonna wait for the master implementation

**Comment by yongbi85** [comment]
Hello,
The Heroic Age is fixed with latest master release, however Dark Reign still gives an error

	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 575, in addStoryArc
self.ArcWatchlist(storyarcid)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 2970, in ArcWatchlist
logger.fdebug('ARC-seriesyear: ' + str(int(arc['SeriesYear'])))
ValueError: invalid literal for int() with base 10: 'None'

**Comment by evilhero** [comment]
It's working fine for me - delete the arc from the Story Arc Management screen, then re-add it again and it should work (probably has some old stale data from the original load that it will retain until you start from fresh).

**Comment by yongbi85** [comment]
I had given up on this but now that i switched to docker i gave it a try again....
The error is different this time but still getting one on dark reign story arc (after i deleted and readded it)

2019-05-04 20:31:30 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/webserve.py", line 683, in addStoryArcself.ArcWatchlist(storyarcid)File "/app/mylar/mylar/webserve.py", line 3600, in ArcWatchlistif any([x['IssueDate'] is None, x['IssueDate'] == '0000-00-00']):TypeError: string indices must be integers
2019-05-04 20:31:30 | DEBUG | B4-ARC-seriesyear: None
2019-05-04 20:31:30 | DEBUG | COMIC-comicyear: 2010
2019-05-04 20:31:30 | DEBUG | int_issue = 1000
2019-05-04 20:31:30 | DEBUG | initial name match - confirming issue # is present in series
2019-05-04 20:31:30 | DEBUG | [Dark Reign] Siege: Secret Warriors : 1
2019-05-04 20:31:30 | DEBUG | IssueArcID: 55707_1657
