### ISSUE TITLE
Moved Mylar to a new server - after copying the DB and doing a locmove cant access comic details

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#1652]
If I try to click into a comic after the move I get ..

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/Mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/Mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 99, in comicDetails
    cskip = mylar.COMICSORT['SortOrder'][i]
KeyError: 0
```

Last snippet from logs
```
11-Jun-2017 10:13:26 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': '
COPPERHEAD', 'ISSUE': '14', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:26 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:26 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'76845'}
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : Now adding/updating issu
es for Birthright
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': '
BIRTHRIGHT', 'ISSUE': '25', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'77405'}
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : Now adding/updating issu
es for Ms. Marvel
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': '
MS MARVEL', 'ISSUE': '19', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'86114'}
11-Jun-2017 10:13:56 - INFO    :: CP Server Thread-11 : Attempting to integrate
Wonder Woman Annual (101798) to the existing series of Wonder Woman(2016)
11-Jun-2017 10:13:59 - INFO    :: CP Server Thread-11 : Successfully integrated
1 issues of Wonder Woman Annual to the series: Wonder Woman
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : Now adding/updating issues for Wonder Woman
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': 'WONDER WOMAN', 'ISSUE': '24', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wanted', 'IssueID': None, 'ComicID': u'91774'}
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : Finished checking for comics on my watchlist.
11-Jun-2017 10:16:24 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.132
BIRTHRIGHT', 'ISSUE': '25', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:26 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:26 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'76845'}
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : Now adding/updating issu
es for Birthright
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': '
BIRTHRIGHT', 'ISSUE': '25', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:38 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'77405'}
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : Now adding/updating issu
es for Ms. Marvel
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : controlValue:{'COMIC': '
MS MARVEL', 'ISSUE': '19', 'WEEKNUMBER': 24, 'YEAR': '2017'}
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : CStatus:None
11-Jun-2017 10:13:47 - INFO    :: CP Server Thread-11 : newValue:{'STATUS': 'Wan
ted', 'IssueID': None, 'ComicID': u'86114'}
11-Jun-2017 10:13:56 - INFO    :: CP Server Thread-11 : Attempting to integrate
Wonder Woman Annual (101798) to the existing series of Wonder Woman(2016)
11-Jun-2017 10:13:59 - INFO    :: CP Server Thread-11 : Successfully integrated
1 issues of Wonder Woman Annual to the series: Wonder Woman
11-Jun-2017 10:14:02 - INFO    :: CP Server Thread-11 : Now adding/updating issu
es for Wonder Woman
```

All other parts of the UI can be accessed. 
There may be an issue with the install as I was not identified to github (forgot) before I did the initial clone.

**Comment by Lusiphur** [comment]
I did a fresh clone using the master branch (cleared out the previous install totally).
Still the same issue after startup.

Logs
```
11-Jun-2017 11:44:01 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.132
11-Jun-2017 11:44:01 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
11-Jun-2017 11:44:01 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : /opt/Mylar/cache
11-Jun-2017 11:44:01 - INFO    :: MAIN : Checking to see if the database has all tables....
11-Jun-2017 11:44:01 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
11-Jun-2017 11:44:01 - INFO    :: MAIN : No Custom Exceptions found - Using base exceptions only. Creating blank custom_exceptions for your personal use.
11-Jun-2017 11:44:01 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
11-Jun-2017 11:44:01 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
11-Jun-2017 11:44:01 - INFO    :: MAIN : Retrieving latest version information from github
11-Jun-2017 11:44:03 - INFO    :: MAIN : Mylar is up to date
11-Jun-2017 11:44:03 - INFO    :: MAIN : Performing a one-time mass update to Comic Location
11-Jun-2017 11:44:03 - INFO    :: MAIN : [DIRECTORY-CHECK] Found comic directory: /mnt/hyena_pool/Comics
11-Jun-2017 11:44:03 - INFO    :: MAIN : FFTONEWCOM_DIR is enabled. Applying the existing folder format to ALL directories regardless of existing location paths
11-Jun-2017 11:44:03 - INFO    :: MAIN : Updated 79 series to a new Comic Location as specified in the config.ini
11-Jun-2017 11:44:03 - INFO    :: MAIN : Remapping the sorting to allow for new additions.
11-Jun-2017 11:44:03 - INFO    :: MAIN : Sucessfully ordered 78 series in your watchlist.
11-Jun-2017 11:44:03 - INFO    :: MAIN : Daemonized to PID: 21338
11-Jun-2017 11:44:03 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/
```

**Comment by Lusiphur** [comment]
Never mind. There was an old process running before I fixed things. It's working now.
