### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by atytel** [evilhero/mylar#1671]
I get a 500 Internal Server Error whenever I try to add a new comic. This includes adding by importing. The following is the error message. 

Traceback (most recent call last):
  File "c:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "c:\Mylar\mylar\helpers.py", line 1369, in havetotals
    "ComicPublished":  re.sub('(N)', '', comic['ComicPublished']).strip(),
  File "c:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by evilhero** [comment]
Mylar will not work with python 3.

**Comment by atytel** [comment]
Is it running python 3, god dammit i had it setup to run 2 this is so annyoing

**Comment by atytel** [comment]
ill try again

**Comment by atytel** [comment]
same error occurs even after python 3 removal

**Comment by evilhero** [comment]
I need a bit more info from your logs - go to the logs tab in mylar, click on the toggle verbose button in the upper right and then try an add again.  Then post the log in here - as long as you're not adding a tpb/gn and it's a normal comic series there shouldn't be any of those errors (unless cv messed up the data again)

**Comment by atytel** [comment]
2017-07-05 08:30:09	WARNING	Comic ID: 76981 has not finished loading. Nulling some values so things display properly until they can populate.
2017-07-05 08:30:01	WARNING	Error trying to validate/create directory. Aborting this process at this time.
2017-07-05 08:30:01	WARNING	[DIRECTORY-CHECK] Could not create directory: Z:\books and comics\Deadpool Bi-Annual (2014)[[Error 3] The system cannot find the path specified: u'Z:\\']. Aborting.
2017-07-05 08:30:01	INFO	[DIRECTORY-CHECK] Creating comic directory (0777) : Z:\books and comics\Deadpool Bi-Annual (2014)
2017-07-05 08:30:01	WARNING	[DIRECTORY-CHECK] Could not find comic directory: Z:\books and comics\Deadpool Bi-Annual (2014)
2017-07-05 08:30:01	DEBUG	new folder format: $Series ($Year)
2017-07-05 08:30:01	DEBUG	No version # found for series, removing from folder format
2017-07-05 08:30:01	INFO	Previous version detected as None - seeing if update required
2017-07-05 08:30:01	INFO	Sucessfully retrieved details for Deadpool Bi-Annual
2017-07-05 08:30:01	INFO	2014
2017-07-05 08:30:01	INFO	Now adding/updating: Deadpool Bi-Annual
2017-07-05 08:30:01	DEBUG	{'ComicIssues': u'1', 'ComicName': u'Deadpool Bi-Annual', 'ComicVersion': 'None', 'FirstIssueID': u'465841', 'ComicPublisher': u'Marvel', 'ComicYear': u'2014', 'ComicImageALT': u'https://comicvine.gamespot.com/api/image/scale_small/4103479-01.jpg', 'ComicURL': u'https://comicvine.gamespot.com/deadpool-biannual/4050-76981/', 'Type': 'Print', 'ComicImage': u'https://comicvine.gamespot.com/api/image/scale_large/4103479-01.jpg', 'Aliases': 'None'}
2017-07-05 08:30:01	DEBUG	comic[ComicVersion]:None
2017-07-05 08:30:01	DEBUG	vari is set to: no
2017-07-05 08:30:01	DEBUG	number of issues CV says it has: 1
2017-07-05 08:30:01	DEBUG	number of issues I counted: 1
2017-07-05 08:29:56	INFO	Attempting to add directly by ComicVineID: 76981
2017-07-05 08:29:41	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2017-07-05 08:29:41	WARNING	There were no files located - check the debugging logs if you think this is in error.
2017-07-05 08:29:41	INFO	there are 0 files.
2017-07-05 08:29:41	DEBUG	[POST-PROCESSING] Manual Run initiated
2017-07-05 08:29:41	DEBUG	[POST-PROCESSING] Not using SABnzbd : Manual Run
2017-07-05 08:29:41	DEBUG	[POST-PROCESSING] nzb folder: C:\Users\adamt\Desktop\look here for comics
2017-07-05 08:29:41	DEBUG	[POST-PROCESSING] nzb name: Manual Run
2017-07-05 08:29:41	INFO	[FOLDER-CHECK] Checking folder C:\Users\adamt\Desktop\look here for comics for newly snatched downloads
2017-07-05 08:29:36	INFO	Web logs cleared

**Comment by evilhero** [comment]
Is Z a mounted drive or something? It says in the log it can't even access Z to be able to create the directory to store the series. Mylar has to be able to access/write/delete to the location where you're storing your comics (Z)

**Comment by atytel** [comment]
It has untill today. So thats weird

**Comment by atytel** [comment]
changed to synthetic link and error still occurs

**Comment by evilhero** [comment]
Creating a symlink won't fix permission problems if that's what it is. Unless you're Z drive is in offline mode, it shouldn't have any problems connecting to it aside from permissions.

**Comment by atytel** [comment]
it has permissions so i dont understand why it is having trouble. Sonarr and radarr can write just fine

**Comment by evilhero** [comment]
Sonarr and radarr don't use python. Different beasts, and completely different programs. 

You haven't indicated what the Z drive is (ie. USB, network, etc), or what branch/commit you're even running of mylar. 

Try changing your comic location path in mylar to a location on the C drive, save the config and restart and then try again (if you want to rule out any sort of permissions, mapping problems with the Z drive)

**Comment by atytel** [comment]
It's a mapped Network drive. And I'll try changing the location. I'm on the most recent version
