### ISSUE TITLE
RSS check error - feed format changed again

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1677]
Not sure which provider. 

```
11-Jul-2017 11:25:48 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Check.
11-Jul-2017 11:25:48 - INFO    :: RSSCHECK : [RSS] Initiating Torrent RSS Feed Check on TorrentProject.
11-Jul-2017 11:25:52 - DEBUG   :: RSSCHECK : Exception generated in thread RSSCHECK: invalid literal for float(): 293.64 KB<br />
        <hr /><br />
        Virtual Super Hero Summer Camp for Children  5
11-Jul-2017 11:25:52 - DEBUG   :: RSSCHECK : 'Traceback (most recent call last):
  File "/opt/mylar/mylar/scheduler.py", line 78, in runAction
    self.action.run()
  File "/opt/mylar/mylar/rsscheckit.py", line 62, in run
    rsscheck.torrents(pickfeed=\'TPSE\')    #TPSE = DEM RSS Check + WWT RSS Check
  File "/opt/mylar/mylar/rsscheck.py", line 279, in torrents
    tsize = helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz))
  File "/opt/mylar/mylar/helpers.py", line 174, in human2bytes
    assert float(num) and letter in symbols
ValueError: invalid literal for float(): 293.64 KB<br />\n        <hr /><br />\n        Virtual Super Hero Summer Camp for Children  5\n'
```

**Comment by evilhero** [comment]
If you're on dev, make sure you're up to date as the fix for that was pushed yesterday (I think it was yesterday, it was pushed into dev tho). 

If you're on master, you'll have to wait for the merge to fix it - hoping to do it today pending the time to do it.

**Comment by barbequesauce** [comment]
I'm in dev and current...

```
Mylar Version: development
-- git build 442c3d936a781c379e4a8b882f36836a125c9e0e.
```

**Comment by evilhero** [comment]
Maybe it's because I'm on my phone and it's truncating, but that's not an up to date dev commit.

**Comment by barbequesauce** [comment]
After several rounds of git fetch / git reset / git shootme, it turned out to be a permissions issue within .git. 

I'm up to date now and the error has disappeared... sorry for the noise.

**Comment by evilhero** [comment]
No worries, and no noise - sometimes my stupid phone truncates the commit #''s and having to reference by copy & paste doesn't work when it does that to me (stupid technology).
