### ISSUE TITLE
NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1678]
hey, i'm still getting an error while searching for some comics.

the issue in question isnt available yet, so there is no response?

public torrents are disabled.

im on dev, latest version.

> 

2017-07-12 18:47:33 | ERROR | Uncaught exception: Traceback (most recent call last):File "D:\mylar\mylar\logger.py", line 158, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "D:\mylar\mylar\webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "D:\mylar\mylar\search.py", line 263, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)File "D:\mylar\mylar\search.py", line 858, in NZB_SEARCHdateconv2 = datetime.datetime(*dateconv[:6])TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
2017-07-12 18:47:33 | INFO | successfully retrieved 6 search results.
2017-07-12 18:47:32 | INFO | payload: {'action': 'groupsearch', 'issue': u'11', 'id': u'333'}
2017-07-12 18:47:32 | WARNING | Unable to properly verify reference on 32P - will update the 32P reference point once the issue has been successfully matched against.
2017-07-12 18:47:32 | INFO | 1 series match the title being search for
2017-07-12 18:47:32 | INFO | Exact series ID already discovered previously. Setting to :Supergirl[333]
2017-07-12 18:47:32 | INFO | publisher search set to : DC
2017-07-12 18:47:32 | INFO | Shhh be very quiet...I'm looking for Supergirl issue: 11 (2017) using 32P
2017-07-12 18:47:32 | INFO | Could not find Issue 11 of Supergirl (2016) using 32P [rss]
2017-07-12 18:47:32 | INFO | Shhh be very quiet...I'm looking for Supergirl issue: 11 (2017) using 32P [RSS]
2017-07-12 18:47:32 | INFO | search provider order is ['32p']
2017-07-12 18:47:32 | INFO | Issue Title given as : None
2017-07-12 18:47:32 | INFO | I Will assume IssueDate as Store Date, but you should probably Refresh the Series and try again if required.
2017-07-12 18:47:32 | INFO | No Store Date found for given issue. This is probably due to not Refreshing the Series beforehand.
2017-07-12 18:47:32 | INFO | Initiating manual search for Supergirl issue: 11
2017-07-12 18:47:29 | INFO | Web logs cleared

**Comment by HypKin** [comment]
its strange, it errors out on tpse even though that issue is available on 32p - it just doesnt find it...

log for action comics:

> 

2017-07-12 22:19:31 | ERROR | Uncaught exception: Traceback (most recent call last):File "D:\mylar\mylar\logger.py", line 158, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "D:\mylar\mylar\webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "D:\mylar\mylar\search.py", line 243, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff)File "D:\mylar\mylar\search.py", line 858, in NZB_SEARCHdateconv2 = datetime.datetime(*dateconv[:6])TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
2017-07-12 22:19:31 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 983 (2017) using TPSE [RSS]
2017-07-12 22:19:31 | INFO | Could not find Issue 983 of Action Comics (2016) using 32P [rss]
2017-07-12 22:19:31 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 983 (2017) using 32P [RSS]
2017-07-12 22:19:31 | INFO | search provider order is ['32p', 'tpse']
2017-07-12 22:19:31 | INFO | Issue Title given as : None
2017-07-12 22:19:31 | INFO | I Will assume IssueDate as Store Date, but you should probably Refresh the Series and try again if required.
2017-07-12 22:19:31 | INFO | No Store Date found for given issue. This is probably due to not Refreshing the Series beforehand.
2017-07-12 22:19:31 | INFO | Initiating manual search for Action Comics issue: 983


log after deactivating public search:

> 

2017-07-12 22:19:31 | ERROR | Uncaught exception: Traceback (most recent call last):File "D:\mylar\mylar\logger.py", line 158, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "D:\mylar\mylar\webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "D:\mylar\mylar\search.py", line 243, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff)File "D:\mylar\mylar\search.py", line 858, in NZB_SEARCHdateconv2 = datetime.datetime(*dateconv[:6])TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
2017-07-12 22:19:31 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 983 (2017) using TPSE [RSS]
2017-07-12 22:19:31 | INFO | Could not find Issue 983 of Action Comics (2016) using 32P [rss]
2017-07-12 22:19:31 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 983 (2017) using 32P [RSS]
2017-07-12 22:19:31 | INFO | search provider order is ['32p', 'tpse']
2017-07-12 22:19:31 | INFO | Issue Title given as : None
2017-07-12 22:19:31 | INFO | I Will assume IssueDate as Store Date, but you should probably Refresh the Series and try again if required.
2017-07-12 22:19:31 | INFO | No Store Date found for given issue. This is probably due to not Refreshing the Series beforehand.
2017-07-12 22:19:31 | INFO | Initiating manual search for Action Comics issue: 983

**Comment by evilhero** [comment]
You need to restart Mylar if you're enabling / disabling providers as the provider_order doesn't get changed until startup so it's probably thinking it's still active otherwise (when it isn't).

As far as the 32P error, I can confirm that it's still erroring out - albeit for a different reason than for what the fix went in for. In your case, because you're running a non-english windows machine, when it converts the upload time of the issue from 32p to a long date format it uses your system language (which is fine). But then when it goes to the next step and actually compares the long date format of the upload to the issue date, it can only convert english weekdays and it's erroring out on that :)  (Who knew?)

Needless to say, I've been workin on this one for a little bit today and think I have it figured out and am just testing out the process to make sure it's working in both the original format and the non-english formats before I commit it up for usage.

**Comment by HypKin** [comment]
its working now!

thank you!
