### ISSUE TITLE
Can't download results

### ISSUE THREAD

**Issue by brdshw** [evilhero/mylar#1695]
I just set up a new mylar install and am having issues retrieving. Mylar finds a result in my torznab, but gives the following errors when trying to download.
`

2017-08-10 15:05:43 | ERROR | Uncaught exception: Traceback (most recent call last):File "/opt/mylar/mylar/logger.py", line 165, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/opt/mylar/mylar/webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "/opt/mylar/mylar/search.py", line 263, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)File "/opt/mylar/mylar/search.py", line 1626, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)File "/opt/mylar/mylar/search.py", line 2266, in searcherrcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)File "/opt/mylar/mylar/rsscheck.py", line 1028, in torsend2clientlogger.info('blah: ' + str(r.status_code))UnboundLocalError: local variable 'r' referenced before assignment
-- | -- | --
2017-08-10 15:05:43 | WARNING | Error fetching data from Torznab (magnet:?xt=urn:btih:8d63222c839a7a303e4dd4093f2f34e331de5d43&dn=the+walking+dead+168+(zone)&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969): No connection adapters were found for 'magnet:?xt=urn:btih:8d63222c839a7a303e4dd4093f2f34e331de5d43&dn=the+walking+dead+168+(zone)&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969'
2017-08-10 15:05:43 | INFO | matched on The Walking Dead
2017-08-10 15:05:43 | INFO | Found The Walking Dead (2017) issue: 168 using Torznab
2017-08-10 15:05:43 | INFO | entry: {'updated': u'Mon, 12 Jun 2017 00:21:00 -0500', 'updated_parsed': time.struct_time(tm_year=2017, tm_mon=6, tm_mday=12, tm_hour=5, tm_min=21, tm_sec=0, tm_wday=0, tm_yday=163, tm_isdst=0), 'links': [{'href': u'magnet:?xt=urn:btih:8d63222c839a7a303e4dd4093f2f34e331de5d43&dn=the+walking+dead+168+(zone)&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969', 'type': 'text/html', 'rel': 'alternate'}, {'length': u'42844816', 'href': u'magnet:?xt=urn:btih:8d63222c839a7a303e4dd4093f2f34e331de5d43&dn=the+walking+dead+168+(zone)&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969', 'type': u'application/x-bittorrent', 'rel': 'enclosure'}], 'title': u'the walking dead 168 (zone)', 'tags': [{'term': u'8020', 'scheme': None, 'label': None}, {'term': u'100602', 'scheme': None, 'label': None}], 'summary_detail': {'base': u'', 'type': 'text/html', 'value': u'', 'language': None}, 'comments': u'https://thepiratebay.org/torrent/17901884/the_walking_dead_168_(zone)', 'summary': u'', 'guidislink': True, 'title_detail': {'base': u'', 'type': 'text/plain', 'value': u'the walking dead 168 (zone)', 'language': None}, 'link': u'magnet:?xt=urn:btih:8d63222c839a7a303e4dd4093f2f34e331de5d43&dn=the+walking+dead+168+(zone)&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969', u'torznab_attr': {'name': u'uploadvolumefactor', 'value': u'1'}, 'id': u'https://thepiratebay.org/torrent/17901884/the_walking_dead_168_(zone)', 'size': u'42844816'}

`

**Comment by evilhero** [comment]
As it stands at the moment, only magnents links used by the TPSE option are working (since torrentproject went to that). I honestly didn't even think of trying with torznab, but it makes sense to some degree as an edge of use case.

You would have much, much better results just using the TPSE option within Mylar as that hits torrentproject, demonoid and worldwidetorrents for public torrent usage. PirateBay is actually pretty useless as far as comics go as it tends to only get the occassional TWD issue, and some odd packs at random intervals.

**Comment by GaitherStephens** [comment]
Any further development on this?  I don't get any luck with TPSE so I would prefer to grab issues using Torznab.  It works great for Headphones, Radarr, and Sonarr.

**Comment by evilhero** [comment]
Nope. Tpb isn't supported as it only returns magnets, plus it doesn't carry enough comics to warrant using.

Try another tracker that actually has comics, and don't use TPB for mylar. There are only a handful of trackers that actually carry comics that are named somewhat normally.

Please don't spam 3 different threads (1 here, 2 on forums) with the same question. Once is more than enough to get attention - responses aren't instant as I don't sit there waiting impatiently for someone to say something isn't working so I can immediately respond. When I see 3 threads by the same individual about the same topic, I usually take 3x as long to respond ;)

TPSE has been shutdown, only demonoid and wwt work within mylar and both rely on RSS feeds so if you're not running mylar when the issue hits, you'll never get it. WWT search support should be in next dev commit (or use jackett for that apparently, just found that out).
