### ISSUE TITLE
Issues with 32p search

### ISSUE THREAD

**Issue by Baldrdk** [evilhero/mylar#1697]
Im getting a wierd respons when using 32p search. When running the test below the setup, i get an ok.

Log:

2017-08-14 21:40:17 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\ProgramData\mylar\mylar\logger.py", line 165, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "C:\ProgramData\mylar\mylar\webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "C:\ProgramData\mylar\mylar\search.py", line 263, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)File "C:\ProgramData\mylar\mylar\search.py", line 554, in NZB_SEARCHa = auth32p.info32p(searchterm=searchterm)TypeError: __init__() should return None, not 'str'
-- | -- | --
2017-08-14 21:40:17 | ERROR | [32P-AUTHENTICATION] [LOGIN FAILED] Disabling 32P provider until login error(s) can be fixed in order to avoid temporary bans.
2017-08-14 21:40:17 | WARNING | [32P-AUTHENTICATION] Both session key and credential-based logins failed.
2017-08-14 21:40:16 | ERROR | [32P-AUTHENTICATION] The data returned by the login page was not JSON:

**Comment by evilhero** [comment]
Did you save the config after you did the test ? Or has your password changed on 32p recently? 
You can't use a VPN when using the auth mode of Mylar (since it signs on using your credentials), but it stores the credentials in a file in the cache folder called `.32p_cookies.dat`. 

If you can browse to the 32p web page from the same machine running Mylar and see if you have a captcha present. If no captcha is present, then with Mylar not running, delete the .32p_cookies.dat file, start it up and see if that helps at all.

Note that if you browse to the 32p site and get either a captcha or saying temp ban due to invalid logins - you have to wait for either/both to clear (the captcha is dependent on the site, the temp ban is like 6 hrs I think).

**Comment by Baldrdk** [comment]
Deleting the cookie file seems to have worked. 
Thank you

**Comment by Baldrdk** [comment]
Woops to earrly its back.
Its kind of wierd because it allso f's up the log view, with some leftovers from the 32p homepage
![image](https://user-images.githubusercontent.com/28227375/29289576-3fd041e8-813d-11e7-94b4-8e7164b56ae0.png)

This only happens when i have 32p searcher enabled. 
?

**Comment by evilhero** [comment]
Try deleting all the .pyc files within the mylar subdirectory (with Mylar not running), and then start it up do a test connection to make sure it works, and then try a search again. 

When you enable /disable providers as  search options, you need to save the config and restart Mylar every time so that Mylar can regenerate the search provider order or else it will try to search against things that aren't enabled and vice-versa.

As far as the graphic, that's weird - I've never seen that happen. I would either restart your browser, or even your machine cause that's really messed up (Mylar has no control over the background other than the css, it's being superimposed by the OS in this case, as it's just a blank css page that's not being overlayed properly for whatever reason).

**Comment by Baldrdk** [comment]
Looks like that the problem is a banned ip, It was hiding further down in the log. 
My browser access to 32p is fine, so i didnt think that was the problem. I have contacted them.
The wierd log view only happens in chrome, so it is properbly a cache thing.
Tanks for your help.

**Comment by thingdeux** [comment]
@Baldrdk - Please close / resolve this issue if satisfied.
