### ISSUE TITLE
Mylar not starting up

### ISSUE THREAD

**Issue by Vuzrak** [evilhero/mylar#1717]
I'm running Mylar on Ubuntu, and I'm getting this error when trying to start it up:

Traceback (most recent call last):
  File "./Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar/mylar/__init__.py", line 41, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "/opt/mylar/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/opt/mylar/mylar/rsscheck.py", line 17, in <module>
    from mylar import db, logger, ftpsshup, helpers, auth32p, utorrent
  File "/opt/mylar/mylar/auth32p.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/opt/mylar/bs4/__init__.py", line 29, in <module>

  File "/opt/mylar/bs4/builder/__init__.py", line 306, in <module>

  File "/opt/mylar/bs4/builder/_html5lib.py", line 57, in <module>
AttributeError: 'module' object has no attribute '_base'

**Comment by evilhero** [comment]
Which version of python are you running mylar against?

**Comment by Vuzrak** [comment]
2.7.14

**Comment by evilhero** [comment]
The bs4 directory should be in the lib directory, not in the root of mylar. 

This changed awhile ago, so I'm surprised that you're encountering this now - has it been awhile since you updated?

Easy fix - Delete the entire bs4 folder from your /opt/mylar location, but first make sure that a bs4 directory exists in /opt/mylar/lib

**Comment by Vuzrak** [comment]
Yup it's been awhile since I updated it.

That fixed it, thanks for the quick fix.
