### ISSUE TITLE
issue when adding series

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1736]
ive been getting this error when i try to add certain series, so far the amazing spider-man (1963) and justice league (2006). any ideas? what other info can i give? it adds the series page but with no issues and ive noticed that there is no volume in the edit settings tab of the series.

WARNING | [FILE-RESCAN] you should either Refresh the series, and/or submit an issue on github in regards to the series and the error.

2017-09-29 01:41:13 | WARNING | [FILE-RESCAN] An error occured trying to get the relevant issue data. This is probably due to the series not having proper issue data.
2017-09-29 01:41:13 | DEBUG | [FILE-RESCAN] temploc: 001
2017-09-29 01:41:13 | DEBUG | No issues with identical issue numbering were detected for this series
2017-09-29 01:41:13 | DEBUG | [MATCH: The Amazing Spider-Man] The Amazing Spider-Man 700.5 (2014).cbz
2017-09-29 01:41:13 | DEBUG | Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
2017-09-29 01:41:13 | INFO | Series_Name: The Amazing Spider-Man --- WatchComic: The Amazing Spider-Man
2017-09-29 01:41:13 | DEBUG | series title possibly: The Amazing Spider-Man
2017-09-29 01:41:13 | DEBUG | issue verified as : 700.5
2017-09-29 01:41:13 | DEBUG | issue_position: 3
2017-09-29 01:41:13 | DEBUG | possible_issuenumbers: [{'position': 3, 'validcountchk': False, 'number': '700.5', 'mod_position': 23}]
2017-09-29 01:41:13 | DEBUG | highest_series_position: 4
2017-09-29 01:41:13 | DEBUG | year verified as: 2014
2017-09-29 01:41:13 | DEBUG | year verified as : 2014
2017-09-29 01:41:13 | DEBUG | sctd: 2017
2017-09-29 01:41:13 | DEBUG | datecheck: [{'date': '2014', 'position': 4, 'mod_position': 29}]
2017-09-29 01:41:13 | DEBUG | date: 2014
2017-09-29 01:41:13 | DEBUG | checking date : 2014
2017-09-29 01:41:13 | DEBUG | I have encountered a decimal issue #: 700.5
2017-09-29 01:41:13 | INFO | [FILENAME]: The Amazing Spider-Man 700.5 (2014).cbz

and once its been added when i try to refresh the series i get the below.

2017-09-29 12:14:12	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Users\Jimmy\Documents\mylar\mylar\logger.py", line 165, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Users\Jimmy\Documents\mylar\mylar\updater.py", line 321, in dbUpdate
chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
File "C:\Users\Jimmy\Documents\mylar\mylar\importer.py", line 431, in addComictoDB
issue_collection(issuedata, nostatus='False')
File "C:\Users\Jimmy\Documents\mylar\mylar\importer.py", line 975, in issue_collection
datechk = datetime.datetime.strptime(dk, "%Y%m%d")
File "C:\Python27\lib\_strptime.py", line 325, in _strptime
(data_string, format))
ValueError: time data '00000000' does not match format '%Y%m%d'
2017-09-29 12:14:12	INFO	Now adding/updating issues for Justice Society of America
2017-09-29 12:14:08	INFO	Sucessfully retrieved issue details for Justice Society of America
2017-09-29 12:14:02	INFO	Attempting to retrieve the comic image for series
2017-09-29 12:14:00	INFO	Directory (D:\Comics\DC Comics\Justice Society of America (V2007)) already exists! Continuing...
2017-09-29 12:14:00	INFO	Previous version detected as None - seeing if update required
2017-09-29 12:14:00	INFO	Sucessfully retrieved details for Justice Society of America
2017-09-29 12:14:00	INFO	Now adding/updating: Justice Society of America
2017-09-29 12:13:57	INFO	[DIRECTORY-CHECK] Found comic directory: D:\Comics\DC Comics\Justice Society of America (V2007)
2017-09-29 12:13:57	INFO	Starting update for 1 active comics

I'm on the most recent Development commit using github desktop to update Mylar on windows 10.

**Comment by jimbojnr81** [comment]
sorry its seems to have cut off my log paste. here's the 2 error messages again


WARNING | [FILE-RESCAN] you should either Refresh the series, and/or submit an issue on github in regards to the series and the error.
--
2017-09-29 01:51:38 | WARNING | [FILE-RESCAN] An error occured trying to get the relevant issue data. This is probably due to the series not having proper issue data.

**Comment by jimbojnr81** [comment]
it might be worth noting that when i switch back to the master branch everything works fine adding the same series with no issue.

**Comment by evilhero** [comment]
Should all be fixed now in the most recent dev commit that went up just a little bit ago.

If you're still having problems, please let me know as this bug has taken an unreal amount of time to track down properly, and I'm totally unsure if it's fixed (I mean I hope and I tested, but this one keeps coming back to haunt me)

**Comment by jimbojnr81** [comment]
I'm all up to date with commits and there's no change, same trace back error when adding or refreshing these series.

**Comment by evilhero** [comment]
Forgot about the importer module when I did the date/time fix. 

Tested against JLA adding and it worked with no errors, so I'm guessing it should be good for you now in the latest dev commit now up.

**Comment by jimbojnr81** [comment]
updated and working perfect. thank you so much for pushing that through so quick! You are the best!

**Comment by jimbojnr81** [comment]
damnit, spoke to soon. The issues is was trying before are working but i've just tried to add a series that i hadn't tried before and its a similar issue, not adding the issues, but also stuck in a constant refresh status (see pics below). 

![image](https://user-images.githubusercontent.com/5010165/31001033-e5617028-a523-11e7-9504-f57d85b1c557.png)
![image](https://user-images.githubusercontent.com/5010165/31001044-face3da6-a523-11e7-8d76-c8befb1b053d.png)

Error looks the same/similar to me

2017-09-29 14:35:34 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Users\Jimmy\Documents\mylar\mylar\logger.py", line 165, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Users\Jimmy\Documents\mylar\mylar\importer.py", line 421, in addComictoDBupdateddata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)File "C:\Users\Jimmy\Documents\mylar\mylar\importer.py", line 1110, in updateissuedataannualchk = annual_check(comicname, SeriesYear, comicid, issuetype, issuechk, annualchk)File "C:\Users\Jimmy\Documents\mylar\mylar\importer.py", line 1501, in annual_checkif firstval['ReleaseDate'] == '00000000':KeyError: 'ReleaseDate'

**Comment by evilhero** [comment]
Heh, that was a typo on my part - I was cutting & pasting and because I have annual integration enabled it never triggered that part of the module during my testing. Changed and updated in the latest dev build now, so you should be good to go from here ;)

**Comment by jimbojnr81** [comment]
awesome! yep working now, thank you!
