### ISSUE TITLE
Story Arc trace back Error

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1739]
Im getting a traceback error when adding or refreshing certain Story Arcs.

this is the error i get when trying to refresh Secret Wars (2014) 

2017-10-03 12:57:38 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Users\Jimmy\Documents\mylar\mylar\logger.py", line 165, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Users\Jimmy\Documents\mylar\mylar\webserve.py", line 576, in addStoryArcself.ArcWatchlist(storyarcid)File "C:\Users\Jimmy\Documents\mylar\mylar\webserve.py", line 2990, in ArcWatchlistlogger.fdebug("issue #: " + str(arc['IssueNumber']) + " is present!")UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 0: ordinal not in range(128)

2017-10-03 12:57:38 | DEBUG | ARC-seriesyear: 2015
2017-10-03 12:57:38 | DEBUG | COMIC-comicyear: 2015
2017-10-03 12:57:38 | DEBUG | int_issue = 500.0
2017-10-03 12:57:38 | DEBUG | initial name match - confirming issue # is present in series
2017-10-03 12:57:38 | DEBUG | [Secret Wars] Secret Wars: Armor Wars : ½

Im also getting the same/similar error when trying to add the Secret Wars: Battleworld (2015) Story Arc

**Comment by evilhero** [comment]
It shouldn't be putting a str on the issue number, which is why the logger is having problems writing it.

I'll try and get a fix out momentarily for it...
