### ISSUE TITLE
UnboundLocalError: local variable 'nzbid' referenced before assignment

### ISSUE THREAD

**Issue by numkem** [evilhero/mylar#1745]
This exception shows up on the master branch.

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 165, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/webserve.py", line 1202, in retryissue
sendit = search.searcher(fullprov, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
File "/app/mylar/mylar/search.py", line 2020, in searcher
nzbid = generate_id(nzbprov, link)
File "/app/mylar/mylar/search.py", line 2804, in generate_id
return nzbid
UnboundLocalError: local variable 'nzbid' referenced before assignment
```

**Comment by evilhero** [comment]
I need to see the debug lines leading up to the error - pasting the log without any references to the data being used makes it impossible to properly debug.

**Comment by numkem** [comment]
Of course, my bad:

```
2017-10-18 09:20:28 | INFO | link : https://api.nzbgeek.info/getnzb/e6b23cccb4b0293d0a3907ab61355d0b.nzb&i=7030&r=9dd85a8a0dea99d254363f4e7b2124bd
-- | -- | --
2017-10-18 09:20:28 | INFO | newznab detected as : Nzbgeek @ https://api.nzbgeek.info/
2017-10-18 09:20:28 | INFO | fetched via newnzab. Retrying the send.
2017-10-18 09:20:28 | INFO | --Referencing : newznab @ 2017-10-09 10:15:00
2017-10-18 09:20:28 | INFO | Located snatched download:
2017-10-18 09:20:28 | INFO | Retrying : 357671
2017-10-18 09:20:28 | INFO | ComicID:42972
```

**Comment by evilhero** [comment]
Is your master up-to-date ? 

This should have all been fixed when dev merged into master last week. 

Also, please enable the debug mode (logs tab, toggle verbose on, then do a 'retry' again in order to get the debug log lines for the retry). I can't tell for sure but either the snatch you're trying to retrieve is invalid for some reason, or it's possible it was not written to the db - but the debug logs might help (and  knowing you're running a current version of Mylar)

**Comment by numkem** [comment]
I looked into the container and I'm running the latest master.

I'll do some more digging and I'll come back if I find anything else more substantial. Could this happen in the case of a incomplete or corrupted nzb?

Thanks!

**Comment by evilhero** [comment]
It shouldn't happen with a corrupted nzb/incomplete unless the given nzbid has been removed from the indexer. The retry option got a bit of a code update on this last master merge, and some of the tables got restructured to accommodate some new fields - it might be just that the information is missing that  Mylar is now looking for. So going forward, it might not occur - but older snatches that you're attempting to retry prior to the update might throw this error.

I'll see if I can look into it abit and figure out what's happening, but if it's like I mentioned above it might be abit difficult to pinpoint exactly - but I'll look into it more regardless....
