### ISSUE TITLE
'pp_crclist' is not defined

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1794]
Running current development branch.

```
02-Dec-2017 10:20:11 - INFO :: CP Server Thread-4 : Starting postprocessing for : Manual Run
02-Dec-2017 10:20:11 - DEBUG :: Thread-37 : [POST-PROCESSING] nzb name: Manual Run
02-Dec-2017 10:20:11 - DEBUG :: Thread-37 : [POST-PROCESSING] nzb folder: /mnt/skytopcliff/completed
02-Dec-2017 10:20:11 - DEBUG :: Thread-37 : [POST-PROCESSING] Not using SABnzbd
02-Dec-2017 10:20:11 - DEBUG :: Thread-37 : [POST-PROCESSING] Manual Run Post-Processing enabled.
02-Dec-2017 10:20:11 - DEBUG :: Thread-37 : [POST-PROCESSING] Manual Run initiated
02-Dec-2017 10:20:11 - ERROR :: Thread-37 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/PostProcessor.py", line 317, in Process
    filelist = flc.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 130, in listFiles
    filelist = self.traverse_directories(self.dir)
  File "/opt/mylar/mylar/filechecker.py", line 1130, in traverse_directories
    pp_crclist.append({'IssueID':   pp['IssueID'],
NameError: global name 'pp_crclist' is not defined

Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/PostProcessor.py", line 317, in Process
    filelist = flc.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 130, in listFiles
    filelist = self.traverse_directories(self.dir)
  File "/opt/mylar/mylar/filechecker.py", line 1130, in traverse_directories
    pp_crclist.append({'IssueID':   pp['IssueID'],
NameError: global name 'pp_crclist' is not defined
```

**Comment by evilhero** [comment]
Crap I forgot to initialize the pp_crclist variable. I'm out atm, will do it asap.

**Comment by barbequesauce** [comment]
Thank you sir!
