### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Neonsa** [evilhero/mylar#1796]
Hi I seem to get the following when running a mass import.
`04-Dec-2017 12:10:32 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\webserve.py", line 4034, in preSearchit
    myDB.upsert("searchresults", nVal, cVal)
  File "C:\Mylar\mylar\db.py", line 170, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "C:\Mylar\mylar\db.py", line 129, in action
    sqlResult = self.connection.execute(query, args)
InterfaceError: Error binding parameter 9 - probably unsupported type.

Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\webserve.py", line 4034, in preSearchit
    myDB.upsert("searchresults", nVal, cVal)
  File "C:\Mylar\mylar\db.py", line 170, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "C:\Mylar\mylar\db.py", line 129, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.InterfaceError: Error binding parameter 9 - probably unsupported type.`

any ideas?

**Comment by evilhero** [comment]
I'm not even sure which branch you're running on atm - which might help pinpoint things (making sure you're up-to-date on whatever branch you're running).

Otherwise, generally speaking it - it looks like it's trying to put an unsupported character into the db when returning the results for the import. This might have to do with the filename, and/or one of the results it's trying to save since it looks like it might have returned more than one result when trying to import.

If you put Mylar into verbose mode (-v on startup, or go into the Logs tab and toggle the Verbose ON button in the upper right corner), and then run the import again if you can - then paste in the debug log showing the leadup to the error - it would help me try to figure out exactly where it's erroring out.

**Comment by Neonsa** [comment]
Sorry the branch version is: 25aa51fc90c388ed056791d7a87b8bc0413e627a (development)

And heres the log


2017-12-08 12:34:02 | INFO | Update complete
-- | -- | --
2017-12-08 12:34:02 | DEBUG | ReScheduled job: DB Updater to 2017-12-08 01:39:02
2017-12-08 12:34:02 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2017-12-08 12:33:49 | INFO | pausing for 60 seconds before continuing to avoid hammering
2017-12-08 12:33:49 | INFO | no errors on data retrieval...proceeding
2017-12-08 12:33:46 | DEBUG | [SSL: True] Search URL: https://omgwtfnzbs.me/api?t=search&q=batgirl%20birds%20of%20prey%2009&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2017-12-08 12:33:39 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 4034, in preSearchitmyDB.upsert("searchresults", nVal, cVal)File "C:\Mylar\mylar\db.py", line 170, in upsertself.action(query, valueDict.values() + keyDict.values())File "C:\Mylar\mylar\db.py", line 129, in actionsqlResult = self.connection.execute(query, args)InterfaceError: Error binding parameter 9 - probably unsupported type.
2017-12-08 12:33:39 | INFO | There is only one result...automagik-mode enabled for Bane: Conquest :: 101164
2017-12-08 12:33:39 | INFO | [IMPORT MATCH] Bane\|Conquest (101164)
2017-12-08 12:33:39 | INFO | LastIssueID: 101164
2017-12-08 12:33:39 | DEBUG | [2017] Comparing: baneconquest - TO - baneconquest
2017-12-08 12:33:39 | DEBUG | [1] search results
2017-12-08 12:33:39 | DEBUG | [RESULT][['2018', '2017']] ComicName:Bane: Conquest -- 2017 [Series years: [u'2017']]
2017-12-08 12:33:39 | DEBUG | there are 1 search results...
2017-12-08 12:33:32 | DEBUG | comicname : Bane - Conquest
2017-12-08 12:33:32 | DEBUG | displaycomic : Bane Conquest
2017-12-08 12:33:32 | INFO | numissues: 3
2017-12-08 12:33:32 | INFO | there
2017-12-08 12:33:32 | INFO | 7000
2017-12-08 12:33:32 | INFO | yearRANGE: ['2017', '2018']
2017-12-08 12:33:32 | INFO | yearTOP: 2018
2017-12-08 12:33:32 | INFO | [none] volume: None
2017-12-08 12:33:32 | INFO | [none] dynamicname: baneconquest
2017-12-08 12:33:32 | INFO | [Bane - Conquest] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2017-12-08 12:33:32 | DEBUG | dyn: baneconquest

**Comment by evilhero** [comment]
Ok, so it's definitely failing on the import - which might have to do with some of the recent changes to the filechecker.

Would you be able to provide the filenames for Bane Conquest, as that's what seems to be throwing the error above?

**Comment by Neonsa** [comment]
Here are the files it's trying to import
Bane Conquest 7 (2018).cbr
Bane Conquest 6 (2017).cbr
Bane Conquest 5 (2017).cbr
Bane - Conquest 05 (of 12) (2017) (Digital) (Zone-Empire).cbr
Bane - Conquest 06 (of 12) (2017) (Digital) (Zone-Empire).cbr
Bane - Conquest 07 (of 12) (2018) (Digital) (Zone-Empire).cbr

**Comment by evilhero** [comment]
That's weird - I just mocked up those filenames and did an import. It picked them up fine, and did the auto-import and then snatched the most recent issue as it was on this week's pull. There was an issue with moving that occurred, mainly due to the folder names not being present, which I'll fix - but otherwise, they imported the data just fine with no errors.

Can you update your Mylar to the most recent ? There were a few fixes that went in just as of yesterday that fixed some file scanning issues - as of this point, I can't replicate the error on a up-to-date version of Mylar (running Ubuntu, but will try Windows next)

**Comment by Neonsa** [comment]
I've updated to the latest and I get the following after freshly starting Mylar


2017-12-09 16:59:24 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 4074, in preSearchitmyDB.upsert("searchresults", nVal, cVal)File "C:\Mylar\mylar\db.py", line 170, in upsertself.action(query, valueDict.values() + keyDict.values())File "C:\Mylar\mylar\db.py", line 129, in actionsqlResult = self.connection.execute(query, args)InterfaceError: Error binding parameter 9 - probably unsupported type.
-- | -- | --
2017-12-09 16:59:24 | INFO | [IMPORT] There is only one result...automagik-mode enabled for Aquaman :: 91738
2017-12-09 16:59:16 | INFO | [IMPORT][Aquaman] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2017-12-09 16:59:16 | INFO | 107 series will be attempted to be imported.
2017-12-09 16:59:16 | INFO | Initiating mass import.
2017-12-09 16:55:52 | INFO | Background Schedulers successfully started...
2017-12-09 16:55:52 | INFO | Firing up the Background Schedulers now....
2017-12-09 16:55:52 | INFO | [FOLDER MONITOR] Enabling folder monitor for : \\nas\downloads\complete every 5 minutes.
2017-12-09 16:55:52 | INFO | [RSS-FEEDS] RSS last run @ 2017-12-09 05:55:21.044000
2017-12-09 16:55:52 | INFO | [RSS-FEEDS] Initiating startup-RSS feed checks.
2017-12-09 16:55:52 | INFO | [WEEKLY] Checking for existance of Weekly Comic listing...
2017-12-09 16:55:51 | INFO | Starting Mylar on http://0.0.0.0:8090/

**Comment by evilhero** [comment]
Start up mylar with the -v option, then do an import but don't use the mass import button, instead just select the particular series that's throwing the error, and try to import that. 

If it works then it's a problem with multiple imports, otherwise if it doesn't work find the mylar.log file in the logs directory and pastebin the log in here so I can see what's happening (the GUI log is nice for GUI stuff, but for troubleshooting it ca  get out of sequence)

**Comment by Neonsa** [comment]
ok so it appears to work doing it one at a time, or selecting the boxes and choosing start import from drop down

**Comment by evilhero** [comment]
Aights that's what I wanted to know - thanks for reporting back.

Now that I know where the problem lies, I hopefully can get a fix out sooner rather than later.

**Comment by Neonsa** [comment]
Maybe I spoke to to soon, this just happened when doing a fresh import selecting all issues and choosing start import from drop down


Timestamp | Level | Message
-- | -- | --
2017-12-11 18:55:04 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 4074, in preSearchitmyDB.upsert("searchresults", nVal, cVal)File "C:\Mylar\mylar\db.py", line 170, in upsertself.action(query, valueDict.values() + keyDict.values())File "C:\Mylar\mylar\db.py", line 129, in actionsqlResult = self.connection.execute(query, args)InterfaceError: Error binding parameter 9 - probably unsupported type.
2017-12-11 18:55:04 | INFO | [IMPORT] There is only one result...automagik-mode enabled for Batman and Harley Quinn :: 105491
2017-12-11 18:55:04 | DEBUG | [IMPORT MATCH] Batman\|HarleyQuinn (105491)
2017-12-11 18:55:04 | DEBUG | [IMPORT] LastIssueID: 105491
2017-12-11 18:55:04 | DEBUG | [IMPORT] [2017] Comparing: batmanharleyquinn - TO - batmanharleyquinn
2017-12-11 18:55:04 | DEBUG | [IMPORT] LastIssueID: 103215
2017-12-11 18:55:04 | DEBUG | [IMPORT] [2017] Comparing: batmanharleyquinn - TO - harleyquinnbatman
2017-12-11 18:55:04 | DEBUG | [IMPORT] [2] search results
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Batman and Harley Quinn -- 2017 [Series years: [u'2017']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Harley Quinn and Batman -- 2017 [Series years: [u'2017']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Coloring DC: Harley Quinn in Batman Adventures: Mad Love -- 2016 [Series years: [u'2016']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Batman: Arkham Knight: Batgirl/Harley Quinn -- 2016 [Series years: [u'2016']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Batman: Arkham Knight: Batgirl & Harley Quinn Special -- 2015 [Series years: [u'2015']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Batman: Harley Quinn -- 2015 [Series years: [u'2015']]
2017-12-11 18:55:04 | DEBUG | [RESULT][['2017']] ComicName:Batman: Harley Quinn -- 1999 [Series years: [u'1999']]
2017-12-11 18:55:04 | DEBUG | there are 7 search results...
2017-12-11 18:55:01 | INFO | pausing for 60 seconds before continuing to avoid hammering
2017-12-11 18:55:01 | DEBUG | calpha/cnumber: None / None
2017-12-11 18:55:01 | INFO | Shhh be very quiet...I'm looking for Justice League issue: 34 (2018) using OMGWTF (newznab)
2017-12-11 18:55:01 | DEBUG | using Newznab host of : OMGWTF
2017-12-11 18:55:01 | INFO | Could not find Issue 34 of Justice League (2016) using TPSE [api]
2017-12-11 18:55:01 | DEBUG | Sending request to [TPSE] for justice league : 34
2017-12-11 18:55:01 | DEBUG | Sending request to [TPSE] for justice league : 034
2017-12-11 18:55:01 | DEBUG | calpha/cnumber: None / None
2017-12-11 18:55:01 | INFO | Shhh be very quiet...I'm looking for Justice League issue: 34 (2018) using TPSE

**Comment by evilhero** [comment]
Ok, after some testing I figured out what the possible problem could be - at least from my test runs. 

It would appear that if you were doing a mass import of quite a few series, it would fire off several threads that would attempt to import a series per thread (so if you had like 20 series that were auto-detected, it would simultaneously almost run 20 separate threads to import them), which wouldn't result in db locking - but at the same time it would also be performing additional queries to any series it wasn't able to garner metadata from - which would cause db locks due to the inability to write. 

Out of curiosity, how many series are you attempting to import ?

I'll try and get this out in abit so you can test things on your end and see if this is fixed now...

**Comment by Neonsa** [comment]
exact number not sure but definately 10+

**Comment by Neonsa** [comment]
So i've installed the new commit, I'm using the mass import button and it appears to be importing without the error coming up. i have noticed however it goes through and imports roughly 8 series, then will go back and run a check for series then not continue importing.
For testing purposes, i removed all series from mylar and rescanned my comic directory. It's certainly going smoother than it was previously.

**Comment by Neonsa** [comment]
May have spoken slightly to soon. Got this. but I believe its different to the last one. 

2017-12-12 22:51:53 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 3922, in preSearchitsresults = mb.findComic(searchterm, mode, issue=numissues, limityear=yearRANGE) #ogcname, mode, issue=numissues, limityear=yearRANGE, explicit='all') #ComicName, mode, issue=numissues, limityear=yearRANGE)File "C:\Mylar\mylar\mb.py", line 117, in findComicsearched = pullsearch(comicapi, comicquery, 0, type)File "C:\Mylar\mylar\mb.py", line 57, in pullsearchPULLURL = mylar.CVURL + str(type) + 's?api_key=' + str(comicapi) + '&filter=name:' + filterline + '&field_list=id,name,start_year,site_detail_url,count_of_issues,image,publisher,deck,description,first_issue,last_issue&format=xml&offset=' + str(offset) # 2012/22/02 - CVAPI flipped back to offset instead of pageUnboundLocalError: local variable 'filterline' referenced before assignment
-- | -- | --
2017-12-12 22:51:53 | DEBUG | [IMPORT] comicname : Harley & Ivy Meet Betty & Veronica
2017-12-12 22:51:53 | DEBUG | [IMPORT] displaycomic : Harley & Ivy Meet Betty & Veronica
2017-12-12 22:51:53 | DEBUG | [IMPORT] number of issues: 1
2017-12-12 22:51:53 | DEBUG | [IMPORT] yearRANGE: ['2018']
2017-12-12 22:51:53 | DEBUG | [IMPORT] yearTOP: 2018
2017-12-12 22:51:53 | DEBUG | [IMPORT] [none] volume: None
2017-12-12 22:51:53 | DEBUG | [IMPORT] [none] dynamicname: harleyivymeetbettyveronica
2017-12-12 22:51:53 | INFO | [IMPORT][Harley & Ivy Meet Betty & Veronica] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.

**Comment by evilhero** [comment]
Yep different error, but related to the search not retrieving results for some reason. At least knowing the series that's problematic, I can try to figure things out from there - thanks for the detailed log/solution ;)

**Comment by Neonsa** [comment]
If it helps compare, here's another.


2017-12-13 14:12:41 | INFO | pausing for 60 seconds before continuing to avoid hammering
-- | -- | --
2017-12-13 14:12:41 | INFO | no errors on data retrieval...proceeding
2017-12-13 14:12:40 | DEBUG | [SSL: False] Search URL: https://nzb.cat/api?t=search&q=batwoman%20003&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2017-12-13 14:12:25 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 4117, in preSearchitself.addbyid(sr['comicid'], calledby=True, imported=imported, ogcname=ogcname, nothread=True)File "C:\Mylar\mylar\webserve.py", line 384, in addbyidreturn importer.addComictoDB(comicid, mismatch, None, imported, ogcname)File "C:\Mylar\mylar\importer.py", line 463, in addComictoDBmoveit.movefiles(comicid, comlocation, imported)File "C:\Mylar\mylar\moveit.py", line 37, in movefilesnfilename = renameit['nfilename']TypeError: 'NoneType' object has no attribute '__getitem__'
2017-12-13 14:12:25 | ERROR | Invalid Issue_Number - please validate.
2017-12-13 14:12:25 | DEBUG | annualize is None
2017-12-13 14:12:24 | DEBUG | issueid:None
2017-12-13 14:12:24 | DEBUG | issue# as per cv: 017
2017-12-13 14:12:24 | DEBUG | comicid: 98534
2017-12-13 14:12:24 | DEBUG |  
2017-12-13 14:12:24 | DEBUG |  
2017-12-13 14:12:24 | DEBUG | Renaming files according to configuration details : $Series $Annual $Issue ($Year)
2017-12-13 14:12:24 | DEBUG | original comicname is : Scooby Apocalypse
2017-12-13 14:12:24 | DEBUG | comlocation is : \\nas\share2\comics\DC Comics/Scooby Apocalypse (2017)
2017-12-13 14:12:24 | INFO | Mass import - Move files
2017-12-13 14:12:24 | INFO | Updating complete for: Scooby Apocalypse
2017-12-13 14:12:24 | INFO | Now adding/updating issues for Scooby Apocalypse

**Comment by evilhero** [comment]
Ok, thanks for providing all of that ;)

Both should be fixed in the latest dev commit that just went up - the Invalid Issue Number is something that would occur under normal renaming circumstances but with only certain options enabled, so I got that patched.

And the search query was because of multiple ```&``` within the series title, and Mylar was incorrectly parsing out the values (it replaces common terms when performing searches on CV so as to not get a whole whack of crap).

**Comment by Neonsa** [comment]
Hey, so another traceback error after updating to the latest commit, and attempting to mass import a new set of comics.

`

2017-12-15 10:49:34 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\webserve.py", line 4057, in preSearchitmyDB.upsert("searchresults", nVal, cVal)File "C:\Mylar\mylar\db.py", line 170, in upsertself.action(query, valueDict.values() + keyDict.values())File "C:\Mylar\mylar\db.py", line 129, in actionsqlResult = self.connection.execute(query, args)InterfaceError: Error binding parameter 9 - probably unsupported type.
-- | -- | --
2017-12-15 10:49:34 | INFO | [IMPORT] Returning results to Select option - there are 2 possibilities, manual intervention required.
2017-12-15 10:49:34 | DEBUG | [IMPORT MATCH] Bombshells\|United (104045)
2017-12-15 10:49:34 | DEBUG | [IMPORT] LastIssueID: 104045
2017-12-15 10:49:34 | DEBUG | [IMPORT] [2017] Comparing: bombshellsunited - TO - bombshellsunited
2017-12-15 10:49:34 | DEBUG | [IMPORT MATCH] Bombshells\|United (103689)
2017-12-15 10:49:34 | DEBUG | [IMPORT] LastIssueID: 103689
2017-12-15 10:49:34 | DEBUG | [IMPORT] [2019] Comparing: bombshellsunited - TO - bombshellsunited
2017-12-15 10:49:34 | DEBUG | [IMPORT] [2] search results
2017-12-15 10:49:34 | DEBUG | [RESULT][['2017', '2016']] ComicName:Bombshells: United -- 2017 [Series years: [u'2017']]
2017-12-15 10:49:34 | DEBUG | [RESULT][['2017', '2016']] ComicName:Bombshells: United -- 2017 [Series years: [u'2017']]
2017-12-15 10:49:34 | DEBUG | there are 2 search results...
2017-12-15 10:49:30 | DEBUG | [IMPORT] comicname : Bombshells - United
2017-12-15 10:49:30 | DEBUG | [IMPORT] displaycomic : Bombshells United
2017-12-15 10:49:30 | DEBUG | [IMPORT] number of issues: 1
2017-12-15 10:49:30 | DEBUG | [IMPORT] yearRANGE: ['2017']
2017-12-15 10:49:30 | DEBUG | [IMPORT] yearTOP: 2017
2017-12-15 10:49:30 | DEBUG | [IMPORT] [none] volume: None
2017-12-15 10:49:30 | DEBUG | [IMPORT] [none] dynamicname: bombshellsunited
2017-12-15 10:49:30 | INFO | [IMPORT][Bombshells - United] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.

`

**Comment by evilhero** [comment]
Try going into the mylar subdirectory and deleting all the .pyc files therein.

There doesn't seem to be anything unique about those series, so I'm wondering if you're using an old compiled version of a module instead of the new ones.

If it errors again, can you provide the filenames of the given files that it's causing the error for?
