### ISSUE TITLE
New PP issue: NoneType is not iterable

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1800]
Only seen this once so far. My bet is it's a unicode thing, as FXCVhrer should be Führer:

```
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : [SUB-PATH] Sub-directory : /mnt/skytopcliff/completed/Wunderwaffen (2016) Empire DCP (Digital)
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : [SUB-PATH] subpath set to : Wunderwaffen (2016) Empire DCP (Digital)
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : Scanner group tag discovered: phillywilly-Empire
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : volume label detected as : Volume 04 @ position: 1
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : checking date : 2016
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : date: 2016
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : datecheck: [{'date': '2016', 'position': 9, 'mod_position': 49}]
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : sctd: 2017
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : year verified as : 2016
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : year verified as: 2016
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : highest_series_position: 9
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : issue_position: 11
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : No issue number present in filename.
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : Extra item(s) are present between the volume label and the issue number. Checking..
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : new split: ['Wunderwaffen', '-', 'The', 'Left', 'Hand', 'of', 'the', 'FXCVhrer', '(2016)', '(Digital)', 'v04']
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : Volume detected as : v04
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : ALT-SERIES NAME [ISSUE TITLE]: Wunderwaffen [None]
05-Dec-2017 17:18:47 - DEBUG   :: Thread-37 : sf_highest_series_pos: ['Wunderwaffen', '-', 'The', 'Left', 'Hand', 'of', 'the', 'FXCVhrer', '(2016)']
05-Dec-2017 17:18:47 - ERROR   :: Thread-37 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/PostProcessor.py", line 317, in Process
    filelist = flc.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 140, in listFiles
    runresults = self.parseit(self.dir, filename, filedir)
  File "/opt/mylar/mylar/filechecker.py", line 884, in parseit
    elif 'XCV' in alt_issue:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by evilhero** [comment]
It looks like it's actually because the filename doesn't have an issue number present in the filename itself. If I recall, that particular series has the volume as the issue number so it's abit messed up. You'd have to change it so it's not ```v04```, but just ```04```.

The XCV thing is actually showing that Mylar had detected a unicode character, and then in order to perform string manipulation and every other magical thing it does, it stores the unicode character in a sequential variable, and replaces it in filename as XCV. Then, when it's done parsing and figuring things out, it replaces the XCV with the sequential variable so that within Mylar it's identical to the original.

**Comment by barbequesauce** [comment]
Got it - thanks.
