### ISSUE TITLE
Pull List IndexError: No item with that key

### ISSUE THREAD

**Issue by leidolf** [evilhero/mylar#1809]
I'm getting this error when I click on "This Week", on the latest version from development branch.  I tried editing the file to alter the SQL but no luck.  Any ideas?

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cherrypy/_cprequest.py", line 645, in respond
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/webserve.py", line 1526, in pullist
    watchlibrary = helpers.listLibrary()
  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/Mylar/mylar/helpers.py", line 1827, in listLibrary
    library[row['ComicID']] = {'comicid':        row['ComicID'],
IndexError: No item with that key

**Comment by evilhero** [comment]
What is your alt_pull set to in the config.ini?

Do you have any items on your watchlist or is it empty?

**Comment by leidolf** [comment]
alt_pull = 2

I have several series that I have as watched.

**Comment by evilhero** [comment]
Can you confirm you're running the latest dev commit via the hash?

I think it's saying that you have a series on your watchlist that doesn't have a comicid, which would mean that you have simething that is stuck in the loading stage and/or error Ed out and can't finish.

If you sort by the last column on the main page you should  be able to view any/all series that are in a loading status - which would be the ones causing the problem. Either delete or even refresh these series and see if that helps.

**Comment by leidolf** [comment]
I had over 50 series suddenly show up as Loading status.  I tried several things to fix the issue but I finally went with uninstalling the Mylar QPKG and installing a new one and recreating the DB.
