### ISSUE TITLE
Import series errors

### ISSUE THREAD

**Issue by Finch106** [evilhero/mylar#1817]
I was initially getting ComicVine API errors, but I did a git-pull to udate Mylar and now am getting this:

Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 3930, in preSearchit
logger.fdebug('[IMPORT] [' + str(len(sresults)) + '] search results')
TypeError: object of type 'bool' has no len()
2017-12-18 18:19:58	WARNING	Error fetching data from ComicVine: [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2017-12-18 18:19:56	INFO	[IMPORT][Old Man Logan] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2017-12-18 18:19:56	INFO	Initiating selected import mode for 20 series.
2017-12-18 18:19:56	INFO	importing selected series.

**Comment by evilhero** [comment]
That's an ssl error against CV. They might be experiencing problems with the API, or your version of python is less than 2.7.9 and/or it doesn't have the required openssl libraries in order to properly verify certificates. You could be hitting your API limit on CV, but I was under the impression it would return a different response. 

Given that you said you were experiencing problems previous to the update, I would guess it would be one of first 2 problems.

**Comment by Gamer106** [comment]
I’m on 2.7.9, but it could be very likely the OpenSSL library requirement. I’ll make sure I get that checked out and will update here.

**Comment by evilhero** [comment]
The normal way to fix things for that stuff has been to do a ```pip install requests[cryptography] ``` - that installs requests for python and then updates all the required python libraries to properly verify certificates (it works for most systems).

**Comment by Gamer106** [comment]
Whelp, it was a combination of things. For whatever reason I was on 2.7.6, after updating and running your command it’s all good.
