### ISSUE TITLE
Issue with Completed download handling

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1827]
So, until I can get #1826 resolved, I've gone back to my tried and true VBS script to start Mylar. When I use a post-processing script or use manually post-processing, everything works as expected. Well I decided I wanted to ditch the PP script and use the Completed Download Handling feature. However, when I do, I get the following traceback error:

2017-12-30 13:03:52 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Program Files (x86)\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\Program Files (x86)\Mylar\mylar\helpers.py", line 2961, in nzb_monitorif nzstat['status'] is False:TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
2017-12-30 13:03:52 | DEBUG | found matching completed item in history. Job has a status of SUCCESS/HEALTH
2017-12-30 13:03:45 | DEBUG | File has now downloaded!
2017-12-30 13:03:45 | DEBUG | Item is no longer in active queue. It should be finished by my calculations
2017-12-30 13:03:34 | DEBUG | valid queue result returned. Analyzing...
2017-12-30 13:03:33 | INFO | [UPDATER] Updated the status (Snatched) complete for X-Men: Gold Issue: 8

**Comment by evilhero** [comment]
Do you happen to still have the comicRN or whatever post-processing script you were running active still? If you enable completed download handling, you cannot run nzbtomedia or comicrn as it could alter the final path/format, and or move it completely before the completed download handling can act on the Download.

**Comment by skywayskase** [comment]
No, I made sure to disable that script and restart NZBget before turning on CDH and testing.

**Comment by skywayskase** [comment]
Something else that's peculiar is that when I was trying to run as Mylar as a service and tested CDH, I didn't actually get that traceback error, I just ran into the same problem I had with the other PP methods I mentioned in #1826.

**Comment by evilhero** [comment]
It looks Iike what's happening at this stage is that it's failing on the filesize verification. Once Mylar detects the download in your nzbget history, it does a filesize comparison to ensure its complete - it takes the file size of the item in history and compares it against what was downloaded. For some reason, they're not the same which is causing mylar to return an empty value which is causing the error.

Can you verify the size of the item in your nzbget history. Then in the lines preceding your log paste, you should see some additional info like health, download left, filesize, etc. - check the filesize there and ideally they should be the same.
