### ISSUE TITLE
Mylar not snatching anything from 32p rss

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#1841]
The last couple of months mylar have stopped automatically downloading torrents from 32p.
I use the rss link below, (With x's as anon.) and legacy mode with the correct passkey in the settings.
RSS is set to download, but it seems that there is an error when it is trying to run. See below.

anyone have an idea what goes wrong.

`http://32pag.es/feeds.php?feed=torrents_all&user=XXXXXXX&auth=XXXXXXXXXXXXXXX&passkey=XXXXXXXXXXXXXXXXXX&authkey=XXXXXXXXXXXXXXXX`

```
ERROR Uncaught exception: Traceback (most recent call last):
 File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 177, in new_run
 old_run(*args, **kwargs)
 File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
 self.__target(*self.__args, **self.__kwargs)
 File "/volume1/@appstore/mylar/share/mylar/mylar/rsscheckit.py", line 66, in run
 rsscheck.torrents(pickfeed='1', feedinfo=mylar.KEYS_32P)
 File "/volume1/@appstore/mylar/share/mylar/mylar/rsscheck.py", line 94, in torrents
 feed = 'https://32pag.es/feeds.php?feed=torrents_all&user=' + feedinfo['user'] + '&auth=' + feedinfo['auth'] + '&passkey=' + feedinfo['passkey'] + '&authkey=' + feedinfo['authkey']
TypeError: 'NoneType' object has no attribute '__getitem__' 
```

**Comment by barbequesauce** [comment]
What Mylar version are you running? Which branch? What OS are you running under? What python version?

Can you provide the 5-10 lines above this error from the log please? They're helpful for context...

**Comment by Lasborg** [comment]
Timestamp	Level	Message
2018-01-12 14:52:06	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/rsscheckit.py", line 66, in run
rsscheck.torrents(pickfeed='1', feedinfo=mylar.KEYS_32P)
File "/volume1/@appstore/mylar/share/mylar/mylar/rsscheck.py", line 94, in torrents
feed = 'https://32pag.es/feeds.php?feed=torrents_all&user=' + feedinfo['user'] + '&auth=' + feedinfo['auth'] + '&passkey=' + feedinfo['passkey'] + '&authkey=' + feedinfo['authkey']
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-01-12 14:52:06	DEBUG	[RSS-FEEDS] 32P mode set to Legacy mode. Monitoring New Releases feed only.
2018-01-12 14:52:06	INFO	[RSS-FEEDS] Initiating Torrent RSS Feed Check on 32P.
2018-01-12 14:52:06	INFO	[RSS-FEEDS] Initiating Torrent RSS Check.
2018-01-12 14:52:05	INFO	[RSS-FEEDS] RSS Feed Check Initalizing....
2018-01-12 14:52:05	INFO	Attempting to run RSS Check Forcibly


Mylar Version:  development
 -- git build f62f937b4a78cb388c13a966f6502f10b2793ad3.
Python Version : 2.7.13
Running on Synology NAS

**Comment by evilhero** [comment]
Can confirm was a bug that was introduced since the config change occurred a few months ago. Not sure why it took this long to figure out (I guess not many people use Legacy mode), but it's fixed now in the latest development commit.

**Comment by Lasborg** [comment]
Updated, the issue is fixed.
Thank you, I will be faster at reporting errors with legacy  mode in the future, I promise. (to much work manually downloading files)
