### ISSUE TITLE
Error on post-processing (comictagger)

### ISSUE THREAD

**Issue by Tucker28** [evilhero/mylar#1847]
I have set up post-processing with comictagger. I have also installed configparser. But after testing with manual post-processing, I get errors every time. It gives the error about converting to CBZ no matter if the convert option is checked or not. I haven't set it up for automatic processing yet as I want to get it working correctly before doing that.

What am I doing wrong?

Thank you,
Scott

2018-01-27 20:23:25 | ERROR | Uncaught exception: Traceback (most recent call last):File "/Applications/Python Scripts/Mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/Applications/Python Scripts/Mylar/mylar/PostProcessor.py", line 846, in Processsrc_location = odirUnboundLocalError: local variable 'odir' referenced before assignment
-- | -- | --
2018-01-27 20:23:24 | WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Python Scripts/Mylar/cache and/or the location where Mylar is trying to tag the files from.
2018-01-27 20:23:22 | INFO | Attempting to move: move
2018-01-27 20:23:22 | INFO | New_Filepath: /Applications/Python Scripts/Mylar/cache/mylar_C3ennG/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 20:23:22 | INFO | New_Folder: /Applications/Python Scripts/Mylar/cache/mylar_C3ennG
2018-01-27 20:23:22 | INFO | Filename: Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 20:23:22 | INFO | Filepath: /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 20:23:22 | INFO | [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
2018-01-27 20:23:22 | INFO | [STORY-ARC POST-PROCESSING] Enabled for Vader Down
2018-01-27 20:23:22 | INFO | [STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.
2018-01-27 20:23:22 | INFO | [POST-PROCESSING][SUCCESSFUL MATCH: Star Wars: Vader Down-86131] Match verified for Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 20:23:22 | INFO | [Star Wars: Vader Down #1] MATCH: /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr / 506185 / 506185
2018-01-27 20:23:22 | INFO | [POST-PROCESSING] Alternate series naming detected: Star Wars
2018-01-27 20:23:22 | INFO | I have located 2 files that I should be able to post-process. Continuing...
2018-01-27 20:23:22 | INFO | there are 2 files.
2018-01-27 20:23:22 | INFO | Starting postprocessing for : Manual Run

**Comment by Tucker28** [comment]
High Sierra 10.13.2
Mylar version is listed as None (Master). I have updated as of last week, but I just did another check for newer versions as I was typing this.
I had thought about unrar being an issue, but could not find a setting for it. I have rarosx 4.2.0.


2018-01-27 21:19:35 | INFO | pausing for 60 seconds before continuing to avoid hammering
-- | -- | --
2018-01-27 21:19:35 | INFO | no errors on data retrieval...proceeding
2018-01-27 21:19:34 | DEBUG | [SSL: True] Search URL: https://api.oznzb.com/api?t=search&q=star%20wars%20mace%20windu%2004&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2018-01-27 21:18:54 | ERROR | Uncaught exception: Traceback (most recent call last):File "/Applications/Python Scripts/Mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/Applications/Python Scripts/Mylar/mylar/PostProcessor.py", line 846, in Processsrc_location = odirUnboundLocalError: local variable 'odir' referenced before assignment
2018-01-27 21:18:54 | DEBUG | [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without metatagging...
2018-01-27 21:18:53 | WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Python Scripts/Mylar/cache and/or the location where Mylar is trying to tag the files from.
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] Absolute path to script: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] Executing command: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/Python Scripts/Mylar/comictagger.py', '-e', '--delete-rar', u'/Applications/Python Scripts/Mylar/cache/mylar_FFzBWs/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr']
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Applications/Python Scripts/Mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/Applications/Python Scripts/Mylar/cache/mylar_FFzBWs/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr']
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] CBL Tagging enabled.
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] CR Tagging enabled.
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] Running the ComicTagger Add-on for Mylar
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] comicpath : /Applications/Python Scripts/Mylar/cache/mylar_FFzBWs
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] sabnzbdscriptpath : /Applications/Python Scripts/Mylar
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] downloadpath : /Volumes/Working/Downloads/Comics
2018-01-27 21:18:53 | DEBUG | [META-TAGGER] scriptname : Mylar.py
2018-01-27 21:18:52 | DEBUG | [META-TAGGER] Paths / Locations:
2018-01-27 21:18:51 | INFO | Attempting to move: move
2018-01-27 21:18:51 | INFO | New_Filepath: /Applications/Python Scripts/Mylar/cache/mylar_FFzBWs/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | INFO | New_Folder: /Applications/Python Scripts/Mylar/cache/mylar_FFzBWs
2018-01-27 21:18:51 | INFO | Filename: Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | INFO | Filepath: /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | DEBUG | [META-TAGGER] Filename is : /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | DEBUG | ComicTagger Path location for internal comictagger.py set to : /Applications/Python Scripts/Mylar/comictagger.py
2018-01-27 21:18:51 | DEBUG | [META-TAGGER] dirName:/Volumes/Working/Downloads/Comics
2018-01-27 21:18:51 | INFO | [STORY-ARC POST-PROCESSING] Metatagging enabled - proceeding...
2018-01-27 21:18:51 | INFO | [STORY-ARC POST-PROCESSING] Enabled for Vader Down
2018-01-27 21:18:51 | INFO | [STORY-ARC MANUAL POST-PROCESSING] I have found 1 issues that belong to Story Arcs. Flinging them into the correct directories.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] There are 1 files found that match on your watchlist, 1 do not match anything.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][CONFIRMED-FORCE-OVERRIDE] Over-ride of matching taken due to exact name matching of series
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : X-Men: Blue [100712]
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: X-Men: Blue-100712] Match verified for X-Men Blue 001 (2017) (Digital) (Zone-Empire).cbr
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against X-Men: Blue-100712
2018-01-27 21:18:51 | DEBUG | [MATCH: X-Men Blue] X-Men Blue 001 (2017) (Digital) (Zone-Empire).cbr
2018-01-27 21:18:51 | INFO | [POST-PROCESSING][SUCCESSFUL MATCH: Star Wars: Vader Down-86131] Match verified for Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | INFO | [Star Wars: Vader Down #1] MATCH: /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire/Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr / 506185 / 506185
2018-01-27 21:18:51 | DEBUG | arcissue: 1000
2018-01-27 21:18:51 | DEBUG | temploc: 1000
2018-01-27 21:18:51 | DEBUG | datematch: True
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] 2016 comparing to 2016 : rechecking by month-check versus year.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] IssueYear (issyr) is 2016
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] 2015 is before the issue year of 2016 that was discovered in the filename
2018-01-27 21:18:51 | DEBUG | IssueDate: 2016-01-31
2018-01-27 21:18:51 | DEBUG | StoreDate 2015-11-18
2018-01-27 21:18:51 | DEBUG | issuechk: 01
2018-01-27 21:18:51 | DEBUG | issuedate:2016-01-31
2018-01-27 21:18:51 | DEBUG | [MATCH: Star Wars - Vader Down] Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | DEBUG | [MATCH: Star Wars - Vader Down] Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | DEBUG | [MATCH: Star Wars - Vader Down] Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] Now Checking if 2 issue(s) may also reside in one of the storyarc's that I am watching.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][NON-MATCH: Star Wars-79398] Incorrect series - not populating..continuing post-processing
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][.:FAIL:.] Issue is before the modified issue year of 2014
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] 2014 comparing to 2016 : rechecking by month-check versus year.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] 2015-01-14 is before the issue year of 2016 that was discovered in the filename
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Star Wars-79398
2018-01-27 21:18:51 | DEBUG | [MATCH: Star Wars - Vader Down] Star Wars - Vader Down 01 (2016) (Digital) (BlackManta-Empire).cbr
2018-01-27 21:18:51 | INFO | [POST-PROCESSING] Alternate series naming detected: Star Wars
2018-01-27 21:18:51 | INFO | I have located 2 files that I should be able to post-process. Continuing...
2018-01-27 21:18:51 | DEBUG | series title possibly: X-Men Blue
2018-01-27 21:18:51 | DEBUG | sf_highest_series_pos: ['X-Men', 'Blue']
2018-01-27 21:18:51 | DEBUG | issue verified as : 001
2018-01-27 21:18:51 | DEBUG | issue_position: 2
2018-01-27 21:18:51 | DEBUG | possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '001', 'mod_position': 11}]
2018-01-27 21:18:51 | DEBUG | highest_series_position: 3
2018-01-27 21:18:51 | DEBUG | year verified as: 2017
2018-01-27 21:18:51 | DEBUG | year verified as : 2017
2018-01-27 21:18:51 | DEBUG | sctd: 2018
2018-01-27 21:18:51 | DEBUG | datecheck: [{'date': '2017', 'position': 3, 'mod_position': 15}]
2018-01-27 21:18:51 | DEBUG | date: 2017
2018-01-27 21:18:51 | DEBUG | checking date : 2017
2018-01-27 21:18:51 | DEBUG | Scanner group tag discovered: Zone-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] subpath set to : X-Men.Blue.001.2017.Digital.Zone-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Sub-directory : /Volumes/Working/Downloads/Comics/X-Men.Blue.001.2017.Digital.Zone-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Original Path : /Volumes/Working/Downloads/Comics
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Checking Folder Name for more information.
2018-01-27 21:18:51 | DEBUG | [CORRECTION] Sub-directory found. Altering path configuration.
2018-01-27 21:18:51 | DEBUG | Alternate series / issue title: Star Wars [Vader Down]
2018-01-27 21:18:51 | DEBUG | series title possibly: Star Wars - Vader Down
2018-01-27 21:18:51 | DEBUG | sf_highest_series_pos: ['Star', 'Wars', '-', 'Vader', 'Down']
2018-01-27 21:18:51 | DEBUG | ALT-SERIES NAME [ISSUE TITLE]: Star Wars [Vader Down]
2018-01-27 21:18:51 | DEBUG | issue verified as : 01
2018-01-27 21:18:51 | DEBUG | issue_position: 5
2018-01-27 21:18:51 | DEBUG | possible_issuenumbers: [{'position': 5, 'validcountchk': False, 'number': '01', 'mod_position': 23}]
2018-01-27 21:18:51 | DEBUG | highest_series_position: 6
2018-01-27 21:18:51 | DEBUG | year verified as: 2016
2018-01-27 21:18:51 | DEBUG | year verified as : 2016
2018-01-27 21:18:51 | DEBUG | sctd: 2018
2018-01-27 21:18:51 | DEBUG | datecheck: [{'date': '2016', 'position': 6, 'mod_position': 26}]
2018-01-27 21:18:51 | DEBUG | date: 2016
2018-01-27 21:18:51 | DEBUG | checking date : 2016
2018-01-27 21:18:51 | DEBUG | Scanner group tag discovered: BlackManta-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] subpath set to : Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Sub-directory : /Volumes/Working/Downloads/Comics/Star.Wars.-.Vader.Down.01.2016.Digital.BlackManta-Empire
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Original Path : /Volumes/Working/Downloads/Comics
2018-01-27 21:18:51 | DEBUG | [SUB-PATH] Checking Folder Name for more information.
2018-01-27 21:18:51 | DEBUG | [CORRECTION] Sub-directory found. Altering path configuration.
2018-01-27 21:18:51 | INFO | there are 2 files.
2018-01-27 21:18:51 | DEBUG | [POST-PROCESSING] Manual Run initiated

**Comment by evilhero** [comment]
None being the commit is not a good thing. You could literally be running any commit on that branch and wouldn't know better. Check your config.ini and make sure the git_branch = master

The unrar setting is hidden in the lib/comictaggerlib/ct_settings/settings.ini and set the unrar_exe_path to the full path to your unrar binary (ie. unrar_exe_path = /usr/local/bin/unrar). You'll have to restart mylar after the ini change so it can load it properly.

Also configparser isn't needed any longer ;)

**Comment by evilhero** [comment]
If you just downloaded the source, I believe the git_branch ends up being None on first run. The best way is to just do a git clone if you can, then updates are handled much easier as well (updates via the GUI work with source too, but there's more room for problems).

The error says the destination path is none for some reason. Is your Comic Location set properly in the GUI? Without the location being set it doesn't know where to move it, but it should have caused errors as well when you added a series to the watchlist. The log lines leading up that error should indicate where it was tying to move it to.

**Comment by Tucker28** [comment]
Yeah, it's set for my Media array. /Volumes/Media/Comics
It always makes new folders under there.

I just downloaded the zip file to install it. It is set to none on the first run, but even after updating, it's still set to none. I'll reinstall it using the git clone as you suggest. Hopefully, I can find which folders and/or files to move to keep the library I have.

**Comment by Tucker28** [comment]
More tired than I thought. You told me which files. Moving the config.ini file won't cause issues?

**Comment by evilhero** [comment]
Nope as long as nothing has changed outside of just reinstalling, putting it into a clean install will load up just fine.

**Comment by evilhero** [comment]
Oh wait that's a story arc post-process. Do you have the storyarc directory option enabled for storyarcs? If you don't it will default to the comic location folder with a  subfolder named storyarcs.

I'm betting if you were to pp the one that's not a story arc, you won't get the problems.

I'm assuming of course that your perms are all set properly, as it's unraring items successfully now as indicated by your log.

**Comment by Tucker28** [comment]
Good catch!

I did put one in there that was not part of a story arc and it performed flawlessly.

I then went and rechecked my StoryArc settings, and they had been cleared somehow... Vader Down was still listed from where I set it up a couple nights ago, yet the options for StoryArcs had been reset. I put them back the way I had them and then put Vader back in the watch directory, and it worked great.

Yes, unrar seems to be working as it should now. I assumed a permissions issue before I wrote in, but they were set correctly.

Thanks so much for the help! =)

If you would like anyone to work on some documentation, I'd be happy to. I saw you mentioned it was something you were having trouble doing while also doing the coding.

**Comment by evilhero** [comment]
Weird how it reset, but it might have to do with the config trying to reload from your original config somehow, but normally obviously it shouldn't be resetting at all.

Yeah the documentation has always been a thorn in my side it seems. If I were to spend the time on the docs, there wouldn't be much time for me to spend on the code portion - so it's usually trying to decide which has more importance, and for the most part a working application is far better than one that doesn't work, but has documentation saying what to do when it did work ;)

I'm all for help with documentation of course, would never turn it down. I did have to disable the wiki edits tho, because some really smart (*scarcasm*) people decided to try and use the wiki as an place to post asking for help. If you do happen to come up with form of docs, let me know and I can temporarily disable the restriction so that you can post it therein.  

And thanks for the offer to help :)

**Comment by Tucker28** [comment]
Sure thing. I'll make a document for ComicTagger option first since that is freshest in my mind.

The StoryArc page keeps resetting every time I visit it.  Even the individual StoryArc of Vader Down has now reset (although it is now complete, so there will be nothing more for it to do). I will probably do Blackest Night next and let you know if it does the same thing.

But I'll come up with a ComicTagger document today. I'll come up with other ones as I learn about them.

Isn't there an IRC channel? I seem to remember seeing one mentioned, but cannot now locate the reference.

**Comment by evilhero** [comment]
Sounds good - the more feedback we get about whether certain things work and don't work, the more things we can try to fix so others don't experience the same types of problems.

Yep, if you check in the 1st tab of the Mylar Configuration it's in there:  #mylar on freenode

**Comment by Tucker28** [comment]
Would it be easier to come up with a document first, or directly into the Wiki?

**Comment by evilhero** [comment]
Probably a document first I'd imagine - it would then let me just check it to ensure that references and such are correct, plus it's always nice to be able to go through some iterations prior to a final item ;)

**Comment by Tucker28** [comment]
Here is what I came up with. I wasn't sure of the CBR to CBZ ONLY option. I know it hides every option beneath it, but beyond that, I'm not sure what it does.

[ComicTagger.pdf](https://github.com/evilhero/mylar/files/1674659/ComicTagger.pdf)

**Comment by evilhero** [comment]
That's pretty good - and yeah there are a bunch of hidden options available in Mylar for comictagger usage , so it's normal for some not to know what they all mean. I'll try and break some down here for you:
- ```CBR to CBZ option``` - if given filename is a cbr, it will convert it to a cbz but will not actually write any metatagging.
- the unrar_exe_path only really needs to be set on MAC OS'. I believe for the other systems, the path coincides with the system path so it can always be found.
- the configparser reminder option in the GUI will be removed in the next dev commit.

There are also a bunch of hidden options in the config.ini to give some more control over how comictagger actually tags:
- ```setdefaultvolume``` (True/False) If set to True, will assign a volume label of 1 to series that have a volume label of None (ie. it is the only volume in the given series). This is actually not a metatagging item, but it directly affects the next 2 options...
- ```cmtag_volume``` (True/False) If set to True, will include the volume label into the metatagging
- ```cmtag_start_year_as_volume``` (True/False) If set to True, will use the start year as the volume label (ie. V2015), as opposed to setting it to False whereby it will use the volume number (ie. V2).

I also noticed that there is an unrar_cmd and a ct_settingspath in the current config.ini, so atm I'm trying to remember if I actually finished the conversion parts so that you could specify the unrar_cmd path directly in the config.ini (it's not necessary, but it's one less .ini file to edit if required).

Here's some other info too:
- when peforming metatagging, Mylar will move/copy the given filename to the cache folder. Once there it will perform metatagging (extract cbr, zip up to cbz, add metatagging, delete cbr) and then move the finished cbz to the series folder. It will then perform a cleanup and remove the cache folder where the metatagging took place (in folders designated as mylar_xxxxx where xxxx is a random alphanumerical sequence)

I'm sure there's more, but atm and with one cup of coffee only that's what I can remember :)
