### ISSUE TITLE
Error when adding a new comic.

### ISSUE THREAD

**Issue by cclick815** [evilhero/mylar#1857]
After updating to (Development) 8568c41baf31d0eba46afdcff0cd7a6e994064fd when I added a new comic to Mylar it adds the Image but never updates the Comic info and I get the following error.

2018-02-17 23:00:01 | ERROR | Uncaught exception: Traceback (most recent call last):  File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 177, in new_run    old_run(*args, **kwargs)  File "/usr/local/python/lib/python2.7/threading.py", line 754, in run    self.__target(*self.__args, **self.__kwargs)  File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 277, in addComictoDB    shutil.copyfile(coverfile, comiclocal)NameError: global name 'coverfile' is not defined
-- | -- | --
2018-02-17 23:00:00 | DEBUG | comic image retrieval status code: 200
2018-02-17 22:59:59 | INFO | Attempting to retrieve the comic image for series
2018-02-17 22:59:57 | INFO | Directory (/volume1/Comics/Marvel/Marvels Avengers Infinity War Prelude (2018)) already exists! Continuing...
2018-02-17 22:59:57 | DEBUG | new folder format: $Publisher/$Series ($Year)
2018-02-17 22:59:57 | DEBUG | No version # found for series, removing from folder format
2018-02-17 22:59:57 | INFO | Previous version detected as None - seeing if update required
2018-02-17 22:59:57 | INFO | Sucessfully retrieved details for Marvel's Avengers: Infinity War Prelude
2018-02-17 22:59:57 | INFO | Now adding/updating: Marvel's Avengers: Infinity War Prelude
2018-02-17 22:59:57 | DEBUG | comic[ComicVersion]:None
2018-02-17 22:59:57 | DEBUG | vari is set to: yes
2018-02-17 22:59:57 | DEBUG | number of issues CV says it has: 0
2018-02-17 22:59:57 | DEBUG | number of issues I counted: 1
2018-02-17 22:59:44 | DEBUG | [RESULT][None] ComicName:Marvel's Avengers: Infinity War Prelude -- 2018 [Series years: [u'2018']]
2018-02-17 22:59:44 | DEBUG | there are 1 search results...

**Comment by evilhero** [comment]
Yep, was a line I missed when I was fixing up the alternate covers portion. Should be all fixed now - thanks for report!

**Comment by cclick815** [comment]
It's working now. Thanks for the quick fix.
