### ISSUE TITLE
Failure on manual Postprocessing

### ISSUE THREAD

**Issue by dazzla76** [evilhero/mylar#1858]
HI,

I'm trying to perform a manual import of a directory, this is something I perform normally on a weekly basis without issue.

I am getting the following error in the log  pretty much immediately.

2018-02-18 20:28:53 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/PostProcessor.py", line 317, in Processfilelist = flc.listFiles()File "/app/mylar/mylar/filechecker.py", line 140, in listFilesrunresults = self.parseit(self.dir, filename, filedir)File "/app/mylar/mylar/filechecker.py", line 884, in parseitelif 'XCV' in alt_issue:TypeError: argument of type 'NoneType' is not iterable
-- | -- | --
2018-02-18 20:28:53 | INFO | there are 349 files.
2018-02-18 20:28:52 | INFO | Starting postprocessing for : Manual Run

**Comment by evilhero** [comment]
Enable debug/verbose logging and post the full filecheck log of what it says - based on that error (which really doesn't say much), I would think you have a file in that directory that has a unicode character in it that Mylar is getting tripped on for some reason.

**Comment by dazzla76** [comment]
Thanks for the quick response.  I'm running the linuxserver distribution so might have issues starting in verbose mode.  I've gone the easy route and cleared down he incoming directory to just a couple, that seems to have sorted it so I suspect you are correct.

Thank you for your time.

**Comment by evilhero** [comment]
No worries - if you happen to figure out which filename was causing the problem, please let me know what it is. 

Odds are I can get Mylar to work with it, but if I don't know what the file is, I can't do much to fix things preemptively until it happens again.
