### ISSUE TITLE
Post-Processing fails with AttributeError: 'module' object has no attribute 'statvfs'

### ISSUE THREAD

**Issue by Perrin75** [evilhero/mylar#1861]
Hello
So three days ago I found Sabnzbd stuck on running ComicRn. I cleared out the queue from Sabnzbd and ran the PP manually and the error below popped up. I haven't changed any permissions on the machine running both Mylar and Sab or on the NAS the comics get moved to after processing.I tried using CDH and it didn't move the files over it just acknowledged that the file downloaded, but it didn't get moved, ComicRn was off on sab at this point. I also used the monitored folder the post processing got the point of moving the file and gave no error , but the file was not moved. I tried different files both sourced on the windows machine or the NAS, but no luck. The source drive as over 100GB and the destination has 1.4TB free space so i don't think its space. I read that os.statvfs is a call that is not available on the windows version of python so that could be the problem, but this was working fine before. Thank you for your help.

2018-02-20 19:12:49 | ERROR | Uncaught exception: Traceback (most recent call last):File "c:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "c:\Mylar\mylar\PostProcessor.py", line 1401, in Processself.Process_next(comicid, issueid, issuenumOG, ml, stat)File "c:\Mylar\mylar\PostProcessor.py", line 2364, in Process_nextcheckspace = helpers.get_free_space(comlocation)File "c:\Mylar\mylar\helpers.py", line 3358, in get_free_spacest = os.statvfs(folder)AttributeError: 'module' object has no attribute 'statvfs'
-- | -- | --
2018-02-20 19:12:49 | DEBUG | [POST-PROCESSING][move] \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire\Angelic 006 (2018) (digital) (d'argh-Empire).cbr ... to ... \\diskstation\comics\Image/Angelic\Angelic_6_(2018).cbr
2018-02-20 19:12:49 | DEBUG | [POST-PROCESSING] odir src : \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire\Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:49 | DEBUG | [POST-PROCESSING] Renaming \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire\Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Destination: \\diskstation\comics\Image/Angelic\Angelic_6_(2018).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Source: \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire\Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | INFO | [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: \\diskstation\comics\Image/Angelic
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] New Filename: Angelic_6_(2018)
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Original Extension: .cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Original Filename: Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] ext:.cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] ofilename: Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] odir: \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] ofilename:Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] New format: $Series $Issue ($Year)
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Not an annual - removing from filename parameters
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] New format is now: $Series $Issue ($Year)
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] No version # found for series, removing from filename
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Comic Version: None
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Comic Location: \\diskstation\comics\Image/Angelic
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Year: 2017
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Series: Angelic
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Publisher: Image
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Issue Year : 2018
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Pretty Comic Issue is : 6
2018-02-20 19:12:48 | DEBUG | Zero level supplement set to none. Issue will be set as : 6
2018-02-20 19:12:48 | DEBUG | issue detected less than 10
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] Zero Suppression set to : none
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] issuenumOG: 6
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] issueid: 660036
2018-02-20 19:12:48 | INFO | [POST-PROCESSING] [1/1] Starting Post-Processing for Angelic issue: 6
2018-02-20 19:12:48 | INFO | [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2018-02-20 19:12:48 | INFO | [DUPECHECK] Duplicate check for \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire\Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | INFO | manual list: [{'ComicName': u'Angelic', 'IssueID': u'660036', 'ComicLocation': u"\\\\diskstation\\comics\\test\\Angelic.006.2018.digital.dargh-Empire\\Angelic 006 (2018) (digital) (d'argh-Empire).cbr", 'Series': 'Angelic', 'One-Off': False, 'AltSeries': None, 'IssueNumber': u'6', 'ComicID': u'104453'}]
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING] There are 1 files found that match on your watchlist, 0 do not match anything.
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING][CONFIRMED-FORCE-OVERRIDE] Over-ride of matching taken due to exact name matching of series
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : Angelic [104453]
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: Angelic-104453] Match verified for Angelic 006 (2018) (digital) (d'argh-Empire).cbr
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-02-20 19:12:48 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Angelic-104453
2018-02-20 19:12:48 | INFO | I have located 1 files that I should be able to post-process. Continuing...
2018-02-20 19:12:48 | DEBUG | series title possibly: Angelic
2018-02-20 19:12:48 | DEBUG | sf_highest_series_pos: ['Angelic']
2018-02-20 19:12:48 | DEBUG | issue verified as : 006
2018-02-20 19:12:48 | DEBUG | issue_position: 1
2018-02-20 19:12:48 | DEBUG | possible_issuenumbers: [{'position': 1, 'validcountchk': False, 'number': '006', 'mod_position': 8}]
2018-02-20 19:12:48 | DEBUG | highest_series_position: 2
2018-02-20 19:12:48 | DEBUG | year verified as: 2018
2018-02-20 19:12:48 | DEBUG | year verified as : 2018
2018-02-20 19:12:48 | DEBUG | sctd: 2018
2018-02-20 19:12:48 | DEBUG | datecheck: [{'date': '2018', 'position': 2, 'mod_position': 12}]
2018-02-20 19:12:48 | DEBUG | date: 2018
2018-02-20 19:12:48 | DEBUG | checking date : 2018
2018-02-20 19:12:48 | DEBUG | Scanner group tag discovered: d'argh-Empire
2018-02-20 19:12:48 | DEBUG | [SUB-PATH] subpath set to : Angelic.006.2018.digital.dargh-Empire
2018-02-20 19:12:48 | DEBUG | [SUB-PATH] Sub-directory : \\diskstation\comics\test\Angelic.006.2018.digital.dargh-Empire
2018-02-20 19:12:48 | DEBUG | [SUB-PATH] Original Path : \\diskstation\comics\test
2018-02-20 19:12:48 | DEBUG | [SUB-PATH] Checking Folder Name for more information.
2018-02-20 19:12:48 | DEBUG | [CORRECTION] Sub-directory found. Altering path configuration.
2018-02-20 19:12:48 | INFO | there are 1 files.
2018-02-20 19:12:47 | DEBUG | [POST-PROCESSING] Manual Run initiated
2018-02-20 19:12:47 | DEBUG | [POST-PROCESSING] Not using SABnzbd : Manual Run
2018-02-20 19:12:47 | DEBUG | [POST-PROCESSING] nzb folder: \\diskstation\comics\test
2018-02-20 19:12:47 | DEBUG | [POST-PROCESSING] nzb name: Manual Run
2018-02-20 19:12:47 | INFO | Starting postprocessing for : Manual Run
2018-02-20 19:12:36 | INFO | Web logs cleared

**Comment by Perrin75** [comment]
That worked thank you.
