### ISSUE TITLE
Error When Downloading Issues

### ISSUE THREAD

**Issue by twitchfidelis** [evilhero/mylar#1863]
Hello-

My Mylar installation has stopped downloading successfully. It seems to find the right file to download, but it errors out before being able to do anything with it. I have included a snippet of my log with debug enabled below. How can I fix this?

My Mylar install is currently set to the master branch.

> 

2018-02-21 09:52:08 | ERROR | Uncaught exception: Traceback (most recent call last):File "c:\Mylar\mylar\logger.py", line 177, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "c:\Mylar\mylar\search.py", line 1879, in searchIssueIDListfoundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)File "c:\Mylar\mylar\search.py", line 255, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)File "c:\Mylar\mylar\search.py", line 1629, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, comicinfo, links, IssueID, ComicID, tmpprov, newznab=newznab_host)File "c:\Mylar\mylar\search.py", line 2031, in searchernzbid = generate_id(nzbprov, link)File "c:\Mylar\mylar\search.py", line 2774, in generate_idurl_parts = urlparse.urlparse(link)File "c:\Python27\lib\urlparse.py", line 143, in urlparsetuple = urlsplit(url, scheme, allow_fragments)File "c:\Python27\lib\urlparse.py", line 176, in urlsplitcached = _parse_cache.get(key, None)TypeError: unhashable type: 'dict'
-- | -- | --
2018-02-21 09:52:08 | DEBUG | nzbname used for post-processing:Rick.and.Morty.001.2015.Digital.AnHeroGold-Empire
2018-02-21 09:52:08 | DEBUG | [SEARCHER] end nzbname: Rick.and.Morty.001.2015.Digital.AnHeroGold-Empire
2018-02-21 09:52:08 | DEBUG | [SEARCHER] nzbname (\s): Rick and Morty 001 2015 Digital AnHeroGold-Empire
2018-02-21 09:52:08 | DEBUG | [SEARCHER] nzbname (remove chars): Rick.and.Morty.001.2015.Digital.AnHeroGold-Empire
2018-02-21 09:52:08 | DEBUG | [SEARCHER] entry[title]: Rick.and.Morty.001.2015.Digital.AnHeroGold-Empire

>

**Comment by evilhero** [comment]
What's the provider you're using with it ?

**Comment by twitchfidelis** [comment]
DogNZB and NZBGeek

**Comment by evilhero** [comment]
And are you doing a one-off from the pull-list, or is it Mylar just doing it's normal rss check, or did you do a manual search (via the magnifying glass), or a forceSearch on the Upcoming tab ?

**Comment by twitchfidelis** [comment]
Awesome. Thank you. Also it happened when I forced a search using the magnifying glass button next to the issue title.

**Comment by hubbcaps** [comment]
Experiencing something similar still

Mylar Version: master
-- git build eb5b6b1d5c5a1b27e852adee177446ef4d08ef8f.
Python Version : 2.7.14

Happens with both Hydra or using DogNZB sans hydra. I can check other providers if needed.

Triggers regardless if I'm searching via Issues Magnifying glass or clicking Force Check on the wanted tab.



Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/webserve.py", line 1344, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/app/mylar/mylar/search.py", line 255, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
File "/app/mylar/mylar/search.py", line 1629, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, links, IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/app/mylar/mylar/search.py", line 2031, in searcher
nzbid = generate_id(nzbprov, link)
File "/app/mylar/mylar/search.py", line 2779, in generate_id
tmpid = urlparse.urlparse(link)[4] #param 4 is the query string from the url.
File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
tuple = urlsplit(url, scheme, allow_fragments)
File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

**Comment by evilhero** [comment]
You're a few commits behind on master, the one just after the commit you're on should fix the problem you're having

**Comment by hubbcaps** [comment]
Welp, I'm an idiot. Thanks dude =]
