### ISSUE TITLE
Issue when downloading

### ISSUE THREAD

**Issue by cuken** [evilhero/mylar#1891]
Hello, i'm getting the following exception when downloading from NZB. This happens on Force Recheck, or individually selecting a comic and clicking search. I'm on the release `9c65a0d37a0723291280f8425a92253637f3acfb`.

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/search.py", line 1795, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/app/mylar/mylar/search.py", line 255, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
File "/app/mylar/mylar/search.py", line 1629, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, links, IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/app/mylar/mylar/search.py", line 2362, in searcher
ss = nzbget.NZBGet()
File "/app/mylar/mylar/nzbget.py", line 37, in __init__
self.nzb_url = '%s://%s:%s@%s:%s/xmlrpc' % (protocol, mylar.CONFIG.NZBGET_USERNAME, mylar.CONFIG.NZBGET_PASSWORD, nzbget_host, mylar.CONFIG.NZBGET_PORT)
UnboundLocalError: local variable 'protocol' referenced before assignment
```

**Comment by barbequesauce** [comment]
Can you please add in the 10-15 lines preceding the traceback? It's tough to understand the context of the message without it...

**Comment by barbequesauce** [comment]
Actually, scratch that. What do you have in your NZBGet Host setting? I'm betting that it is just an IP address or a hostname without http:// or https:// in front of it...

**Comment by cuken** [comment]
That was it! I missed the http:// in front of the IP call to NZBGet. >.< 
Perhaps some validation on those fields would be a nice addition.
