### ISSUE TITLE
Error Searching on Public Torrents

### ISSUE THREAD

**Issue by evilduck83** [evilhero/mylar#1894]
When I enable search on Torrents (public only) and do a search I get the following error and the search stops:

2018-03-17 13:07:17 | ERROR | Uncaught exception: Traceback (most recent call last):  <br>File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 177, in new_run    <br>old_run(*args, **kwargs)  <br>File "/usr/local/python/lib/python2.7/threading.py", line 754, in run    <br>self.__target(*self.__args, **self.__kwargs)  <br>File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1419, in queueissue     <br>foundcom, prov = search.search_init(ComicName, ComicIssue,  ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate,  IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode,  ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe,  allow_packs=AllowPacks)  <br>File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 317, in search_init     <br>findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear,  Publisher, IssueDate, StoreDate, searchprov, send_prov_count,  IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion,  SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID,  issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName,  allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit,  manual=manual)  <br>File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 562, in NZB_SEARCH    <br>bb = ww.wwt_connect()  <br>File "/volume1/@appstore/mylar/share/mylar/mylar/wwt.py", line 53, in wwt_connect    <br>soup = BeautifulSoup(r.content, "html5lib")  <br>File "/usr/local/mylar/share/mylar/lib/bs4/__init__.py", line 165, in __init__    % ",".join(features))<br>FeatureNotFound:  Couldn't find a tree builder with the features you requested: html5lib.  Do you need to install a parser library?
-- | -- | :--

Usenet works without Problems.

Mylar Version: development
-- git build 4508f62b5bf946f352e470076c923a8cfed6a646.
Python Version : 2.7.13

**Comment by evilhero** [comment]
With wwt integration, you need to have html5lib installed so the parser can properly parse the given webpages (it no longer is limited to just monitoring the RSS feeds) - it can be installed by doing a ```pip install html5lib```and won't affect other items, as to use html5lib it has to be directly called against.

**Comment by evilduck83** [comment]
Ok, I'm dumb. I tried installing html5lib but it still didn't work. Since I am running Mylar on a Synology NAS i had to install the packages hrough the the Synology Interface.
It's working now. Thanks for this program and the help!
