### ISSUE TITLE
New Mylar user, error initiating download

### ISSUE THREAD

**Issue by DrewBloodPPS** [evilhero/mylar#1907]
Had good luck getting Sonarr and Radarr running on my Xpenology setup, so now working on Mylar. Having some trouble getting it going and not sure what the error is. Here is a relevant chunk of the debug log. No clue what this might mean.

2018-04-03 11:58:50	ERROR	Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/search.py", line 1790, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "/app/mylar/mylar/search.py", line 255, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)
File "/app/mylar/mylar/search.py", line 1624, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/app/mylar/mylar/search.py", line 2346, in searcher
ss = nzbget.NZBGet()
File "/app/mylar/mylar/nzbget.py", line 37, in __init__
self.nzb_url = '%s://%s:%s@%s:%s/xmlrpc' % (protocol, mylar.CONFIG.NZBGET_USERNAME, mylar.CONFIG.NZBGET_PASSWORD, nzbget_host, mylar.CONFIG.NZBGET_PORT)
UnboundLocalError: local variable 'protocol' referenced before assignment
2018-04-03 11:58:49	DEBUG	Successfully changed permissions [0777 / 0660]
2018-04-03 11:58:49	DEBUG	Cache Directory successfully found at : /config/mylar/cache. Ensuring proper permissions.
2018-04-03 11:58:49	DEBUG	[FILENAME] end nzbname: XXXXXXFILENAMEXXXXXXX
2018-04-03 11:58:49	DEBUG	[FILENAME] nzbname (\s): XXXXXXFILENAMEXXXXXXX
2018-04-03 11:58:49	DEBUG	[FILENAME] filename (remove chars): XXXXXXFILENAMEXXXXXXX
2018-04-03 11:58:46	INFO	download-retrieved headers: {'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'content-disposition': 'attachment; filename="XXXXXXFILENAMEXXXXXXX"', 'transfer-encoding': 'chunked', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'x-dnzb-name': 'XXXXXXFILENAMEXXXXXXX', 'x-dnzb-category': 'Books > Comics', 'connection': 'keep-alive', 'x-dnzb-moreinfo': '', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Tue, 03 Apr 2018 16:58:07 GMT', 'cf-ray': '405d1400f87f1fa6-DFW', 'server': 'cloudflare', 'content-type': 'application/x-nzb'}
2018-04-03 11:58:45	INFO	Download URL: https://api.nzbplanet.net/api?apikey=XXXXXXXXXXXXXXXXXXa070&t=get&id=XXXXXXXXXXXXXXXXXX [VerifySSL:True]
2018-04-03 11:58:45	DEBUG	link given by: newznab
2018-04-03 11:58:45	INFO	XXXXXXFILENAMEXXXXXXX using NZBPlanet (newznab)

**Comment by evilhero** [comment]
Make sure you put either the http / https in the nzbget host configuration as it indicates in the small print beneath the field itself. The error is basically saying there's no http/https protocol provided, so it can't send it due to an invalid url.

**Comment by DrewBloodPPS** [comment]
That worked! Thanks for the help. Now to work on post-processing. Hopefully don't need to bother you again for a while.
