### ISSUE TITLE
Can't add comics

### ISSUE THREAD

**Issue by gilly65** [evilhero/mylar#1909]
When I try to add any comic now, it doesn't.
It goes through the motions, but then it seems to get stuck on the page where it should load the comic info, it shows this;

 Comic ID: 105886 (None)
(Comic information is currently being loaded)

[that was for: Iron Maiden Legacy of the Beast (2017)
and nothing else happens, I have left it for a day before, still nothing.
I have tried several different comics, same result for all of them.

This is running on a QNAP NAS, Python 2.7.13 (according to Mylar)

Here is a section of the log file after the 2nd attempt to add it;

2018-04-04 09:26:37 | ERROR | Uncaught exception: Traceback (most recent call last):  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/mylar/logger.py", line 177, in new_run    old_run(*args, **kwargs)  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/lib/python2.7/threading.py", line 754, in run    self.__target(*self.__args, **self.__kwargs)  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/mylar/importer.py", line 356, in addComictoDB    filechecker.setperms(comiclocal)  File "/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/mylar/filechecker.py", line 1386, in setperms    chgroup = getgrnam(mylar.CONFIG.CHGROUP)[2]KeyError: 'getgrnam(): name not found: admin'
-- | -- | --
2018-04-04 09:26:36 | DEBUG | comic image retrieval status code: 200
2018-04-04 09:26:35 | INFO | Attempting to retrieve the comic image for series
2018-04-04 09:26:33 | INFO | Directory (/share/CACHEDEV1_DATA/Multimedia/Comics/Iron Maiden Legacy of the Beast (2017)) already exists! Continuing...
2018-04-04 09:26:33 | DEBUG | new folder format: $Series ($Year)
2018-04-04 09:26:33 | DEBUG | No version # found for series, removing from folder format
2018-04-04 09:26:33 | INFO | Previous version detected as None - seeing if update required
2018-04-04 09:26:33 | INFO | Sucessfully retrieved details for Iron Maiden Legacy of the Beast
2018-04-04 09:26:33 | INFO | Now adding/updating: Iron Maiden Legacy of the Beast
2018-04-04 09:26:33 | DEBUG | comic[ComicVersion]:None
2018-04-04 09:26:33 | DEBUG | vari is set to: no
2018-04-04 09:26:33 | DEBUG | number of issues CV says it has: 4
2018-04-04 09:26:33 | DEBUG | number of issues I counted: 4
2018-04-04 09:25:56 | WARNING | [Warning] ComicID: 105886 is incomplete - Removing from DB. You should try to re-add the series.
2018-04-04 09:25:44 | DEBUG | comic image retrieval status code: 200
2018-04-04 09:25:43 | INFO | Attempting to retrieve the comic image for series

Any help would be appreciated.
Th@nX

**Comment by evilhero** [comment]
You have your group permissions in Mylar set incorrectly. The error is saying that there is no group called 'admin' on your system, so it's failing to change the ownership. 

So, fix the group permission so that it's correct - or even use the numerical equivalent for the admin group or whatever it's called to coincide with your comics location. 

You can also just turn off the ownership portion (if you're sure ownership is fine), and/or turn off overall permissions within Mylar entirely (normally this option works best if you have one user running all your stuff, since then ownership between files isn't an issue) - but that depends entirely on your system and how other things are configured.

**Comment by gilly65** [comment]
Cool, as soon as I left the group section blank, it worked fine.
I had thought I disabled the entire Permissions section but it is still enabled, maybe I didn't save it correctly the first time, either way, this is working.

Thank you!
