### ISSUE TITLE
Cannot add series, new docker install

### ISSUE THREAD

**Issue by joshuadavidthomas** [evilhero/mylar#1911]
## Expected Behavior

On a new install of the docker version of mylar, I would like to add my first series to follow either by searching or finding it on the This Week tab.

## Current Behavior

When I add a series it shows up on home page with 'None' in all columns. The status indicator spins on loop. Clicking through to the comic page, it has the header 'Comic ID: 107512 (None)' with '(Comic information is currently being loaded)' underneath. Comic information doesn't seem to load, whether I just leave the page sitting there or forcing a refresh. The link address for the header is http://XXX.XXX.XXX.XXX:8090/None.

## Context

* Docker Version: 18.03.0-ce
* Operating System: Ubuntu Server 16.04.4
* Container Version: latest from https://hub.docker.com/r/linuxserver/mylar/

## Logs
```
2018-04-05 16:46:27 | INFO | [1/2] Refreshing :Comic ID: 107512 (None) [107512]
2018-04-05 16:46:27 | ERROR | Comic ID: 107512 failed during a previous add /refresh as it has no Last Update timestamp. Forcing refresh now.
2018-04-05 16:43:29 | WARNING | Comic ID: 89350 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:43:29 | WARNING | Comic ID: 107512 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:42:05 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/updater.py", line 325, in dbUpdatechkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)File "/app/mylar/mylar/importer.py", line 84, in addComictoDBcheckdirectory = filechecker.validateAndCreateDirectory(comlocation, True)File "/app/mylar/mylar/filechecker.py", line 1338, in validateAndCreateDirectoryif os.path.exists(dir):File "/usr/lib/python2.7/genericpath.py", line 26, in existsos.stat(path)TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-04-05 16:42:05 | INFO | Starting update for 1 active comics
2018-04-05 16:42:03 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/updater.py", line 325, in dbUpdatechkstatus = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)File "/app/mylar/mylar/importer.py", line 84, in addComictoDBcheckdirectory = filechecker.validateAndCreateDirectory(comlocation, True)File "/app/mylar/mylar/filechecker.py", line 1338, in validateAndCreateDirectoryif os.path.exists(dir):File "/usr/lib/python2.7/genericpath.py", line 26, in existsos.stat(path)TypeError: coercing to Unicode: need string or buffer, NoneType found
2018-04-05 16:42:03 | INFO | Starting update for 1 active comics
2018-04-05 16:41:27 | INFO | [1/2] Refreshing :Comic ID: 107512 (None) [107512]
2018-04-05 16:41:27 | ERROR | Comic ID: 107512 failed during a previous add /refresh as it has no Last Update timestamp. Forcing refresh now.
2018-04-05 16:38:24 | WARNING | Comic ID: 89350 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:38:24 | WARNING | Comic ID: 107512 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:38:17 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/importer.py", line 233, in addComictoDBcomlocation = os.path.join(mylar.CONFIG.DESTINATION_DIR, helpers.replace_all(chunk_folder_format, values))File "/usr/lib/python2.7/posixpath.py", line 70, in joinelif path == '' or path.endswith('/'):AttributeError: 'NoneType' object has no attribute 'endswith'
2018-04-05 16:38:17 | INFO | Updated version to :v6
2018-04-05 16:38:17 | INFO | Previous version detected as None - seeing if update required
2018-04-05 16:38:17 | INFO | Sucessfully retrieved details for Black Panther
2018-04-05 16:38:17 | INFO | Now adding/updating: Black Panther
2018-04-05 16:37:05 | WARNING | Comic ID: 107512 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:36:27 | INFO | [1/1] Refreshing :Comic ID: 107512 (None) [107512]
2018-04-05 16:36:27 | ERROR | Comic ID: 107512 failed during a previous add /refresh as it has no Last Update timestamp. Forcing refresh now.
2018-04-05 16:35:30 | WARNING | Comic ID: 107512 has not finished loading. Nulling some values so things display properly until they can populate.
2018-04-05 16:31:50 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/importer.py", line 233, in addComictoDBcomlocation = os.path.join(mylar.CONFIG.DESTINATION_DIR, helpers.replace_all(chunk_folder_format, values))File "/usr/lib/python2.7/posixpath.py", line 70, in joinelif path == '' or path.endswith('/'):AttributeError: 'NoneType' object has no attribute 'endswith'
2018-04-05 16:31:50 | INFO | Previous version detected as None - seeing if update required
2018-04-05 16:31:50 | INFO | Sucessfully retrieved details for Rise of the Black Panther
2018-04-05 16:31:50 | INFO | Now adding/updating: Rise of the Black Panther
2018-04-05 16:31:48 | INFO | Attempting to add directly by ComicVineID: 107512
```

**Comment by evilhero** [comment]
You have to set a ComicLocation value in the GUI for Mylar to be able to create the directory and write to it.
From the read.me
```Make sure you specify Comic Location in the Configuration! (Mylar auto-creates the Comic Series directories under the Comic Location. The directory is displayed on the Comic Detail page).```

**Comment by joshuadavidthomas** [comment]
Thanks! That fixed it. Must have glossed over that when reading.
