### ISSUE TITLE
Mylar not searching correctly on 'force search'

### ISSUE THREAD

**Issue by arqcan** [evilhero/mylar#1913]
I am running Mylar Version: development -- git build a895f3f8d367d1d345341278e5c0cde5dfacd153 and Python Version : 2.7.14.

I have about 30 comics that are listed as wanted and when i force search for them, it searches for one issues, get an error [which i will paste below] and then search for a second issue and then stops searching. I know the second issue it searches for is available but for some reason it cannot see any results.
-------------
2018-04-07 23:03:27	DEBUG	findloop: 0 / findcount: 1
2018-04-07 23:03:27	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using WWT (torznab).
2018-04-07 23:03:27	DEBUG	using Torznab host of : WWT
2018-04-07 23:03:27	INFO	Could not find Issue 1 of New Mutants: Dead Souls (2018) using Public Torrents [api]
2018-04-07 23:03:27	INFO	query set to : new mutants dead souls 1
2018-04-07 23:03:27	DEBUG	Sending request to [WWT-SEARCH] for new mutants dead souls : 001
2018-04-07 23:03:27	DEBUG	findloop: 0 / findcount: 1
2018-04-07 23:03:27	INFO	Shhh be very quiet...I'm looking for New Mutants Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 23:03:27	INFO	Alternate Search pattern detected...re-adjusting to : New Mutants Dead Souls
2018-04-07 23:03:27	INFO	query set to : new mutants dead souls 1
2018-04-07 23:03:27	DEBUG	Sending request to [WWT-SEARCH] for new mutants dead souls : 001
2018-04-07 23:03:27	DEBUG	findloop: 0 / findcount: 1
2018-04-07 23:03:27	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 23:03:27	DEBUG	Initiating Search via : api
2018-04-07 23:03:27	DEBUG	srchloop: 2
2018-04-07 23:03:27	DEBUG	calpha/cnumber: None / None
2018-04-07 23:03:27	INFO	search provider order is ['public torrents', 'torznab:WWT']
2018-04-07 23:03:27	DEBUG	there are : 0 nzb providers you have selected.
2018-04-07 23:03:27	DEBUG	There are 2 torrent providers you have selected.
2018-04-07 23:03:27	DEBUG	nzbprovider(s): []
2018-04-07 23:03:27	DEBUG	Checking for torrent enabled.
2018-04-07 23:03:27	INFO	Issue Title given as : chapter 1: new dawn fades
2018-04-07 23:03:27	DEBUG	Publisher is : Marvel
2018-04-07 23:03:27	INFO	[SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : New Mutants Dead Souls
2018-04-07 23:03:27	INFO	returning false
2018-04-07 23:03:27	DEBUG	[ISSUE-STATUS] Issue Status Check for 662749
2018-04-07 23:03:27	INFO	result: {'Issue_Number': u'1', 'IssueID': u'662749', 'StoreDate': u'2018-03-14', 'StoryArcID': None, 'SARC': None, 'IssueArcID': None, 'mode': 'want', 'IssueDate': u'2018-05-31', 'ComicID': u'109202'}
2018-04-07 23:03:27	INFO	Initiating Search scan at the scheduled interval of 360 minutes.
2018-04-07 23:03:27	INFO	[SEARCH] Running Search for Wanted.
2018-04-07 23:03:27	INFO	[Auto-Search (trigger: interval[6:00:00], next run at: 2018-04-08 04:02:26 UTC)] Now force submitting job for jobid search
2018-04-07 23:03:22	DEBUG	If you read this message, debug logging is available
2018-04-07 23:03:22	INFO	Verbose toggled, set to True
2018-04-07 23:03:11	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2018-04-07 23:03:11	WARNING	There were no files located - check the debugging logs if you think this is in error.
2018-04-07 23:03:11	INFO	there are 0 files.
2018-04-07 23:03:11	INFO	[FOLDER-CHECK] Checking folder F:\Downloads\Mylar for newly snatched downloads
2018-04-07 23:03:10	INFO	Update complete
2018-04-07 23:02:27	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using WWT (torznab).
2018-04-07 23:02:26	INFO	Could not find Issue 1 of New Mutants: Dead Souls (2018) using Public Torrents [api]
2018-04-07 23:02:26	INFO	query set to : new mutants dead souls 1
2018-04-07 23:02:26	INFO	Shhh be very quiet...I'm looking for New Mutants Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 23:02:26	INFO	Alternate Search pattern detected...re-adjusting to : New Mutants Dead Souls
2018-04-07 23:02:26	INFO	query set to : new mutants dead souls 1
2018-04-07 23:02:26	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 23:02:26	INFO	search provider order is ['public torrents', 'torznab:WWT']
2018-04-07 23:02:26	INFO	Issue Title given as : chapter 1: new dawn fades
2018-04-07 23:02:26	INFO	[SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : New Mutants Dead Souls
2018-04-07 23:02:26	INFO	returning false
2018-04-07 23:02:26	INFO	result: {'Issue_Number': u'1', 'IssueID': u'662749', 'StoreDate': u'2018-03-14', 'StoryArcID': None, 'SARC': None, 'IssueArcID': None, 'mode': 'want', 'IssueDate': u'2018-05-31', 'ComicID': u'109202'}
2018-04-07 23:02:26	INFO	Initiating Search scan at the scheduled interval of 360 minutes.
2018-04-07 23:02:26	INFO	[SEARCH] Running Search for Wanted.
2018-04-07 23:02:26	INFO	[Auto-Search (trigger: interval[6:00:00], next run at: 2018-04-08 03:54:10 UTC)] Now force submitting job for jobid search
2018-04-07 22:58:10	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2018-04-07 22:58:10	WARNING	There were no files located - check the debugging logs if you think this is in error.
2018-04-07 22:58:10	INFO	there are 0 files.
2018-04-07 22:58:10	INFO	[FOLDER-CHECK] Checking folder F:\Downloads\Mylar for newly snatched downloads
2018-04-07 22:58:10	INFO	Update complete
2018-04-07 22:54:10	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using WWT (torznab).
2018-04-07 22:54:10	INFO	Could not find Issue 1 of New Mutants: Dead Souls (2018) using Public Torrents [api]
2018-04-07 22:54:10	INFO	query set to : new mutants dead souls 1
2018-04-07 22:54:10	INFO	Shhh be very quiet...I'm looking for New Mutants Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 22:54:10	INFO	Alternate Search pattern detected...re-adjusting to : New Mutants Dead Souls
2018-04-07 22:54:10	INFO	query set to : new mutants dead souls 1
2018-04-07 22:54:10	INFO	Shhh be very quiet...I'm looking for New Mutants: Dead Souls issue: 1 (2018) using Public Torrents.
2018-04-07 22:54:10	INFO	search provider order is ['public torrents', 'torznab:WWT']
2018-04-07 22:54:10	INFO	Issue Title given as : chapter 1: new dawn fades
2018-04-07 22:54:10	INFO	[SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : New Mutants Dead Souls
2018-04-07 22:54:10	INFO	returning false
2018-04-07 22:54:10	INFO	result: {'Issue_Number': u'1', 'IssueID': u'662749', 'StoreDate': u'2018-03-14', 'StoryArcID': None, 'SARC': None, 'IssueArcID': None, 'mode': 'want', 'IssueDate': u'2018-05-31', 'ComicID': u'109202'}
2018-04-07 22:54:10	INFO	Initiating Search scan at the scheduled interval of 360 minutes.
2018-04-07 22:54:10	INFO	[SEARCH] Running Search for Wanted.
2018-04-07 22:54:10	INFO	[Auto-Search (trigger: interval[6:00:00], next run at: 2018-04-08 01:46:19 UTC)] Now force submitting job for jobid search
2018-04-07 22:53:10	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2018-04-07 22:53:10	WARNING	There were no files located - check the debugging logs if you think this is in error.
2018-04-07 22:53:10	INFO	there are 0 files.
2018-04-07 22:53:10	INFO	[FOLDER-CHECK] Checking folder F:\Downloads\Mylar for newly snatched downloads
2018-04-07 22:53:10	INFO	Update complete
2018-04-07 22:49:39	ERROR	Uncaught exception: Traceback (most recent call last):
File "e:\Mylar\mylar\logger.py", line 324, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "e:\Mylar\mylar\search.py", line 2123, in searchIssueIDList
foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks)
File "e:\Mylar\mylar\search.py", line 334, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host)
File "e:\Mylar\mylar\search.py", line 636, in NZB_SEARCH
torznab_fix = host.torznab
NameError: global name 'host' is not defined
2018-04-07 22:49:39	INFO	Shhh be very quiet...I'm looking for Invincible issue: 136 (2017) using WWT (torznab).
2018-04-07 22:49:39	INFO	Could not find Issue 136 of Invincible (2003) using Public Torrents [api]
2018-04-07 22:49:38	INFO	query set to : invincible 136
2018-04-07 22:49:38	INFO	Shhh be very quiet...I'm looking for Invincible issue: 136 (2017) using Public Torrents.
2018-04-07 22:49:38	INFO	search provider order is ['public torrents', 'torznab:WWT']
2018-04-07 22:49:38	INFO	Issue Title given as : the end of all things part four
2018-04-07 22:49:38	INFO	searching for issueid: 595722
2018-04-07 22:48:10	INFO	Background Schedulers successfully started...
2018-04-07 22:48:10	INFO	Firing up the Background Schedulers now....
2018-04-07 22:48:10	INFO	[FOLDER MONITOR] Enabling folder monitor for : F:\Downloads\Mylar every 5 minutes.
2018-04-07 22:48:10	INFO	[WEEKLY] Checking for existance of Weekly Comic listing...
2018-04-07 22:48:10	INFO	[POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
2018-04-07 22:48:10	INFO	[POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
2018-04-07 22:48:08	INFO	Starting Mylar on http://0.0.0.0:8090/
2018-04-07 22:48:08	INFO	[DIRECTORY-CHECK] Found comic directory: e:\Mylar
2018-04-07 22:48:08	INFO	Sucessfully ordered 143 series in your watchlist.
2018-04-07 22:48:08	INFO	Remapping the sorting to allow for new additions.
2018-04-07 22:48:08	INFO	Config GIT Branch: development
2018-04-07 22:48:08	INFO	Successfully discovered local IP and locking it in as : 10.8.0.81
2018-04-07 22:48:08	INFO	Correcting Null entries that make the main page break on startup.
2018-04-07 22:48:08	INFO	Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2018-04-07 22:48:08	INFO	Populating Custom Exception listings into Mylar....

Any idea what is causing the search to not work correctly?

**Comment by arqcan** [comment]
I have also tested this on manual searching for a missing issue and i get the same error;


2018-04-08 10:49:11 | ERROR | Uncaught exception: Traceback (most recent call last):File "e:\Mylar\mylar\logger.py", line 324, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "e:\Mylar\mylar\webserve.py", line 1419, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "e:\Mylar\mylar\search.py", line 334, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host)File "e:\Mylar\mylar\search.py", line 636, in NZB_SEARCHtorznab_fix = host.torznabNameError: global name 'host' is not defined
-- | -- | --

**Comment by arqcan** [comment]
Issue is now sorted, the Torznab link needed a '/' at the end which was not required before the latest commit.
