### ISSUE TITLE
Index error on successful search

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1944]
I was searching my logs for errors and found this one, looks like it halts the results on getting a new comic added:
```
03-May-2018 11:24:27 - INFO    :: mylar.sender.42 : Thread-17 : sending now to http://10.0.1.64:8081/api
03-May-2018 11:24:27 - INFO    :: mylar.sender.49 : Thread-17 : {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_mTdn_F']}
03-May-2018 11:24:27 - INFO    :: mylar.searcher.2807 : Thread-17 : Successfully sent nzb file to SABnzbd
03-May-2018 11:24:27 - INFO    :: mylar.nzblog.683 : Thread-17 : setting the nzbid for this download grabbed by dognzb in the nzblog to : 41cce240ef3bbcd2ed1f1a2d606f7c0d
03-May-2018 11:24:27 - ERROR   :: mylar.excepthook.313 : Thread-17 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 335, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/importer.py", line 483, in addComictoDB
    search.searchforissue(result['IssueID'])
  File "/app/mylar/mylar/search.py", line 2084, in searchforissue
    updater.foundsearch(result['ComicID'], result['IssueID'], mode=mode, provider=prov, SARC=result['SARC'], IssueArcID=result['IssueArcID'], hash=foundNZB['info']['t_hash'])
IndexError: No item with that key
```

**Comment by evilhero** [comment]
Where were you initiating the search from - the arcs page, pullist, wanted tab or the series detail page?

Not sure which value it's having a problem with, cause it doesn't explicitly say. Might help to have more context, but I would think offhand it would be due to an invalid comicid / issueid.

**Comment by weidercs** [comment]
Started from the weekly pull list, added new series from the +add button.

**Comment by evilhero** [comment]
So it added, then it auto searched for any new issues, found one and snatched it but then got the error. Weird, what was the series you added (I'm assuming it was this week's pull)

**Comment by weidercs** [comment]
Legion from last week's pull.

**Comment by weidercs** [comment]
Additional logs, sorry didn't go further back before:
```
03-May-2018 11:24:11 - INFO    :: mylar.addbyid.415 : CP Server Thread-3 : Attempting to add directly by ComicVineID: 108105
03-May-2018 11:24:14 - INFO    :: mylar.addComictoDB.113 : Thread-17 : Now adding/updating: Legion
03-May-2018 11:24:14 - INFO    :: mylar.addComictoDB.166 : Thread-17 : Sucessfully retrieved details for Legion
03-May-2018 11:24:14 - INFO    :: mylar.addComictoDB.172 : Thread-17 : Previous version detected as None - seeing if update required
03-May-2018 11:24:14 - WARNING :: mylar.validateAndCreateDirectory.1351 : Thread-17 : [DIRECTORY-CHECK] Could not find comic directory: /comics/Legion (2018)
03-May-2018 11:24:14 - INFO    :: mylar.validateAndCreateDirectory.1354 : Thread-17 : [DIRECTORY-CHECK] Creating comic directory (0777) : /comics/Legion (2018)
03-May-2018 11:24:16 - INFO    :: mylar.getImage.3472 : Thread-17 : Attempting to retrieve the comic image for series
03-May-2018 11:24:20 - INFO    :: mylar.addComictoDB.338 : Thread-17 : Sucessfully retrieved issue details for Legion
03-May-2018 11:24:23 - INFO    :: mylar.updateissuedata.1100 : Thread-17 : Now adding/updating issues for Legion
03-May-2018 11:24:23 - INFO    :: mylar.addComictoDB.408 : Thread-17 : Updating complete for: Legion
03-May-2018 11:24:23 - INFO    :: mylar.forceRescan.930 : Thread-17 : [FILE-RESCAN] Now checking files for Legion (2018) in /comics/Legion (2018)
03-May-2018 11:24:23 - INFO    :: mylar.traverse_directories.1177 : Thread-17 : there are 0 files.
03-May-2018 11:24:23 - INFO    :: mylar.forceRescan.1453 : Thread-17 : [FILE-RESCAN] Total files located: 0
03-May-2018 11:24:23 - INFO    :: mylar.forceRescan.1553 : Thread-17 : [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 4 ]
03-May-2018 11:24:23 - INFO    :: mylar.addComictoDB.450 : Thread-17 : Checking this week pullist for new issues of Legion
03-May-2018 11:24:23 - INFO    :: mylar.addComictoDB.478 : Thread-17 : Attempting to grab wanted issues for : Legion
03-May-2018 11:24:23 - INFO    :: mylar.search_init.70 : Thread-17 : Issue Title given as : trauma part one
03-May-2018 11:24:23 - INFO    :: mylar.search_init.168 : Thread-17 : search provider order is ['dognzb', 'Experimental', 'newznab:NZBGeek']
03-May-2018 11:24:23 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using dognzb [RSS].
03-May-2018 11:24:23 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using dognzb [rss]
03-May-2018 11:24:23 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using experimental [RSS].
03-May-2018 11:24:23 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using experimental [rss]
03-May-2018 11:24:23 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using NZBGeek(newznab) [RSS].
03-May-2018 11:24:24 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using NZBGeek [rss]
03-May-2018 11:24:24 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using dognzb [RSS].
03-May-2018 11:24:24 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using dognzb [rss]
03-May-2018 11:24:24 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using experimental [RSS].
03-May-2018 11:24:24 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using experimental [rss]
03-May-2018 11:24:24 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using NZBGeek(newznab) [RSS].
03-May-2018 11:24:24 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using NZBGeek [rss]
03-May-2018 11:24:24 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using dognzb [RSS].
03-May-2018 11:24:25 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using dognzb [rss]
03-May-2018 11:24:25 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using experimental [RSS].
03-May-2018 11:24:25 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using experimental [rss]
03-May-2018 11:24:25 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using NZBGeek(newznab) [RSS].
03-May-2018 11:24:25 - INFO    :: mylar.search_init.364 : Thread-17 : Could not find Issue 1 of Legion (2018) using NZBGeek [rss]
03-May-2018 11:24:25 - INFO    :: mylar.NZB_SEARCH.475 : Thread-17 : Shhh be very quiet...I'm looking for Legion issue: 1 (2018) using dognzb.
03-May-2018 11:24:25 - INFO    :: mylar.NZB_SEARCH.681 : Thread-17 : pausing for 60 seconds before continuing to avoid hammering
03-May-2018 11:24:26 - INFO    :: mylar.NZB_SEARCH.753 : Thread-17 : no errors on data retrieval...proceeding
03-May-2018 11:24:26 - INFO    :: mylar.searcher.2324 : Thread-17 : Found Legion (2018) issue: 1 using dognzb
03-May-2018 11:24:26 - INFO    :: mylar.searcher.2329 : Thread-17 : nzbid: 41cce240ef3bbcd2ed1f1a2d606f7c0d
03-May-2018 11:24:26 - INFO    :: mylar.searcher.2330 : Thread-17 : IssueID: 655505
03-May-2018 11:24:26 - INFO    :: mylar.searcher.2331 : Thread-17 : oneoff: False
03-May-2018 11:24:26 - INFO    :: mylar.failed_check.244 : Thread-17 : prov  : dognzb[41cce240ef3bbcd2ed1f1a2d606f7c0d]
03-May-2018 11:24:26 - INFO    :: mylar.failed_check.255 : Thread-17 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
03-May-2018 11:24:27 - INFO    :: mylar.sender.41 : Thread-17 : parameters set to {'nzbname': u'Legion.001.2018.Digital.Zone-Empire.nzb', 'apikey': 'a33cd8b087d73c55f45cb624e73d1ecb', 'name': u'http://172.17.0.13:8090/api?apikey=7bce7b74c89dd8751a5f15996fc14303&cmd=downloadNZB&nzbname=Legion.001.2018.Digital.Zone-Empire.nzb', 'cmd': 'downloadNZB', 'cat': 'comics', 'priority': '-100', 'mode': 'addurl', 'output': 'json'}
03-May-2018 11:24:27 - INFO    :: mylar.sender.42 : Thread-17 : sending now to http://10.0.1.64:8081/api
03-May-2018 11:24:27 - INFO    :: mylar.sender.49 : Thread-17 : {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_mTdn_F']}
03-May-2018 11:24:27 - INFO    :: mylar.searcher.2807 : Thread-17 : Successfully sent nzb file to SABnzbd
03-May-2018 11:24:27 - INFO    :: mylar.nzblog.683 : Thread-17 : setting the nzbid for this download grabbed by dognzb in the nzblog to : 41cce240ef3bbcd2ed1f1a2d606f7c0d
03-May-2018 11:24:27 - ERROR   :: mylar.excepthook.313 : Thread-17 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 335, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/importer.py", line 483, in addComictoDB
    search.searchforissue(result['IssueID'])
  File "/app/mylar/mylar/search.py", line 2084, in searchforissue
    updater.foundsearch(result['ComicID'], result['IssueID'], mode=mode, provider=prov, SARC=result['SARC'], IssueArcID=result['IssueArcID'], hash=foundNZB['info']['t_hash'])
IndexError: No item with that key
```

**Comment by evilhero** [comment]
Haven't had a chance to check into this - weekend too busy. Hopefully will have some time today to look and see what's occuring.

**Comment by hitnrun30** [comment]
Please, its annoying.  I believe mine has to do with the download of newer image for the comic

**Comment by evilhero** [comment]
What does saying that it "annoys" you have to do with anything in THIS thread - which has nothing to do with the alternate covers. If it's a problem, just turn it off until it gets addressed.

I can tell you that getting a notification telling me how much something annoys you and not then not contributing to the thread, well let's be honest - it's annoying.

**Comment by hitnrun30** [comment]
Very true, my bad.  I have been looking at the code and in my case, which I believe is also what they are having, is that its has a number for the comic it wants, but that data is not in the comics table so the issueid is null.

08-May-2018 11:00:52 - ERROR   :: mylar.excepthook.313 : Thread-35 : Uncaught exception: Traceback (most recent call last):
  File "C:\HTPC\Mylar\mylar\logger.py", line 335, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\HTPC\Mylar\mylar\updater.py", line 183, in dbUpdate
    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear)
  File "C:\HTPC\Mylar\mylar\importer.py", line 361, in addComictoDB
    imageurl = mylar.cv.getComic(comicid, 'image', issueid=imagetopull[0])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by evilhero** [comment]
Again @hitnrun30, what you're discussing has nothing to do with this thread. You've already provided your error message in the other thread pertaining to that. If you look at the error messages in this thread compared to what you just posted - they are nothing alike. I'll look into the alternate cover problem when I can, but continually posting this stuff unfortunately isn't helping anyone at this point in time.

As far as the db - you're a bit off on the workflow. In order for a series to get added, it has to have data in the comics table - null issueid's can only occur on the pullist as those get populated differently and they are treated differently. If an issue for a given series is listed on the series page, it has to have an issueid or else it would not exist on the page (very basic explanation). The imagetopull is from a previous CV lookup which contains all the relevant information pertaining to the image that it's supposed to retrieve - one of those is the issueid.

**Comment by weidercs** [comment]
Verified fixed in [0b19008](https://github.com/evilhero/mylar/commit/0b190081ce14d85a26f0bda329f7463601d74923) Closing

**Comment by evilhero** [comment]
@weidercs thanks for verifying it works! 
I couldn't replicate the problem on my end, so I tried to fix it based on your error message alone ;)

**Comment by weidercs** [comment]
@evilhero Wizard status verified! Worked perfect, pulled a new series error free.  Go teamwork ;)
