### ISSUE TITLE
cannot start with HTTPS enabled - module pyopenssl missing

### ISSUE THREAD

**Issue by nopoz** [evilhero/mylar#1946]
Using latest version from github https://github.com/evilhero/mylar/commit/c047a88463b593f1753b8ccefc045ab2b8046fb7 I get an error when enabling https. Using synology NAS. 

```
07-May-2018 12:59:10 - ERROR   :: mylar.excepthook.313 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/usr/local/mylar/share/mylar/Mylar.py", line 342, in <module>
    main()
  File "/usr/local/mylar/share/mylar/Mylar.py", line 308, in main
    webstart.initialize(web_config)
  File "/volume2/@appstore/mylar/share/mylar/mylar/webstart.py", line 183, in initialize
    cherrypy.server.start()
  File "/volume2/@appstore/mylar/share/mylar/cherrypy/_cpserver.py", line 140, in start
  File "/volume2/@appstore/mylar/share/mylar/cherrypy/_cpserver.py", line 131, in httpserver_from_self
  File "/volume2/@appstore/mylar/share/mylar/cherrypy/_cpwsgi_server.py", line 50, in __init__
  File "/volume2/@appstore/mylar/share/mylar/cherrypy/wsgiserver/__init__.py", line 1964, in get_ssl_adapter_class
ImportError: No module named ssl_pyopenssl
```

**Comment by evilhero** [comment]
I would assume based on that error that you don't have the pyopenssl module installed, which is required for https.
