### ISSUE TITLE
Issue with post-processing : ComicRN: /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by ChapeLu** [evilhero/mylar#1947]
Hi,

I'm running Mylar on Unraid in a docker and up to now post-processing worked perfectly, I was getting logs about my autoProcessComics.py being out of date so decided to update my files and since then can't get it to work. Unfortunately I've done it the same time as new development update so not sure if it's the update or me updating the script files that caused the issue. I'm getting this in NZBGET log:

Tue May 08 2018 21:13:41	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire added to queue
Tue May 08 2018 21:13:41	INFO	Reordering files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:56	INFO	Successfully downloaded Infinity.Countdown.001.2018.Digital.Zone-Empire/Infinity Countdown 001 (2018) (Digital) (Zone-Empire).cbr
Tue May 08 2018 21:13:56	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire completely downloaded
Tue May 08 2018 21:13:56	INFO	Queueing Infinity.Countdown.001.2018.Digital.Zone-Empire for post-processing
Tue May 08 2018 21:13:57	INFO	Checking renamed files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	No renamed files found for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Nothing to par-check for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Nothing to unpack for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Cleaning up Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Nothing to cleanup for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Moving completed files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Moving file Infinity Countdown 001 (2018) (Digital) (Zone-Empire).cbr to /downloads/comics/Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	Move for Infinity.Countdown.001.2018.Digital.Zone-Empire successful
Tue May 08 2018 21:13:57	INFO	Executing post-process-script ComicRN.py for Infinity.Countdown.001.2018.Digital.Zone-Empire
Tue May 08 2018 21:13:57	INFO	ComicRN: /usr/bin/env: ‘python’: No such file or directory
Tue May 08 2018 21:13:57	ERROR	Post-process-script ComicRN.py for Infinity.Countdown.001.2018.Digital.Zone-Empire failed (terminated with unknown status)
Tue May 08 2018 21:13:58	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire added to history

Any help would be appreciated.

**Comment by evilhero** [comment]
At the top of the ComicRN script there's what is called a 'shebang', which is just the # sign followed by an exclamation point. It indicates where on the local system the executable to python can be located so that the script can be run.

In your case, your python executable isn't located in /usr/bin/python (probably cause of unRAID) , so you can either remove the line entirely and see if it  can load it based on your system, or specify the path to your python in place of what's there.

**Comment by ChapeLu** [comment]
Right, I don't remember doing anything to the previous version of ComicRN and it was working fine, foolishly I forgot to do the backup of my old file. I vaguely remember doing something to get scripts to work but that was some years ago. I have two seperate dockers in Unraid, Mylar and NZBGet, just to clarify, script calls for python in Nzbget docker right? I want to pint point the right docker to deal with.

Thanks

**Comment by evilhero** [comment]
Yep, the ComicRN script is called by the downloader - so the downloader has to be able to access the python executable in order to call the script.

**Comment by ChapeLu** [comment]
Ok now I remember changing #!/usr/bin/env python to #!/usr/bin/env python2 long time ago, I did that now but get different warning:

Wed May 09 2018 15:40:20	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire added to queue
Wed May 09 2018 15:40:20	INFO	Reordering files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:30	INFO	Successfully downloaded Infinity.Countdown.001.2018.Digital.Zone-Empire/Infinity Countdown 001 (2018) (Digital) (Zone-Empire).cbr
Wed May 09 2018 15:40:30	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire completely downloaded
Wed May 09 2018 15:40:30	INFO	Queueing Infinity.Countdown.001.2018.Digital.Zone-Empire for post-processing
Wed May 09 2018 15:40:30	INFO	Checking renamed files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:30	INFO	No renamed files found for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Nothing to par-check for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Nothing to unpack for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Cleaning up Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Nothing to cleanup for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Moving completed files for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Moving file Infinity Countdown 001 (2018) (Digital) (Zone-Empire).cbr to /downloads/comics/Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	Move for Infinity.Countdown.001.2018.Digital.Zone-Empire successful
Wed May 09 2018 15:40:31	INFO	Executing post-process-script ComicRN.py for Infinity.Countdown.001.2018.Digital.Zone-Empire
Wed May 09 2018 15:40:31	INFO	ComicRN: Requests module not found on system. I'll revert so this will work, but you probably should install
Wed May 09 2018 15:40:31	INFO	ComicRN: requests to bypass this in the future (ie. pip install requests)
Wed May 09 2018 15:40:31	INFO	ComicRN: Loading config from /downloads/!Nzbget/scripts/autoProcessComics.cfg
Wed May 09 2018 15:40:31	INFO	ComicRN: Traceback (most recent call last):
Wed May 09 2018 15:40:31	INFO	ComicRN:   File "/downloads/!Nzbget/scripts/ComicRN.py", line 49, in <module>
Wed May 09 2018 15:40:31	INFO	ComicRN:     result = autoProcessComics.processIssue(os.environ['NZBPP_DIRECTORY'], os.environ['NZBPP_NZBNAME'], failed=failit, comicrn_version=comicrn_version)
Wed May 09 2018 15:40:31	INFO	ComicRN:   File "/downloads/!Nzbget/scripts/autoProcessComics.py", line 40, in processIssue
Wed May 09 2018 15:40:31	INFO	ComicRN:     apikey = config.get("Mylar", "apikey")
Wed May 09 2018 15:40:31	INFO	ComicRN:   File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
Wed May 09 2018 15:40:31	INFO	ComicRN:     raise NoOptionError(option, section)
Wed May 09 2018 15:40:31	INFO	ComicRN: ConfigParser.NoOptionError: No option 'apikey' in section: 'Mylar'
Wed May 09 2018 15:40:31	ERROR	Post-process-script ComicRN.py for Infinity.Countdown.001.2018.Digital.Zone-Empire failed (terminated with unknown status)
Wed May 09 2018 15:40:32	INFO	Collection Infinity.Countdown.001.2018.Digital.Zone-Empire added to history

I'm sorry for trouble, I have no idea about linux etc.

**Comment by evilhero** [comment]
The autoProcessComics.cfg needs to be updated. The script changed in the last month (thus the version change warning in Mylar), whereby you no longer need to enter in a user/pass from the autoProcessComics.cfg file. All that's required now is the apikey for Mylar. 
- So first, you need to ensure that you have the API enabled within Mylar (Configuration/Web Interface/API and Enable API). If you don't have an API Key listed therein, you need to generate one via the Generate button. Once it's generated, make sure to save the configuration and then copy the key.
- Then copy the autoProcessComics.cfg.sample from the post-processing subdirectory within Mylar, to your nzbget scripts directory. Enter in all the correct values as per your old autoProcessComics.cfg file, save for the username and passwordd, and make sure to put in the apikey that you generated above (of if one was already present). Save the autoProcessComics.cfg.sample as autoProcessComics.cfg and it will overwrite your old cfg file then.
- That should be all that's required, try again and see if it works.

**Comment by ChapeLu** [comment]
It works!!! Sort of, files are downloaded and moved but I still get errors:

Wed May 09 2018 16:09:36	INFO	ComicRN: Requests module not found on system. I'll revert so this will work, but you probably should install
Wed May 09 2018 16:09:36	INFO	ComicRN: requests to bypass this in the future (ie. pip install requests)
Wed May 09 2018 16:09:36	INFO	ComicRN: Loading config from /downloads/!Nzbget/scripts/autoProcessComics.cfg
Wed May 09 2018 16:09:36	INFO	ComicRN: Opening URL: http://192.168.0.66:8090/api?apikey=(myapi)&apc_version=2.03&comicrn_version=1.01&nzb_name=Infinity.Countdown.003.2018.Digital.Zone-Empire&cmd=forceProcess&nzb_folder=%2Fdownloads%2Fcomics%2FInfinity.Countdown.003.2018.Digital.Zone-Empire&failed=0
Wed May 09 2018 16:09:36	INFO	ComicRN: nzb name: Infinity.Countdown.003.2018.Digital.Zone-Empire
Wed May 09 2018 16:09:36	INFO	ComicRN: nzb folder: /downloads/comics/Infinity.Countdown.003.2018.Digital.Zone-Empire
Wed May 09 2018 16:09:36	INFO	ComicRN: nzbname: Infinity.Countdown.003.2018.Digital.Zone-Empire
Wed May 09 2018 16:09:36	INFO	ComicRN: Issue Year: 2018
Wed May 09 2018 16:09:36	INFO	ComicRN: Publisher: Marvel
Wed May 09 2018 16:09:36	INFO	ComicRN: Series: Infinity Countdown
Wed May 09 2018 16:09:36	INFO	ComicRN: Year: 2018
Wed May 09 2018 16:09:36	INFO	ComicRN: Comic Location: /comics/Marvel/Infinity Countdown (2018)
Wed May 09 2018 16:09:36	INFO	ComicRN: Comic Version: None
Wed May 09 2018 16:09:36	INFO	ComicRN: No version # found for series - tag will not be available for renaming.
Wed May 09 2018 16:09:36	INFO	ComicRN: Original Filename: Infinity Countdown 003 (2018) (Digital) (Zone-Empire).cbr [.cbr]
Wed May 09 2018 16:09:36	INFO	ComicRN: New Filename: Infinity Countdown V2018 003 (2018)
Wed May 09 2018 16:09:36	INFO	ComicRN: Source:/downloads/comics/Infinity.Countdown.003.2018.Digital.Zone-Empire/Infinity Countdown 003 (2018) (Digital) (Zone-Empire).cbr
Wed May 09 2018 16:09:36	INFO	ComicRN: Destination:/comics/Marvel/Infinity Countdown (2018)/Infinity Countdown V2018 003 (2018).cbr
Wed May 09 2018 16:09:36	INFO	ComicRN: [move] /downloads/comics/Infinity.Countdown.003.2018.Digital.Zone-Empire/Infinity Countdown 003 (2018) (Digital) (Zone-Empire).cbr - to - /comics/Marvel/Infinity Countdown (2018)/Infinity Countdown V2018 003 (2018).cbr
Wed May 09 2018 16:09:36	INFO	ComicRN: Removed temporary directory : /downloads/comics/Infinity.Countdown.003.2018.Digital.Zone-Empire
Wed May 09 2018 16:09:36	INFO	ComicRN: Post Processing SUCCESSFUL!
Wed May 09 2018 16:09:36	INFO	ComicRN: Traceback (most recent call last):
Wed May 09 2018 16:09:36	INFO	ComicRN:   File "/downloads/!Nzbget/scripts/ComicRN.py", line 49, in <module>
Wed May 09 2018 16:09:36	INFO	ComicRN:     result = autoProcessComics.processIssue(os.environ['NZBPP_DIRECTORY'], os.environ['NZBPP_NZBNAME'], failed=failit, comicrn_version=comicrn_version)
Wed May 09 2018 16:09:36	INFO	ComicRN:   File "/downloads/!Nzbget/scripts/autoProcessComics.py", line 102, in processIssue
Wed May 09 2018 16:09:36	INFO	ComicRN:     if any("Post Processing SUCCESSFUL" in s for s in result.split('\n')):
Wed May 09 2018 16:09:36	INFO	ComicRN: AttributeError: 'list' object has no attribute 'split'
Wed May 09 2018 16:09:36	ERROR	Post-process-script ComicRN.py for Infinity.Countdown.003.2018.Digital.Zone-Empire failed (terminated with unknown status)
Wed May 09 2018 16:09:36	INFO	Collection Infinity.Countdown.003.2018.Digital.Zone-Empire added to history

**Comment by evilhero** [comment]
Make sure you install requests for python - the ComicRN uses that to access Mylar's API which is what's causing the initial error. You don't have to, but it's generally more reliable to use it and it's a very well known module.

Also make sure you're using the latest autoProcessComics - newest version just went into development to address the last error in your log (was a stupid conversion problem). Newest autoProcessComics.py is now 2.04.
