### ISSUE TITLE
If File Missing Or Renamed, Post Processing Crashes

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1982]
If a file in the watched folder is renamed, moved (sometimes by Mylar itself) or deleted the post processing thread encounters an exception and stops doing anything until Mylar is restarted or a manual post-processing process is started.

I've tried to omit parts of the log that were unrelated to this task.

(I assuming this log is read from bottom to top, but it looks like it finds the issue, moves it and then for some reason tries to access it from the original location and crashes.)

(There is some other strange behavior, renaming is disabled yet it still goes through the trouble of figuring out what the new name should be, should probably skip that...)

```
2018-06-11 15:14:55	ERROR	Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 336, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/PostProcessor.py", line 1253, in Process
dupthis = helpers.duplicate_filecheck(ml['ComicLocation'], ComicID=comicid, IssueID=issueid)
File "/app/mylar/mylar/helpers.py", line 2089, in duplicate_filecheck
filesz = os.path.getsize(filename)
File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr'
2018-06-11 15:14:55	INFO	[DUPECHECK] Duplicate check for /downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:55	DEBUG	[ISSUE-STATUS] Issue Status Check for 21018
2018-06-11 15:14:55	INFO	[POST-PROCESSING] Post-Processing completed for: Amethyst, Princess of Gemworld issue: 12
2018-06-11 15:14:55	DEBUG	writing: {'Status': 'Downloaded', 'Location': u'Amethyst - Princess of Gemworld v1 012.cbr'} -- {'IssueID': u'26133'}
2018-06-11 15:14:55	INFO	[POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Amethyst, Princess of Gemworld issue: 12
2018-06-11 15:14:54	INFO	[POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
2018-06-11 15:14:54	DEBUG	[POST-PROCESSING][UPDATER] issueid: 26133
2018-06-11 15:14:54	DEBUG	[POST-PROCESSING][UPDATER] comicid: 3437
2018-06-11 15:14:53	DEBUG	incremented havefiles: 12
2018-06-11 15:14:53	DEBUG	status: Snatched
2018-06-11 15:14:53	DEBUG	totalfiles: 16
2018-06-11 15:14:53	DEBUG	Successfully changed ownership and permissions [1024:101] / [0777 / 0777]
2018-06-11 15:14:53	DEBUG	sub_path: /downloads/mylar [cacheonly: False][del_nzbdir: True]
2018-06-11 15:14:53	DEBUG	odir: /downloads/mylar [filename: Amethyst - Princess of Gemworld v1 012.cbr][self.nzb_folder: /downloads/mylar]
2018-06-11 15:14:53	DEBUG	File Option: move [META-ENABLED: False]
2018-06-11 15:14:53	INFO	[POST-PROCESSING] move successful to : /comics/new/Amethyst Princess of Gemworld (1985)/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[FREESPACE-CHECK] /comics/new/Amethyst Princess of Gemworld (1985) has 8.4TiB free
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING][move] /downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr ... to ... /comics/new/Amethyst Princess of Gemworld (1985)/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] odir src : /downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Destination: /comics/new/Amethyst Princess of Gemworld (1985)/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Source: /downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	INFO	[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /comics/new/Amethyst Princess of Gemworld (1985)
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] New Filename: Amethyst - Princess of Gemworld v1 012
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Rename Files is not enabled - keeping original filename.
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Original Filename: Amethyst - Princess of Gemworld v1 012.cbr [.cbr]
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] ext:.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] ofilename: Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] odir: /downloads/mylar
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] ofilename:Amethyst - Princess of Gemworld v1 012.cbr
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] New format: $Series $Issue ($Year)
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Not an annual - removing from filename parameters
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] New format is now: $Series $Annual $Issue ($Year)
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] No version # found for series, removing from filename
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Comic Version: None
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Comic Location: /comics/new/Amethyst Princess of Gemworld (1985)
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Year: 1985
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Series: Amethyst, Princess of Gemworld
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Publisher: DC Comics
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Issue Year : 1985
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Pretty Comic Issue is : 12
2018-06-11 15:14:53	DEBUG	Zero level supplement set to none.Issue will be set as : 12
2018-06-11 15:14:53	DEBUG	issue detected greater than 10, but less than 100
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] Zero Suppression set to : none
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] issuenumOG: 12
2018-06-11 15:14:53	DEBUG	[POST-PROCESSING] issueid: 26133
2018-06-11 15:14:53	INFO	[POST-PROCESSING] [23/65] Starting Post-Processing for Amethyst, Princess of Gemworld issue: 12
2018-06-11 15:14:53	INFO	[DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2018-06-11 15:14:53	INFO	[DUPECHECK] Duplicate check for /downloads/mylar/Amethyst - Princess of Gemworld v1 012.cbr
```

**Comment by evilhero** [comment]
It looks like you have 2 post-processing runs going simultaneously for some reason, so when it moves the one the other cannot find it and errors out. This is expected behaviour when you have BOTH comicRN and Completed Download Handling enabled. You can have only one as otherwise you'll get race conditions that would lead to exactly this.

If Mylar is performing a post-process on a given issue, nothing else should be trying to rename / move it for obvious reasons. I mean at some point user accountability has to come into play as if a file is being pp'd and mylar is performing the rename, move, delete, etc then there shouldn't be another process attempting to fight for control (save for the double post-processing method described above).

The rename portion doesn't hurt anything or lessen the pp time. It has to load up all the correct series/issue info for the given issue anyways in order to verify /check things so the data is there, the log is just simply displaying things for troubleshooting / information than anything else.

**Comment by Bigwookiemike** [comment]
I had a similar issue and I turned off meta tagging and now it is working. Meta tagging is not important to me I can use comicrack for that.

**Comment by LeeThompson** [comment]
@evilhero I understand the race condition but it should be more robust.  If multiple post-processing threads can run it should be able to handle it (either by locking and allowing only one or being able to continue).    Once that exception hits, it doesn't do any more post processing.         Is there a good way to send you debug logs?    Posting debug logs in the clear is not something I like to do.

**Comment by evilhero** [comment]
If you're sending logs pertaining to having both post-processing options enabled, then there's no need to as it's a known 'issue'. The reason why it's in quotes is because there's not a lot that can be done to accommodate external scripts running and have Mylar detect them so they don't conflict with one another (this includes ComicRN). One of the guys in the irc gave me some food for thought about how to possible try and deal with things, so we'll see if I can figure out a method that works well going forward.

Properly Ttrapping the OSError you posted is a simple fix that would stop things from post-processing and can be easily done. 

An update to dev (soon) will have queues for all searches, post-processing, and monitoring. This will take care of the locking/multiple threads/db locks etc - and it will behave as a FIFO workflow. The main reason why I switched to queues was the memory usage - but obviously there are some added benefits to using queues.  It is just going thru a testing phase now to ensure that it's not going to cause too many problems for users when it hits development, so hopefully it'll hit dev soon for everyone to use.
