### ISSUE TITLE
Post processing crashes

### ISSUE THREAD

**Issue by frameset** [evilhero/mylar#1986]
When trying to post process some of this week's comics I'm getting the following error:

2018-06-14 09:05:01 | ERROR | Uncaught exception: Traceback (most recent call last):File "/opt/mylar/mylar/logger.py", line 336, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/opt/mylar/mylar/PostProcessor.py", line 1220, in Processself.nzb_or_oneoff_pp(tinfo=pp)File "/opt/mylar/mylar/PostProcessor.py", line 1611, in nzb_or_oneoff_ppreturn self.Process_next(comicid, issueid, issuenumOG)File "/opt/mylar/mylar/PostProcessor.py", line 2166, in Process_nextupdater.totals(comicid, havefiles='+1',issueid=issueid,file=dst)File "/opt/mylar/mylar/updater.py", line 1574, in totalshavefiles = int(hf['Have']) +1TypeError: int() argument must be a string or a number, not 'NoneType'
-- | -- | --

I've tried using different search providers but I still get this error. I have made sure I do not have completed download handling on, and I've made sure my cfg files for ComicRN.py are up to date.

I've just noticed that the affected comics have a "none/?" as issue amount, which could be why it's being passed a "NoneType" instead of an int.

I'll try refreshing all comics with that error and see if it resolves.

**Comment by galacticat** [comment]
I am seeing a similar error when trying to post process. I do not see "none/?" as the issue amount.

Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 336, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/PostProcessor.py", line 378, in Process
filelist = flc.listFiles()
File "/app/mylar/mylar/filechecker.py", line 143, in listFiles
runresults = self.parseit(self.dir, filename, filedir)
File "/app/mylar/mylar/filechecker.py", line 882, in parseit
elif 'XCV' in issue_number:
TypeError: argument of type 'NoneType' is not iterable

**Comment by evilhero** [comment]
@frameset : try the latest development commit - if you refresh the series, you should be all straightened out.

@galacticat : completely different issue (the error messages are entirely different). But regardless, the filename you're trying to post-process has an invalid character within it. Without seeing the logs, posting just the error message is akin to going to a mechanic and saying it doesn't work. If you can't find the problematic file, please start a new issue with the debug log showing the lead up to the error for more help.

**Comment by frameset** [comment]
Since refreshing the series I've had no further errors this week. I did notice that all the series I had issues with were series I had added to "watch" before they hit comicvine, i.e. brand new volumes this week.

I'm hesitant to join the development commit, so I'm happy to wait for it to hit master. Do you think it might be worth keeping this issue open till week and seeing if it happens again?

**Comment by evilhero** [comment]
When you say 'watch', I'm assuming you're meaning the 'auto-watch' feature of the pull-list where you can mark issues as Wanted that don't have any series data on CV yet? 

If so, then that might be the culprit in the update sequence, since it's trying to update the counts but the issue data isn't present for it to account for (weird round and round type issue, but foreseeable). If this is the case, then we can leave this open until this happens again with the auto-watch feature.
