### ISSUE TITLE
Post processing error that stops all process

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1991]
Hi, I'm running a manual post-processing and I'm getting this error that is stopping all the process.

Here's my debug log. I'm on the development branch last version.

```
2018-06-15 09:11:30 | ERROR | Uncaught exception: Traceback (most recent call last):File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 336, in new_runold_run(*args, **kwargs)File "/usr/local/python/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 1266, in Processself.Process_next(comicid, issueid, issuenumOG, ml, stat)File "/volume1/@appstore/mylar/share/mylar/mylar/PostProcessor.py", line 2166, in Process_nextupdater.totals(comicid, havefiles='+1',issueid=issueid,file=dst)File "/volume1/@appstore/mylar/share/mylar/mylar/updater.py", line 1574, in totalshavefiles = int(hf['Have']) +1TypeError: int() argument must be a string or a number, not 'NoneType'
-- | -- | --
2018-06-15 09:11:30 | DEBUG | status: Wanted
2018-06-15 09:11:30 | DEBUG | totalfiles: 1
2018-06-15 09:11:30 | DEBUG | Sub-directory detected during cleanup. Will attempt to remove if empty: /volume1/downloads/comics
2018-06-15 09:11:30 | DEBUG | sub_path: /volume1/downloads/comics [cacheonly: False][del_nzbdir: True]
2018-06-15 09:11:30 | DEBUG | odir: /volume1/downloads/comics [filename: The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr][self.nzb_folder: /volume1/downloads/comics/]
2018-06-15 09:11:30 | DEBUG | File Option: copy [META-ENABLED: False]
2018-06-15 09:11:30 | INFO | [POST-PROCESSING] copy successful to : /volume1/comic/The Magic Order (2018)/The Magic Order 1 (2018).cbr
2018-06-15 09:11:27 | DEBUG | [FREESPACE-CHECK] /volume1/comic/The Magic Order (2018) has 443.4GiB free
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][copy] /volume1/downloads/comics/The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr ... to ... /volume1/comic/The Magic Order (2018)/The Magic Order 1 (2018).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] odir src : /volume1/downloads/comics/The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Renaming /volume1/downloads/comics/The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Destination: /volume1/comic/The Magic Order (2018)/The Magic Order 1 (2018).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Source: /volume1/downloads/comics/The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | INFO | [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /volume1/comic/The Magic Order (2018)
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] New Filename: The Magic Order 1 (2018)
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Original Filename: The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr [.cbr]
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] ext:.cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] ofilename: The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] odir: /volume1/downloads/comics
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] ofilename:The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] New format: $Series $Issue ($Year)
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Not an annual - removing from filename parameters
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] New format is now: $Series $Annual $Issue ($Year)
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] No version # found for series, removing from filename
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Comic Version: None
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Comic Location: /volume1/comic/The Magic Order (2018)
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Year: 2018
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Series: The Magic Order
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Publisher: Image
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Issue Year : 2018
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Pretty Comic Issue is : 1
2018-06-15 09:11:27 | DEBUG | Zero level supplement set to none. Issue will be set as : 1
2018-06-15 09:11:27 | DEBUG | issue detected less than 10
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] Zero Suppression set to : none
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] issuenumOG: 1
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] issueid: 672852
2018-06-15 09:11:27 | INFO | [POST-PROCESSING] [1/4] Starting Post-Processing for The Magic Order issue: 1
2018-06-15 09:11:27 | INFO | [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2018-06-15 09:11:27 | INFO | [DUPECHECK] Duplicate check for /volume1/downloads/comics/The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING] There are 4 files found that match on your watchlist, 0 files are considered one-off's, and 0 files do not match anything
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: Mister Miracle-103397] Match verified for Mister Miracle 009 (2018) (2 covers) (digital) (Son of Ultron-Empire).cbr.cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][CLOCATION] /volume1/downloads/comics/
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Issue Year of 2018 is a match to the year found in the filename of : 2018
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v4 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Mister Miracle-103397
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: The Punisher-90118] Match verified for The Punisher 226 (2018) (digital) (Oroboros-DCP).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][CLOCATION] /volume1/downloads/comics/
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Issue Year of 2018 is a match to the year found in the filename of : 2018
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v8 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against The Punisher-90118
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: Detective Comics-91098] Match verified for Detective Comics 982 (2018) (Webrip) (The Last Kryptonian-DCP).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][CLOCATION] /volume1/downloads/comics/
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Issue Year of 2018 is a match to the year found in the filename of : 2018
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v3 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Detective Comics-91098
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: The Magic Order-111537] Match verified for The Magic Order 001 (2018) (Digital) (Zone-Empire).cbr
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][CLOCATION] /volume1/downloads/comics/
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-06-15 09:11:27 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against The Magic Order-111537
2018-06-15 09:11:27 | INFO | I have located 4 files that I should be able to post-process. Continuing...
2018-06-15 09:11:27 | DEBUG | series title possibly: Mister Miracle
2018-06-15 09:11:27 | DEBUG | sf_highest_series_pos: ['Mister', 'Miracle']
2018-06-15 09:11:27 | DEBUG | issue verified as : 009
2018-06-15 09:11:27 | DEBUG | issue_position: 2
2018-06-15 09:11:27 | DEBUG | possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '009', 'mod_position': 15}]
2018-06-15 09:11:27 | DEBUG | highest_series_position: 3
2018-06-15 09:11:27 | DEBUG | year verified as: 2018
2018-06-15 09:11:27 | DEBUG | year verified as : 2018
2018-06-15 09:11:27 | DEBUG | sctd: 2018
2018-06-15 09:11:27 | DEBUG | datecheck: [{'date': '2018', 'position': 3, 'mod_position': 19}]
2018-06-15 09:11:27 | DEBUG | date: 2018
2018-06-15 09:11:27 | DEBUG | checking date : 2018
2018-06-15 09:11:27 | DEBUG | Scanner group tag discovered: Son of Ultron-Empire
2018-06-15 09:11:27 | DEBUG | [FILENAME]: Mister Miracle 009 (2018) (2 covers) (digital) (Son of Ultron-Empire).cbr.cbr
2018-06-15 09:11:27 | DEBUG | series title possibly: The Punisher
2018-06-15 09:11:27 | DEBUG | sf_highest_series_pos: ['The', 'Punisher']
2018-06-15 09:11:27 | DEBUG | issue verified as : 226
2018-06-15 09:11:27 | DEBUG | issue_position: 2
2018-06-15 09:11:27 | DEBUG | possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '226', 'mod_position': 13}]
2018-06-15 09:11:27 | DEBUG | highest_series_position: 3
2018-06-15 09:11:27 | DEBUG | year verified as: 2018
2018-06-15 09:11:27 | DEBUG | year verified as : 2018
2018-06-15 09:11:27 | DEBUG | sctd: 2018
2018-06-15 09:11:27 | DEBUG | datecheck: [{'date': '2018', 'position': 3, 'mod_position': 17}]
2018-06-15 09:11:27 | DEBUG | date: 2018
2018-06-15 09:11:27 | DEBUG | checking date : 2018
2018-06-15 09:11:27 | DEBUG | Scanner group tag discovered: Oroboros-DCP
2018-06-15 09:11:27 | DEBUG | [FILENAME]: The Punisher 226 (2018) (digital) (Oroboros-DCP).cbr
2018-06-15 09:11:27 | DEBUG | series title possibly: Detective Comics
2018-06-15 09:11:27 | DEBUG | sf_highest_series_pos: ['Detective', 'Comics']
2018-06-15 09:11:27 | DEBUG | issue verified as : 982
2018-06-15 09:11:27 | DEBUG | issue_position: 2
2018-06-15 09:11:27 | DEBUG | possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '982', 'mod_position': 17}]
2018-06-15 09:11:27 | DEBUG | highest_series_position: 3
2018-06-15 09:11:27 | DEBUG | year verified as: 2018
2018-06-15 09:11:27 | DEBUG | year verified as : 2018
2018-06-15 09:11:27 | DEBUG | sctd: 2018
2018-06-15 09:11:27 | DEBUG | datecheck: [{'date': '2018', 'position': 3, 'mod_position': 21}]
2018-06-15 09:11:27 | DEBUG | date: 2018


```

**Comment by evilhero** [comment]
On the main watchlist screen, what is the have/total file count for the series that's erroring in the log?

Based on that error it would seem that either the total or have column is None instead of a numeric. This can usually be fixed by doing a Refresh Series option from the series detail page and then the post-processing will be able to complete on next run.
