### ISSUE TITLE
Post Processing Hangs for First Issues

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#2006]
This past week I had a few series that just started.  The post processing script hung on all of those series but ran fine for everything else.  Also, it appeared to only hang at the end.  It transcoded the file and moved it to the proper directory, but then seemed to hang after that.  Below are the logs for the most recent attempt.

2018-06-23 20:01:30 | ERROR | Uncaught exception: Traceback (most recent call last):  File "C:\Mylar\mylar\logger.py", line 336, in new_run    old_run(*args, **kwargs)  File "C:\Python27\lib\threading.py", line 763, in run    self.__target(*self.__args, **self.__kwargs)  File "C:\Mylar\mylar\PostProcessor.py", line 1300, in Process    self.Process_next(comicid, issueid, issuenumOG, ml, stat)  File "C:\Mylar\mylar\PostProcessor.py", line 2245, in Process_next    updater.totals(comicid, havefiles='+1',issueid=issueid,file=dst)  File "C:\Mylar\mylar\updater.py", line 1581, in totals    havefiles = int(hf['Have']) +1TypeError: int() argument must be a string or a number, not 'NoneType'
-- | -- | --
2018-06-23 20:01:30 | INFO | [POST-PROCESSING]  move successful to : F:\Torrents\Usenet\Comics\Buffy the Vampire Slayer  Season 12 The Reckoning (2018)\Buffy the Vampire Slayer Season 12 The  Reckoning 001.cbr
2018-06-23 20:01:30 | INFO | [POST-PROCESSING][DIRECTORY-CHECK]  Found comic directory: F:\Torrents\Usenet\Comics\Buffy the Vampire  Slayer Season 12 The Reckoning (2018)
2018-06-23 20:01:30 | WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ]  Failed to convert cbr to cbz - check permissions on folder :  C:\Mylar\cache/ and/or the location where Mylar is trying to tag the  files from.
2018-06-23 20:01:30 | INFO | [POST-PROCESSING] [1/1] Starting Post-Processing for Buffy the Vampire Slayer Season 12: The Reckoning issue: 1
2018-06-23 20:01:30 | INFO | [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2018-06-23 20:01:30 | INFO | [DUPECHECK]  Duplicate check for  F:\Torrents\Buffy.the.Vampire.Slayer.Season.12.001.-.The.Reckoning.2018.digital.Son.of.Ultro\Buffy  the Vampire Slayer Season 12 001 - The Reckoning (2018) (digital) (Son  of Ultron-Empire).cbr
2018-06-23 20:01:30 | INFO | temploc: 001
2018-06-23 20:01:30 | INFO | loopchk: [u'Buffy\|VampireSlayerSeason12']
2018-06-23 20:01:30 | INFO | [POST-PROCESSING] Alternate series naming detected: Buffy the Vampire Slayer Season 12 The Reckoning
2018-06-23 20:01:30 | INFO | I have located 1 files that I should be able to post-process. Continuing...
2018-06-23 20:01:30 | INFO | there are 1 files.
2018-06-23 20:01:30 | INFO | Starting postprocessing for : Manual Run

**Comment by evilhero** [comment]
I believe this is the same thing as happening in #1986.

Did you have these series as auto-watch on the pullist?

**Comment by wraith1385** [comment]
Yeah, I had to wait to add them until Wednesday since they were new, but they were set as auto-watch.
