### ISSUE TITLE
Error 500 when searching.

### ISSUE THREAD

**Issue by Sinarth** [evilhero/mylar#2019]
Hi. I had Mylar installed and working perfectly but then I had a minor mishap witch resulted in a crash of my Windows Server 2012 R2 OS to witch I did a rollback and got the OS running but now whenever I try to search for comics I get the 500 Internal Server Error.

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "c:\Mylar\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "c:\Mylar\lib\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\lib\cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 294, in searchit
    if mylar.COMICVINE_API is None:
AttributeError: 'module' object has no attribute 'COMICVINE_API'
Powered by CherryPy 3.6.0
```

I've tried deleting the Mylar folder and uninstall Python, CherryPy and Git. I've reinstalled it following the guide found here: https://www.htpcguides.com/install-mylar-windows-usenet-comics/
I also created a new ComicVine account to generate a new API to see if that was the problem.

Now I'm at a total loss as how to proceed, My understanding of GitHub is somewhat limited so I'm unsure if I was able to completely remove all files belonging to Mylar so that I can Reconfigure it from the beginning.
Is there a command to do a complete whipe of Mylar?

**Comment by evilhero** [comment]
No need to reinstall everything. If you're on the development branch the fix just went in that addresses the error.

However it will still not work since the error it's trying to log is indicating that it cannot reach comicvine for some reason. Do you have a firewall or something blocking Mylar's access to the internet? Otherwise, having an incorrect CV apikey would trigger the error since it cannot access the apikey (thnx bbq for helping)

**Comment by Sinarth** [comment]
A little update so far on my progress.

I did update Mylar and the Error 500 stopped, so that's progress. :)
Now when I search for a comic I this message on the Command Prompt:
```
17-jul-2018 17:07:35 - WARNING :: CP Server Thread-8 : mb.py:pullsearch:74 : Err
or fetching data from ComicVine: [SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:726)
17-jul-2018 17:07:35 - ERROR :: CP Server Thread-8 : webserve.py:searchit:293 :
Unable to retrieve results from ComicVine: 'bool' object is not iterable
```

I've checked my config.ini file and the api key is listed there.


I'm not sure if you wanted the C:\Mylar\config.ini file or the C:\Mylar\.git\config file. Either way I'm posting both.

```
[Client]
nzb_downloader = 0
torrent_downloader = 0

[General]
ignore_havetotal = False
syno_fix = False
nzb_startup_search = False
create_folders = True
skipped2wanted = False
auto_update = False
zero_level_n = none
update_ended = False
enable_rss = False
grabbag_dir = None
search_delay = 1
rename_files = False
file_format = $Series $Annual $Issue ($Year)
add_to_csv = True
folder_scan_log_verbose = False
interface = default
comic_cover_local = False
folder_format = $Series ($Year)
delete_remove_dir = False
failed_auto = False
destination_dir = None
refresh_cache = 7
failed_download_handling = False
autowant_all = False
use_maxsize = False
read2filename = False
oldconfig_version = None
annuals_on = False
launch_browser = False
unicode_issuenumber = False
show_icons = False
send2read = False
cache_dir = None
dynamic_update = 4
replace_char = .
replace_spaces = False
minimal_ini = False
move_files = False
preferred_quality = 0
maintainseriesfolder = False
use_minsize = False
minsize = None
wanted_tab_off = False
alternate_latest_series_covers = False
multiple_dest_dirs = None
snatched_havetotal = False
lowercase_filenames = False
correct_metadata = False
zero_level = False
upcoming_snatched = True
highcount = 0
maxsize = None
autowant_upcoming = True
config_version = 8

[NZBGet]
nzbget_client_post_processing = False
nzbget_category = None
nzbget_priority = Default
nzbget_directory = None
nzbget_password = None
nzbget_port = None
nzbget_username = None
nzbget_host = None

[SABnzbd]
sab_client_post_processing = False
sab_to_mylar = False
sab_host = None
sab_password = None
sab_apikey = None
sab_directory = None
sab_category = None
sab_priority = Default
sab_username = None

[PostProcess]
pre_scripts = None
snatch_script = None
file_opts = move
extra_scripts = None
enable_snatch_script = False
enable_check_folder = False
local_torrent_pp = False
check_folder = None
snatchedtorrent_notify = False
enable_extra_scripts = False
post_processing = False
post_processing_script = None
enable_pre_scripts = False

[Metatagging]
setdefaultvolume = False
cbr2cbz_only = False
unrar_cmd = None
ct_cbz_overwrite = False
cmtag_volume = True
enable_meta = False
ct_settingspath = None
cmtag_start_year_as_volume = False
cmtagger_path = None
ct_tag_cr = True
ct_tag_cbl = True

[Weekly]
weekfolder = False
pack_0day_watchlist_only = True
weekfolder_format = 0
alt_pull = 2
weekfolder_loc = None
biggie_pub = 55
pull_refresh = None
indie_pub = 75

[Scheduler]
search_interval = 360
rss_checkinterval = 20
download_scan_interval = 5
check_github_interval = 360

[Interface]
http_password = None
https_chain = None
authentication = 0
http_port = 8090
login_timeout = 43800
http_root = /
https_force_on = False
https_cert = None
http_host = 0.0.0.0
enable_https = False
https_key = None
host_return = None
http_username = None

[Import]
imp_metadata = False
comic_dir = None
imp_move = False
imp_rename = False
add_comics = False

[PUSHBULLET]
pushbullet_channel_tag = None
pushbullet_deviceid = None
pushbullet_apikey = None
pushbullet_enabled = False
pushbullet_onsnatch = False

[NMA]
nma_priority = 0
nma_onsnatch = False
nma_apikey = None
nma_enabled = False

[Perms]
chmod_file = 0660
chowner = None
enforce_perms = True
chmod_dir = 0777
chgroup = None

[Deluge]
deluge_host = None
deluge_label = None
deluge_username = None
deluge_password = None

[CV]
cv_verify = True
cv_only = True
cvinfo = False
blacklisted_publishers = None
comicvine_api = 883h3nn1j289d97364688aeg032kjuy858hcns83
cv_onetimer = True
cvapi_rate = 2

[Rtorrent]
rtorrent_ca_bundle = None
rtorrent_directory = None
rtorrent_authentication = basic
rtorrent_host = None
rtorrent_label = None
rtorrent_rpc_url = None
rtorrent_startonload = False
rtorrent_verify = False
rtorrent_password = None
rtorrent_ssl = False
rtorrent_username = None

[32P]
mode_32p = False
password_32p = None
verify_32p = True
enable_32p = False
search_32p = False
username_32p = None
deep_search_32p = False
passkey_32p = None
rssfeed_32p = None

[Newznab]
newznab = False
extra_newznabs = 

[Torznab]
extra_torznabs = 
enable_torznab = False
torznab_apikey = None
torznab_category = None
torznab_host = None
torznab_verify = False
torznab_name = None

[Git]
git_user = evilhero
check_github = False
git_path = None
check_github_on_startup = False
git_branch = None

[Transmission]
transmission_username = None
transmission_host = None
transmission_directory = None
transmission_password = None

[TELEGRAM]
telegram_enabled = False
telegram_token = None
telegram_onsnatch = False
telegram_userid = None

[Tablet]
tab_enable = False
tab_host = None
tab_directory = None
tab_user = None
tab_pass = None

[qBittorrent]
qbittorrent_startonload = False
qbittorrent_username = None
qbittorrent_label = None
qbittorrent_password = None
qbittorrent_folder = None
qbittorrent_host = None

[Providers]
usenet_retention = 1500
provider_order = 

[StoryArc]
storyarcdir = False
arc_folderformat = None
copy2arcdir = False
search_storyarcs = False
upcoming_storyarcs = False
arc_fileops = copy

[Duplicates]
ddump = False
duplicate_dump = None
dupeconstraint = filesize

[PUSHOVER]
pushover_enabled = False
pushover_priority = 0
pushover_userkey = None
pushover_apikey = None
pushover_onsnatch = False
pushover_device = None

[Experimental]
altexperimental = False
experimental = False

[AutoSnatch]
auto_snatch = False
pp_sshuser = None
auto_snatch_script = None
pp_sshlocalcd = None
pp_sshhost = None
pp_sshport = 22
pp_sshkeyfile = None
pp_sshpasswd = None

[Blackhole]
blackhole_dir = None

[NZBsu]
nzbsu_apikey = None
nzbsu = False
nzbsu_uid = None
nzbsu_verify = True

[uTorrent]
utorrent_password = None
utorrent_username = None
utorrent_host = None
utorrent_label = None

[Update]
newcom_dir = None
fftonewcom_dir = False
locmove = False

[Logs]
log_dir = c:\Mylar\logs
max_logsize = 10000000
log_level = 1
max_logfiles = 5

[Watchdir]
torrent_local = False
local_watchdir = None

[Torrents]
enable_torrent_search = False
enable_torrents = False
minseeds = 0
enable_public = False
allow_packs = False

[DOGnzb]
dognzb = False
dognzb_verify = True
dognzb_apikey = None

[OPDS]
opds_metainfo = False
opds_authentication = False
opds_username = None
opds_password = None
opds_enable = False

[Seedbox]
seedbox_port = None
seedbox_user = None
seedbox_pass = None
seedbox_watchdir = None
seedbox_host = None
torrent_seedbox = False

[BOXCAR]
boxcar_enabled = False
boxcar_token = None
boxcar_onsnatch = False

[SLACK]
slack_onsnatch = False
slack_enabled = False
slack_webhook_url = None

[Prowl]
prowl_enabled = False
prowl_priority = 0
prowl_keys = None
prowl_onsnatch = False

[API]
api_key = None
api_enabled = False

```
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/evilhero/mylar
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "development"]
	remote = origin
	merge = refs/heads/development

```


I've tried turning off Windows Firewall and ESET File Security that I'm using but that didn't change.

`can you please rerun from a command line using the -v flag, then post the resulting log file?`
I'm don't really know what you're asking for with the above question.


Thanks for taking you time and helping me! :D

**Comment by evilhero** [comment]
It looks like you don't have openssl installed for python (I'm assuming since you uninstalled it earlier, you never reinstalled it), since it ant verify the certificate.

You need to have pyopenssl installed along with openssl, but all of these can be installed from the requests package (```pip install requests[cryptography] ```)

**Comment by evilhero** [comment]
Yeah it's the pyopenssl / openssl that's the problem. I forgot they changed it from cryptography to security. So try ```pip install requests[security]``` and that should pull down the required modules for you to use.
