### ISSUE TITLE
Justice league dark 2 post processing problem

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#2067]
Mylar. Finds comics, downloads, then renames and puts it in the right folders. But with this one and a couple others once it downloads. The comics are automatically unzipped and I have a folder with the like 22 pics of the comic for example.

I have other comics download just perfect.

Log below:

2018-09-01 22:10:45 | INFO | [FOLDER-CHECK] Finished checking for newly snatched downloads
2018-09-01 22:10:45 | WARNING | There were no files located - check the debugging logs if you think this is in error.
2018-09-01 22:10:45 | INFO | there are 0 files.
2018-09-01 22:10:45 | DEBUG | [POST-PROCESSING] Manual Run initiated
2018-09-01 22:10:45 | DEBUG | [POST-PROCESSING] Manual Run Post-Processing enabled.
2018-09-01 22:10:45 | DEBUG | [POST-PROCESSING] Not using SABnzbd
2018-09-01 22:10:45 | DEBUG | [POST-PROCESSING] nzb folder: /volume1/NZBGet/dst/comics
2018-09-01 22:10:45 | DEBUG | [POST-PROCESSING] nzb name: Manual Run
2018-09-01 22:10:45 | INFO | [FOLDER-CHECK] Checking folder /volume1/NZBGet/dst/comics for newly snatched downloads
2018-09-01 22:10:13 | INFO | File successfully downloaded - now initiating completed downloading handling.
2018-09-01 22:10:13 | DEBUG | location found @ /volume1/NZBGet/dst/comics/Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:10:13 | DEBUG | Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire has final file size of 74MB
2018-09-01 22:10:13 | DEBUG | found matching completed item in history. Job has a status of SUCCESS/UNPACK
2018-09-01 22:10:07 | DEBUG | File has now downloaded!
2018-09-01 22:10:07 | DEBUG | Item is no longer in active queue. It should be finished by my calculations
2018-09-01 22:09:57 | DEBUG | destination: /volume1/NZBGet/inter/Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.#10395
2018-09-01 22:09:57 | DEBUG | health: 100
2018-09-01 22:09:57 | DEBUG | Download Left: 6MB
2018-09-01 22:09:57 | DEBUG | FileSize: 74MB
2018-09-01 22:09:57 | DEBUG | name: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:57 | DEBUG | status: DOWNLOADING
2018-09-01 22:09:49 | INFO | [UPDATER] Updated the status (Snatched) complete for Justice League Dark Issue: 2
2018-09-01 22:09:48 | DEBUG | [UPDATER] Provider is NZBGeek (newznab)
2018-09-01 22:09:48 | INFO | [UPDATER] Updating status to snatched
2018-09-01 22:09:48 | DEBUG | [UPDATER] issueid: 680706
2018-09-01 22:09:48 | DEBUG | [UPDATER] comicid: 112455
2018-09-01 22:09:48 | DEBUG | I found Justice League Dark #2
2018-09-01 22:09:48 | DEBUG | findit = found!
2018-09-01 22:09:47 | DEBUG | Deleted stale entry from nzblog for IssueID: 680706 [NZBGeek(newznab)]
2018-09-01 22:09:47 | DEBUG | valid queue result returned. Analyzing...
2018-09-01 22:09:47 | INFO | setting the nzbid for this download grabbed by NZBGeek(newznab) in the nzblog to : 56531ba55a04805ab34c4c79088b2aa1
2018-09-01 22:09:47 | DEBUG | Now checking the active queue of nzbget for the download
2018-09-01 22:09:47 | DEBUG | Found matching comic...preparing to send to Updater with IssueID: 680706 and nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:47 | INFO | Now loading from queue: {'status': True, 'apicall': True, 'NZBID': 10395, 'issueid': u'680706', 'comicid': u'112455'}
2018-09-01 22:09:47 | INFO | Successfully sent nzb to NZBGet!
2018-09-01 22:09:47 | DEBUG | sending now to http://dont need:dont need@192.168.2.129:6789/xmlrpc
2018-09-01 22:09:47 | DEBUG | Successfully changed permissions [0777 / 0660]
2018-09-01 22:09:47 | DEBUG | Cache Directory successfully found at : /volume1/@appstore/mylar/cache. Ensuring proper permissions.
2018-09-01 22:09:47 | DEBUG | [FILENAME] end nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-01 22:09:47 | DEBUG | [FILENAME] nzbname (\s): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-01 22:09:47 | DEBUG | [FILENAME] filename (remove chars): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-01 22:09:47 | DEBUG | filename within nzb: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-01 22:09:47 | DEBUG | Status code returned: 200
2018-09-01 22:09:45 | DEBUG | [PAYLOAD] Download URL: https://api.nzbgeek.info/api?apikey=YOUDONTNEEDTOKNOWTHIS&t=get&id=56531ba55a04805ab34c4c79088b2aa1 [VerifySSL:True]
2018-09-01 22:09:45 | DEBUG | Re-routing incorrect RSS URL response for NZBGeek to correct API
2018-09-01 22:09:45 | DEBUG | link given by: newznab
2018-09-01 22:09:45 | INFO | Found Justice League Dark (2018) issue: 2 using NZBGeek(newznab) [RSS]
2018-09-01 22:09:45 | DEBUG | issues match!
2018-09-01 22:09:45 | DEBUG | nzbname used for post-processing:Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:45 | DEBUG | [SEARCHER] end nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:45 | DEBUG | [SEARCHER] nzbname (\s): Justice League Dark 002 2018 2 covers digital Son of Ultron-Empire
2018-09-01 22:09:45 | DEBUG | [SEARCHER] nzbname (remove chars): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:45 | DEBUG | [SEARCHER] entry[title]: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-01 22:09:45 | DEBUG | integer value of issue we have found : 2000
2018-09-01 22:09:45 | DEBUG | issue we found for is : 002
2018-09-01 22:09:45 | DEBUG | integer value of issue we are looking for : 2000
2018-09-01 22:09:45 | DEBUG | issue we are looking for is : 2
2018-09-01 22:09:45 | DEBUG | this should be a match!
2018-09-01 22:09:45 | DEBUG | it's a go captain... - we matched 100.0%!
2018-09-01 22:09:45 | DEBUG | Match to series : 100.0 %.
2018-09-01 22:09:45 | DEBUG | splitit-len:3
2018-09-01 22:09:45 | DEBUG | scount:3
2018-09-01 22:09:45 | DEBUG | word matched on : dark
2018-09-01 22:09:45 | DEBUG | 2 Comparing: dark .to. dark
2018-09-01 22:09:45 | DEBUG | scount : 2
2018-09-01 22:09:45 | DEBUG | splitit: dark
2018-09-01 22:09:45 | DEBUG | word matched on : league
2018-09-01 22:09:45 | DEBUG | 1 Comparing: league .to. league
2018-09-01 22:09:45 | DEBUG | scount : 1
2018-09-01 22:09:45 | DEBUG | splitit: league
2018-09-01 22:09:45 | DEBUG | word matched on : justice
2018-09-01 22:09:45 | DEBUG | 0 Comparing: justice .to. justice
2018-09-01 22:09:45 | DEBUG | scount : 0
2018-09-01 22:09:45 | DEBUG | splitit: justice
2018-09-01 22:09:45 | DEBUG | Watchlist-length: 3
2018-09-01 22:09:45 | DEBUG | search-length: 3
2018-09-01 22:09:45 | DEBUG | length match..proceeding
2018-09-01 22:09:45 | DEBUG | len-watchcomic : 3
2018-09-01 22:09:45 | DEBUG | splitst : 3
2018-09-01 22:09:45 | DEBUG | ['justice', 'league', 'dark'] watchlist word count: 3
2018-09-01 22:09:45 | DEBUG | ['justice', 'league', 'dark', '002'] nzb series word count: 3
2018-09-01 22:09:45 | DEBUG | adjusting from: justice league dark 002 to: 002
2018-09-01 22:09:45 | DEBUG | adjusted nzb comic and issue: justice league dark 002
2018-09-01 22:09:45 | DEBUG | original nzb comic and issue: justice league dark 002
2018-09-01 22:09:45 | DEBUG | Scanner detected: 2 covers digital son of ultron-empire
2018-09-01 22:09:45 | DEBUG | covers detected: 2 covers digital son of ultron-empire
2018-09-01 22:09:45 | DEBUG | mini-series detected : 2 covers digital son of ultron-empire
2018-09-01 22:09:45 | DEBUG | 2. Bracket Word: 2 covers digital son of ultron-empire
2018-09-01 22:09:45 | DEBUG | 2018 - right years match baby!
2018-09-01 22:09:45 | DEBUG | year looking for: 2018
2018-09-01 22:09:45 | DEBUG | year detected: 2018
2018-09-01 22:09:45 | DEBUG | 1. Bracket Word: 2018
2018-09-01 22:09:45 | DEBUG | ComVersChk : 2
2018-09-01 22:09:45 | DEBUG | UseFuzzy is : None
2018-09-01 22:09:45 | DEBUG | Comic: justice league dark 002
2018-09-01 22:09:45 | DEBUG | 0. Bracket Word: justice league dark 002
2018-09-01 22:09:45 | DEBUG | Cleantitle: justice league dark 002 (2018) 2 covers digital son of ultron-empire
2018-09-01 22:09:45 | DEBUG | detected invalid nzb filename - attempting to detect year to continue
2018-09-01 22:09:45 | DEBUG | Cleantitle: justice league dark 002 2018 2 covers digital son of ultron-empire

**Comment by barbequesauce** [comment]
What branch and commit are you running? You’ll find this on the bottom of any webpage...

**Comment by evilhero** [comment]
Do you happen to have nzb2mylar (or something similar) running in nzbget against the comics category?

**Comment by evilhero** [comment]
Are these previous snatches that failed and already exist in the nzbget history? If these are retries (it sounds like it), then nzbget will just try to link to the existing file, but that's not the location that mylar was told it would be at initially.

Can you clear your nzbget history of the given items (remove all instances of it I believe its called), and then try the download again.

I'm assuming these are normal snatches within mylar, or are they retries as well?

**Comment by lostkt87** [comment]
I have retried downloading many times to see if it would post process correctly. The one above is an an example. I just now cleared all logs and now will post those results

**Comment by lostkt87** [comment]
2018-09-02 08:46:12 | INFO | [FOLDER-CHECK] Finished checking for newly snatched downloads
2018-09-02 08:46:12 | WARNING | There were no files located - check the debugging logs if you think this is in error.
2018-09-02 08:46:12 | INFO | there are 0 files.
2018-09-02 08:46:12 | DEBUG | [POST-PROCESSING] Manual Run initiated
2018-09-02 08:46:12 | DEBUG | [POST-PROCESSING] Manual Run Post-Processing enabled.
2018-09-02 08:46:12 | DEBUG | [POST-PROCESSING] Not using SABnzbd
2018-09-02 08:46:12 | DEBUG | [POST-PROCESSING] nzb folder: /volume1/NZBGet/dst/comics
2018-09-02 08:46:12 | DEBUG | [POST-PROCESSING] nzb name: Manual Run
2018-09-02 08:46:12 | INFO | [FOLDER-CHECK] Checking folder /volume1/NZBGet/dst/comics for newly snatched downloads
2018-09-02 08:46:04 | INFO | Update complete
2018-09-02 08:46:04 | DEBUG | ReScheduled job: DB Updater to 2018-09-02 13:51:04
2018-09-02 08:46:04 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2018-09-02 08:44:56 | INFO | Completed search request.
2018-09-02 08:44:56 | INFO | [UPDATER] Updated the status (Snatched) complete for Justice League Dark Issue: 2
2018-09-02 08:44:55 | DEBUG | [UPDATER] Provider is NZBGeek (newznab)
2018-09-02 08:44:55 | INFO | [UPDATER] Updating status to snatched
2018-09-02 08:44:55 | DEBUG | [UPDATER] issueid: 680706
2018-09-02 08:44:55 | DEBUG | [UPDATER] comicid: 112455
2018-09-02 08:44:55 | DEBUG | findit = found!
2018-09-02 08:44:54 | DEBUG | Deleted stale entry from nzblog for IssueID: 680706 [NZBGeek(newznab)]
2018-09-02 08:44:54 | ERROR | Uncaught exception: Traceback (most recent call last):File "/volume1/@appstore/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/volume1/@appstore/mylar/mylar/helpers.py", line 3045, in nzb_monitornzstat = nz.processor(item)File "/volume1/@appstore/mylar/mylar/nzbget.py", line 106, in processorreturn self.historycheck(nzbinfo)File "/volume1/@appstore/mylar/mylar/nzbget.py", line 171, in historycheckhq = [hs for hs in history if hs['NZBID'] == nzbid and ('SUCCESS' in hs['Status'] or ('COPY' in hs['Status'] and 'DELETED' not in hq[0]['Status']))]UnboundLocalError: local variable 'hq' referenced before assignment
2018-09-02 08:44:54 | WARNING | Unable to locate NZBID 10397 in active queue. Could it be finished already ?
2018-09-02 08:44:54 | DEBUG | valid queue result returned. Analyzing...
2018-09-02 08:44:54 | INFO | setting the nzbid for this download grabbed by NZBGeek(newznab) in the nzblog to : 56531ba55a04805ab34c4c79088b2aa1
2018-09-02 08:44:54 | DEBUG | Now checking the active queue of nzbget for the download
2018-09-02 08:44:54 | DEBUG | Found matching comic...preparing to send to Updater with IssueID: 680706 and nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:54 | INFO | Now loading from queue: {'status': True, 'apicall': True, 'NZBID': 10397, 'issueid': u'680706', 'comicid': u'112455'}
2018-09-02 08:44:54 | INFO | Successfully sent nzb to NZBGet!
2018-09-02 08:44:54 | DEBUG | sending now to http://lostkt87:Maugwi0910@192.168.2.129:6789/xmlrpc
2018-09-02 08:44:54 | DEBUG | Successfully changed permissions [0777 / 0660]
2018-09-02 08:44:54 | DEBUG | Cache Directory successfully found at : /volume1/@appstore/mylar/cache. Ensuring proper permissions.
2018-09-02 08:44:54 | DEBUG | [FILENAME] end nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-02 08:44:54 | DEBUG | [FILENAME] nzbname (\s): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-02 08:44:54 | DEBUG | [FILENAME] filename (remove chars): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-02 08:44:54 | DEBUG | filename within nzb: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire.nzb
2018-09-02 08:44:54 | DEBUG | Status code returned: 200
2018-09-02 08:44:53 | DEBUG | [PAYLOAD] Download URL: https://api.nzbgeek.info/api?apikey=YOUDONTNEEDTOKNOWTHIS&t=get&id=56531ba55a04805ab34c4c79088b2aa1 [VerifySSL:True]
2018-09-02 08:44:53 | DEBUG | Re-routing incorrect RSS URL response for NZBGeek to correct API
2018-09-02 08:44:53 | DEBUG | link given by: newznab
2018-09-02 08:44:53 | INFO | Found Justice League Dark (2018) issue: 2 using NZBGeek(newznab) [RSS]
2018-09-02 08:44:53 | DEBUG | issues match!
2018-09-02 08:44:53 | DEBUG | nzbname used for post-processing:Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | [SEARCHER] end nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | [SEARCHER] nzbname (\s): Justice League Dark 002 2018 2 covers digital Son of Ultron-Empire
2018-09-02 08:44:53 | DEBUG | [SEARCHER] nzbname (remove chars): Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | [SEARCHER] entry[title]: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | integer value of issue we have found : 2000
2018-09-02 08:44:53 | DEBUG | issue we found for is : 002
2018-09-02 08:44:53 | DEBUG | integer value of issue we are looking for : 2000
2018-09-02 08:44:53 | DEBUG | issue we are looking for is : 2
2018-09-02 08:44:53 | DEBUG | this should be a match!
2018-09-02 08:44:53 | DEBUG | it's a go captain... - we matched 100.0%!
2018-09-02 08:44:53 | DEBUG | Match to series : 100.0 %.
2018-09-02 08:44:53 | DEBUG | splitit-len:3
2018-09-02 08:44:53 | DEBUG | scount:3
2018-09-02 08:44:53 | DEBUG | word matched on : dark
2018-09-02 08:44:53 | DEBUG | 2 Comparing: dark .to. dark
2018-09-02 08:44:53 | DEBUG | scount : 2
2018-09-02 08:44:53 | DEBUG | splitit: dark
2018-09-02 08:44:53 | DEBUG | word matched on : league
2018-09-02 08:44:53 | DEBUG | 1 Comparing: league .to. league
2018-09-02 08:44:53 | DEBUG | scount : 1
2018-09-02 08:44:53 | DEBUG | splitit: league
2018-09-02 08:44:53 | DEBUG | word matched on : justice
2018-09-02 08:44:53 | DEBUG | 0 Comparing: justice .to. justice
2018-09-02 08:44:53 | DEBUG | scount : 0
2018-09-02 08:44:53 | DEBUG | splitit: justice
2018-09-02 08:44:53 | DEBUG | Watchlist-length: 3
2018-09-02 08:44:53 | DEBUG | search-length: 3
2018-09-02 08:44:53 | DEBUG | length match..proceeding
2018-09-02 08:44:53 | DEBUG | len-watchcomic : 3
2018-09-02 08:44:53 | DEBUG | splitst : 3
2018-09-02 08:44:53 | DEBUG | ['justice', 'league', 'dark'] watchlist word count: 3
2018-09-02 08:44:53 | DEBUG | ['justice', 'league', 'dark', '002'] nzb series word count: 3
2018-09-02 08:44:53 | DEBUG | adjusting from: justice league dark 002 to: 002
2018-09-02 08:44:53 | DEBUG | adjusted nzb comic and issue: justice league dark 002
2018-09-02 08:44:53 | DEBUG | original nzb comic and issue: justice league dark 002
2018-09-02 08:44:53 | DEBUG | Scanner detected: 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | covers detected: 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | mini-series detected : 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | 2. Bracket Word: 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | 2018 - right years match baby!
2018-09-02 08:44:53 | DEBUG | year looking for: 2018
2018-09-02 08:44:53 | DEBUG | year detected: 2018
2018-09-02 08:44:53 | DEBUG | 1. Bracket Word: 2018
2018-09-02 08:44:53 | DEBUG | ComVersChk : 2
2018-09-02 08:44:53 | DEBUG | UseFuzzy is : None
2018-09-02 08:44:53 | DEBUG | Comic: justice league dark 002
2018-09-02 08:44:53 | DEBUG | 0. Bracket Word: justice league dark 002
2018-09-02 08:44:53 | DEBUG | Cleantitle: justice league dark 002 (2018) 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | detected invalid nzb filename - attempting to detect year to continue
2018-09-02 08:44:53 | DEBUG | Cleantitle: justice league dark 002 2018 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | Entry: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | Thu, 23 Aug 2018 06:39:29 +0000 is after store date of 2018-08-22
2018-09-02 08:44:53 | DEBUG | size given as: 74.1 MB
2018-09-02 08:44:53 | DEBUG | comsize_b: 77714000
2018-09-02 08:44:53 | DEBUG | sub:Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | checking search result: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | Sun, 03 Dec 2017 13:05:44 +0000 is before store date of 2018-08-22. Ignoring search result as this is not the right issue

year detected: 2018
--
2018-09-02 08:44:53 | DEBUG | 1. Bracket Word: 2018
2018-09-02 08:44:53 | DEBUG | ComVersChk : 2
2018-09-02 08:44:53 | DEBUG | UseFuzzy is : None
2018-09-02 08:44:53 | DEBUG | Comic: justice league dark 002
2018-09-02 08:44:53 | DEBUG | 0. Bracket Word: justice league dark 002
2018-09-02 08:44:53 | DEBUG | Cleantitle: justice league dark 002 (2018) 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | detected invalid nzb filename - attempting to detect year to continue
2018-09-02 08:44:53 | DEBUG | Cleantitle: justice league dark 002 2018 2 covers digital son of ultron-empire
2018-09-02 08:44:53 | DEBUG | Entry: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | Thu, 23 Aug 2018 06:39:29 +0000 is after store date of 2018-08-22
2018-09-02 08:44:53 | DEBUG | size given as: 74.1 MB
2018-09-02 08:44:53 | DEBUG | comsize_b: 77714000
2018-09-02 08:44:53 | DEBUG | sub:Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | checking search result: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:53 | DEBUG | Sun, 03 Dec 2017 13:05:44 +0000 is before store date of 2018-08-22. Ignoring search result as this is not the right issue.
2018-09-02 08:44:53 | DEBUG | [CONV]pubdate: 2017-12-03 < storedate: 2018-08-21
2018-09-02 08:44:53 | DEBUG | size given as: 39.8 MB
2018-09-02 08:44:53 | DEBUG | comsize_b: 41696000
2018-09-02 08:44:53 | DEBUG | sub:For PostalPop - JL Dark 29 [1/1] - Justice League Dark 029 (2014) (Digital) (Cypher-Empire)
2018-09-02 08:44:53 | DEBUG | checking search result: For PostalPop - JL Dark 29 [1/1] - Justice League Dark 029 (2014) (Digital) (Cypher-Empire)
2018-09-02 08:44:53 | DEBUG | Sending request to RSS for Justice League Dark : 002 (2018)
2018-09-02 08:44:53 | DEBUG | findloop: 0 / findcount: 1
2018-09-02 08:44:53 | INFO | Shhh be very quiet...I'm looking for Justice League Dark issue: 2 (2018) using NZBGeek(newznab) [RSS].
2018-09-02 08:44:53 | DEBUG | using Newznab host of : NZBGeek
2018-09-02 08:44:53 | INFO | Could not find Issue 2 of Justice League Dark (2018) using nzb.su [rss]
2018-09-02 08:44:53 | ERROR | [PAYLOAD:NONE] Unable to download nzb from link: https://api.nzb.su/getnzb/d967bb4bfb54dbe97ee0cfaebeff87c2.nzb [https://api.nzb.su/getnzb/d967bb4bfb54dbe97ee0cfaebeff87c2.nzb]
2018-09-02 08:44:53 | DEBUG | Status code returned: 200
2018-09-02 08:44:52 | DEBUG | [PAYLOAD-NONE]Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL:True]
2018-09-02 08:44:52 | DEBUG | link given by: nzb.su
2018-09-02 08:44:52 | INFO | Found Justice League Dark (2018) issue: 2 using nzb.su [RSS]
2018-09-02 08:44:52 | DEBUG | issues match!
2018-09-02 08:44:52 | DEBUG | nzbname used for post-processing:Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:52 | DEBUG | [SEARCHER] end nzbname: Justice.League.Dark.002.2018.2.covers.digital.Son.of.Ultron-Empire
2018-09-02 08:44:52 | DEBUG | [SEARCHER] nzbname (\s): Justice League Dark 002 2018 2 covers digital Son of Ultron-Empire
2018-09-02 08:44:52 | DEBUG | [SEARCHER] nzbname (remove chars): Justice League Dark 002 2018 2 covers digital Son of Ultron-Empire
2018-09-02 08:44:52 | DEBUG | [SEARCHER] entry[title]: Justice League Dark 002 (2018) (2 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | integer value of issue we have found : 2000
2018-09-02 08:44:52 | DEBUG | issue we found for is : 002
2018-09-02 08:44:52 | DEBUG | integer value of issue we are looking for : 2000
2018-09-02 08:44:52 | DEBUG | issue we are looking for is : 2
2018-09-02 08:44:52 | DEBUG | this should be a match!
2018-09-02 08:44:52 | DEBUG | it's a go captain... - we matched 100.0%!
2018-09-02 08:44:52 | DEBUG | Match to series : 100.0 %.
2018-09-02 08:44:52 | DEBUG | splitit-len:3
2018-09-02 08:44:52 | DEBUG | scount:3
2018-09-02 08:44:52 | DEBUG | word matched on : dark
2018-09-02 08:44:52 | DEBUG | 2 Comparing: dark .to. dark
2018-09-02 08:44:52 | DEBUG | scount : 2
2018-09-02 08:44:52 | DEBUG | splitit: dark
2018-09-02 08:44:52 | DEBUG | word matched on : league
2018-09-02 08:44:52 | DEBUG | 1 Comparing: league .to. league
2018-09-02 08:44:52 | DEBUG | scount : 1
2018-09-02 08:44:52 | DEBUG | splitit: league
2018-09-02 08:44:52 | DEBUG | word matched on : justice
2018-09-02 08:44:52 | DEBUG | 0 Comparing: justice .to. justice
2018-09-02 08:44:52 | DEBUG | scount : 0
2018-09-02 08:44:52 | DEBUG | splitit: justice
2018-09-02 08:44:52 | DEBUG | Watchlist-length: 3
2018-09-02 08:44:52 | DEBUG | search-length: 3
2018-09-02 08:44:52 | DEBUG | length match..proceeding
2018-09-02 08:44:52 | DEBUG | len-watchcomic : 3
2018-09-02 08:44:52 | DEBUG | splitst : 3
2018-09-02 08:44:52 | DEBUG | ['justice', 'league', 'dark'] watchlist word count: 3
2018-09-02 08:44:52 | DEBUG | ['justice', 'league', 'dark', '002'] nzb series word count: 3
2018-09-02 08:44:52 | DEBUG | adjusting from: justice league dark 002 to: 002
2018-09-02 08:44:52 | DEBUG | adjusted nzb comic and issue: justice league dark 002
2018-09-02 08:44:52 | DEBUG | original nzb comic and issue: justice league dark 002
2018-09-02 08:44:52 | DEBUG | Scanner detected: son of ultron-empire
2018-09-02 08:44:52 | DEBUG | mini-series detected : son of ultron-empire
2018-09-02 08:44:52 | DEBUG | 7. Bracket Word: son of ultron-empire
2018-09-02 08:44:52 | DEBUG | digital edition detected
2018-09-02 08:44:52 | DEBUG | 5. Bracket Word: digital
2018-09-02 08:44:52 | DEBUG | covers detected: 2 covers
2018-09-02 08:44:52 | DEBUG | 3. Bracket Word: 2 covers
2018-09-02 08:44:52 | DEBUG | 2018 - right years match baby!
2018-09-02 08:44:52 | DEBUG | year looking for: 2018
2018-09-02 08:44:52 | DEBUG | year detected: 2018
2018-09-02 08:44:52 | DEBUG | 1. Bracket Word: 2018
2018-09-02 08:44:52 | DEBUG | ComVersChk : 2
2018-09-02 08:44:52 | DEBUG | UseFuzzy is : None
2018-09-02 08:44:52 | DEBUG | Comic: justice league dark 002
2018-09-02 08:44:52 | DEBUG | 0. Bracket Word: justice league dark 002
2018-09-02 08:44:52 | DEBUG | Cleantitle: justice league dark 002 (2018) (2 covers) (digital) (son of ultron-empire)
2018-09-02 08:44:52 | DEBUG | Cleantitle: justice league dark 002 (2018) (2 covers) (digital) (son of ultron-empire)
2018-09-02 08:44:52 | DEBUG | Entry: Justice League Dark 002 (2018) (2 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | Wed, 22 Aug 2018 18:52:37 -0400 is after store date of 2018-08-22
2018-09-02 08:44:52 | DEBUG | size given as: 74.1 MB
2018-09-02 08:44:52 | DEBUG | comsize_b: 77750554
2018-09-02 08:44:52 | DEBUG | sub:Justice League Dark 002 (2018) (2 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | checking search result: Justice League Dark 002 (2018) (2 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | Wed, 25 Jul 2018 16:31:15 -0400 is before store date of 2018-08-22. Ignoring search result as this is not the right issue.
2018-09-02 08:44:52 | DEBUG | [CONV]pubdate: 2018-07-25 < storedate: 2018-08-21
2018-09-02 08:44:52 | DEBUG | size given as: 34.5 MB
2018-09-02 08:44:52 | DEBUG | comsize_b: 36196499
2018-09-02 08:44:52 | DEBUG | sub:Justice League Dark 001 (2018) (3 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | checking search result: Justice League Dark 001 (2018) (3 covers) (digital) (Son of Ultron-Empire)
2018-09-02 08:44:52 | DEBUG | Sending request to RSS for Justice League Dark : 002 (2018)
2018-09-02 08:44:52 | DEBUG | findloop: 0 / findcount: 1
2018-09-02 08:44:52 | INFO | Shhh be very quiet...I'm looking for Justice League Dark issue: 2 (2018) using nzb.su [RSS]

**Comment by lostkt87** [comment]
Looks like it grabbed again I have a copy in nzbget
