### ISSUE TITLE
OPDS 500 Error

### ISSUE THREAD

**Issue by JacksonB** [evilhero/mylar#2076]
Running development branch, version 16ae80c1374f15d8d3b374ecdd6313273e49bae5. Up to date at the time of this posting.

My OPDS recent stopped working and I've narrowed it down to at least a couple of titles. When I try to browse to recent feed, I get the following error from the HTTP server. There are no errors in the mylar log files (with debug logging enabled).

```
http://host//opds?cmd=Recent
Traceback (most recent call last):
  File "/opt/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 5204, in opds
    data = op.fetchData()
  File "/opt/mylar/mylar/opds.py", line 84, in fetchData
    result = methodToCall(**self.kwargs)
  File "/opt/mylar/mylar/opds.py", line 457, in _Recent
    image = issuebook['ImageURL_ALT']
IndexError: No item with that key
```

When I browse to the specific title, I get a very similar error:

```
http://host/opds?cmd=Comic&comicid=96284
Traceback (most recent call last):
  File "/opt/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 5204, in opds
    data = op.fetchData()
  File "/opt/mylar/mylar/opds.py", line 84, in fetchData
    result = methodToCall(**self.kwargs)
  File "/opt/mylar/mylar/opds.py", line 385, in _Comic
    image = issue['ImageURL_ALT']
KeyError: 'ImageURL_ALT'
```

So far I've found this with two titles. Both have colons (:) in the name and both have annuals. But other titles with those attributes don't have this issue so I'm continuing to try to narrow it down.

**Comment by barbequesauce** [comment]
What are the titles, so I can try to replicate?

**Comment by JacksonB** [comment]
Peter Parker: Spectacular Spider-Man
Star Wars: Doctor Aphra

Issues persist after removing and then re-adding the titles.

**Comment by barbequesauce** [comment]
and you're seeing the issue only in the "recently added" view? not in the series view?

**Comment by JacksonB** [comment]
Of the two errors above, the first is when I browse to the recent view. The second is when I browse to the specific series. I included the OPDS urls at the top of the error but it looks like it blended in. My apologies.

**Comment by barbequesauce** [comment]
The good news is that we can recreate it and know what caused it.
The bad news is that it's OPDS-wide and not just those series.

Code diving now... stay tuned.

**Comment by barbequesauce** [comment]
#2077 should fix this.

**Comment by JacksonB** [comment]
Fixed! Thanks for looking into it so quickly!
