### ISSUE TITLE
Manual Post Processing failing suddenly

### ISSUE THREAD

**Issue by baz1860** [evilhero/mylar#2078]
I've had great success with manual post-processing (neither ComicRN or CDH in NZBGet work for me for some reason) but it's stopped working in the last day...

As soon as I trigger it, this appears in the log file - hopefully it means more to you than it does to me!

2018-09-14 21:27:58 | ERROR | Uncaught exception: Traceback (most recent call last):File "/Applications/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/Applications/mylar/mylar/PostProcessor.py", line 709, in Processif datematch == 'True':UnboundLocalError: local variable 'datematch' referenced before assignment

**Comment by evilhero** [comment]
Without the debug log showing the post-processing from start to the error, it's really hard to figure out what's happening from just an error message alone. 

Please post the debug log and we can look further into things.

**Comment by baz1860** [comment]
So, I started manually manual-processing before I saw your reply, and the only thing I had moved out of the folder was Swamp Thing (2011) - in doing so manual post-processing appears to be working again and thus I have no debug logs... Thank you though...
