### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pjremy** [evilhero/mylar#2085]
I have the following error when deleting comic:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/Mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/Mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 919, in deleteSeries
    helpers.ComicSort(sequence='update')
  File "/opt/Mylar/mylar/helpers.py", line 765, in ComicSort
    mylar.COMICSORT['LastOrderID'] = mylar.COMICSORT['SortOrder'][placemnt]['ComicID']
IndexError: list index out of range

Thank you in advance.

**Comment by evilhero** [comment]
How are you deleting the series and from what page?

Are you up to date on master / development?

Are you deleting the series on a given browser tab, and then going to another tab (or browser) to perform some other action and getting the error?
