### ISSUE TITLE
Uncaught exception after successful search NZB not sent to downloader

### ISSUE THREAD

**Issue by roofuskit** [evilhero/mylar#2105]
Here is the log. It looks like everything went well until the uncaught exception error. Nothing ended up in history either.

2018-10-26 10:45:58 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 336, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/helpers.py", line 3007, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/app/mylar/mylar/search.py", line 2118, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)File "/app/mylar/mylar/search.py", line 348, in search_initfindit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)File "/app/mylar/mylar/search.py", line 1785, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)File "/app/mylar/mylar/search.py", line 2719, in searcherss = nzbget.NZBGet()File "/app/mylar/mylar/nzbget.py", line 38, in __init__val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignment
-- | -- | --
2018-10-26 10:45:58 | DEBUG | Cache Directory successfully found at : /config/mylar/cache
2018-10-26 10:45:58 | DEBUG | [FILENAME] end nzbname: X-Men.Black.-.Juggernaut.001.2018.Digital.Zone-Empire.nzb
2018-10-26 10:45:58 | DEBUG | [FILENAME] nzbname (\s): X-Men.Black.-.Juggernaut.001.2018.Digital.Zone-Empire.nzb
2018-10-26 10:45:58 | DEBUG | [FILENAME] filename (remove chars): X-Men.Black.-.Juggernaut.001.2018.Digital.Zone-Empire.nzb
2018-10-26 10:45:58 | DEBUG | filename within nzb: X-Men.Black.-.Juggernaut.001.(2018).(Digital).(Zone-Empire).nzb
2018-10-26 10:45:58 | DEBUG | Status code returned: 200
2018-10-26 10:45:56 | DEBUG | [PAYLOAD-NONE]Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL:True]
2018-10-26 10:45:56 | DEBUG | [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
2018-10-26 10:45:56 | INFO | [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
2018-10-26 10:45:56 | INFO | prov : dognzb[afe076500a314db9290ea0d80634f007]
2018-10-26 10:45:56 | INFO | oneoff: False
2018-10-26 10:45:56 | INFO | IssueID: 689883
2018-10-26 10:45:56 | INFO | nzbid: afe076500a314db9290ea0d80634f007
2018-10-26 10:45:56 | DEBUG | link given by: dognzb
2018-10-26 10:45:56 | INFO | Found X-Men: Black - Juggernaut (2018) issue: 1 using dognzb
2018-10-26 10:45:56 | DEBUG | issues match!
2018-10-26 10:45:56 | DEBUG | nzbname used for post-processing:X-Men.Black.-.Juggernaut.001.2018.Digital.Zone-Empire
2018-10-26 10:45:56 | DEBUG | [SEARCHER] end nzbname: X-Men.Black.-.Juggernaut.001.2018.Digital.Zone-Empire
2018-10-26 10:45:56 | DEBUG | [SEARCHER] nzbname (\s): X-Men Black - Juggernaut 001 2018 Digital Zone-Empire
2018-10-26 10:45:56 | DEBUG | [SEARCHER] nzbname (remove chars): X-Men.Black.-.Juggernaut.001. 2018 . Digital . Zone-Empire
2018-10-26 10:45:56 | DEBUG | [SEARCHER] entry[title]: X-Men.Black.-.Juggernaut.001.(2018).(Digital).(Zone-Empire)
2018-10-26 10:45:56 | DEBUG | integer value of issue we have found : 1000
2018-10-26 10:45:56 | DEBUG | issue we found for is : 001
2018-10-26 10:45:56 | DEBUG | integer value of issue we are looking for : 1000
2018-10-26 10:45:56 | DEBUG | issue we are looking for is : 1
2018-10-26 10:45:56 | DEBUG | this should be a match!
2018-10-26 10:45:56 | DEBUG | it's a go captain... - we matched 100.0%!
2018-10-26 10:45:56 | DEBUG | Match to series : 100.0 %.
2018-10-26 10:45:56 | DEBUG | splitit-len:4
2018-10-26 10:45:56 | DEBUG | scount:4
2018-10-26 10:45:56 | DEBUG | word matched on : juggernaut
2018-10-26 10:45:56 | DEBUG | 3 Comparing: juggernaut .to. juggernaut
2018-10-26 10:45:56 | DEBUG | scount : 3
2018-10-26 10:45:56 | DEBUG | splitit: juggernaut
2018-10-26 10:45:56 | DEBUG | word matched on : black
2018-10-26 10:45:56 | DEBUG | 2 Comparing: black .to. black
2018-10-26 10:45:56 | DEBUG | scount : 2
2018-10-26 10:45:56 | DEBUG | splitit: black
2018-10-26 10:45:56 | DEBUG | word matched on : men
2018-10-26 10:45:56 | DEBUG | 1 Comparing: men .to. men
2018-10-26 10:45:56 | DEBUG | scount : 1
2018-10-26 10:45:56 | DEBUG | splitit: men
2018-10-26 10:45:56 | DEBUG | word matched on : x
2018-10-26 10:45:56 | DEBUG | 0 Comparing: x .to. x
2018-10-26 10:45:56 | DEBUG | scount : 0
2018-10-26 10:45:56 | DEBUG | splitit: x
2018-10-26 10:45:56 | DEBUG | Watchlist-length: 4
2018-10-26 10:45:56 | DEBUG | search-length: 4
2018-10-26 10:45:56 | DEBUG | length match..proceeding
2018-10-26 10:45:56 | DEBUG | len-watchcomic : 4
2018-10-26 10:45:56 | DEBUG | splitst : 4
2018-10-26 10:45:56 | DEBUG | ['x', 'men', 'black', 'juggernaut'] watchlist word count: 4
2018-10-26 10:45:56 | DEBUG | ['x', 'men', 'black', 'juggernaut', '001'] nzb series word count: 4
2018-10-26 10:45:56 | DEBUG | adjusting from: x men black juggernaut 001 to: 001
2018-10-26 10:45:56 | DEBUG | adjusted nzb comic and issue: x men black juggernaut 001
2018-10-26 10:45:56 | DEBUG | There is a - present in the series title. Ignoring position: 12
2018-10-26 10:45:56 | DEBUG | [X-Men: Black - Juggernaut] I have found a - within the nzbname @ position: 12
2018-10-26 10:45:56 | DEBUG | There is a - present in the series title. Ignoring position: 1
2018-10-26 10:45:56 | DEBUG | [X-Men: Black - Juggernaut] I have found a - within the nzbname @ position: 1
2018-10-26 10:45:56 | DEBUG | original nzb comic and issue: x-men black - juggernaut 001
2018-10-26 10:45:56 | DEBUG | Scanner detected: zone-empire
2018-10-26 10:45:56 | DEBUG | 5. Bracket Word: zone-empire
2018-10-26 10:45:56 | DEBUG | digital edition detected
2018-10-26 10:45:56 | DEBUG | 3. Bracket Word: digital
2018-10-26 10:45:56 | DEBUG | 2018 - right years match baby!
2018-10-26 10:45:56 | DEBUG | year looking for: 2018
2018-10-26 10:45:56 | DEBUG | year detected: 2018
2018-10-26 10:45:56 | DEBUG | 1. Bracket Word: 2018
2018-10-26 10:45:56 | DEBUG | Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
2018-10-26 10:45:56 | DEBUG | ComVersChk : 0
2018-10-26 10:45:56 | DEBUG | UseFuzzy is : None
2018-10-26 10:45:56 | DEBUG | Comic: x-men black - juggernaut 001
2018-10-26 10:45:56 | DEBUG | 0. Bracket Word: x-men black - juggernaut 001
2018-10-26 10:45:56 | DEBUG | Cleantitle: x-men black - juggernaut 001 (2018) (digital) (zone-empire)
2018-10-26 10:45:56 | DEBUG | Cleantitle: x-men black - juggernaut 001 (2018) (digital) (zone-empire)
2018-10-26 10:45:56 | DEBUG | Entry: X-Men.Black.-.Juggernaut.001.(2018).(Digital).(Zone-Empire)
2018-10-26 10:45:56 | DEBUG | Wed, 24 Oct 2018 11:05:14 -0600 is after store date of 2018-10-24
2018-10-26 10:45:56 | DEBUG | sub:X-Men.Black.-.Juggernaut.001.(2018).(Digital).(Zone-Empire)
2018-10-26 10:45:56 | DEBUG | checking search result: X-Men.Black.-.Juggernaut.001.(2018).(Digital).(Zone-Empire)
2018-10-26 10:45:56 | INFO | no errors on data retrieval...proceeding
2018-10-26 10:45:55 | DEBUG | [SSL: True] Search URL: https://api.dognzb.cr/api?t=search&q=x%20men%20black%20juggernaut%20001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2018-10-26 10:45:55 | INFO | pausing for 60 seconds before continuing to avoid hammering
2018-10-26 10:45:55 | DEBUG | findloop: 0 / findcount: 1
2018-10-26 10:45:55 | INFO | Shhh be very quiet...I'm looking for X-Men Black - Juggernaut issue: 1 (2018) using dognzb.
2018-10-26 10:45:55 | INFO | Alternate Search pattern detected...re-adjusting to : X-Men Black - Juggernaut
2018-10-26 10:45:55 | INFO | no errors on data retrieval...proceeding
2018-10-26 10:45:55 | DEBUG | [SSL: True] Search URL: https://api.dognzb.cr/api?t=search&q=x%20men%20black%20juggernaut%20001&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2018-10-26 10:45:55 | INFO | pausing for 60 seconds before continuing to avoid hammering
2018-10-26 10:45:55 | DEBUG | findloop: 0 / findcount: 1
2018-10-26 10:45:55 | INFO | Shhh be very quiet...I'm looking for X-Men: Black - Juggernaut issue: 1 (2018) using dognzb.
2018-10-26 10:45:55 | DEBUG | Initiating Search via : api
2018-10-26 10:45:55 | DEBUG | srchloop: 2
2018-10-26 10:45:55 | INFO | Could not find Issue 1 of X-Men: Black - Juggernaut (2018) using LOCAL [rss]
2018-10-26 10:45:55 | DEBUG | Sending request to RSS for X-Men Black - Juggernaut : 1 (2018)
2018-10-26 10:45:55 | DEBUG | findloop: 0 / findcount: 1
2018-10-26 10:45:55 | INFO | Shhh be very quiet...I'm looking for X-Men Black - Juggernaut issue: 1 (2018) using LOCAL(newznab) [RSS].
2018-10-26 10:45:55 | DEBUG | using Newznab host of : LOCAL
2018-10-26 10:45:55 | INFO | Alternate Search pattern detected...re-adjusting to : X-Men Black - Juggernaut
2018-10-26 10:45:55 | DEBUG | Sending request to RSS for X-Men: Black - Juggernaut : 1 (2018)

**Comment by evilhero** [comment]
This just came up in some other issues - you need to specify a protocol for your nzbget host address within Mylar (either http or https). Save the config once that's done and you should be good to go thereafter.

**Comment by roofuskit** [comment]
Well that's a little embarrassing considering it gives the http:// in the example directly below it. Thank you! Working perfectly now.
