### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' when adding title

### ISSUE THREAD

**Issue by PCurd** [evilhero/mylar#2129]
Adding https://comicvine.gamespot.com/lone-wolf-and-cub/4050-9319/ gave error above, full output below. Looks like it might be related to the new GN handling code since this title is sort of a collection of GNs.

```
03-Dec-2018 09:57:54 - INFO :: mylar.addComictoDB.117 : Thread-24 : Now adding/updating: Lone Wolf and Cub
03-Dec-2018 09:57:54 - INFO :: mylar.addComictoDB.170 : Thread-24 : Sucessfully retrieved details for Lone Wolf and Cub
03-Dec-2018 09:57:54 - INFO :: mylar.addComictoDB.176 : Thread-24 : Previous version detected as None - seeing if update required
03-Dec-2018 09:57:54 - WARNING :: mylar.validateAndCreateDirectory.1509 : Thread-24 : [DIRECTORY-CHECK] Could not find comic directory: M:\Comics\Lone Wolf and Cub (2000)
03-Dec-2018 09:57:54 - INFO :: mylar.validateAndCreateDirectory.1512 : Thread-24 : [DIRECTORY-CHECK] Creating comic directory (0777) : M:\Comics\Lone Wolf and Cub (2000)
03-Dec-2018 09:57:56 - INFO :: mylar.getImage.3531 : Thread-24 : Attempting to retrieve the comic image for series
03-Dec-2018 09:58:01 - INFO :: mylar.addComictoDB.361 : Thread-24 : Sucessfully retrieved issue details for Lone Wolf and Cub
03-Dec-2018 09:58:08 - INFO :: mylar.updateissuedata.1104 : Thread-24 : Now adding/updating issues for Lone Wolf and Cub
03-Dec-2018 09:58:10 - INFO :: mylar.addComictoDB.408 : Thread-24 : Updating complete for: Lone Wolf and Cub
03-Dec-2018 09:58:10 - INFO :: mylar.forceRescan.937 : Thread-24 : [FILE-RESCAN] Now checking files for Lone Wolf and Cub (2000) in M:\Comics\Lone Wolf and Cub (2000)
03-Dec-2018 09:58:10 - INFO :: mylar.traverse_directories.1318 : Thread-24 : there are 10 files.
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: The] Error detecting issue # - ignoring this result : The
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Assassing11s] Error detecting issue # - ignoring this result : Assassing11s
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Road] Error detecting issue # - ignoring this result : Road
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2000)] Error detecting issue # - ignoring this result : (2000)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '01', 'position': 4}
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: The] Error detecting issue # - ignoring this result : The
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Gateless] Error detecting issue # - ignoring this result : Gateless
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Barrier] Error detecting issue # - ignoring this result : Barrier
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2000)] Error detecting issue # - ignoring this result : (2000)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '02', 'position': 4}
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:10 - ERROR :: mylar.parseit.349 : Thread-24 : Exception: could not convert string to float: the
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: The] Error detecting issue # - ignoring this result : The
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Flute] Error detecting issue # - ignoring this result : Flute
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: of] Error detecting issue # - ignoring this result : of
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: the] Error detecting issue # - ignoring this result : the
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Fallen] Error detecting issue # - ignoring this result : Fallen
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Tiger] Error detecting issue # - ignoring this result : Tiger
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2000)] Error detecting issue # - ignoring this result : (2000)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '03', 'position': 4}
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: The] Error detecting issue # - ignoring this result : The
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Bell] Error detecting issue # - ignoring this result : Bell
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Warden] Error detecting issue # - ignoring this result : Warden
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2000)] Error detecting issue # - ignoring this result : (2000)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '04', 'position': 4}
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Black] Error detecting issue # - ignoring this result : Black
03-Dec-2018 09:58:10 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wind] Error detecting issue # - ignoring this result : Wind
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '05', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lanterns] Error detecting issue # - ignoring this result : Lanterns
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: for] Error detecting issue # - ignoring this result : for
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: the] Error detecting issue # - ignoring this result : the
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Dead] Error detecting issue # - ignoring this result : Dead
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '06', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cloud] Error detecting issue # - ignoring this result : Cloud
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Dragon] Error detecting issue # - ignoring this result : Dragon
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wind] Error detecting issue # - ignoring this result : Wind
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Tiger] Error detecting issue # - ignoring this result : Tiger
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '07', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - ERROR :: mylar.parseit.349 : Thread-24 : Exception: could not convert string to float: Death
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Chains] Error detecting issue # - ignoring this result : Chains
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: of] Error detecting issue # - ignoring this result : of
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Death] Error detecting issue # - ignoring this result : Death
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '08', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - ERROR :: mylar.parseit.349 : Thread-24 : Exception: could not convert string to float: the
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Echo] Error detecting issue # - ignoring this result : Echo
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: of] Error detecting issue # - ignoring this result : of
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: the] Error detecting issue # - ignoring this result : the
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Assassin] Error detecting issue # - ignoring this result : Assassin
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '09', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Lone] Error detecting issue # - ignoring this result : Lone
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Wolf] Error detecting issue # - ignoring this result : Wolf
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: and] Error detecting issue # - ignoring this result : and
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Cub] Error detecting issue # - ignoring this result : Cub
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: -] Error detecting issue # - ignoring this result : -
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Hostage] Error detecting issue # - ignoring this result : Hostage
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: Child] Error detecting issue # - ignoring this result : Child
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (2001)] Error detecting issue # - ignoring this result : (2001)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.697 : Thread-24 : [could not convert string to float: (digital)] Error detecting issue # - ignoring this result : (digital)
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.851 : Thread-24 : UNKNOWN TPB/GN detected. Volume assumption is number: {'volume': '10', 'position': 4}
03-Dec-2018 09:58:11 - INFO :: mylar.parseit.1042 : Thread-24 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
03-Dec-2018 09:58:11 - ERROR :: mylar.excepthook.315 : Thread-24 : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 430, in addComictoDB
    updater.forceRescan(comicid)
  File "D:\Mylar\mylar\mylar\updater.py", line 1067, in forceRescan
    temploc = tmpfc['JusttheDigits'].replace('_', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'

Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 430, in addComictoDB
    updater.forceRescan(comicid)
  File "D:\Mylar\mylar\mylar\updater.py", line 1067, in forceRescan
    temploc = tmpfc['JusttheDigits'].replace('_', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by evilhero** [comment]
Yeah something with the file parser it looks like - the series adds fine (just tested it), but when it goes to scan the directory for issues it's choking on the filename for some reason.

I'm going to guess it's because the series on CV isn't designated as  TPB/GN, so Mylar is assuming it's a normal issue-type series that should contain issue numbers. Your filenames probably don't have issue numbers, since they're considered TPB's, so it's erroring.

Can you confirm some of the filenames that you have in that series directory so I can run some quick mock up tests on my end to try and fix the issue ?

**Comment by PCurd** [comment]
Sorry for the delay, the files are all named like:

```
Shaman King v01 (2003) (Digital) (AnHeroGold-Empire).cbz
Shaman King v02 (2004) (Digital) (AnHeroGold-Empire).cbz
...
Shaman King v32 (2011) (Digital) (AnHeroGold-Empire).cbz
```

With the v number and the year increasing where necessary

**Comment by evilhero** [comment]
@BenBeyond Those are actual regular series, what @PCurd is talking about is in regards to TPB/GN's being improperly scanned in. So entirely different error is occurring on your end - please create a separate issue and include the relevant information along with a debug log showing the error in context and I can help further.

**Comment by gamergeekv2** [comment]
I'm having the same issue as @BenBeyond but I hadn't seen he opened a ticket yet so I opened one. #2136

**Comment by stoofz** [comment]
Similar issue

  | ERROR | Exception: could not convert string to float: West

**Comment by evilhero** [comment]
Exception isn't an error - it's a trapped exception that does not break anything. If it was a traceback error, then it's an actual error. Also one line, no help.

**Comment by evilhero** [comment]
This has all been fixed in the development build - but you need to enable the option for series that Mylar has considered a Print edition vs TPB/GN. The file parser that is used is dependent on the Edition setting within the series detail page. If this is set to the wrong type, it won't be able to scan the files properly (ie. if it's set to Print and you're trying to scan in volume editions it won't be able to pick anything up and will throw a traceback error). The file parser definitions are currently being used when ReChecking Files, Post-Processing, and searching (this is in the dev build only atm). We currently need to fix some of the error messages being produced so that users can more readily know what's happening when something fails due to being the wrong Edition type.

You can change the Edition and ```force it to TPB/GN``` for series that Mylar thinks is a Print, or you can ```force it to Print``` for series that Mylar thinks is a TPB/GN mistakingly. This is all accomplished on the Edit tab for the given series and the option will change dynamically depending on what Mylar initially determines the series edition type is: 
![tpbgn](https://user-images.githubusercontent.com/909424/50602621-b9abe400-0e85-11e9-8467-0a9da71ecb78.png)

Once you enable the option, and click on Update the Edition field will update accordingly to the correct value and the correct file parser will be used. As a reference, this has been tested against the series indicated in this thread, as well as some additional ones.

You can also now use the ```$Type``` variable in your Folder Format / File Format string in order to indicate in your folders/filenames that a given series/issue is a TPB.

**Comment by PCurd** [comment]
That looks like it did it, all files detected - thanks! I can see that adding "volume" into the filename will fix it for future files, I'll try to remember to do "Volume 01" instead of "v01" in future. Thanks!
