### ISSUE TITLE
Internal Error 500 when clicking on "This Week" (pulllist)

### ISSUE THREAD

**Issue by lamahmud** [evilhero/mylar#2133]
Hi,
I'm on the development version.  When I click on the pullist (This Week button), I get the following error:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Volumes/MacHD/Users/lam/Applications/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Volumes/MacHD/Users/lam/Applications/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Volumes/MacHD/Users/lam/Applications/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Volumes/MacHD/Users/lam/Applications/mylar/mylar/webserve.py", line 1629, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/Volumes/MacHD/Users/lam/Applications/mylar/mylar/webserve.py", line 1919, in manualpull
    weeklypull.pullit()
  File "/Volumes/MacHD/Users/lam/Applications/mylar/mylar/weeklypull.py", line 359, in pullit
    comicnm = issname[1]
IndexError: list index out of range
Powered by CherryPy 3.6.0

The debug logs show:

2018-12-06 14:13:03 | INFO | Preparing to update to the new listing.
-- | -- | --
2018-12-06 14:13:03 | DEBUG | today: 20181128
2018-12-06 14:13:03 | DEBUG | shipdate: 20181205
2018-12-06 14:13:03 | DEBUG | no substitues.csv file located - not performing substitutions on weekly pull list
2018-12-06 14:13:03 | INFO | [PULL-LIST] Populating & Loading pull-list data from file
2018-12-06 14:13:03 | INFO | Weekly pull list present - checking if it's up-to-date..
2018-12-06 14:13:03 | INFO | ALT_PULL: 0 PULLBYFILE: True week: 48 year: 2018
2018-12-06 14:13:03 | INFO | trying to repopulate to week: 48-2018
2018-12-06 14:12:51 | DEBUG | Configuration written to disk.
2018-12-06 14:12:51 | DEBUG | Provider Order is now set : {'1': u'MyAnonamouse', '0': 'Experimental', '2': u'TPB'}
2018-12-06 14:12:51 | DEBUG | 3 entries are enabled.
2018-12-06 14:12:51 | DEBUG | 1 Disabled entries exist, removing from ordering sequence
2018-12-06 14:12:51 | DEBUG | existing Order count does not match New Order count
2018-12-06 14:12:51 | DEBUG | Provider sequence already pre-exists. Re-loading and adding/remove any new entries
2018-12-06 14:12:51 | DEBUG | Original provider_order sequence: {'1': 'Experimental', '0': 'public torrents', '3': u'TPB', '2': u'MyAnonamouse'}
2018-12-06 14:12:51 | DEBUG | Writing configuration to file
2018-12-06 14:12:51 | INFO | Now saving config...
2018-12-06 14:12:03 | INFO | Preparing to update to the new listing.
2018-12-06 14:12:03 | DEBUG | today: 20181128
2018-12-06 14:12:03 | DEBUG | shipdate: 20181205
2018-12-06 14:12:03 | DEBUG | no substitues.csv file located - not performing substitutions on weekly pull list
2018-12-06 14:12:03 | INFO | [PULL-LIST] Populating & Loading pull-list data from file
2018-12-06 14:12:03 | INFO | Weekly pull list present - checking if it's up-to-date..
2018-12-06 14:12:03 | INFO | ALT_PULL: 0 PULLBYFILE: True week: 48 year: 2018
2018-12-06 14:12:03 | INFO | trying to repopulate to week: 48-2018
2018-12-06 14:11:59 | DEBUG | If you can read this message, debug logging is now working
2018-12-06 14:11:59 | INFO | Verbose (DEBUG) logging is enabled
2018-12-06 14:10:47 | INFO | Preparing to update to the new listing.
2018-12-06 14:10:47 | INFO | [PULL-LIST] Populating & Loading pull-list data from file
2018-12-06 14:10:47 | INFO | Weekly pull list present - checking if it's up-to-date..

**Comment by evilhero** [comment]
Make sure your alt_pull value is set to 2 in the config.ini (with Mylar shutdown). After you change the value, and save the config, start Mylar back up and it should automatically start to recreate the pull properly. If it doesn't start to recreate it - go into the Weekly tab and click on the ```Recreate Pullist``` option.

You can tell if you're on the proper alt_pull method easily by just looking at the pull-list itself. If the titles are all capitalised, you're on alt_pull = 0, and you need to manually change it.
