### ISSUE TITLE
500 Internal Server Error when clicking on This Week

### ISSUE THREAD

**Issue by inc0gnitus** [evilhero/mylar#2139]
For the couple of weeks, when I click This Week it throws an internal server error. Running fully updated (via "git pull") and haven't seen any other issues.

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/Mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/Mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 1629, in pullist
    repoll = self.manualpull(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "/opt/Mylar/mylar/webserve.py", line 1919, in manualpull
    weeklypull.pullit()
  File "/opt/Mylar/mylar/weeklypull.py", line 359, in pullit
    comicnm = issname[1]
IndexError: list index out of range
Powered by CherryPy 3.6.0
```

Not sure if there's a file somewhere that's messed up or what to do to fix it. 

The mylar log has:

```
10-Dec-2018 13:45:36 - INFO    :: mylar.pullist.1628 : CP Server Thread-10 : trying to repopulate to week: 49-2018
10-Dec-2018 13:45:36 - INFO    :: mylar.manualpull.1914 : CP Server Thread-10 : ALT_PULL: 0 PULLBYFILE: True week: 49 year: 2018
10-Dec-2018 13:45:37 - INFO    :: mylar.pullit.41 : CP Server Thread-10 : Weekly pull list present - checking if it's up-to-date..
10-Dec-2018 13:45:37 - INFO    :: mylar.pullit.89 : CP Server Thread-10 : [PULL-LIST] Populating & Loading pull-list data from file
```

Thanks.

**Comment by evilhero** [comment]
I'm pretty sure your ```alt_pull``` value in the config.ini is set to either ```0``` or ```1```, when it should be set to ```2``` (ie. ```alt_pull = 2```). Make sure Mylar isn't running when you change the value, then start up Mylar and go to the Weekly tab. It should recreate the pull-list on startup, but if it doesn't and you can get into the weekly pull, do a ```Recreate Pullist``` option from the top menu options and you'll be back up and running.

**Comment by inc0gnitus** [comment]
That's what it was. Changing that fixed it right now. Thanks for such a quick response!
