### ISSUE TITLE
Connection Refused on Manual Search

### ISSUE THREAD

**Issue by Romdeau4** [evilhero/mylar#2141]
New docker image attempting to use Mylar with Torrents. I successfully added the ComicVine API and torrent client, but when attempting to search for a comic, the following error is generated:
```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/helpers.py", line 3007, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/app/mylar/mylar/search.py", line 2141, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)
File "/app/mylar/mylar/search.py", line 336, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)
File "/app/mylar/mylar/search.py", line 623, in NZB_SEARCH
bb = ww.wwt_connect()
File "/app/mylar/mylar/wwt.py", line 49, in wwt_connect
cf_cookievalue, cf_user_agent = s.get_tokens(newurl, user_agent=mylar.CV_HEADERS['User-Agent'])
File "/app/mylar/lib/cfscrape/__init__.py", line 177, in get_tokens
resp = scraper.get(url, **kwargs)
File "/app/mylar/lib/requests/sessions.py", line 477, in get
return self.request('GET', url, **kwargs)
File "/app/mylar/lib/cfscrape/__init__.py", line 64, in request
resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
File "/app/mylar/lib/requests/sessions.py", line 465, in request
resp = self.send(prep, **send_kwargs)
File "/app/mylar/lib/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/app/mylar/lib/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by evilhero** [comment]
WWT changed their domain from the .me TLD to the .to TLD - the fix is in development atm, and I'm nowhere near a pc to push anything out.

2 files need to be fixed:
- ```mylar/__init__.py```: 
find the WWTURL reference and change the new domain name on ~ line 246
```WWTURL = 'https://www.worldwidetorrents.to/'```
- ```mylar/wwt.py```: change the self.url to the new domain name on ~line 31
```self.url = 'https://www.worldwidetorrents.to/'```

delete the .pyc files that are in the mylar directory and you'll be good to go.
