### ISSUE TITLE
Post Processing not Working

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#2144]
![image](https://user-images.githubusercontent.com/5505883/49954254-10994b80-fece-11e8-9481-67a5f7c5792c.png)

I am trying to manually PP my download folder, which I have done in the past to quickly organize recently downloaded issues.  There are probably 7 new issues in that folder, for series/volumes that already exist in Mylar.  If I wait or force the folder monitor job, it says the same at the end...

**Comment by evilhero** [comment]
Are you up to date on the branch you're running? A bunch of fixes went into development a few days ago that fixed some post-processing problems.

**Comment by BenBeyond** [comment]
![image](https://user-images.githubusercontent.com/5505883/49955554-19d7e780-fed1-11e8-8f11-6e2d1e607379.png)

I am pretty sure I am up to date, checking for a new version doesn't return any new code...

**Comment by evilhero** [comment]
Enable debug logging and try the manual scan. There's something happening therein that will explain more as to what's happening (can't duplicate any error atm on my end but that's my local installation).

**Comment by Lusiphur** [comment]
Same issue for me.

Something interesting in my log tho ..


2018-12-14 20:03:44 | ERROR | Uncaught exception: Traceback (most recent call last):File "/opt/Mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/opt/Mylar/mylar/PostProcessor.py", line 556, in Processtemploc= just_the_digits.replace('_', ' ')AttributeError: 'NoneType' object has no attribute 'replace'
-- | -- | --
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: From Hell: Master Edition-114218] Match verified for From Hell - Master Edition 002 (2018) (Digital) (Zone-Empire).cbr
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : From Hell - Master Edition [114218]
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][CLOCATION] /hyena_pool/Incoming/Comics
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] IssueYear (issyr) is 2019
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against From Hell: Master Edition-114218
2018-12-14 20:03:44 | DEBUG | temploc: 002
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING] Alternate series naming detected: From Hell
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: Cemetery Beach-113439] Match verified for Cemetery Beach 004 (2018) (Digital) (Zone-Empire).cbr
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : Cemetery Beach [113439]
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][CLOCATION] /hyena_pool/Incoming/Comics
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] IssueYear (issyr) is 2019
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against Cemetery Beach-113439
2018-12-14 20:03:44 | DEBUG | temploc: 004
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: From Hell: Master Edition-114218] Match verified for From Hell - Master Edition 001 (2018) (Digital) (Zone-Empire).cbr
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : From Hell - Master Edition [114218]
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][CLOCATION] /hyena_pool/Incoming/Comics
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY][Lone Volume MATCH] Volume label of None indicates only volume for this series on your watchlist.
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][ISSUE-VERIFY] Now checking against From Hell: Master Edition-114218
2018-12-14 20:03:44 | DEBUG | temploc: 001
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING] Alternate series naming detected: From Hell
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][SUCCESSFUL MATCH: Birthright-77405] Match verified for Birthright 034 (2018) (digital) (Son of Ultron-Empire).cbr
2018-12-14 20:03:44 | DEBUG | [POST-PROCESSING][DEFINITIVE-NAME MATCH] Definitive name match exactly to : Birthright [77405]


Configuration Options
Mylar Version: development
-- 
git build 75d77546fe88d56a04ca9d9b10d6120b76e7b3d2.
Python Version : 2.7.12Language : en_GB.UTF-8
--

**Comment by evilhero** [comment]
@BenBeyond are there any specials/annuals in your post-processing directory that you're trying to post-process ? 

There are still some problems with annuals/specials being post-processed correctly if you have the annuals integration enabled (or I guess if you don't depending on the circumstance). 

Can you also verify what your annuals integration option is set to?

**Comment by judzk** [comment]
Same here with annual integration
`2018-12-16 16:00:02 | INFO | [POST-PROCESSING] No matches for Manual Run ... exiting.
-- | -- | --
2018-12-16 16:00:02 | DEBUG | [POST-PROCESSING] There are 0 files found that match on your watchlist, 0 files are considered one-off's, and 43 files do not match anything
2018-12-16 16:00:02 | ERROR | [POST-PROCESSING] No Series in Watchlist - checking against Story Arcs (just in case). If I do not find anything, maybe you should be running Import?
2018-12-16 16:00:02 | INFO | I have located 43 files that I should be able to post-process. Continuing...

`

**Comment by BenBeyond** [comment]
My annual integration is turned off. I had a couple of annuals in the directory, but none that I wanted or had separate annual series to match into, they were just lumped in with larger, full comic run downloads...

I have removed those unwanted annuals and tried another manual processing, but the same results...

**Comment by evilhero** [comment]
Can you paste in the files in the folder you're trying to post-process? One of them is holding things back, only I don't know what files are in the directory so I can't even mock up some fake names to try and duplicate.

**Comment by judzk** [comment]
Ok i tried to PP one by one, here the names that mess with my post processing
Daughters of the Dragon 002 (2018) (Digital Original) (Zone-Empire).cbz
Mr & Mrs X 006 (2019) (Digital) (Zone-Empire).cbr
Peter Parker - The Spectacular Spider-Man 313 (2019) (Oroboros-DCP).cbr
The Unbeatable Squirrel Girl 039 (2019) (Digital) (Zone-Empire).cbr
Oblivion Song By Kirkman De Felici 007 (2018)(Digital)(TCHQ).cbr

And one of them have a "%" work after that i remove it

**Comment by Lusiphur** [comment]
I was trying to post process that issue of Oblivion Song too.

**Comment by evilhero** [comment]
Oblivion Song won't pp as the name in the file isn't what Mylar has it as. You need to add ```Oblivion Song By Kirkman De Felici``` to the ```Alternate Search Name``` field of the given series (which is on the Edit tab on the series detail page). Once it's added/updated, doing the post-process will work for that particular issue. I just mocked up the same filenames that @judzk provided (after I added them to my watchlist), and they all pp'd fine, save for the Oblivion Song until I added in the Alternate Search Name which then pp'd fine.

As for the other issues, for those issues that are not post-processing - if you go to the series detail page for each of those, is the given issue you're trying to post-process exist? If it doesn't exist, then the series was never refreshed properly for some reason, and Mylar can't post-process it as it doesn't think that particular issue number exists for the given series yet (ie. if the series goes up to 9 in Mylar, and you're trying to pp issue 10, it won't). In these cases, doing a manual refresh of the given series will allow the post-processing to be completed properly.

There might be some problems with the series on a given week not properly being refreshed to bring in new issue data - I'll have to do some digging / testing to see if I can figure out what's happening tho.

**Comment by LIMRoss** [comment]
This took me a week and some to figure out. If you have a TPB in your scrapping directory and it fits the criteria for an existing series, it'll blow up the post processing. My examples would be Motherlands (2018) and some random Stars Wars book that didn't have a number.

**Comment by Lusiphur** [comment]
Pp is not working at all this week. Running some tests to try and figure out what's going on.

**Comment by HypKin** [comment]
same problem here, almost no post processing. (only annuals worked for me???)

**Comment by Lusiphur** [comment]
Seems fixed now in the new version on the Development branch.

**Comment by HypKin** [comment]
yes, after the update my mylar spammed my phone with push messages ;)

thank you evilhero!
