### ISSUE TITLE
kwargs error in searching task

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#2161]
I added a Newznab search provided and I'm seeing this error in the logs. This is affecting auto downloading. It seems it doesn't continue after this error even using the torrent searches.

My version is:
Configuration OptionsMylar Version: master-- git build 34e540c75f06b773e5c8f0c0605345e3911f48c7.Python Version : 2.7.13

Any assistance will be appreciated.

```
2019-01-04 18:36:38 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/helpers.py", line 3007, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/app/mylar/mylar/search.py", line 2141, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)File "/app/mylar/mylar/search.py", line 336, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)File "/app/mylar/mylar/search.py", line 1790, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)File "/app/mylar/mylar/search.py", line 2880, in searchersendtosab = ss.sender()File "/app/mylar/mylar/sabnzbd.py", line 53, in sender'nzo_id': ''.join(sendresponse['nzo_ids']),KeyError: 'nzo_ids'
-- | -- | --
```

**Comment by evilhero** [comment]
What's the new provider you added and what version is your sabnzbd client?

**Comment by evilhero** [comment]
Your version of sabnzbd is too old to use with Completed Download Handling within Mylar. 

If you intend to stick to that version, you'll have to disable it and use the ComicRN script to autoprocess your sabnzbd downloads.

**Comment by cesalo** [comment]
I believe I'm not using that or do you mean something else? I have Sabnzbd putting the files in the monitor directory of Mylar. "Completed Download Handling" is unchecked.

![image](https://user-images.githubusercontent.com/16859916/50710554-4fd43b80-1039-11e9-91dd-3788453f4e3f.png)

**Comment by evilhero** [comment]
Ok, so if CDH is disabled then It's probably  because your version of sabnzbd doesn't return the nzo_ids of what it's  downloading.

I'd have to look more into it to see about some kind of blind fix (since I don't run that version it's be hard to test against properly).

Aside from either upgrading sabnzbd or installing/using nzbget, you'd have to wait for the possible fix to hit the branch in this particular case.

**Comment by evilhero** [comment]
Actually maybe you can assist abit since I can't test it against that exact version, and you currently have it.

There's a INFO level logging line right before that error occurred that shows what your sabnzbd client is sending back as a response to Mylar sending the nzb to it. So it would be literally like this:
```
INFO parameters set to _something not important atm_
INFO sending now to http://yoursabnzbdurl/api
INFO **_<response sent back from sabnzbd in json format>_**
ERROR traceback error _you posted._ 

```
If you could paste in that response line it would be really beneficial so I could see exactly what's being returned and try to fix things based on that (just xxx any api information if you can) which would make the turnaround for this mucho quicker.

Cheers,

**Comment by cesalo** [comment]
I found this, let me know if is good enough or if you need anything else.
```
04-Jan-2019 18:36:37 - DEBUG   :: mylar.searcher.2373 : SEARCH-QUEUE : issues match!
04-Jan-2019 18:36:37 - INFO    :: mylar.searcher.2389 : SEARCH-QUEUE : Found xxxxx (2019) issue: 5 using NZBPlanet (newznab)
04-Jan-2019 18:36:37 - DEBUG   :: mylar.searcher.2391 : SEARCH-QUEUE : link given by: newznab
04-Jan-2019 18:36:37 - DEBUG   :: mylar.searcher.2494 : SEARCH-QUEUE : [PAYLOAD-NONE]Download URL: https://api.nzbplanet.net/getnzb/xxxxxxxxxxxxxxxx=xYOUDONTNEEDTOKNOWTHISx [VerifySSL:True]
04-Jan-2019 18:36:38 - DEBUG   :: mylar.searcher.2514 : SEARCH-QUEUE : Status code returned: 200
04-Jan-2019 18:36:38 - DEBUG   :: mylar.searcher.2553 : SEARCH-QUEUE : [FILENAME] filename (remove chars): xxxxxxxxxxxxxxxxxxxxxxx.cbr
04-Jan-2019 18:36:38 - DEBUG   :: mylar.searcher.2556 : SEARCH-QUEUE : [FILENAME] nzbname (\s): xxxxxxxxxxxxxx
04-Jan-2019 18:36:38 - DEBUG   :: mylar.searcher.2558 : SEARCH-QUEUE : [FILENAME] end nzbname: xxxxxxxxxxxxxxxxx
04-Jan-2019 18:36:38 - INFO    :: mylar.searcher.2564 : SEARCH-QUEUE : filen: xxxxxxxxxxxxxxxx -- nzbname: xxxxxxxxxxxxxxxx are not identical. Storing extra value as : xxxxxxxxxxxx
04-Jan-2019 18:36:38 - DEBUG   :: mylar.searcher.2569 : SEARCH-QUEUE : Cache Directory successfully found at : /app/mylar/cache/. Ensuring proper permissions.
04-Jan-2019 18:36:38 - DEBUG   :: mylar.setperms.1440 : SEARCH-QUEUE : Successfully changed ownership and permissions [380:378] / [0777 / 0660]
04-Jan-2019 18:36:38 - INFO    :: mylar.sender.42 : SEARCH-QUEUE : parameters set to {'nzbname': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'apikey': u'xxxxxxxxxxxxxxxxxxxxxxxx', 'name': u'http://xxxxxxxxxxxxxxxx/api?apikey=xxxxxxxxxxxxxxxxx&cmd=downloadNZB&nzbname=xxxxxxxxxxxxxx', 'cmd': 'downloadNZB', 'cat': u'mylar', 'priority': '-100', 'mode': 'addurl', 'output': 'json'}
04-Jan-2019 18:36:38 - INFO    :: mylar.sender.43 : SEARCH-QUEUE : sending now to http://xxxxxxxxxxxxx/api
04-Jan-2019 18:36:38 - INFO    :: mylar.sender.50 : SEARCH-QUEUE : {u'status': True}
04-Jan-2019 18:36:38 - DEBUG   :: mylar.checkParams.80 : CP Server Thread-11 : Matched to key. Api set to : download mode.
04-Jan-2019 18:36:38 - DEBUG   :: mylar.fetchData.110 : CP Server Thread-11 : Received API command: downloadNZB
04-Jan-2019 18:36:38 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/helpers.py", line 3007, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/app/mylar/mylar/search.py", line 2141, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)
  File "/app/mylar/mylar/search.py", line 336, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)
  File "/app/mylar/mylar/search.py", line 1790, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/app/mylar/mylar/search.py", line 2880, in searcher
    sendtosab = ss.sender()
  File "/app/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
KeyError: 'nzo_ids'
```
