### ISSUE TITLE
Post Processing getting stuck

### ISSUE THREAD

**Issue by Tanick42** [evilhero/mylar#2173]
I noticed that nzbget was hanging on post-processing today (I hadn't updated in a while, so I did today - this is happening after updating).  Cancelled post-processing, same errors happen with the next item, so it doesn't look isolated to a specific file.

Relevant bits from the log:
2019-01-22 20:26:24	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\HTPC\Mylar\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\HTPC\Mylar\mylar\PostProcessor.py", line 1468, in Process
self.nzb_or_oneoff_pp(tinfo=pp)
File "C:\HTPC\Mylar\mylar\PostProcessor.py", line 1908, in nzb_or_oneoff_pp
return self.Process_next(comicid, issueid, issuenumOG)
File "C:\HTPC\Mylar\mylar\PostProcessor.py", line 2350, in Process_next
if ml['ForcedMatch'] is True:
TypeError: 'NoneType' object has no attribute '__getitem__'
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Rename Files is not enabled - keeping original filename.
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Original Filename: Amazing Spider-Man 013 (2019) (Digital) (Zone-Empire).cbr [.cbr]
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] ofilename: Amazing Spider-Man 013 (2019) (Digital) (Zone-Empire).cbr
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] odir: C:\ProgramData\NZBGet\complete\comics\Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] ofilename: Amazing Spider-Man 013 (2019) (Digital) (Zone-Empire).cbr
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] odir (root): C:\ProgramData\NZBGet\complete\comics\Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] New format: $Series $Issue ($Year)
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Not an annual - removing from filename parameters
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Comic Version: v5
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Comic Location: \\192.168.0.5\comics\Amazing Spider-Man (2018)
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Year: 2018
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Series: The Amazing Spider-Man
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Publisher: Marvel
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Issue Year : 2019
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Pretty Comic Issue is : 13
2019-01-22 20:26:24	DEBUG	Zero level supplement set to none.Issue will be set as : 13
2019-01-22 20:26:24	DEBUG	issue detected greater than 10, but less than 100
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] Zero Suppression set to : none
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] issuenumOG: 13
2019-01-22 20:26:24	DEBUG	[POST-PROCESSING] issueid: 697624
2019-01-22 20:26:24	INFO	[POST-PROCESSING] [1/1] Starting Post-Processing for The Amazing Spider-Man issue: 13
2019-01-22 20:26:24	INFO	[DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2019-01-22 20:26:24	INFO	[DUPECHECK] Duplicate check for C:\ProgramData\NZBGet\complete\comics\Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:24	INFO	[POST-PROCESSING] issuenzb found.
2019-01-22 20:26:24	INFO	[PPINFO-POST-PROCESSING-ATTEMPT] {'publisher': None, 'comicname': u'The Amazing Spider-Man', 'issueid': u'697624', 'comiclocation': None, 'sarc': None, 'issuenumber': u'13', 'oneoff': None, 'comicid': u'112161'}
2019-01-22 20:26:19	DEBUG	[POST-PROCESSING] Issueid: 697624
2019-01-22 20:26:17	DEBUG	[POST-PROCESSING] After conversions, nzbname is : Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	DEBUG	[NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Amazing Spider-Man 013 2019 Digital Zone-Empire
2019-01-22 20:26:17	DEBUG	[NZBNAME] nzbname (remove chars): Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	DEBUG	[NZBNAME]: Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	DEBUG	[POST-PROCESSING] NZB name as passed from NZBGet: Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	DEBUG	[POST-PROCESSING] Using NZBGET
2019-01-22 20:26:17	DEBUG	[POST-PROCESSING] nzb folder: C:\ProgramData\NZBGet\complete\comics\Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	DEBUG	[POST-PROCESSING] nzb name: Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	INFO	Starting postprocessing for : Amazing.Spider-Man.013.2019.Digital.Zone-Empire
2019-01-22 20:26:17	INFO	ComicRN.py version: 1.01 -- autoProcessComics.py version: 2.04
2019-01-22 20:26:17	INFO	[API] Api Call from ComicRN detected - initiating script

**Comment by evilhero** [comment]
Yep, looks like it was a variable reference I missed - it would affect ComicRN usage regardless of the client, but manual post-processing would work fine (which is what I tested against if I recall). 

Thanks for the detailed bug report!  Should be all fixed now in development f53ad0f

**Comment by Tanick42** [comment]
Thanks for the quick fix. Just updated and can confirm that it solved the problem.
