### ISSUE TITLE
Search fails on NZB.su 

### ISSUE THREAD

**Issue by drmikenz** [evilhero/mylar#2183]
Just started using Mylar, running on OSX 10.14.2, and using the development branch. I've added a couple of series but searches consistently fail.

First get a warning:

[ERROR] 'site' [{'newznab': {u'size': u'29130425', u'hash': u'3611b7dd686451149826c0e4f33066c6', 'id': u'16daa938e960042e03afa04f48e34b29', 'tags': {}}, 'updated': u'Fri, 01 Feb 2019 01:04:06 -0500', 'updated_parsed': time.struct_time(tm_year=2019, tm_mon=2, tm_mday=1, tm_hour=6, tm_min=4, tm_sec=6, tm_wday=4, tm_yday=32, tm_isdst=0), 'links': [{'href': u'https://api.nzb.su/getnzb/16daa938e960042e03afa04f48e34b29.nzb&i=187899&r=32794c1e57ae4e4928e19ad31f39b49d', 'type': 'text/html', 'rel': 'alternate'}, {'length': u'29130425', 'href': u'https://api.nzb.su/getnzb/16daa938e960042e03afa04f48e34b29.nzb&i=187899&r=32794c1e57ae4e4928e19ad31f39b49d', 'type': u'application/x-nzb', 'rel': 'enclosure'}], 'title': u'West.Coast.Avengers.007.2019.Digital.Zone-Empire', 'tags': [{'term': u'Books > Comics', 'scheme': None, 'label': None}], 'summary_detail': {'base': u'', 'type': 'text/html', 'value': u'West.Coast.Avengers.007.2019.Digital.Zone-Empire', 'language': None}, 'comments': u'https://api.nzb.su/details/16daa938e960042e03afa04f48e34b29#comments', 'summary': u'West.Coast.Avengers.007.2019.Digital.Zone-Empire', 'guidislink': True, 'title_detail': {'base': u'', 'type': 'text/plain', 'value': u'West.Coast.Avengers.007.2019.Digital.Zone-Empire', 'language': None}, 'link': u'https://api.nzb.su/getnzb/16daa938e960042e03afa04f48e34b29.nzb&i=187899&r=32794c1e57ae4e4928e19ad31f39b49d', 'id': u'https://api.nzb.su/details/16daa938e960042e03afa04f48e34b29'}]

and then and error

ERROR | Uncaught exception: Traceback (most recent call last):File "/Users/mikearmour/mylar-development/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "/Users/mikearmour/mylar-development/mylar/helpers.py", line 3124, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/Users/mikearmour/mylar-development/mylar/search.py", line 1845, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "/Users/mikearmour/mylar-development/mylar/search.py", line 360, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "/Users/mikearmour/mylar-development/mylar/search.py", line 1289, in NZB_SEARCHif (all([nzbprov == '32P', RSS == 'no', allow_packs == True]) and any([entry['pack'] == '1', entry['pack'] == '2'])) or (all([nzbprov == 'ddl', entry['pack'] is True])): #allow_packs is TrueFile "./lib/feedparser.py", line 317, in __getitem__return UserDict.__getitem__(self, realkey)KeyError: 'pack'
-- | --

If i go to the url found in the warning 'https://api.nzb.su/getnzb/16daa938e960042e03afa04f48e34b29.nzb&i=187899&r=32794c1e57ae4e4928e19ad31f39b49d' its the correct NZB for the issue. 

any ideas ?

**Comment by evilhero** [comment]
Ok, now that's what I needed to see ;)

Fixed the relevant error so that it shouldn't trigger again. Let me know if this fixes things for you please.

**Comment by drmikenz** [comment]
> Ok, now that's what I needed to see ;)
> 
> Fixed the relevant error so that it shouldn't trigger again. Let me know if this fixes things for you please.

you are a legend :) works perfectly. enjoy the coffees!
