### ISSUE TITLE
Just Updated - Database Locked

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#2189]
I just updated to the latest develop build, and when I try to start Mylar, I get

```
08-Feb-2019 09:48:08 - WARNING :: mylar.dbcheck.511 : MainThread : Unable to update readinglist table to new storyarc table format.
08-Feb-2019 09:48:08 - ERROR   :: mylar.initialize.189 : MainThread : Cannot connect to the database: database is locked
08-Feb-2019 09:48:28 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 09:48:29 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 09:48:30 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 09:48:31 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 09:48:32 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 09:48:38 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 348, in <module>
    main()
  File "Mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/opt/Mylar/mylar/__init__.py", line 254, in initialize
    helpers.updateComicLocation()
  File "/opt/Mylar/mylar/helpers.py", line 816, in updateComicLocation
    dirlist = myDB.select("SELECT * FROM comics")
  File "/opt/Mylar/mylar/db.py", line 144, in select
    sqlResults = self.fetch(query, args).fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
```

Mylar won't start.

**Comment by evilhero** [comment]
Can you paste the complete debug log from the very start ? Do you have any other process/program accessing the mylar.db that would lock the db ?

**Comment by DrSeussFreak** [comment]
Nothing else should be touching the db

What is the log level value for debug?

**Comment by evilhero** [comment]
Start it from a command line prompt as ```python Mylar.py -v``` and then everything will break in the console (it will still produce logs in the log files for cutting/pasting).

**Comment by DrSeussFreak** [comment]
I just read log_level 2 is debug, I just started it with that.  Would you prefer me to do what you just mentioned instead?

**Comment by evilhero** [comment]
It doesn't matter - as long as you see DEBUG lines in the log, that's what we're after and trying to get it right from the initial start.

**Comment by DrSeussFreak** [comment]
```
root@media-01:/opt/Mylar# python Mylar.py -v
log language set to en_US
Verbose/Debugging mode enabled...
Initializing startup sequence....
08-Feb-2019 10:02:17 - DEBUG :: mylar.configure.750 : MainThread : Log dir: /opt/Mylar/logs
08-Feb-2019 10:02:17 - DEBUG :: mylar.configure.877 : MainThread : Setting ComicTagger settings default path to : /opt/Mylar/lib/comictaggerlib/ct_settings
08-Feb-2019 10:02:17 - INFO :: mylar.initialize.185 : MainThread : Checking to see if the database has all tables....
08-Feb-2019 10:02:22 - WARNING :: mylar.dbcheck.511 : MainThread : Unable to update readinglist table to new storyarc table format.
08-Feb-2019 10:02:27 - ERROR :: mylar.initialize.189 : MainThread : Cannot connect to the database: database is locked
08-Feb-2019 10:02:27 - INFO :: mylar.initialize.199 : MainThread : Successfully discovered local IP and locking it in as : 10.0.1.71
08-Feb-2019 10:02:27 - DEBUG :: mylar.initialize.211 : MainThread : Logger set to use : Rotational Log Handler (default)
08-Feb-2019 10:02:27 - DEBUG :: mylar.initialize.244 : MainThread : SEARCH_TIER_DATE set to : 2019-01-25
08-Feb-2019 10:02:27 - INFO :: mylar.updateComicLocation.810 : MainThread : Performing a one-time mass update to Comic Location
08-Feb-2019 10:02:27 - INFO :: mylar.validateAndCreateDirectory.1566 : MainThread : [DIRECTORY-CHECK] Found comic directory: /media/comics
08-Feb-2019 10:02:47 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 10:02:48 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 10:02:49 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 10:02:50 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 10:02:51 - WARNING :: mylar.fetch.98 : MainThread : Database Error: database is locked
08-Feb-2019 10:02:52 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 348, in <module>
    main()
  File "Mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/opt/Mylar/mylar/__init__.py", line 254, in initialize
    helpers.updateComicLocation()
  File "/opt/Mylar/mylar/helpers.py", line 816, in updateComicLocation
    dirlist = myDB.select("SELECT * FROM comics")
  File "/opt/Mylar/mylar/db.py", line 144, in select
    sqlResults = self.fetch(query, args).fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'

Traceback (most recent call last):
  File "Mylar.py", line 348, in <module>
    main()
  File "Mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/opt/Mylar/mylar/__init__.py", line 254, in initialize
    helpers.updateComicLocation()
  File "/opt/Mylar/mylar/helpers.py", line 816, in updateComicLocation
    dirlist = myDB.select("SELECT * FROM comics")
  File "/opt/Mylar/mylar/db.py", line 144, in select
    sqlResults = self.fetch(query, args).fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
```

**Comment by DrSeussFreak** [comment]
Just for an FYI

root@media-01:/opt/Mylar# git rev-parse HEAD
33c09924f67b980d3a3331e3f0c56c5841f5cb9b

**Comment by evilhero** [comment]
How do you normally start Mylar? As a daemon ?
if you do a ```ps - A | grep 'python'``` from the cli, does it show anything ? If it does, then do a ```ps -xg``` and try to locate the PID's from the 1st in the 2nd (assuming you're running it as your user here)

**Comment by DrSeussFreak** [comment]
Yes, it runs as a daemon, there is a mylar service set to start at boot

```
ps -A | grep 'python'
  3205 ?        00:00:00 python
```

```
mylar@media-01:~$ ps -xg
   PID TTY      STAT   TIME COMMAND
  3205 ?        D      0:00 /usr/bin/python Mylar.py --quiet --daemon --nolaunch --pidfile=/var/run/mylar/mylar.pid --datadir=/opt/Mylar --port=9093
  3391 ?        S      0:00 /usr/bin/python Mylar.py --quiet --daemon --nolaunch --pidfile=/var/run/mylar/mylar.pid --datadir=/opt/Mylar --port=9093
  3447 pts/0    S      0:00 -su
  3454 pts/0    R+     0:00 ps -xg
```

**Comment by evilhero** [comment]
According to that - you have 2 instances running already. Kill both (```kill -9 3205```, ```kill -9 3391```, then try to start it up via the command line again and see if that drops the db locking.

**Comment by DrSeussFreak** [comment]
Yea, I was already there trying this, problem I am having is when I start the service, it is hanging, and the log is created, but stays at 0 bytes.

I have had a tail of mylar.log going for a while, without any change.  Checking to see why the performance problem.

**Comment by evilhero** [comment]
Ok, so don't start the service. Just try to get it running via the command line, when there are no other instances of mylar running in the background (kill the service maybe). 

Once you can get it running from the command line, the service will work (and the command line interface has more to display when running)...

**Comment by DrSeussFreak** [comment]
it started up via 'python Mylar.py -v'

I then closed that thread, cleaned up the process and am trying to start the service, but it is hanging.  I see the process created from the mylar user, but it is timing out

```
Feb 08 11:12:04 media-01 systemd[1]: mylar.service: Start operation timed out. Terminating.
Feb 08 11:12:04 media-01 systemd[1]: mylar.service: Failed with result 'timeout'.
Feb 08 11:12:04 media-01 systemd[1]: Failed to start starts instance of Mylar.
-- Subject: Unit mylar.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit mylar.service has failed.
-- 
-- The result is RESULT.
```

**Comment by DrSeussFreak** [comment]
I figured out why it was timing out.  Somehow

the below got set

```
[Update]
newcom_dir = /media/comics
fftonewcom_dir = True
locmove = True
```

They were false, not sure what happened.
