### ISSUE TITLE
Mylar won't start due to no module pkg_ressouces

### ISSUE THREAD

**Issue by shaavik** [evilhero/mylar#2198]
I have cloned mylar.
When running, I get python Error : 

Traceback (most recent call last):
  File "C:\Mylar\mylar\mylar\Mylar.py", line 26, in <module>
    import mylar
  File "C:\Mylar\mylar\mylar\mylar\__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "C:\Mylar\mylar\mylar\lib\apscheduler\schedulers\background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler
  File "C:\Mylar\mylar\mylar\lib\apscheduler\schedulers\base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

**Comment by evilhero** [comment]
Please follow the issue template.
