### ISSUE TITLE
Unable to Add Series

### ISSUE THREAD

**Issue by Webby2687** [evilhero/mylar#2213]
I am searching for a series and trying to add it to my library. I have done this in the past with no issue, but in the last few weeks have been unable to add new series. I've seen issues in the past with special characters in the series name preventing the import. I thought this might be the case so i tried a one word series with no special characters to confirm. Both logs are below. Thank you in advance for your help/time!

Log for adding 'Stronghold':

2019-02-21 23:24:15 | WARNING | Comic ID: 117225 has not finished loading. Nulling some values so things display properly until they can populate.
-- | -- | --
2019-02-21 23:24:15 | WARNING | Comic ID: 113505 has not finished loading. Nulling some values so things display properly until they can populate.
2019-02-21 23:23:48 | ERROR | Uncaught exception: Traceback (most recent call last):File "c:\Mylar\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "c:\Mylar\mylar\importer.py", line 218, in addComictoDBcomlocation = dothedew.folder_create()File "c:\Mylar\mylar\filers.py", line 130, in folder_createcomlocation = re.sub('/', '\\', comlocation)File "c:\Python27\lib\re.py", line 155, in subreturn _compile(pattern, flags).sub(repl, string, count)File "c:\Python27\lib\re.py", line 286, in _subxtemplate = _compile_repl(template, pattern)File "c:\Python27\lib\re.py", line 273, in _compile_replraise error, v # invalid expressionerror: bogus escape (end of line)
2019-02-21 23:23:48 | INFO | Previous version detected as None - seeing if update required
2019-02-21 23:23:48 | INFO | Sucessfully retrieved details for Stronghold
2019-02-21 23:23:48 | INFO | Now adding/updating: Stronghold

Log trying to add 'Archie: 1941':

2019-02-21 23:15:28 | WARNING | Comic ID: 113505 has not finished loading. Nulling some values so things display properly until they can populate.
-- | -- | --
2019-02-21 23:15:28 | INFO | Mylar is up to date
2019-02-21 23:15:18 | WARNING | Comic ID: 113505 has not finished loading. Nulling some values so things display properly until they can populate.
2019-02-21 23:12:29 | ERROR | Uncaught exception: Traceback (most recent call last):File "c:\Mylar\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "c:\Mylar\mylar\importer.py", line 218, in addComictoDBcomlocation = dothedew.folder_create()File "c:\Mylar\mylar\filers.py", line 130, in folder_createcomlocation = re.sub('/', '\\', comlocation)File "c:\Python27\lib\re.py", line 155, in subreturn _compile(pattern, flags).sub(repl, string, count)File "c:\Python27\lib\re.py", line 286, in _subxtemplate = _compile_repl(template, pattern)File "c:\Python27\lib\re.py", line 273, in _compile_replraise error, v # invalid expressionerror: bogus escape (end of line)
2019-02-21 23:12:29 | INFO | Previous version detected as None - seeing if update required
2019-02-21 23:12:29 | INFO | Sucessfully retrieved details for Archie: 1941
2019-02-21 23:12:29 | INFO | Now adding/updating: Archie: 1941

Environment
 - OS: Windows 10
 - Branch / commit: Dev git build 59ae20278904f422f6b99b7b171648fa32db10e4

**Comment by evilhero** [comment]
Check your folder format path in the configuration - you most likely have a ```/``` that needs to be changed to ```\``` as that's not a valid Windows directory with it in it.

**Comment by Webby2687** [comment]
That fixed it, thank you for the help!
