### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' 

### ISSUE THREAD

**Issue by andrewenriquez** [evilhero/mylar#2214]
Im new to mylar so this might be an oversight on my part. Not sure what is going on but every time I restart mylar and try and manual search for a comic book I know exists, I get this error.

`Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/helpers.py", line 3124, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/app/mylar/mylar/search.py", line 1846, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 360, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 944, in NZB_SEARCH
conv_minsize = helpers.human2bytes(mylar.CONFIG.MINSIZE + "M")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

I'm using NZBGet for downloading and nzbgeek for seaching if that makes a difference. 

Weirdly, It seems to work up until this error but nothing is ever downloaded. Here is debug logs of it.

`2019-02-21 23:58:37 | DEBUG | size given as: 30.0 MB
-- | -- | --
2019-02-21 23:58:37 | DEBUG | comsize_b: 31489000
2019-02-21 23:58:37 | DEBUG | sub:Detective.Comics.998.2019.Webrip.The.Last.Kryptonian-DCP
2019-02-21 23:58:37 | DEBUG | checking search result: Detective.Comics.998.2019.Webrip.The.Last.Kryptonian-DCP
2019-02-21 23:58:37 | INFO | no errors on data retrieval...proceeding
2019-02-21 23:58:33 | DEBUG | [SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=detective%20comics%20998&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
2019-02-21 23:58:33 | INFO | pausing for 60 seconds before continuing to avoid hammering
2019-02-21 23:58:33 | DEBUG | findloop: 0 / findcount: 1
2019-02-21 23:58:33 | INFO | Shhh be very quiet...I'm looking for Detective Comics issue: 998 (2019) using nzbgeek (newznab).
2019-02-21 23:58:33 | DEBUG | using Newznab host of : nzbgeek
2019-02-21 23:58:33 | DEBUG | Initiating Search via : api
2019-02-21 23:58:33 | DEBUG | srchloop: 2
2019-02-21 23:58:33 | DEBUG | calpha/cnumber: None / None
2019-02-21 23:58:33 | DEBUG | search provider order is ['newznab:nzbgeek']
2019-02-21 23:58:33 | DEBUG | Usenet Retention : 1500 days
2019-02-21 23:58:33 | DEBUG | there are : 1 nzb providers you have selected.
2019-02-21 23:58:33 | DEBUG | There are 0 torrent providers you have selected.
2019-02-21 23:58:33 | DEBUG | nzbprovider(s): ['newznab:nzbgeek']
2019-02-21 23:58:33 | DEBUG | Checking for torrent enabled.
2019-02-21 23:58:33 | DEBUG | Issue Title given as : mythology: hell and back
2019-02-21 23:58:33 | DEBUG | Publisher is : DC Comics
`

 Any help would be appreciated, Thanks!

**Comment by andrewenriquez** [comment]
Not sure if it makes a difference but i'm using mylar in an Unraid docker container.

**Comment by evilhero** [comment]
Check your minimum size entry in the configuration. Either it is enabled and has no value entered, or there is an invalid entry (in MB with just numerics no letters)

**Comment by andrewenriquez** [comment]
YES! that did the trick. I had them checked without anything in them. Now I'm having an issue where downloads from getcomics.info are getting stuck in cache folder and are not being properly Post-Processed. Any ideas? Thanks.

**Comment by evilhero** [comment]
Get a debug log showing the snatch using ddl and what happens thereafter and we can take a look at things.

**Comment by andrewenriquez** [comment]
Seems like clearing the snatch and a restart did the trick. Thanks!
