### ISSUE TITLE
Unable to PULL (or IMPORT) Anything (Synology 918+)

### ISSUE THREAD

**Issue by trilidar** [evilhero/mylar#2216]
Everything appears configured correctly (can verify APIs, etc).
Have confirmed correct folder rights (folders created, but nothing downloaded/moved).

Logs show the following:

2019-02-26 16:33:09 | ERROR | Uncaught exception: Traceback (most recent call last):File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/var/packages/python/target/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 226, in addComictoDBcheckdirectory = filechecker.validateAndCreateDirectory(comlocation, True)File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 1578, in validateAndCreateDirectorysetperms(dir.rstrip(), True)File "/volume1/@appstore/mylar/share/mylar/mylar/filechecker.py", line 1607, in setpermschowner = getpwnam(mylar.CONFIG.CHOWNER)[2]KeyError: 'getpwnam(): name not found: none'
-- | -- | --
2019-02-26 16:33:09 | INFO | [DIRECTORY-CHECK] Creating comic directory (0777) : /volume1/Media/Comics/Batgirl An Adult Coloring Book (2017)
2019-02-26 16:33:09 | WARNING | [DIRECTORY-CHECK] Could not find comic directory: /volume1/Media/Comics/Batgirl An Adult Coloring Book (2017)

Running the following (current) version on a Synology 918+:

Mylar Version: master
-- git build f837fea36114c5bdb7d0b1e2647ad335d270a1c5.
Python Version : 2.7.14
Language : en_US.UTF-8

I'm completely at a loss and ANY help resolving this would be GREATLY appreciated.

Much thanks,

**Comment by evilhero** [comment]
You have a username set for owner permissions in Mylar that doesn't exist on your system. Either leave them blank, and/or turn off the enforce permissions option - or you need to find out what the user is that's running mylar and use that name/UID.

The permissions on synology tend to be locked down pretty good and are enforced thru some other means than just by OS - so I usually just say to turn off the enforce permissions within Mylar. As long as you have normal permissions for everything that Mylar needs access to, you should be fine.

**Comment by trilidar** [comment]
That was it!

Thank you (literally from the bottom of my heart)!
