### ISSUE TITLE
Mylar terminates upon opening - 'Config' object has no attribute 'NZB_CLIENT_POST_PROCESSING'

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#2217]
`log language set to en_US
Initializing startup sequence....
27-Feb-2019 15:41:17 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\PythonPrograms\mylar-development\mylar.py", line 348, in <module>
    main()
  File "C:\PythonPrograms\mylar-development\mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\PythonPrograms\mylar-development\mylar\__init__.py", line 177, in initialize
    CONFIG = cc.read(startup=True)
  File "C:\PythonPrograms\mylar-development\mylar\config.py", line 538, in read
    self.configure()
  File "C:\PythonPrograms\mylar-development\mylar\config.py", line 906, in configure
    if all([mylar.NZBPOOL is None, self.POST_PROCESSING is True]) and ( all([self.NZB_DOWNLOADER == 0, self.SAB_CLIENT_POST_PROCESSING is True]) or all([self.NZB_DOWNLOADER == 1, self.NZB_CLIENT_POST_PROCESSING is True]) ):
AttributeError: 'Config' object has no attribute 'NZB_CLIENT_POST_PROCESSING'

Traceback (most recent call last):
  File "C:\PythonPrograms\mylar-development\mylar.py", line 348, in <module>
    main()
  File "C:\PythonPrograms\mylar-development\mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\PythonPrograms\mylar-development\mylar\__init__.py", line 177, in initialize
    CONFIG = cc.read(startup=True)
  File "C:\PythonPrograms\mylar-development\mylar\config.py", line 538, in read
    self.configure()
  File "C:\PythonPrograms\mylar-development\mylar\config.py", line 906, in configure
    if all([mylar.NZBPOOL is None, self.POST_PROCESSING is True]) and ( all([self.NZB_DOWNLOADER == 0, self.SAB_CLIENT_POST_PROCESSING is True]) or all([self.NZB_DOWNLOADER == 1, self.NZB_CLIENT_POST_PROCESSING is True]) ):
AttributeError: 'Config' object has no attribute 'NZB_CLIENT_POST_PROCESSING'
`

**Comment by lodasi** [comment]
Literally just terminates upon opening. Unable to do anything.
