### ISSUE TITLE
host_return setting breaks mylar/sab interaction

### ISSUE THREAD

**Issue by 13and3** [evilhero/mylar#2242]
Mylar sends incorrect IP over to Sab, so per another issue I set the host_return to 127.0.0.1, and now it throws an exception when trying to write to sab:

```

19-Mar-2019 18:44:33 - ERROR :: mylar.excepthook.315 : Thread-31 : Uncaught exception: Traceback (most recent call last):
  File "/Users/13and3/mylar/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1911, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 2620, in searcher
    sendtosab = ss.sender()
  File "/Users/13and3/mylar/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
TypeError: sequence item 0: expected string, NoneType found

Traceback (most recent call last):
  File "/Users/13and3/mylar/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1911, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 2620, in searcher
    sendtosab = ss.sender()
  File "/Users/13and3/mylar/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by evilhero** [comment]
Please follow the issue template, it's there for a reason and to help us help you.

**Comment by 13and3** [comment]
Ok.  Append to my original message, OS/X Mojave + Master branch

**Comment by 13and3** [comment]
c79cbe5a0eadd539801a5e3377fecebb852c1fe3

**Comment by barbequesauce** [comment]
Again - follow the template - we need the log. Exception detail indicates what broke, but supplies no context leading up to the break.

**Comment by 13and3** [comment]
```19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.856 : Thread-35 : sub: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.974 : Thread-35 : Year has been fuzzied for this series, ignoring store date comparison entirely.
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1098 : Thread-35 : Entry: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.325 : Thread-35 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.328 : Thread-35 : NEW split_file3: [u'Action', u'Comics', u'1006', u'2019', u'Webrip', u'The', u'Last', u'Kryptonian-DCP']
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.392 : Thread-35 : NEWLY SPLIT REORGD: [u'Action', u'Comics', u'1006', u'2019', u'Webrip', u'The', u'Last', u'Kryptonian-DCP']
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.427 : Thread-35 : checking date : 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.430 : Thread-35 : date: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.741 : Thread-35 : datecheck: [{'date': u'2019', 'position': 3, 'mod_position': 19}]
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.747 : Thread-35 : sctd: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.756 : Thread-35 : year verified as : 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.762 : Thread-35 : year verified as: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.792 : Thread-35 : highest_series_position: 3
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.798 : Thread-35 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': u'1006', 'mod_position': 14}, {'position': 3, 'validcountchk': False, 'number': u'2019', 'mod_position': 19}]
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.804 : Thread-35 : hyphen located at position: 50
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.806 : Thread-35 : yearposition: 3
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.836 : Thread-35 : Already validated year, ignoring as possible issue number: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.841 : Thread-35 : issue number :1006
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.870 : Thread-35 : issue_position: 2
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.887 : Thread-35 : issue verified as : 1006
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.1011 : Thread-35 : sf_highest_series_pos: [u'Action', u'Comics']
19-Mar-2019 18:50:21 - DEBUG :: mylar.parseit.1043 : Thread-35 : series title possibly: Action Comics
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1115 : Thread-35 : parsed_info: {'series_volume': None, 'booktype': 'issue', 'issueid': None, 'sub': None, 'comiclocation': None, 'reading_order': None, 'parse_status': 'success', 'dynamic_name': u'ActionComics', 'series_name': u'Action Comics', 'comicfilename': u'Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP', 'issue_number': u'1006', 'issue_year': '2019', 'scangroup': None, 'alt_series': None, 'alt_issue': None, 'series_name_decoded': 'Action Comics'}
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1124 : Thread-35 : match_check: {'justthedigits': u'1006', 'issueid': None, 'match_type': None, 'sub': None, 'comiclocation': None, 'booktype': 'issue', 'series_name': u'Action Comics', 'comicfilename': u'Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP', 'annual_comicid': None, 'issue_year': '2019', 'volume': None, 'process_status': 'match', 'scangroup': None, 'alt_series': None, 'alt_issue': None, 'series_volume': None}
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1188 : Thread-35 : year detected: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1190 : Thread-35 : year looking for: 2019
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1192 : Thread-35 : 2019 - right years match baby!
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1370 : Thread-35 : issue we are looking for is : 1006
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1371 : Thread-35 : integer value of issue we are looking for : 1006000
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1378 : Thread-35 : issue we found for is : 1006
19-Mar-2019 18:50:21 - DEBUG :: mylar.NZB_SEARCH.1380 : Thread-35 : integer value of issue we have found : 1006000
19-Mar-2019 18:50:21 - DEBUG :: mylar.nzbname_create.2021 : Thread-35 : [SEARCHER] entry[title]: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.nzbname_create.2026 : Thread-35 : [SEARCHER] nzbname (remove chars): Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.nzbname_create.2031 : Thread-35 : [SEARCHER] nzbname (\s): Action Comics 1006 2019 Webrip The Last Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.nzbname_create.2038 : Thread-35 : [SEARCHER] end nzbname: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.nzbname_create.2043 : Thread-35 : nzbname used for post-processing: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP
19-Mar-2019 18:50:21 - DEBUG :: mylar.searcher.2098 : Thread-35 : issues match!
19-Mar-2019 18:50:21 - INFO :: mylar.searcher.2117 : Thread-35 : Found Action Comics (2019) #1006 using dognzb
19-Mar-2019 18:50:21 - DEBUG :: mylar.searcher.2119 : Thread-35 : link given by: dognzb
19-Mar-2019 18:50:21 - INFO :: mylar.searcher.2122 : Thread-35 : nzbid: d9bbcf030a1bc4fdd57cdad5f64bb21c
19-Mar-2019 18:50:21 - INFO :: mylar.searcher.2123 : Thread-35 : IssueID: 696323
19-Mar-2019 18:50:21 - INFO :: mylar.searcher.2124 : Thread-35 : oneoff: False
19-Mar-2019 18:50:21 - INFO :: mylar.failed_check.244 : Thread-35 : prov  : dognzb[d9bbcf030a1bc4fdd57cdad5f64bb21c]
19-Mar-2019 18:50:21 - INFO :: mylar.failed_check.255 : Thread-35 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
19-Mar-2019 18:50:21 - DEBUG :: mylar.searcher.2142 : Thread-35 : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
19-Mar-2019 18:50:21 - DEBUG :: mylar.searcher.2222 : Thread-35 : [PAYLOAD-NONE] Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL: True]
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2242 : Thread-35 : Status code returned: 200
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2264 : Thread-35 : filename within nzb: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2281 : Thread-35 : [FILENAME] filename (remove chars): Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2284 : Thread-35 : [FILENAME] nzbname (\s): Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2286 : Thread-35 : [FILENAME] end nzbname: Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb
19-Mar-2019 18:50:22 - DEBUG :: mylar.searcher.2297 : Thread-35 : Cache Directory successfully found at : /Users/13and3/mylar/mylar/cache. Ensuring proper permissions.
19-Mar-2019 18:50:22 - DEBUG :: mylar.setperms.1659 : Thread-35 : Successfully changed permissions [0777 / 0660]
19-Mar-2019 18:50:22 - INFO :: mylar.sender.42 : Thread-35 : parameters set to {'nzbname': u'Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb', 'apikey': 'b36855394be10bf0faea3fb219badf33', 'name': u'127.0.0.1/api?apikey=67d3ec0325ab2e250aeabd6fdad82ba8&cmd=downloadNZB&nzbname=Action.Comics.1006.2019.Webrip.The.Last.Kryptonian-DCP.nzb', 'cmd': 'downloadNZB', 'priority': '-100', 'mode': 'addurl', 'output': 'json'}
19-Mar-2019 18:50:22 - INFO :: mylar.sender.43 : Thread-35 : sending now to http://127.0.0.1:8080/api
19-Mar-2019 18:50:22 - INFO :: mylar.sender.50 : Thread-35 : {u'status': True, u'nzo_ids': [None]}
19-Mar-2019 18:50:22 - ERROR :: mylar.excepthook.315 : Thread-35 : Uncaught exception: Traceback (most recent call last):
  File "/Users/13and3/mylar/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1911, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 2620, in searcher
    sendtosab = ss.sender()
  File "/Users/13and3/mylar/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
TypeError: sequence item 0: expected string, NoneType found

Traceback (most recent call last):
  File "/Users/13and3/mylar/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1911, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 2620, in searcher
    sendtosab = ss.sender()
  File "/Users/13and3/mylar/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),```

**Comment by 13and3** [comment]
an aside: it's also having trouble parsing some file names from this action comics run, but I know that's a more difficult problem.

**Comment by evilhero** [comment]
Logs says it sent it fine to your client - is your client downloading the item and just not doing anything after ? 

Also what version of SABnzbd are you running ?

**Comment by 13and3** [comment]
Mylar sends incorrect IP over to Sab (it sends an IP Address not even in my CIDR).  Sab just spins on that incorrect IP Address.  It is incorrect, I 100% promise you.  Since SAB is on the same machine, not sure why it even bothers to send the IP address rather than localhost.

I googled and found that it was recommended in other similar issues to manually set the host IP. I set it to 127.0.0.1, and when I do, mylar throws an exception (per above) and Sab never gets the cached nzb url.

**Comment by evilhero** [comment]
Mylar scans your machine ips on startup and detects what it thinks is its' ip. It sometimes will autodetect the incorrect ip in various different network configs, usually docker related or multiple nics. The autodetect works fine in a vanilla type of network setup. 

You also have to enter the full host into the return_host (ie. http://127.0.0.1:8090), and your sabnzbd version has to be of at least 0.80. 

If you're using the return host option, you need to make sure you set your mylar host to 0.0.0.0 (from what I remember, it's literally been years since anyone has had problems with this). 

Have you tried the test connection button for sabnzbd within mylar? What does it display (debug logs too - would only be 1/2 lines)

**Comment by 13and3** [comment]
the lack of the port number may be the issue, I'll check tomorrow and close the issue if that's the case.

I use many VPNs, it may be caused by that, but the CIDR is a local block, not a VPN block.

**Comment by 13and3** [comment]
Something is wrong with the host_return implementation.  

If I set host_return 127.0.0.1:8090, send to SAB is unsuccessful (it does NOT queue anything up).

If I set the host_return to None, sab DOES get a message queued, and it has the wrong IP address.


Here are the abbreviated logs differentiating where two scenarios diverge:

Set to static IP:
`26-Mar-2019 15:08:10 - INFO :: mylar.failed_check.255 : Thread-13 : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
26-Mar-2019 15:08:10 - INFO :: mylar.searcher.2292 : Thread-13 : filen: Batgirl05220162coversDigitalZone-Empire.nzb -- nzbname: Batgirl.052.2016.2.covers.Digital.Zone-Empire are not identical. Storing extra value as : Batgirl05220162coversDigitalZone-Empire
26-Mar-2019 15:08:10 - INFO :: mylar.sender.42 : Thread-13 : parameters set to {'nzbname': u'Batgirl.052.2016.2.covers.Digital.Zone-Empire.nzb', 'apikey': u'b36855394be10bf0faea3fb219badf33', 'name': u'127.0.0.1:8090/api?apikey=1fa164f02b3d0a9eb8c356e773fee575&cmd=downloadNZB&nzbname=Batgirl.052.2016.2.covers.Digital.Zone-Empire.nzb', 'cmd': 'downloadNZB', 'priority': '-100', 'mode': 'addurl', 'output': 'json'}
26-Mar-2019 15:08:10 - INFO :: mylar.sender.43 : Thread-13 : sending now to http://127.0.0.1:8080/api
26-Mar-2019 15:08:10 - INFO :: mylar.sender.50 : Thread-13 : {u'status': True, u'nzo_ids': [None]}
26-Mar-2019 15:08:10 - ERROR :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/Users/13and3/mylar/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1911, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 359, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 1487, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/Users/13and3/mylar/mylar/mylar/search.py", line 2620, in searcher
    sendtosab = ss.sender()
  File "/Users/13and3/mylar/mylar/mylar/sabnzbd.py", line 53, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
TypeError: sequence item 0: expected string, NoneType found`


Set to None:
`26-Mar-2019 15:18:26 - INFO :: mylar.nzb_monitor.3175 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'issueid': u'527102', 'apicall': True, 'nzo_id': u'SABnzbd_nzo_8c3Hiq', 'queue': {'output': 'json', 'search': u'SABnzbd_nzo_8c3Hiq', 'apikey': u'b36855394be10bf0faea3fb219badf33', 'mode': 'queue'}, 'comicid': u'42604'}
26-Mar-2019 15:18:26 - INFO :: mylar.processor.67 : AUTO-COMPLETE-NZB : sending now to http://127.0.0.1:8080/api
26-Mar-2019 15:18:26 - INFO :: mylar.processor.68 : AUTO-COMPLETE-NZB : parameters set to {'status': True, 'issueid': u'527102', 'apicall': True, 'nzo_id': u'SABnzbd_nzo_8c3Hiq', 'queue': {'output': 'json', 'search': u'SABnzbd_nzo_8c3Hiq', 'apikey': u'b36855394be10bf0faea3fb219badf33', 'mode': 'queue'}, 'comicid': u'42604'}
26-Mar-2019 15:18:31 - INFO :: mylar.processor.76 : AUTO-COMPLETE-NZB : successfully queried the queue for status
26-Mar-2019 15:18:31 - INFO :: mylar.processor.100 : AUTO-COMPLETE-NZB : File has now downloaded!`

**Comment by 13and3** [comment]
```
[Interface]
http_password = None
https_chain = None
authentication = 0
http_port = 8090
login_timeout = 43800
http_root = /
https_force_on = False
https_cert = None
http_host = 0.0.0.0
enable_https = False
https_key = None
host_return = None
http_username = None
alphaindex = True
```

**Comment by 13and3** [comment]
```

[SABnzbd]
sab_client_post_processing = True
sab_to_mylar = False
sab_host = http://127.0.0.1:8080
sab_password = None
sab_apikey = b36855394be10bf0faea3fb219badf33
sab_version = 2.3.8
sab_directory = None
sab_category = None
sab_priority = Default
sab_username = None```

**Comment by evilhero** [comment]
The host_return implementation works fine, however, again - you NEED to specify the full host url (including the protocol) in the host_return field.

**Comment by 13and3** [comment]
You're 100% right.  I needed to set the full URL, Protocol + host + port and now it works A-O-K

Thanks for the help!
