### ISSUE TITLE
Unable to manage comics

### ISSUE THREAD

**Issue by Magnus010** [evilhero/mylar#2259]
After adding some Discworld graphic novels (Mort, Guards! Guards!, The Colour of Magic, and The Light Fantastic), I'm unable to select the "Manage comics" link. Also, the default page does not load either. Both attempts result in an Error 500:

```500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 73, in home
    comics = helpers.havetotals()
  File "/app/mylar/mylar/helpers.py", line 1408, in havetotals
    logger.warn(comic['ComicName'] + ' has not finished loading. Nulling some values so things display properly until they can populate.')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

The Logs don't show the error (that I've seen), and I don't see the same error in the Docker container.
Here's the version #: Version: 3f30faee32129d7670f9d7d590d3941fc3bd5b88 ((HEAD detached at 3f30fae))
I'm running it on an Ubuntu 18.04 system from the linuxserver/mylar:latest Docker image.

**Comment by Magnus010** [comment]
I restarted the Docker container and it looks like it's working with no issues now. Never mind, sorry about the trouble!
