### ISSUE TITLE
Search Fail Due to Bug, When Usenet RSS is Disabled 

### ISSUE THREAD

**Issue by Budlyte** [evilhero/mylar#2284]
My search providers are Newznab & Experimental, no torrents or getcomics.

Mylar stopped finding just about anything, and seemed to only check RSS feeds when I did a manual search, so I disabled RSS and now the search runs into the below error.

2019-05-25 00:00:55 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "C:\Mylar\mylar\helpers.py", line 3144, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "C:\Mylar\mylar\search.py", line 1855, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "C:\Mylar\mylar\search.py", line 359, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "C:\Mylar\mylar\search.py", line 1487, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)File "C:\Mylar\mylar\search.py", line 2486, in searcherss = nzbget.NZBGet()File "C:\Mylar\mylar\nzbget.py", line 38, in __init__val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignment
-- | -- | --

**Comment by Budlyte** [comment]
Looks like it's trying to parse my Newznab Host, currently set to "http://api.dognzb.cr".

**Comment by evilhero** [comment]
We have an issue template for a reason - please use it if you would like future assistance on any issue. 

You also don't have a protocol (http/https) supplied for your nzbget host within mylar.
