### ISSUE TITLE
Attribute Error 'NoneType' object as no attribute 'lower'

### ISSUE THREAD

**Issue by trumblejoe** [evilhero/mylar#2306]
**Describe the bug**
Scan Comic Library, Background Import fails.

**Screenshots/Logs**

2019-07-06 21:23:43 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/webserve.py", line 4497, in preSearchitif 'annual' in getiss.lower():AttributeError: 'NoneType' object has no attribute 'lower'
-- | -- | --
2019-07-06 21:23:43 | DEBUG | [IMPORT] [!none] volume: v01
2019-07-06 21:23:43 | DEBUG | [IMPORT] [!none] dynamicname: batmandeathoffamily
2019-07-06 21:23:43 | INFO | [IMPORT][Batman - Death of the Family (v01)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.

**Environment (please complete the following information):**
 - OS: Debian
Mylar Version: (HEAD detached at 68a8e77)-- git build 68a8e77ad15a960b62106616c38e277ff0ec01cb.Python Version : 2.7.16Language : en_US.UTF-8

**Additional information**
Error fully ends bulk background import. Frustrating as it doesn't allow me to be left with only the problem children for further analysis.

**Comment by barbequesauce** [comment]
Sorry about this - but we need the log file, not a copy paste from the log page. Believe it or not there is more detail in the log file...

@evilhero #carepackage

**Comment by evilhero** [comment]
Looking at that dynamicname, I'd guess you're trying to import in some TPB/GN's that don't have an issue number. Also, for future reference, full debug logs - not posting the logs means a reply is not going to be high on our to-do list. 

Mylar supports searching / scanning for these types of volumes, however the import process has to be recoded to accomodate the possibility of a lack of an issue number within the filename.

ATM, the only solution is to remove those items from your import directory and manually add the series, move the files over kinda deal. 

No timetable as to when this gets integrated for the import either. Wouldn't expect anything until after summer as probably not much is going to get done while school is out.
