### ISSUE TITLE
nothing is downloaded with ddl 

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#2311]
**Describe the bug**
I have never gotten ddl to work. I get an Uncaught exception error see the log. It seems to find the correct comic to download, but cant download it.

**Screenshots/Logs**

2019-07-22 16:46:35 | INFO | Update complete
-- | -- | --
2019-07-22 16:46:35 | DEBUG | ReScheduled job: DB Updater to 2019-07-22 14:51:35
2019-07-22 16:46:34 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2019-07-22 16:41:37 | ERROR | Uncaught exception: Traceback (most recent call last):File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/local/python/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 3147, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1855, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 359, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1476, in NZB_SEARCHnzbname = nzbname_create(nzbprov, info=mylar.COMICINFO, title=ComicTitle) #entry['title'])File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1986, in nzbname_createif os.path.exists(mylar.CONFIG.BLACKHOLE_DIR):File "/volume1/@appstore/mylar/env/lib/python2.7/genericpath.py", line 26, in existsos.stat(path)TypeError: coercing to Unicode: need string or buffer, NoneType found
2019-07-22 16:41:37 | DEBUG | integer value of issue we have found : 52000
2019-07-22 16:41:37 | DEBUG | issue we found for is : 52
2019-07-22 16:41:37 | DEBUG | integer value of issue we are looking for : 52000
2019-07-22 16:41:37 | DEBUG | issue we are looking for is : 52
2019-07-22 16:41:37 | DEBUG | Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
2019-07-22 16:41:37 | DEBUG | match_check: {'justthedigits': u'52', 'issueid': None, 'match_type': None, 'sub': None, 'comiclocation': None, 'booktype': 'issue', 'series_name': u'Giant Days', 'comicfilename': u'Giant Days #52 (2019)', 'annual_comicid': None, 'issue_year': '2019', 'volume': None, 'process_status': 'match', 'scangroup': None, 'alt_series': None, 'alt_issue': None, 'series_volume': None}
2019-07-22 16:41:37 | DEBUG | parsed_info: {'series_volume': None, 'booktype': 'issue', 'issueid': None, 'sub': None, 'comiclocation': None, 'reading_order': None, 'parse_status': 'success', 'dynamic_name': u'GiantDays', 'series_name': u'Giant Days', 'comicfilename': u'Giant Days #52 (2019)', 'issue_number': u'52', 'issue_year': '2019', 'scangroup': None, 'alt_series': None, 'alt_issue': None, 'series_name_decoded': 'Giant Days'}
2019-07-22 16:41:37 | DEBUG | series title possibly: Giant Days
2019-07-22 16:41:37 | DEBUG | sf_highest_series_pos: [u'Giant', u'Days']
2019-07-22 16:41:37 | DEBUG | issue verified as : 52
2019-07-22 16:41:37 | DEBUG | issue_position: 2
2019-07-22 16:41:37 | DEBUG | issue number :#52
2019-07-22 16:41:37 | DEBUG | possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': u'#52', 'mod_position': 11}]
2019-07-22 16:41:37 | DEBUG | highest_series_position: 3
2019-07-22 16:41:37 | DEBUG | year verified as: 2019
2019-07-22 16:41:37 | DEBUG | year verified as : 2019
2019-07-22 16:41:37 | DEBUG | sctd: 2019
2019-07-22 16:41:37 | DEBUG | datecheck: [{'date': u'2019', 'position': 3, 'mod_position': 15}]
2019-07-22 16:41:37 | DEBUG | date: 2019
2019-07-22 16:41:37 | DEBUG | checking date : 2019
2019-07-22 16:41:37 | DEBUG | Iissue number found: #52
2019-07-22 16:41:37 | DEBUG | NEWLY SPLIT REORGD: [u'Giant', u'Days', u'#52', u'(2019)']
2019-07-22 16:41:37 | DEBUG | Entry: Giant Days #52 (2019)
2019-07-22 16:41:37 | DEBUG | [CONV] Wed, 03 Jul 2019 00:00:00 is after store date of 2019-07-03
2019-07-22 16:41:37 | DEBUG | usedate: 2019-07-03
2019-07-22 16:41:37 | DEBUG | date used is : 2019-07-03
2019-07-22 16:41:37 | DEBUG | store date used is : 2019-07-03
2019-07-22 16:41:37 | DEBUG | size given as: 36.0 MB
2019-07-22 16:41:37 | DEBUG | comsize_b: 37748736
2019-07-22 16:41:37 | DEBUG | sub: Giant Days #52 (2019)
2019-07-22 16:41:37 | DEBUG | checking search result: Giant Days #52 (2019)
2019-07-22 16:41:37 | DEBUG | Giant Days #43 (2018) [34 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #44 (2018) [31 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #45 (2018) [30 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #46 (2019) [30 M]
2019-07-22 16:41:37 | DEBUG | Giant Days - Where Women Glow And Men Plunder #1 (2018) [50 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #47 (2019) [30 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #48 (2019) [32 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #49 (2019) [34 M]
2019-07-22 16:41:37 | DEBUG | Giant Days Vol. 1 - 8 (TPB) (2015-2018) [1.1 G]
2019-07-22 16:41:37 | DEBUG | Giant Days #50 (2019) [34 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #51 (2019) [31 M]
2019-07-22 16:41:37 | DEBUG | Giant Days #52 (2019) [36 M]
2019-07-22 16:41:37 | INFO | There are 12 results
2019-07-22 16:41:35 | INFO | Update complete
2019-07-22 16:41:34 | DEBUG | ReScheduled job: DB Updater to 2019-07-22 14:46:34
2019-07-22 16:41:34 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2019-07-22 16:41:34 | DEBUG | Sending request to DDL site for : Giant Days 52
2019-07-22 16:41:34 | DEBUG | findloop: 0 / findcount: 1
2019-07-22 16:41:34 | INFO | Shhh be very quiet...I'm looking for Giant Days issue: 52 (2019) using ddl.
2019-07-22 16:41:34 | INFO | Could not find Issue 52 of Giant Days (2015) using 32P [api]
2019-07-22 16:41:34 | DEBUG | findloop: 0 / findcount: 1
2019-07-22 16:41:34 | INFO | Shhh be very quiet...I'm looking for Giant Days issue: 52 (2019) using 32P.
2019-07-22 16:41:34 | DEBUG | Initiating Search via : api
2019-07-22 16:41:34 | INFO | Could not find Issue 52 of Giant Days (2015) using ddl [rss]
2019-07-22 16:41:34 | DEBUG | Sending request to [ddl] RSS for Giant Days : 52
2019-07-22 16:41:34 | DEBUG | findloop: 0 / findcount: 1
2019-07-22 16:41:34 | INFO | Shhh be very quiet...I'm looking for Giant Days issue: 52 (2019) using ddl [RSS].
2019-07-22 16:41:34 | INFO | Could not find Issue 52 of Giant Days (2015) using 32P [rss]

**Environment (please complete the following information):**
 - OS: Linux, Synology DS
Mylar Version: Development-- git build 68a8e77ad15a960b62106616c38e277ff0ec01cb
--

**Comment by barbequesauce** [comment]
Do you have blackhole_dir set in your config.ini? If you do, does the mylar user have read/write access to it?

**Comment by Lasborg** [comment]
blackhole_dir = None

And there are no changes to DDL settings in the INI

**Comment by Lasborg** [comment]
blackhole_dir = None

And there are no changes to DDL settings in the INI

**Comment by Lasborg** [comment]
blackhole_dir = None

And there are no changes to DDL settings in the INI

**Comment by Lasborg** [comment]
blackhole_dir = None

And there are no changes to DDL settings in the INI

**Comment by evilhero** [comment]
You have blackhole enabled for nzbs and it's throwing off the checks. Set it to sab/nzbget for the time being to bypass until a fix comes out.

Also, you don't need to answer the same question multiple times - we get notified every time.

**Comment by evilhero** [comment]
You have blackhole enabled for nzbs and it's throwing off the checks. Set it to sab/nzbget for the time being to bypass until a fix comes out.

Also, you don't need to answer the same question multiple times - we get notified every time.

**Comment by evilhero** [comment]
You have blackhole enabled for nzbs and it's throwing off the checks. Set it to sab/nzbget for the time being to bypass until a fix comes out.

Also, you don't need to answer the same question multiple times - we get notified every time.

**Comment by evilhero** [comment]
You have blackhole enabled for nzbs and it's throwing off the checks. Set it to sab/nzbget for the time being to bypass until a fix comes out.

**Comment by Lasborg** [comment]
Changing Usenet settings from Blackhole to Sabnzbd fixed the issue.
Thank you.
