### ISSUE TITLE
Uncaught exception: Traceback (most recent call last):

### ISSUE THREAD

**Issue by WraithTDK** [evilhero/mylar#2336]
**Describe the bug**
I'm having a real devil of a time getting Mylar to recognize downloaded comics in the monitored folder. I thought it was just a matter of it getting confused by the tags scanner put at the end of file names. But I just noticed that errors are cropping up in the logs when I try to run a manual post-process (see below)

**Screenshots/Logs**
Below is the error. I've also attached the log ([mylar.log](https://github.com/evilhero/mylar/files/3513233/mylar.log)), with error start at line 344:

18-Aug-2019 15:47:31 - ERROR   :: mylar.excepthook.315 : Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/PostProcessor.py", line 403, in Process
    filelist = flc.listFiles()
  File "/opt/mylar/mylar/filechecker.py", line 147, in listFiles
    runresults = self.parseit(self.dir, filename, filedir)
  File "/opt/mylar/mylar/filechecker.py", line 1056, in parseit
    elif 'XCV' in issue_number:
TypeError: argument of type 'NoneType' is not iterable

**Environment (please complete the following information):**
 - OS: Linux (exact details unclear, on a seedbox)
 - Branch / commit: 68a8e77ad15a960b62106616c38e277ff0ec01cb (master)

**Additional information**
Is there a way to better train Mylar to recognize filenames? Teach it to ignore tags? Or just manually point it at a file and tell it "this file is this item on my want-list"?

**Comment by WraithTDK** [comment]
Figured it out. _Nightwing v02 - Back to Blüdhaven_ was killing it. I presume because of the Umlaut. Pulled that issue and things are running as expected.
