### ISSUE TITLE
StoryArc add error

### ISSUE THREAD

**Issue by m00n22** [evilhero/mylar#2347]
When adding any StoryArc i get served with an 500 Internal Server Error. I can add a normal serie without problems.

**ERROR**
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/mylar/webserve.py", line 525, in addStoryArc
    buf = StringIO(r.content)
NameError: global name 'StringIO' is not defined
```

**VERBOSE LOG**
```
2019-09-13 09:11:49 | DEBUG | comic image retrieval status code: 200
-- | -- | --
2019-09-13 09:11:49 | INFO | imageurl: https://comicvine.gamespot.com/api/image/scale_large/6407309-5793928428-latest
2019-09-13 09:11:49 | INFO | Attempting to retrieve the comic image for series
2019-09-13 09:11:41 | INFO | Web logs cleared
```

**DEBUG LOG**

```
13-Sep-2019 09:20:05 - DEBUG   :: mylar.searchit.266 : CP Server Thread-6 : story_arc mode enabled.
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.146 : CP Server Thread-6 : there are 1 search results...
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.171 : CP Server Thread-6 : story_arc ascension
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.174 : CP Server Thread-6 : length: 2
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.177 : CP Server Thread-6 : story_arc
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.179 : CP Server Thread-6 : yes
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.183 : CP Server Thread-6 : name: The Clone Conspiracy
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.177 : CP Server Thread-6 : publisher
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.189 : CP Server Thread-6 : publisher check.
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.199 : CP Server Thread-6 : length: 2
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.202 : CP Server Thread-6 : publisher
13-Sep-2019 09:20:07 - DEBUG   :: mylar.findComic.202 : CP Server Thread-6 : story_arc
13-Sep-2019 09:20:10 - DEBUG   :: mylar.storyarcinfo.483 : CP Server Thread-6 : story_arc ascension
13-Sep-2019 09:20:10 - DEBUG   :: mylar.storyarcinfo.515 : CP Server Thread-6 : hit it.
13-Sep-2019 09:20:10 - DEBUG   :: mylar.storyarcinfo.519 : CP Server Thread-6 : firstid: 553945
13-Sep-2019 09:20:12 - DEBUG   :: mylar.storyarcinfo.522 : CP Server Thread-6 : success
13-Sep-2019 09:20:12 - INFO    :: mylar.findComic.215 : CP Server Thread-6 : [IMAGE] : https://comicvine.gamespot.com/api/image/scale_large/5575142-the-clone-conspiracy-1-main-cover.jpg
13-Sep-2019 09:20:41 - INFO    :: mylar.addStoryArc.507 : CP Server Thread-2 : Attempting to retrieve the comic image for series
13-Sep-2019 09:20:41 - INFO    :: mylar.addStoryArc.513 : CP Server Thread-2 : imageurl: https://comicvine.gamespot.com/api/image/scale_large/5575142-the-clone-conspiracy-1-main-cover.jpg
13-Sep-2019 09:20:41 - DEBUG   :: mylar.addStoryArc.519 : CP Server Thread-2 : comic image retrieval status code: 200
```

 - OS: Synology DS918+ Docker container
 - Version: 9fb9ab4d732fad1c181df54e419975e5ec823d2a ((HEAD detached at 9fb9ab4))

**Comment by Bussterj** [comment]
Any update on this I'm getting the same error

**Comment by Forbes256** [comment]
Same here. Tried on two different installs. One on Docker, one on Mac running Dev

**Comment by evilhero** [comment]
Should be all fixed now in both branches.

**Comment by Bussterj** [comment]
Updated and fixed :)

**Comment by Forbes256** [comment]
Excellent work! Updated and fixed here as well.
