### ISSUE TITLE
Error: table ddl_info already exists

### ISSUE THREAD

**Issue by dreaganluna** [evilhero/mylar#2364]
**Describe the bug**
Mylar does not start up anymore, throwing an error over and over in the log files: "table ddl_info already exists". This has gone on for a couple of days now, so unfortunately I can't trace back to or how this has happened.

**Screenshots/Logs**
```
21-Oct-2019 11:22:09 - INFO    :: mylar.initialize.186 : MainThread : Checking to see if the database has all tables....
21-Oct-2019 11:22:09 - ERROR   :: mylar.initialize.190 : MainThread : Cannot connect to the database: malformed database schema (ddl_info) - table ddl_info already exists
21-Oct-2019 11:22:09 - INFO    :: mylar.initialize.200 : MainThread : Successfully discovered local IP and locking it in as : 192.168.0.248
21-Oct-2019 11:22:09 - INFO    :: mylar.initialize.262 : MainThread : Remapping the sorting to allow for new additions.
21-Oct-2019 11:22:09 - ERROR   :: mylar.fetch.105 : MainThread : Fatal error executing query: malformed database schema (ddl_info) - table ddl_info already exists
21-Oct-2019 11:22:09 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "c:\Mylar\Mylar.py", line 348, in <module>
    main()
  File "c:\Mylar\Mylar.py", line 166, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "c:\Mylar\mylar\__init__.py", line 263, in initialize
    COMICSORT = helpers.ComicSort(sequence='startup')
  File "c:\Mylar\mylar\helpers.py", line 725, in ComicSort
    comicsort = myDB.select("SELECT * FROM comics ORDER BY ComicSortName COLLATE NOCASE")
  File "c:\Mylar\mylar\db.py", line 144, in select
    sqlResults = self.fetch(query, args).fetchall()
  File "c:\Mylar\mylar\db.py", line 89, in fetch
    sqlResult = cursor.execute(query)
DatabaseError: malformed database schema (ddl_info) - table ddl_info already exists
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: dev/29f39e5

**Additional information**
There might have been some kind of network issue at home recently, but I don't think that could have caused this. Is there any way to recover from this?

**Comment by dreaganluna** [comment]
Tried to recover the DB myself by going `sqlite3 mylar.db ".dump" | sqlite3 new-mylar.db`, and using that one instead, which seems to have worked.
Still don't know though how this could have happened.
