### ISSUE TITLE
Exception on Manual Search

### ISSUE THREAD

**Issue by marartner** [evilhero/mylar#2398]
**Describe the bug**
When clicking "Manual Search" for an issue, nothing much happens and there's a message in the logs. It's a brand new setup and this happens for any comic/issue.

**Screenshots/Logs**
```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/importer.py", line 476, in addComictoDB
search.searchforissue(result['IssueID'])
File "/app/mylar/mylar/search.py", line 1862, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 359, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/app/mylar/mylar/search.py", line 1489, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
File "/app/mylar/mylar/search.py", line 2493, in searcher
ss = nzbget.NZBGet()
File "/app/mylar/mylar/nzbget.py", line 38, in __init__
val = (protocol,)
UnboundLocalError: local variable 'protocol' referenced before assignment
```

**Environment (please complete the following information):**
https://hub.docker.com/r/linuxserver/mylar
though I had the same problem when I tried to run Mylar on my Mac directly without Docker, so it doesn't seem OS specific.

**Comment by evilhero** [comment]
You need to include the protocol (http/https) for your nzbget host address within Mylar.

**Comment by marartner** [comment]
Ah, that was indeed the reason, thank you!
