### ISSUE TITLE
Uncaught exception error

### ISSUE THREAD

**Issue by shaunvis** [evilhero/mylar#2410]
Everything was working fine until the past few days. Nothing changed or was updated but now I'm getting this error. Any ideas?

Uncaught exception: Traceback (most recent call last): File "/app/mylar/mylar/logger.py", line 337, in new_run old_run(*args, **kwargs) File "/usr/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs) File "/app/mylar/mylar/PostProcessor.py", line 403, in Process filelist = flc.listFiles() File "/app/mylar/mylar/filechecker.py", line 147, in listFiles runresults = self.parseit(self.dir, filename, filedir) File "/app/mylar/mylar/filechecker.py", line 353, in parseit tmpfilename = re.sub(i, 'XCV', tmpfilename) File "/usr/lib/python2.7/re.py", line 155, in sub return _compile(pattern, flags).sub(repl, string, count) File "/usr/lib/python2.7/re.py", line 251, in _compile raise error, v # invalid expression error: unbalanced parenthesis
--

**Comment by evilhero** [comment]
Please follow the issue template and include a debug log showing what occurs prior to the error.

**Comment by shaunvis** [comment]
I forgot about debug logs, thanks. Turning that on & digging through it helped me figure it out.

Just an FYI since this is odd, it was caused by a folder in my completed folder folder. When Mylar went to grab things it downloaded or if I did a manual import, it saw the folder (Folder name: "Pleasuredome Rules") and freaked out.  I deleted that folder and everything started working again.

**Comment by evilhero** [comment]
If there were filenames within that folder, odds are it was one of the naming conventions in there that was causing it to parse it incorrectly.

If you could pass along the name of the file it was trying to parse and died on, I can figure out why it died and attempt to fix things for future use.

**Comment by shaunvis** [comment]
Here's the sections it got hung on. The folder just had some pdfs in it, "ReadMe (Dansk).pdf", ReadMe (Ελληνικά).pdf, etc.. 

Let me know if you need more info

31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.230 : Thread-14 : [SUB-PATH] Checking Folder Name for more information.
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.232 : Thread-14 : [SUB-PATH] Original Path : /SabComplete
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.233 : Thread-14 : [SUB-PATH] Sub-directory : /SabComplete/Pleasuredome Rules
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.246 : Thread-14 : [SUB-PATH] subpath set to : Pleasuredome Rules
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.433 : Thread-14 : NEWLY SPLIT REORGD: ['ReadMe', '(Dansk)']
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.803 : Thread-14 : datecheck: []
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.853 : Thread-14 : No year present within title - ignoring as a variable.
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.856 : Thread-14 : highest_series_position: 2
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.953 : Thread-14 : issue_position: 2
31-Jan-2020 15:13:03 - INFO    :: mylar.parseit.968 : Thread-14 : No issue number present in filename.
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.1105 : Thread-14 : sf_highest_series_pos: ['ReadMe', '(Dansk)']
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.1150 : Thread-14 : series title possibly: ReadMe (Dansk)
31-Jan-2020 15:13:03 - INFO    :: mylar.parseit.1189 : Thread-14 : Possible UKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
31-Jan-2020 15:13:03 - DEBUG   :: mylar.listFiles.146 : Thread-14 : [FILENAME]: ReadMe (Ελληνικά).pdf
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.228 : Thread-14 : [CORRECTION] Sub-directory found. Altering path configuration.
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.230 : Thread-14 : [SUB-PATH] Checking Folder Name for more information.
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.232 : Thread-14 : [SUB-PATH] Original Path : /SabComplete
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.233 : Thread-14 : [SUB-PATH] Sub-directory : /SabComplete/Pleasuredome Rules
31-Jan-2020 15:13:03 - DEBUG   :: mylar.parseit.246 : Thread-14 : [SUB-PATH] subpath set to : Pleasuredome Rules

**Comment by TheFirstAv3nger** [comment]
This is happening to me also. Just random comics, but always the same ones. I'm using the dev branch on windows and just pulled yesterday. 

Here is a log of a fresh restart, me manually searching for a comic I know throws the error, then me manually searching for a different comic, which then mylar hangs on any search until a restart.


2020-02-06 20:42:29 | INFO | [WANTED-SEARCH] Now Queueing Hal Jordan and the Green Lantern Corps (2016) #10 for search
-- | -- | --
2020-02-06 20:42:29 | INFO | Initiating manual search for Hal Jordan and the Green Lantern Corps issue: 10
2020-02-06 20:42:05 | ERROR | Uncaught exception: Traceback (most recent call last):File "c:\Mylar\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "c:\Python27\lib\threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "c:\Mylar\mylar\helpers.py", line 3170, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "c:\Mylar\mylar\search.py", line 1862, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "c:\Mylar\mylar\search.py", line 359, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "c:\Mylar\mylar\search.py", line 625, in NZB_SEARCHbb = b.search()File "c:\Mylar\mylar\getcomics.py", line 68, in searchreturn self.search_results()File "c:\Mylar\mylar\getcomics.py", line 128, in search_resultsoption_find = option_find.findNext(text=True)AttributeError: 'NoneType' object has no attribute 'findNext'
2020-02-06 20:42:05 | INFO | There are 12 results
2020-02-06 20:42:02 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using ddl.
2020-02-06 20:42:02 | INFO | Could not find Issue 45 of The Flash (2016) using NzbGeek [api]
2020-02-06 20:42:02 | INFO | no errors on data retrieval...proceeding
2020-02-06 20:41:57 | INFO | Pausing for 60 seconds before continuing to avoid hammering
2020-02-06 20:41:57 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using NzbGeek (newznab).
2020-02-06 20:41:57 | INFO | Could not find Issue 45 of The Flash (2016) using ddl [rss]
2020-02-06 20:41:57 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using ddl [RSS].
2020-02-06 20:41:57 | INFO | Could not find Issue 45 of The Flash (2016) using NzbGeek [rss]
2020-02-06 20:41:57 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using NzbGeek (newznab) [RSS].
2020-02-06 20:41:57 | INFO | Could not find Issue 45 of The Flash (2016) using ddl [rss]
2020-02-06 20:41:57 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using ddl [RSS].
2020-02-06 20:41:57 | INFO | Could not find Issue 45 of The Flash (2016) using NzbGeek [rss]
2020-02-06 20:41:57 | INFO | Shhh be very quiet...I'm looking for The Flash issue: 45 (2018) using NzbGeek (newznab) [RSS].
2020-02-06 20:41:56 | INFO | [SEARCH-QUEUE] Now loading item from search queue: {'comicname': u'The Flash', 'issueid': u'667604', 'seriesyear': u'2016', 'booktype': u'Print', 'issuenumber': u'45', 'comicid': u'91750'}
2020-02-06 20:41:53 | INFO | [WANTED-SEARCH] Now Queueing The Flash (2016) #45 for search
2020-02-06 20:41:53 | INFO | Initiating manual search for The Flash issue: 45
2020-02-06 20:41:11 | INFO | Background Schedulers successfully started...
2020-02-06 20:41:11 | INFO | Firing up the Background Schedulers now....
2020-02-06 20:41:11 | INFO | [RSS-FEEDS] RSS last run @ 2020-02-07 01:04:48.297000
2020-02-06 20:41:11 | INFO | [RSS-FEEDS] Initiating startup-RSS feed checks.
2020-02-06 20:41:11 | INFO | [WEEKLY] Checking for existance of Weekly Comic listing...

**Comment by evilhero** [comment]
@TheFirstAv3nger this unfortunately has nothing to do with the original poster's post, which was dealing with manual post-processing, not downloading an item using DDL. Topics have to remain on topic, or else they'll get lost in the shuffle and never responded to.

Please submit a new issue ticket with the relevant information as per the issue template, and please remember to include debug logs along with it (it saves us having to just ask for them, cause looking at what you posted, I'd ask for them before anything else).
