### ISSUE TITLE
Unable to process nzb's - uncaught error

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#2411]
````
Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/Mylar/mylar/helpers.py", line 3170, in search_queue
ss_queue = mylar.search.searchforissue(item['issueid'])
File "/opt/Mylar/mylar/search.py", line 1862, in searchforissue
foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 359, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
File "/opt/Mylar/mylar/search.py", line 659, in NZB_SEARCH
a = auth32p.info32p(searchterm=searchterm)
File "/opt/Mylar/mylar/auth32p.py", line 76, in __init__
mylar.INKDROPS_32P = lses.inkdrops['results'][0]['inkdrops']
TypeError: 'NoneType' object has no attribute '__getitem__'
````

This was trying to pull Lois Lane issue 8 from nzbplanet (it's definitely there) manually.

````
Mylar Version: development
-- git build f49f563e301239880a42c209484eaf1899d39654.
Python Version : 2.7.12
Language : en_GB.UTF-8
````

It seems to be failing on matching all nzbd's.

**Comment by barbequesauce** [comment]
32p is down, disable it in your providers page.
