### ISSUE TITLE
Comictagger bug. removed signed argument.

### ISSUE THREAD

**Issue by kalinon** [evilhero/mylar#2435]
https://github.com/evilhero/mylar/blob/d3cb7f87c5a6f73866da12dafeeefd1982e2ff02/lib/comictaggerlib/comicapi/comicarchive.py#L876

```
16-Apr-2020 14:54:57 - INFO    :: mylar.run.204 : CP Server Thread-5 : Traceback (most recent call last):
  File "/opt/mylar/comictagger.py", line 5, in <module>
    ctmain()
  File "/opt/mylar/lib/comictaggerlib/main.py", line 62, in ctmain
    cli.cli_mode(opts, settings)
  File "/opt/mylar/lib/comictaggerlib/cli.py", line 193, in cli_mode
    process_file_cli(f, opts, settings, match_results)
  File "/opt/mylar/lib/comictaggerlib/cli.py", line 231, in process_file_cli
    if not ca.seemsToBeAComicArchive():
  File "/opt/mylar/lib/comictaggerlib/comicapi/comicarchive.py", line 727, in seemsToBeAComicArchive
    (self.getNumberOfPages() > 0)
  File "/opt/mylar/lib/comictaggerlib/comicapi/comicarchive.py", line 893, in getNumberOfPages
    self.page_count = len(self.getPageNameList())
  File "/opt/mylar/lib/comictaggerlib/comicapi/comicarchive.py", line 876, in getPageNameList
    files = natsorted(files, key=keyfunc, signed=False)
TypeError: natsorted() got an unexpected keyword argument 'signed'
```

**Comment by evilhero** [comment]
The version of natsort you have installed isn't supported by this version of Mylar. Either pip uninstall your version, install a version less than 5 or even better install Mylar3 since this version of mylar isn't being supported any longer as per the readme.

**Comment by kalinon** [comment]
Roger, didnt know there was a new version. Thanks.
