### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by nate235** [evilhero/mylar#2439]
**Describe the bug**
Installing Mylar using the readme installation instruction results in a few errors. Initially I thought this was because it was using an older version of python, so I unintalled all other versions of python and installed 3.8.1 since it was mentioned in the readme. I still got exceptions when installing, which mention microst visual studio 14, which I installed. Trying pip38 and py install command result in errors. I got stuck at my current error message, though it could just be brain fatigue and something obvious. I apologise if this is something silly/PMAC related.

**Screenshots/Logs**
I didn't find a log file. The posted log is only of the error message and the last line of succesful for brevity. I can add it all if needed. I'm not sure where the logs the last line of the error refers to.
```
Collecting unrar-cffi==0.1.0a5
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mnfmo\\AppData\\Local\\Temp\\pip-install-cufecal6\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\mnfmo\\AppData\\Local\\Temp\\pip-install-cufecal6\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mnfmo\AppData\Local\Temp\pip-pip-egg-info-buku83a9'
         cwd: C:\Users\mnfmo\AppData\Local\Temp\pip-install-cufecal6\unrar-cffi\
    Complete output (129 lines):
    _configtest.c
    _cffi_backend.c
    c/_cffi_backend.c(370): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(371): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(1062): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1071): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1096): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1119): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1138): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1152): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1301): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1303): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1653): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1654): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1656): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1668): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1669): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1672): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1691): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1735): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1800): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1802): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1813): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(1816): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(2206): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(2211): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(2215): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(2230): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(2289): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(3218): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(3933): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(4033): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(4149): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(4190): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(4734): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(4752): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(4893): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(4884): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(4905): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(5299): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(5346): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(5353): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(5572): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned short', possible loss of data
    c/_cffi_backend.c(5701): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(5705): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(5721): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(5734): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    c/_cffi_backend.c(5763): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    c/_cffi_backend.c(5813): warning C4244: 'function': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
    c/_cffi_backend.c(5898): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
    c/_cffi_backend.c(6360): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\parse_c_type.c(218): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\parse_c_type.c(287): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\parse_c_type.c(341): warning C4244: '=': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\parse_c_type.c(445): warning C4244: 'return': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(425): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(430): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(448): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(460): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(559): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(621): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(700): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\realize_c_type.c(753): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(130): warning C4244: 'initializing': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(306): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(358): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(384): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(405): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\lib_obj.c(419): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(170): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(215): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(247): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(248): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(260): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(261): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(281): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(301): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(302): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(307): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(327): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\cdlopen.c(331): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\mnfmo\AppData\Local\Temp\easy_install-6ix_fgk_\cffi-1.14.0\c\call_python.c(110): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    ffi.c
    prep_cif.c
    c/libffi_msvc\prep_cif.c(166): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
    types.c
       Creating library build\temp.win-amd64-3.8\Release\c\_cffi_backend.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\c\_cffi_backend.cp38-win_amd64.exp
    Generating code
    Finished generating code

    Installed c:\users\mnfmo\appdata\local\temp\pip-install-cufecal6\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg
    Searching for pycparser
    Reading https://pypi.org/simple/pycparser/
    Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl#sha256=7582ad22678f0fcd81102833f60ef8d0e57288b6b5fb00323d101be910e35705
    Best match: pycparser 2.20
    Processing pycparser-2.20-py2.py3-none-any.whl
    Installing pycparser-2.20-py2.py3-none-any.whl to c:\users\mnfmo\appdata\local\temp\pip-install-cufecal6\unrar-cffi\.eggs

    Installed c:\users\mnfmo\appdata\local\temp\pip-install-cufecal6\unrar-cffi\.eggs\pycparser-2.20-py3.8.egg
    preprocessing extension headers
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mnfmo\AppData\Local\Temp\pip-install-cufecal6\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 445, in __init__
        _Distribution.__init__(self, {
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\mnfmo\appdata\local\temp\pip-install-cufecal6\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\mnfmo\appdata\local\temp\pip-install-cufecal6\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\mnfmo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Environment (please complete the following information):**
 - OS: Windows 10.
 - Branch / commit: Dev/94dcfd1

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
With Mylar3, Python3.8+ isn't supported on Windows due to the requirement of the unrar-cffi library which is used by ComicTagger. This will be fixed in a soon to be released commit, but in the meantime the only solution is to downgrade your python to the newest of the 3.7.x branch  (3.7.6 I think is the latest), so that the requirements.txt can compile the unrar-cffi properly.

Also, Mylar3 has it's own repo and issue tracker - [here](https://github.com/mylar3/mylar3)

**Comment by nate235** [comment]
Ahhh crap sorry I must have come here after closing the Mylar3 git, so sorry! I'll try that and move over there if I have further issues, thanks so much. Unfortunately I can't see how an option to delete this, only close it. So if you can/want to delete it, please feel free to. Thanks again.
