### ISSUE TITLE
Uncaught Expection not sure of the root cause

### ISSUE THREAD

**Issue by war3zlod3r** [evilhero/mylar#2441]
2020-09-14 17:23:52 | ERROR | [POST-PROCESSING] /config/mylar/cache not empty. Skipping removal of directory - this will either be caught in further post-processing or it will have to be manually deleted.
-- | -- | --
2020-09-14 17:23:31 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/helpers.py", line 3170, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/app/mylar/mylar/search.py", line 1862, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "/app/mylar/mylar/search.py", line 359, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "/app/mylar/mylar/search.py", line 902, in NZB_SEARCHtmpsz = entry.enclosures[0]AttributeError: 'dict' object has no attribute 'enclosures'
2020-09-14 17:23:14 | ERROR | Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar

**Comment by evilhero** [comment]
Please follow the template and include either the carepackage.zip, or a full debug log. Since you're running with warnings only I'm guessing, you'll have to enable debug logging, then re-run whatever it was that you were doing in order to properly populate the log for us to check out. 

Pasting just the error doesn't give us enough information to even attempt to try and track things down.

**Comment by war3zlod3r** [comment]
I’ll try to check my log settings and do it again no idea what happened I had just cleared the logs then restarted and this is the entirety of the log.

**Comment by war3zlod3r** [comment]
@evilhero is it possible to enable debug logging on startup, I can't seem to get it on before the error triggers. Also what is carepackage.zip and how can I generate it?
