### ISSUE TITLE
Unable to add comic to database

### ISSUE THREAD

**Issue by cclick815** [evilhero/mylar#2446]
**Describe the bug**
I'm unable to insert the current The Amazing Spider-Man series into the DB due to LR being into the issue numbers

**Screenshots/Logs**

2020-11-11 22:57:50 | ERROR | Uncaught exception: Traceback (most recent call last):  File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 337, in new_run    old_run(*args, **kwargs)  File "/var/packages/python/target/lib/python2.7/threading.py", line 754, in run    self.__target(*self.__args, **self.__kwargs)  File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 345, in addComictoDB     updateddata = updateissuedata(comicid, comic['ComicName'], issued,  comicIssues, calledfrom, SeriesYear=SeriesYear,  latestissueinfo=latestissueinfo)  File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 1267, in updateissuedata    latestiss = issnum  File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 1048, in issuedigits    decisval = int(decis)ValueError: invalid literal for int() with base 10: 'LR'

2020-11-11 22:57:50 | INFO | Now adding/updating issues for The Amazing Spider-Man
-- | -- | --
2020-11-11 22:57:50 | DEBUG | Finished Annual checking.
2020-11-11 22:57:50 | INFO | Successfully integrated 1 annuals into the series: The Amazing Spider-Man
2020-11-11 22:57:49 | DEBUG | Sending request to RSS for The Legend of Zelda Twilight Princess : 006 (2020)
2020-11-11 22:57:49 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:49 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda Twilight Princess issue: 6 (2020) using NZB Find (newznab) [RSS].
2020-11-11 22:57:49 | DEBUG | Using Newznab host of : NZB Find
2020-11-11 22:57:49 | INFO | Alternate Search pattern detected...re-adjusting to : The Legend of Zelda Twilight Princess
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 95808
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 95808
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - 113685 already exists within current annual list for series.
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - 113685 added to series list as an Annual
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - 112161 found. Assuming it is part of the greater collection.
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - tradeback/collected edition detected - skipping 2189
2020-11-11 22:57:49 | DEBUG | [IMPORTER-ANNUAL] - there are 4 results.
2020-11-11 22:57:49 | DEBUG | [RESULT][None] ComicName:Amazing Spider-Man Annual -- 2014 [Series years: [u'2014']]
2020-11-11 22:57:49 | DEBUG | [RESULT][None] ComicName:Amazing Spider-Man Annual -- 2016 [Series years: [u'2016']]
2020-11-11 22:57:49 | DEBUG | [RESULT][None] ComicName:Amazing Spider-Man Annual -- 2018 [Series years: [u'2018']]
2020-11-11 22:57:49 | DEBUG | [RESULT][None] ComicName:The Amazing Spider-Man Annual -- 1964 [Series years: [u'1964', '1965']]
2020-11-11 22:57:49 | DEBUG | there are 4 search results...
2020-11-11 22:57:48 | DEBUG | Sending request to RSS for The Legend of Zelda: Twilight Princess : 006 (2020)
2020-11-11 22:57:48 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:48 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda: Twilight Princess issue: 6 (2020) using NZB Find (newznab) [RSS].
2020-11-11 22:57:48 | DEBUG | Using Newznab host of : NZB Find
2020-11-11 22:57:48 | INFO | Could not find Issue 6 of The Legend of Zelda: Twilight Princess (2017) using NZBgeek [rss]
2020-11-11 22:57:47 | DEBUG | Sending request to RSS for The Legend of Zelda Twilight Princess : 006 (2020)
2020-11-11 22:57:47 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:47 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda Twilight Princess issue: 6 (2020) using NZBgeek (newznab) [RSS].
2020-11-11 22:57:47 | DEBUG | Using Newznab host of : NZBgeek
2020-11-11 22:57:47 | INFO | Alternate Search pattern detected...re-adjusting to : The Legend of Zelda Twilight Princess
2020-11-11 22:57:46 | DEBUG | Sending request to RSS for The Legend of Zelda: Twilight Princess : 006 (2020)
2020-11-11 22:57:46 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:46 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda: Twilight Princess issue: 6 (2020) using NZBgeek (newznab) [RSS].
2020-11-11 22:57:46 | DEBUG | Using Newznab host of : NZBgeek
2020-11-11 22:57:46 | INFO | Could not find Issue 6 of The Legend of Zelda: Twilight Princess (2017) using ddl [rss]
2020-11-11 22:57:46 | DEBUG | [IMPORTER-ANNUAL] - Annual Year:2018
2020-11-11 22:57:46 | DEBUG | there are 1 annuals within this series.
2020-11-11 22:57:46 | DEBUG | querying range from 0 to 100
2020-11-11 22:57:46 | DEBUG | there are 1 search results...
2020-11-11 22:57:45 | DEBUG | Sending request to [ddl] RSS for The Legend of Zelda Twilight Princess : 006
2020-11-11 22:57:45 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:45 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda Twilight Princess issue: 6 (2020) using ddl [RSS].
2020-11-11 22:57:45 | INFO | Alternate Search pattern detected...re-adjusting to : The Legend of Zelda Twilight Princess
2020-11-11 22:57:44 | DEBUG | Sending request to [ddl] RSS for The Legend of Zelda: Twilight Princess : 006
2020-11-11 22:57:44 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:44 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda: Twilight Princess issue: 6 (2020) using ddl [RSS].
2020-11-11 22:57:44 | INFO | Could not find Issue 6 of The Legend of Zelda: Twilight Princess (2017) using experimental [rss]
2020-11-11 22:57:44 | DEBUG | Attempting to integrate Amazing Spider-Man Annual (113685) to the existing series of The Amazing Spider-Man(2018)
2020-11-11 22:57:44 | DEBUG | comic[ComicVersion]:None
2020-11-11 22:57:44 | DEBUG | comic[ComicVersion]:None
2020-11-11 22:57:44 | DEBUG | vari is set to: no
2020-11-11 22:57:44 | DEBUG | number of issues CV says it has: 1
2020-11-11 22:57:44 | DEBUG | number of issues I counted: 1
2020-11-11 22:57:43 | DEBUG | Sending request to RSS for The Legend of Zelda Twilight Princess : 006 (2020)
2020-11-11 22:57:43 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:43 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda Twilight Princess issue: 6 (2020) using experimental [RSS].
2020-11-11 22:57:43 | INFO | Alternate Search pattern detected...re-adjusting to : The Legend of Zelda Twilight Princess
2020-11-11 22:57:42 | DEBUG | Sending request to RSS for The Legend of Zelda: Twilight Princess : 006 (2020)
2020-11-11 22:57:42 | DEBUG | findloop: 0 / findcount: 1
2020-11-11 22:57:42 | INFO | Shhh be very quiet...I'm looking for The Legend of Zelda: Twilight Princess issue: 6 (2020) using experimental [RSS].
2020-11-11 22:57:42 | INFO | Could not find Issue 6 of The Legend of Zelda: Twilight Princess (2017) using dognzb [rss]

**Environment (please complete the following information):**
 - OS: Synology
 - Branch / commit: Version: 94dcfd13f6c8be5836ca76324ebbe585bda642fc (development) 

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
Note this repo is effectively retired as Python 2 is out of support.

This bug has been squashed in the current version of the current repo - https://GitHub.com/mylar3/mylar3
