### ISSUE TITLE
Repeated error with search.py, most searches not happening

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#2447]
This seems to crop up fairly often, Mylar will grab an episode maybe once or twice a day, usually right after restarting, but otherwise won't search or find issues. The logs show this error repeating frequently:

`

2020-11-24 12:29:49 | ERROR | Traceback (most recent call last):  File "/app/mylar3/mylar/search.py", line 3093, in searchforissue    foundNZB, prov = search_init(  File "/app/mylar3/mylar/search.py", line 515, in search_init    findit = NZB_SEARCH(  File "/app/mylar3/mylar/search.py", line 2404, in NZB_SEARCH    searchresult = searcher(  File "/app/mylar3/mylar/search.py", line 4030, in searcher    ss = nzbget.NZBGet()  File "/app/mylar3/mylar/nzbget.py", line 38, in __init__    val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignmentTraceback (most recent call last):  File "/app/mylar3/mylar/search.py", line 3093, in searchforissue    foundNZB, prov = search_init(  File "/app/mylar3/mylar/search.py", line 515, in search_init    findit = NZB_SEARCH(  File "/app/mylar3/mylar/search.py", line 2404, in NZB_SEARCH    searchresult = searcher(  File "/app/mylar3/mylar/search.py", line 4030, in searcher    ss = nzbget.NZBGet()  File "/app/mylar3/mylar/nzbget.py", line 38, in __init__    val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignment
-- | -- | --

`

**Comment by barbequesauce** [comment]
Please repost in the mylar3 repo
