### ISSUE TITLE
error importing cbl

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#2449]
hey
i was trying to import a CBL file.
I put in this location:
/Users/joelhandloff/Firsttry.xml

Clicked import
And got
Traceback (most recent call last):
  File "/home/hd27/moleboy/apps/mylar/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/hd27/moleboy/apps/mylar/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/hd27/moleboy/apps/mylar/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/hd27/moleboy/apps/mylar/mylar/webserve.py", line 3313, in importReadlist
    file = open(filename)
IOError: [Errno 2] No such file or directory: u'/Users/joelhandloff/Firsttry.xml'

**Comment by thewindupboy** [comment]
I'm an idiot. Ignore me.
