### ISSUE TITLE
Traceback errors post manual search failure

### ISSUE THREAD

**Issue by dfjkl** [evilhero/mylar#756]
....also noting that since the issues are on nzb.su from what I can see...the manual search failing is somewhat annoying, but also I don't know what the traceback here is supposed to specifically be for/mean.  I thought maybe it's odd that the software is for some odd reason using the server shortname itself (despite that not being the DNS I'm using for the local site), but it does resolve on the system....

2014-06-21 23:54:08	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\opt\mylar\mylar\logger.py", line 141, in new_run
old_run(*args, **kwargs)
File "C:\opt\Python27\lib\threading.py", line 504, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\opt\mylar\mylar\webserve.py", line 812, in queueissue
raise cherrypy.HTTPRedirect("comicDetails?ComicID=%s" % ComicID)
HTTPRedirect: (['http://media_server:8090/comicDetails?ComicID=53919'], 303)
2014-06-21 23:54:08	INFO	Issue not found. Status kept as Wanted.
2014-06-21 23:54:08	INFO	Could not find Issue 19 of All-New X-Men(2013) using nzb.su
2014-06-21 23:54:06	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\opt\mylar\mylar\logger.py", line 141, in new_run
old_run(*args, **kwargs)
File "C:\opt\Python27\lib\threading.py", line 504, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\opt\mylar\mylar\webserve.py", line 812, in queueissue
raise cherrypy.HTTPRedirect("comicDetails?ComicID=%s" % ComicID)
HTTPRedirect: (['http://media_server:8090/comicDetails?ComicID=53919'], 303)
2014-06-21 23:54:06	INFO	Issue not found. Status kept as Wanted.
2014-06-21 23:54:06	INFO	Could not find Issue 20 of All-New X-Men(2013) using nzb.su
2014-06-21 23:54:04	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\opt\mylar\mylar\logger.py", line 141, in new_run
old_run(*args, **kwargs)
File "C:\opt\Python27\lib\threading.py", line 504, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\opt\mylar\mylar\webserve.py", line 812, in queueissue
raise cherrypy.HTTPRedirect("comicDetails?ComicID=%s" % ComicID)
HTTPRedirect: (['http://media_server:8090/comicDetails?ComicID=53919'], 303)

**Comment by solspire** [comment]
j'ai aussi cette erreur....

Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1544, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 283, in search_init
if searchprov == '32P':
UnboundLocalError: local variable 'searchprov' referenced before assignment

**Comment by evilhero** [comment]
@solspire: after any configuration change regarding providers (enabling / disabling),  you need to save the config and restart mylar. 

The error you're getting is typically due to not restarting after a provider change of some kind.
