### ISSUE TITLE
Uncaught Exception gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by hideadesign** [evilhero/mylar#908]
Hello

When i use Force Check i have the following error:

29-Dec-2014 11:00:51 - ERROR   :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/mylar-master/mylar/logger.py", line 141, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mylar-master/mylar/search.py", line 1294, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSe$
  File "/mylar-master/mylar/search.py", line 217, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, Com$
  File "/mylar-master/mylar/search.py", line 1183, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov)
  File "/mylar-master/mylar/search.py", line 1593, in searcher
    rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov)
  File "/mylar-master/mylar/rsscheck.py", line 811, in torsend2client
    tssh = ftpsshup.putfile(filepath,filename)
  File "/mylar-master/mylar/ftpsshup.py", line 23, in putfile
    transport = paramiko.Transport((host, port))
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 285, in __init__
    for (family, socktype, proto, canonname, sockaddr) in socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

**Comment by hideadesign** [comment]
i changed the seetings of my seedbox to enable a watchdir and now it works

thanks for your help
