### ISSUE TITLE
Mylar fails to start when previously working - 500 internal server error

### ISSUE THREAD

**Issue by Leempi** [evilhero/mylar#926]
Hi all. Not sure what happened. I'm assuming python was updated automatically on the synology box. Getting the following error when trying to visit Mylar:

    500 Internal Server Error

    The server encountered an unexpected condition which prevented it from fulfilling the request.

    Traceback (most recent call last):
      File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
        response.body = self.handler()
      File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 73, in home
        comics = helpers.havetotals()
      File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 1090, in havetotals
        comiclist = myDB.select('SELECT * from comics order by ComicSortName COLLATE NOCASE')
      File "/volume1/@appstore/mylar/share/mylar/mylar/db.py", line 145, in select
        sqlResults = self.fetch(query, args).fetchall()
    AttributeError: 'NoneType' object has no attribute 'fetchall'
    Powered by CherryPy 3.2.0

I'd like some idea of how to go about fixing this, without having to do a re-install, change to development branch, update, import all comics again, etc.

Any help appreciated.

Thanks!

**Comment by evilhero** [comment]
You have a series in your watchlist that's incomplete because it never finished loafing properly.  Since you can't get to the main page, have you tried just restarting mylar? 

Otherwise your other option is to get to the Manage Comics screen (Manage tab/Manage Comics button)  and find the series that's in Loading status or has errors listed and delete them.

**Comment by Leempi** [comment]
... restarting worked. I feel stupid. Thank you.
