### ISSUE TITLE
PostProcessing error when Annual exists

### ISSUE THREAD

**Issue by tjiddy** [evilhero/mylar#940]
using latest dev branch.  Series w/ no annual post process fine.  Series with an existing annual fail postprocessing with the following message

```
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] [453414] Issue match - fcdigit: 3000 ... int_iss: 3000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Matched...issue: Hulk#3 --- 3000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filename: Hulk #003 (2014).cbz
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filesize: 37801004
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] issueID to write to db:453414
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] temploc: 004
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] [456023] Issue match - fcdigit: 4000 ... int_iss: 4000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Matched...issue: Hulk#4 --- 4000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filename: Hulk #004 (2014).cbz
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filesize: 34102465
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] issueID to write to db:456023
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] temploc: 006
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] [465844] Issue match - fcdigit: 6000 ... int_iss: 6000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] Matched...issue: Hulk#6 --- 6000
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filename: Hulk #006 (2014).cbz
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] .......filesize: 46392539
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] issueID to write to db:465844
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] temploc: Annual.001
05-Feb-2015 04:17:41 - DEBUG   :: Post-Processing : Annual detected.
05-Feb-2015 04:17:45 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/srv/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/srv/mylar/mylar/PostProcessor.py", line 570, in Process
    return self.Process_next(comicid,issueid,issuenumOG)
  File "/srv/mylar/mylar/PostProcessor.py", line 1024, in Process_next
    updater.forceRescan(comicid,module=module)
  File "/srv/mylar/mylar/updater.py", line 890, in forceRescan
    if fcnew[som+1].isdigit():
IndexError: list index out of range
```

If I delete the annual(s) and retry post processing, it is successful.
Existing annuals are in the format  Hulk #Annual 001 (2014).cbz

**Comment by evilhero** [comment]
It's due to the formatting of the issue - the '#' sign is in the wrong place (at least where Mylar would be expecting it). The word 'annual' is part of the actual title 'hulk', not part of the issue numbering - so because of this, and because that's how CV has it as well (CV lists annuals as their own separate entry, not part of the actual series it belongs to) - you'd need to have it as 'Hulk Annual #001 (2014).cbz" and then Mylar will recognize it.

Mylar adds in the wording 'annual' to different parts of the GUI to help distinguish items, but the actual numbering is just a numeric.

**Comment by tjiddy** [comment]
You were right.  that fixed the issue.  thank you.
