### ISSUE TITLE
not downloading anymore 

### ISSUE THREAD

**Issue by dirtymurt** [evilhero/mylar#946]
getting this error

Timestamp   Level   Message
2015-02-17 00:45:48 ERROR   Uncaught exception: Traceback (most recent call last):
File "D:\GIT\mylar\mylar\logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "D:\GIT\mylar\mylar\webserve.py", line 1124, in retryissue
link = 'http://nzb.su/getnzb/' + str(id) + '.nzb&i=' + str(mylar.NZBSU_ID) + '&r=' + str(mylar.NZBSU_APIKEY)
AttributeError: 'module' object has no attribute 'NZBSU_ID'
2015-02-17 00:45:48 INFO    --Referencing : nzb.su @ 2015-02-15 22:54:57
2015-02-17 00:45:48 INFO    Located snatched download:
2015-02-17 00:45:48 INFO    Retrying : 479264
2015-02-17 00:45:48 INFO    ComicID:78550
2015-02-17 00:45:29 INFO    [ComicVine API] Comicvine API count now at : 0 / 400 in 6.43 minutes.

**Comment by evilhero** [comment]
Yes there's a git pull request for the fix.. It should be nzbsu_uid not nzbsu_id

**Comment by dirtymurt** [comment]
now getting this after the update

Uncaught exception: Traceback (most recent call last):
File "D:\GIT\mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "D:\GIT\mylar\mylar\webserve.py", line 1168, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True)
File "D:\GIT\mylar\mylar\search.py", line 1800, in searcher
notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
File "D:\GIT\mylar\mylar\search.py", line 1805, in notify_snatch
snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
Off a retry correct? 

Try downloading it normally (ie. Manual search or mark wanted). If it's a retry, I still need to address the year not being passed to the notifier script (that's why it's erroring)

**Comment by dirtymurt** [comment]
ahhh ok, thank you
