### ISSUE TITLE
Update Crashing?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#969]
I am stuck in the loop:
Click the update link
Mylar is updating...60 seconds
Web browser times out.
service start/restart/force-reload does nothing
server has to be rebooted to get mylar running again
update link reappears

What do? I forgot

**Comment by evilhero** [comment]
You probably modified a file (or something) which is causing it to hang. Check the log, it should say which files it's having problems updating or shutdown mylar, do a 'git stash' from within the mylar directory and then start up mylar and try update again.

**Comment by AtariBaby** [comment]
Here's what I see in terminal:
```
misterfantastic@dualboot:~/.mylar$ sudo service mylar start
Removing stale /var/run/mylar.pid
Starting mylar
misterfantastic@dualboot:~/.mylar$
```
There is no update to mylar.log from recent attempts. This was the last thing there:
```
27-Mar-2015 10:53:13 - INFO    :: CP Server Thread-5 : Retrieving latest version information from github
27-Mar-2015 10:53:13 - INFO    :: CP Server Thread-5 : Comparing currently installed version with latest github version
27-Mar-2015 10:53:14 - INFO    :: CP Server Thread-5 : New version is available. You are 1 commits behind
27-Mar-2015 10:53:26 - INFO    :: MAIN : Received signal: update
27-Mar-2015 10:53:31 - DEBUG   :: MAIN : [ComicVine API] ComicVine API Check Running...
27-Mar-2015 10:53:31 - DEBUG   :: MAIN : [ComicVine API] API Start Monitoring Time (~15mins): 2015-03-27 10:50:51
27-Mar-2015 10:53:31 - DEBUG   :: MAIN : [ComicVine API] Time now: 2015-03-27 10:53:31
27-Mar-2015 10:53:31 - INFO    :: MAIN : [ComicVine API] Comicvine API count now at : 0 / 400 in 2.67 minutes.
27-Mar-2015 10:53:31 - INFO    :: MAIN : Mylar is updating...
27-Mar-2015 10:53:31 - DEBUG   :: MAIN : Trying to execute: "git pull origin development" with shell in /home/misterfantastic/.mylar
27-Mar-2015 10:53:33 - DEBUG   :: MAIN : Git output: From https://github.com/evilhero/mylar
 * branch            development -> FETCH_HEAD
   052e6ec..cdc3e8a  development -> origin/development
Updating 052e6ec..cdc3e8a
Fast-forward
 data/css/style.css                                 |  20 -
 data/interfaces/default/comicdetails.html          |   4 +-
 data/interfaces/default/config.html                |   3 +-
 data/interfaces/default/css/style.css              | 391 +++++------
 data/interfaces/default/images/android.png         | Bin 0 -> 3139 bytes
 data/interfaces/default/importresults.html         |  54 +-
 data/interfaces/default/importresults_popup.html   |   2 +-
 data/interfaces/default/index.html                 |  12 +-
 data/interfaces/default/manage.html                |   3 +-
 data/interfaces/default/readinglist.html           | 287 ++++----
 data/interfaces/default/storyarc.html              | 149 ++++
 .../{readlist.html => storyarc_detail.html}        |  43 +-
 data/interfaces/default/upcoming.html              |  91 ++-
 mylar/PostProcessor.py                             |  44 +-
 mylar/__init__.py                                  | 287 ++++----
 mylar/cmtagmylar.py                                |   1 +
 mylar/cv.py                                        |  20 +-
 mylar/db.py                                        |  19 +-
 mylar/filechecker.py                               |   4 +-
 mylar/ftpsshup.py                                  | 139 +++-
 mylar/helpers.py                                   | 145 ++--
 mylar/importer.py                                  |  13 +-
 mylar/moveit.py                                    |  12 +-
 mylar/rsscheck.py                                  |   1 -
 mylar/search.py                                    | 151 +++--
 mylar/searchit.py                                  |   5 +-
 mylar/updater.py                                   | 219 ++++--
 mylar/versioncheck.py                              |   2 +-
 mylar/webserve.py                                  | 746 +++++++++++----------
 mylar/weeklypull.py                                | 254 +++++--
 mylar/weeklypullit.py                              |   1 +
 31 files changed, 1889 insertions(+), 1233 deletions(-)
 create mode 100644 data/interfaces/default/images/android.png
 create mode 100755 data/interfaces/default/storyarc.html
 rename data/interfaces/default/{readlist.html => storyarc_detail.html} (85%)

27-Mar-2015 10:53:33 - INFO    :: MAIN : Mylar is restarting...
27-Mar-2015 10:53:33 - INFO    :: MAIN : Restarting Mylar with ['/usr/bin/python', '/home/misterfantastic/.mylar/Mylar.py', '-q', '--nolaunch']
```
If I type "git stash" in mylar directory, I see
```
No local changes to save
```

**Comment by evilhero** [comment]
Try running it directly from the shell instead of as a service and see what messages occur.

**Comment by AtariBaby** [comment]
Thanks:
```
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/home/misterfantastic/.mylar/mylar/__init__.py", line 40, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search, PostProcessor, weeklypull, helpers, scheduler
  File "/home/misterfantastic/.mylar/mylar/rsscheckit.py", line 22, in <module>
    from mylar import logger, rsscheck, helpers
  File "/home/misterfantastic/.mylar/mylar/rsscheck.py", line 7, in <module>
    import ftpsshup
  File "/home/misterfantastic/.mylar/mylar/ftpsshup.py", line 3, in <module>
    import paramiko
ImportError: No module named paramiko
```

**Comment by evilhero** [comment]
Yeah two fixes went up in the last 10 minutes for that error and a subsequent one, both of which stop mylar from starting properly. 

You'll have to do a fresh git clone in your mylar directory (best to backup your config.ini and mylar.db just in case but it shouldn't hammer them) and pull it down so that you can get a clean copy.

**Comment by AtariBaby** [comment]
Back in business, thank you!
