### ISSUE TITLE
paramiko??

### ISSUE THREAD

**Issue by Rumtum** [evilhero/mylar#970]
After the latest update, I get the following error.

Do I need to install something else?

C:\Program Files (x86)\Mylar>"C:\Program Files (x86)\Python27\python.exe" mylar.
py
Traceback (most recent call last):
  File "mylar.py", line 26, in <module>
    import mylar
  File "C:\Program Files (x86)\Mylar\mylar\__init__.py", line 40, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit
, dbupdater, PostProcessor, helpers, scheduler #versioncheck, rsscheck, search,
PostProcessor, weeklypull, helpers, scheduler
  File "C:\Program Files (x86)\Mylar\mylar\rsscheckit.py", line 22, in <module>
    from mylar import logger, rsscheck, helpers
  File "C:\Program Files (x86)\Mylar\mylar\rsscheck.py", line 7, in <module>
    import ftpsshup
  File "C:\Program Files (x86)\Mylar\mylar\ftpsshup.py", line 3, in <module>
    import paramiko
ImportError: No module named paramiko

**Comment by evilhero** [comment]
Well Paramiko, but if you don't have a seedbox or want to use the new send to tablet option (android users only) then you don't need to install it.

Either way, the fix went up a few minutes ago - so you'll have to grab the newest version. Sorry, hit the commit button a few seconds too early ;)
