### ISSUE TITLE
Unable to Recreate Pull list

### ISSUE THREAD

**Issue by edru** [evilhero/mylar#980]
Browser generates this error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/jollyroger/ServerApps/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/jollyroger/ServerApps/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/jollyroger/ServerApps/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/jollyroger/ServerApps/Mylar/mylar/webserve.py", line 1614, in pullrecreate
    weeklypull.pullit(forcecheck)
  File "/home/jollyroger/ServerApps/Mylar/mylar/weeklypull.py", line 447, in pullit
    pullitcheck(forcecheck=forcecheck)
  File "/home/jollyroger/ServerApps/Mylar/mylar/weeklypull.py", line 787, in pullitcheck
    statusupdate = updater.upcoming_update(ComicID=ComicID, ComicName=ComicName, IssueNumber=ComicIssue, IssueDate=ComicDate, forcecheck=forcecheck)
  File "/home/jollyroger/ServerApps/Mylar/mylar/updater.py", line 357, in upcoming_update
    logger.fdebug('...Existing status: ' + og_status)
TypeError: cannot concatenate 'str' and 'NoneType' objects

Logs show nothing wrong and say the list was updated.

**Comment by evilhero** [comment]
Can you post the portion of the mylar.log file just prior to that error? At that stage, the status of the new issue shouldn't be None (it should be Wanted or Skipped at the very least if it's a new pull) - I can see why it would error, I just need to see the log so I can understand the exact reason why and fix it, el pronto ;)

**Comment by edru** [comment]
http://pastebin.com/RB0ufTRm

stopped Mylar, deleted logs, restarted Mylar, attempted to recreate pull list.

**Comment by evilhero** [comment]
Try manually refreshing the Convergence series in your watchlist. Then do a recreate pullist and see if that works. 

Looks like it was hitting the refresh limit on the series (it only does a refresh on a weekly match every 6hrs if required) and was erroring out due to in an invalid status - I'll have to look into this more but I think a manual refresh should straighten things out for you.

**Comment by edru** [comment]
I tried to refresh the lists, but then got this error:

Uncaught exception: Traceback (most recent call last):
File "/home/jollyroger/ServerApps/Mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/jollyroger/ServerApps/Mylar/mylar/updater.py", line 211, in dbUpdate
for ann in annualsnew:
UnboundLocalError: local variable 'annualsnew' referenced before assignment

**Comment by edru** [comment]
Just deleted all convergence related comics, then readded them. That seemed to do the trick.
