### ISSUE TITLE
Uncaugt exception in search

### ISSUE THREAD

**Issue by rupaschomaker** [evilhero/mylar#981]
```
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : integer value of issue we have found : 23100
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : [SEARCHER] entry[title]: Action.Comics.v2.023.1.(2013)..(Webrip).(The.Last.Kryptonian-DCP
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (\s): Action.Comics.v2.023.1.(2013)..(Webrip).(The.Last.Kryptonian-DCP
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (space to .): Action.Comics.v2.023.1.(2013)..(Webrip).(The.Last.Kryptonian-DCP
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : [SEARCHER] end nzbname: Action.Comics.v2.023.1.2013..Webrip.The.Last.Kryptonian-DCP
16-Apr-2015 10:21:25 - DEBUG   :: Thread-12 : nzbname used for post-processing:Action.Comics.v2.023.1.2013..Webrip.The.Last.Kryptonian-DCP
16-Apr-2015 10:21:26 - DEBUG   :: Thread-12 : nzo_info:{}
16-Apr-2015 10:21:26 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1406, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 206, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1285, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov)
  File "/volume1/@appstore/mylar/share/mylar/mylar/search.py", line 1668, in searcher
    filen = re.sub('.cbr', '', filen).strip()
  File "/usr/local/mylar/env/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

This causes the search thread to error out and no more processing happens so no downloads this week.

**Comment by rupaschomaker** [comment]
This leads to the link:

    http://www.usenet-crawler.com/getnzb/990b5f65468f640bc570719e0d234180.nzb&i=153294&r=21bf042bc96ed3da387f5e46be43f2e9

which turns out to be a link marked as spam by usenet-crawler so there is no corresponding nzb file to download.

**Comment by evilhero** [comment]
Ahh yeah that would do it. I'll have to add in an exception check there to catch the stray ones like that. I'll get it added for the next commit. 

Thanks for the error report and follow up solution!

**Comment by rupaschomaker** [comment]
I made that function fail the entry so that it would keep trying the other
hits. My change was quick and assumes you have fail processing turned on,
but worked well. I'm sure the right fix will come soon. I did add a log
entry for the link as well...

**Comment by evilhero** [comment]
Well I'm glad the failed processing is working, I use it on mine and haven't had too many problems with it running (and those that did happen, I obviously fixed lol). I do plan on making a Failed management section (or the like) as there's currently no way to unmark a failed download as good within mylar. 

Just curious for the nzb marked as spam, does it have a relevant x-header or something to distinguish it as spam vs not?

**Comment by rupaschomaker** [comment]
No, there was nothing usable in the header. Instead in my hack, if there
was no filename discoverable to just return mark as failed. The contents
are a HTML page with "marked as spam" or some crap like that.

**Comment by evilhero** [comment]
If you've already tested your hack/fix, if you want to share the code, I'll patch it up into mylar since I probably couldn't duplicate the problem very easily.

**Comment by rupaschomaker** [comment]
Try this one.  Note that in the case you don't have failed download handling, this returns sab-fail regardless of what your download provider is.  I'm pretty sure that is not a good assumption.

```
diff --git a/mylar/search.py b/mylar/search.py
index 29e8de5..cc55c28 100755
--- a/mylar/search.py
+++ b/mylar/search.py
@@ -1662,18 +1662,20 @@ def searcher(nzbprov, nzbname, comicinfo, link, IssueID, ComicID, tmpprov, direc
                        filen = item[item.index("filename=") + 9:].strip(';').strip('"')
         logger.fdebug('nzo_info:' + str(nzo_info))

-        #convert to a generic type of format to help with post-processing.
-        filen = re.sub('.cbr', '', filen).strip()
-        filen = re.sub('.cbz', '', filen).strip()
-        filen = re.sub("\&", 'and', filen)
-        filen = re.sub('[\,\:\?\'\(\)]', '', filen)
-
+        if filen is None:
+            logger.error('Unable to download nzb from link: ' + str(link))
+        else:
+            #convert to a generic type of format to help with post-processing.
+            filen = re.sub('.cbr', '', filen).strip()
+            filen = re.sub('.cbz', '', filen).strip()
+            filen = re.sub("\&", 'and', filen)
+            filen = re.sub('[\,\:\?\'\(\)]', '', filen)

-        if re.sub('.nzb','', filen.lower()).strip() != re.sub('.nzb','', nzbname.lower()).strip():
-            alt_nzbname = re.sub('.nzb','', filen).strip()
-            alt_nzbname = re.sub('[\s+]', ' ', alt_nzbname)
-            alt_nzbname = re.sub('[\s\_]', '.', alt_nzbname)
-            logger.info('filen: ' + alt_nzbname + ' -- nzbname: ' + nzbname + ' are not identical. Storing extra value as : ' + alt_nzbname)
+            if re.sub('.nzb','', filen.lower()).strip() != re.sub('.nzb','', nzbname.lower()).strip():
+                alt_nzbname = re.sub('.nzb','', filen).strip()
+                alt_nzbname = re.sub('[\s+]', ' ', alt_nzbname)
+                alt_nzbname = re.sub('[\s\_]', '.', alt_nzbname)
+                logger.info('filen: ' + alt_nzbname + ' -- nzbname: ' + nzbname + ' are not identical. Storing extra value as : ' + alt_nzbname)


     #check if nzb is in do not download list
@@ -1718,6 +1720,9 @@ def searcher(nzbprov, nzbname, comicinfo, link, IssueID, ComicID, tmpprov, direc

     if mylar.FAILED_DOWNLOAD_HANDLING:
         if nzbid is not None:
+            if filen is None:
+                return FailedMark(ComicID=ComicID, IssueID=IssueID, id=nzbid, nzbname=nzbname, prov=nzbprov)
+
             call_the_fail = Failed.FailedProcessor(nzb_name=nzbname, id=nzbid, issueid=IssueID, comicid=ComicID, prov=tmpprov)
             check_the_fail = call_the_fail.failed_check()
             if check_the_fail == 'Failed':
@@ -1726,6 +1731,9 @@ def searcher(nzbprov, nzbname, comicinfo, link, IssueID, ComicID, tmpprov, direc
                 #continue
             elif check_the_fail == 'Good':
                 logger.fdebug('[FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.')
+    else:
+        if filen is None:
+            return "sab-fail"

     logger.fdebug('issues match!')
     logger.info(u"Found " + ComicName + " (" + str(comyear) + ") issue: " + IssueNumber + " using " + str(tmpprov) )
```
