### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Aimhere2k** [evilhero/mylar#991]
Hi,

I'm running Mylar on a Synology Diskstation. It's the SynoCommunity package, where SynoCommunity says it's version v20140528-3.

Every once in awhile, when I've left it alone for some time, I come back and load up the web interface and find the following:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 74, in home
    comics = helpers.havetotals()
  File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 1125, in havetotals
    comiclist = myDB.select('SELECT * from comics order by ComicSortName COLLATE NOCASE')
  File "/volume1/@appstore/mylar/share/mylar/mylar/db.py", line 145, in select
    sqlResults = self.fetch(query, args).fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
```

No matter how much I try to refresh, the web interface won't load. I've also tried clearing my browser cache to no avail. I find I have to use Synology's Package Manager to stop Mylar, then restart it. After that, it seems to work again.

When this happens, I've looked at the Mylar logs in /usr/local/mylar/var/logs, but don't really know what I'm looking for. It appears Mylar is still processing stuff in the background (the timestamps are up-to-the-minute current), but I'm seeing messages like the following:

```
26-Apr-2015 08:10:29 - INFO    :: Thread-737 : RSS Feed Check was last run at : 2015-04-26 07:40:29
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : Updating RSS Run time to : 2015-04-26 08:10:29
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : [ComicVine API] ComicVine API Check Running...
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : [ComicVine API] API Start Monitoring Time (~15mins): 2015-04-
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : [ComicVine API] Time now: 2015-04-26 08:10:29
26-Apr-2015 08:10:29 - INFO    :: Thread-737 : [RSS] Initiating RSS Feed Check for NZB Providers.
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : newznab name:UsenetCrawler - enabled: 1
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : newznab name:Oznzb - enabled: 1
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : newznab name:nzb.is - enabled: 1
26-Apr-2015 08:10:29 - DEBUG   :: Thread-737 : there are : 4 nzb RSS search providers you have enabled.
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : 50 results from Experimental feed indexed.
26-Apr-2015 08:10:48 - DEBUG   :: Thread-737 : UsenetCrawler now being updated...
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : [UsenetCrawler] 0 entries indexed.
26-Apr-2015 08:10:48 - DEBUG   :: Thread-737 : Oznzb now being updated...
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : [Oznzb] 0 entries indexed.
26-Apr-2015 08:10:48 - DEBUG   :: Thread-737 : nzb.is now being updated...
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : [nzb.is] 0 entries indexed.
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : [RSS] RSS Feed Check/Update Complete
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : [RSS] Watchlist Check for new Releases
26-Apr-2015 08:10:48 - INFO    :: Thread-737 : Initiating RSS Search Scan at scheduled interval of 30 minute
26-Apr-2015 08:11:10 - WARNING :: Thread-737 : Database Error: database is locked
26-Apr-2015 08:11:11 - WARNING :: Thread-737 : Database Error: database is locked
26-Apr-2015 08:11:12 - WARNING :: Thread-737 : Database Error: database is locked
26-Apr-2015 08:11:13 - WARNING :: Thread-737 : Database Error: database is locked
26-Apr-2015 08:11:14 - WARNING :: Thread-737 : Database Error: database is locked
```

The "database error" messages are particularly concerning.

Any ideas why this is happening?

**Comment by evilhero** [comment]
I'll try and break this down for ya :
- the synopackage stuff just doesn't work usually. I have no affiliation with them, and haven't worked with them on stuff, but the last I checked the release they install by default is from early  2014 which is far outdated. Which means you have to update and then  switch branches (see next point). If it's working now, it seems something will end up not working because of how it's installed. 
- you're probably on the master branch, not the development  (development branch has the database locking issue fixed). 

Try to install mylar via git (as it was created for). I can then help troubleshoot more if you need it, but unless you're at least on the most stable branch (recent development), there's not much I can do.

**Comment by Aimhere2k** [comment]
Thanks for the reply. I found issue #354 on github (same info also on 
the Synology forums), and I am now running the development branch. We'll 
see how that goes...

Aimhere
