### ISSUE TITLE
Mylar home page misreporting number of comics in "Have" field as None

### ISSUE THREAD

**Issue by anxst** [evilhero/mylar#994]
On the Home page, I have a number of comics that are misreporting the number of comics as None out of ##, for example "None/40". All of them were comics that were scanned in on initial setup. All those added manually later don't have this issue. More than likely something caused the number field there to get filled in as a "None" type, but where on earth is it? How can I update it to be correct?

**Comment by evilhero** [comment]
Have you tried to manually refresh one of the series that is having the problem? Odds are that will fix it (it usually fixes most types of incomplete problems), and if it works you can then do a 'db Update active series' off the Manage /Advanced Options tab to do your entire watchlist. 

It's possible that comicvine was down, or it couldn't be reached somehow (or even your comicvine API key max was hit) and because of those things it wasn't able to fully refresh the series and None'd the total. It's kind of hard to say exactly what led to the problem, but the refresh should right the wrong. 

(you probably want to make sure you're on the development branch too prior to doing the update all option)

**Comment by anxst** [comment]
Attempts to manually refresh the series with the issue result in:

    Uncaught exception: Traceback (most recent call last):
    File "C:\mylar-master\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
    File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "C:\mylar-master\mylar\updater.py", line 195, in dbUpdate
    forceRescan(ComicID)
    File "C:\mylar-master\mylar\updater.py", line 927, in forceRescan
    if fcnew[som+1].isdigit():
    IndexError: list index out of range

**Comment by evilhero** [comment]
What is the series? (comicid if you have it)

It looks like the series has an issue that's a non-numeric and it's throwing things off, but I need to know the series to know exactly.

**Comment by anxst** [comment]
Action Comics v2 (2011) http://www.comicvine.com/action-comics/4050-42563/

**Comment by evilhero** [comment]
Try deleting the series and reading it again.. There's nothing abnormal about that series so it's probably something missing from the db for some reason.

**Comment by anxst** [comment]
Tried that earlier. Even with a mylar restart after delete prior to re-add, the db value of None seems to hang in there. Is there a way to clean the db after I remove the series?

**Comment by evilhero** [comment]
Ok so then it's not a data issue, but a parsing one.. What do the filenames look like in that folder? There's one it's getting stuck on in particular but you didn't paste that portion of the mylar.log file.

**Comment by anxst** [comment]
From the Logs webpage, we get:

    2015-04-28 06:30:39	ERROR	Uncaught exception: Traceback (most recent call last):
    File "C:\mylar-master\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
    File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "C:\mylar-master\mylar\updater.py", line 927, in forceRescan
    if fcnew[som+1].isdigit():
    IndexError: list index out of range
    2015-04-28 06:30:24	INFO	[FILE-RESCAN] Now checking files for Action Comics (2011) in    :Action Comics (2011)
    2015-04-28 06:30:11	INFO	[FILE-RESCAN] Now checking files for Action Comics (2011) in     F:\My Comics\DC Comics/Action Comics (2011)
    2015-04-28 06:30:11	INFO	I have added 0 new issues for this series that were not present before.
    2015-04-28 06:30:11	INFO	In the process of converting the data to CV, I changed the status of 45 issues.
    2015-04-28 06:30:02	INFO	returning to dbupdate module
    2015-04-28 06:30:02	INFO	Updating complete for: Action Comics
    2015-04-28 06:29:54	INFO	Now adding/updating issues for Action Comics
    2015-04-28 06:29:53	INFO	Successfully integrated 3 issues of Action Comics Annual to the series: Action Comics
    2015-04-28 06:29:51	INFO	Attempting to integrate Action Comics Annual (53508) to the existing series of Action Comics(2011)
    2015-04-28 06:29:50	INFO	Sucessfully retrieved issue details for Action Comics
    2015-04-28 06:29:47	INFO	Successfully retrieved cover for Action Comics
    2015-04-28 06:29:47	INFO	Image header check: jpeg
    2015-04-28 06:29:47	INFO	Directory (F:\My Comics\DC Comics/Action Comics (2011)) already exists! Continuing...
    2015-04-28 06:29:45	INFO	Successfully integrated 3 issues of Action Comics Annual to the series: Action Comics
    2015-04-28 06:29:44	INFO	Attempting to integrate Action Comics Annual (53508) to the existing series of Action Comics(2011)
    2015-04-28 06:29:43	INFO	Sucessfully retrieved details for Action Comics
    2015-04-28 06:29:43	INFO	Now adding/updating: Action Comics
    2015-04-28 06:29:42	INFO	[ComicVine API] Comicvine API count now at : 0 / 400 in 8.1 minutes.
    2015-04-28 06:29:42	INFO	[DIRECTORY-CHECK] Found comic directory: F:\My Comics\DC Comics/Action Comics (2011)
    2015-04-28 06:29:41	INFO	Starting update for 1 active comics
    2015-04-28 06:29:35	INFO	[FILE-RESCAN] Now checking files for Action Comics (2011) in F:\My Comics\DC Comics/Action Comics (2011)

But in the mylar.log file, there are no logs from today. They are all from yesterday. Does it stage the logs elsewhere before writing them to the mylar.log file?

**Comment by evilhero** [comment]
No, the logs get written to the file immediately. You're on Windows, so it's either you're getting a 'database locking error' somewhere or the log file isn't rolling over to the next file because it's being locked by windows. 

Both of these issues (and the error you originally posted about) have been addressed in the development branch of mylar, so you'll need to be on that branch or wait for it to be pushed to mylar (no eta of when that will be just yet).

**Comment by anxst** [comment]
Sorry, I see you did mention that earlier, I missed it. Now on Dev branch, a refresh gets me:

	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] subname no brackets: Action Comics #023.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [#] charpos: [14]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [.] charpos: [17]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Decimal check.
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : fndit: 17
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : isdigit1: 3
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : isdigit2: 1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] decimal issue detected.
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : as_start: 20 --- !!53508
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : as_start: 27 --- !!53508
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Extracted comicid for given annual : 53508
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] AS_Alt : ['Action Comics Annual']
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] watchcomic:Action Comics ..comparing to found file: Action Comics 023.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Complete matching list of names to this file [1] : ['Action Comics']
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] AS_Tuple : [{'AS_Alternate': 'Action Comics Annual', 'ComicID': u'53508'}]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Action Comics Annual comparing to Action Comics 023.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Action Comics - watchlist match on : F:\My Comics\DC Comics/Action Comics (2011)\Action Comics #023.1.cbr
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] cchk is : Action Comics
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] we should remove 2 characters
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] detected 1 special characters
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : i,j:0,17
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : 19 - subname: Action Comics 023.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : digitchk: 3.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] special character appears outside of title - ignoring @ position: 17
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] nonocount [1] cchk [Action Comics] length [13]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] final jtd_len to prune [13]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] before title removed from FILENAME [Action Comics #023.1.cbr]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] after title removed from FILENAME [ #023.1.cbr]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] creating just the digits using SUBNAME, pruning first [13] chars from [Action Comics 023.1]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] after title removed from SUBNAME [023.1]
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Possible issue title is : 3.1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : st:1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : st_d:3
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : st_e:1
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] This is a decimal issue.
	28-Apr-2015 17:14:28 - DEBUG   :: Thread-14 : [FILECHECKER] Invalid character found in filename after item removal - cannot find issue # with this present. Temporarily removing it from the comparison to be able to proceed.
	28-Apr-2015 17:14:28 - ERROR   :: Thread-14 : Uncaught exception: Traceback (most recent call last):
	  File "C:\mylar-master\mylar\logger.py", line 159, in new_run
		old_run(*args, **kwargs)
	  File "C:\Python27\lib\threading.py", line 763, in run
		self.__target(*self.__args, **self.__kwargs)
	  File "C:\mylar-master\mylar\updater.py", line 260, in dbUpdate
		forceRescan(ComicID)
	  File "C:\mylar-master\mylar\updater.py", line 754, in forceRescan
		tmpval = filechecker.listFiles(dir=rescan['ComicLocation'], watchcomic=rescan['ComicName'], Publisher=rescan['ComicPublisher'], AlternateSearch=altnames)
	  File "C:\mylar-master\mylar\filechecker.py", line 763, in listFiles
		justthedigits = justthedigits_1.split(' ', 1)[1]
	IndexError: list index out of range

So it appears to be issue 23.1, which it sees as a decimal issue. Unsure why it's still unhappy.

**Comment by evilhero** [comment]
Looks like that's just due to the most recent development commit. I'll have to get it fixed when I can get to a machine later tonight.

**Comment by anxst** [comment]
And sure enough, latest commit fixes the issue. Thanks so much for being super communicative on this, and for working so hard on this program as a whole!
