### ISSUE TITLE
Issue with my Pull List

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#997]
I was checking to see why none of my comics were downloading and i noticed that it was only checking for the first 2 things on my weekly pull list. I tried recreating the pull list but it continued to do the same thing so I went to the wanted tab to do a force search and that's when it spit out the error below.  

ERROR   Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "C:\Mylar\mylar\search.py", line 1406, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "C:\Mylar\mylar\search.py", line 206, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Mylar\mylar\search.py", line 1285, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov)
File "C:\Mylar\mylar\search.py", line 1679, in searcher
filen = re.sub('.cbr', '', filen).strip()
File "C:\Python27\lib\re.py", line 151, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by evilhero** [comment]
I think you might have an extra Newznab provider enabled within your configuration, or an empty one in your provider_order line in the config.ini. 

If it's the config.ini one, delete the entire line from the config.ini (male sure mylar is shutdown before editing) , save it and start up mylar to see if that resolves it. 

If it doesn't, and the first option isn't valid, if you could post the mylar.log showing the lines previously to the error you posted, it would be helpful in figuring things out.

**Comment by wraith1385** [comment]
I had seen that solution in another issue on here and so I tried it already, but it didn't fix it.  This is the provider order from config.ini

provider_order = 0, nzb.su, 1, dognzb

Here are several lines of the log before the error:

2015-04-29 23:16:48 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using dognzb [RSS]
2015-04-29 23:16:48 	INFO 	Could not find Issue 40 of Batman(2011) using nzb.su
2015-04-29 23:16:48 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using nzb.su [RSS]
2015-04-29 23:16:48 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 23:16:48 	INFO 	Issue Title given as : endgame, part six
2015-04-29 23:16:48 	INFO 	Finished searching via :api. Issue not found - status kept as Wanted.
2015-04-29 23:16:48 	INFO 	Could not find Issue 4 of Convergence(2015) using dognzb
2015-04-29 23:15:46 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:14:43 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:13:39 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:13:39 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using dognzb
2015-04-29 23:13:39 	INFO 	Could not find Issue 4 of Convergence(2015) using nzb.su
2015-04-29 23:12:39 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:11:39 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:10:38 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-04-29 23:10:38 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using nzb.su
2015-04-29 23:10:38 	INFO 	Finished searching via :rss. Issue not found - status kept as Wanted.
2015-04-29 23:10:38 	INFO 	Could not find Issue 4 of Convergence(2015) using dognzb
2015-04-29 23:10:30 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using dognzb [RSS]
2015-04-29 23:10:30 	INFO 	Could not find Issue 4 of Convergence(2015) using nzb.su
2015-04-29 23:10:30 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using nzb.su [RSS]
2015-04-29 23:10:30 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 23:10:29 	INFO 	Issue Title given as : None
2015-04-29 23:10:29 	INFO 	Initiating Search scan at requested interval of 360 minutes.
2015-04-29 22:55:34 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using dognzb [RSS]
2015-04-29 22:55:34 	INFO 	Could not find Issue 40 of Batman(2011) using nzb.su
2015-04-29 22:55:34 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using nzb.su [RSS]
2015-04-29 22:55:34 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 22:55:34 	INFO 	Issue Title given as : endgame, part six
2015-04-29 22:55:34 	INFO 	Finished searching via :rss. Issue not found - status kept as Wanted.
2015-04-29 22:55:34 	INFO 	Could not find Issue 4 of Convergence(2015) using dognzb
2015-04-29 22:55:25 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using dognzb [RSS]
2015-04-29 22:55:25 	INFO 	Could not find Issue 4 of Convergence(2015) using nzb.su
2015-04-29 22:55:25 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using nzb.su [RSS]
2015-04-29 22:55:25 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 22:55:25 	INFO 	Issue Title given as : None
2015-04-29 22:55:25 	INFO 	Initiating Search Scan at scheduled interval of 30 minutes.
2015-04-29 22:55:25 	INFO 	[RSS] Watchlist Check for new Releases
2015-04-29 22:55:25 	INFO 	[RSS] RSS Feed Check/Update Complete
2015-04-29 22:55:25 	INFO 	[RSS] 25 entries have been indexed and are now going to be stored for caching.
2015-04-29 22:55:24 	INFO 	[RSS] (dognzb) 25 entries indexed.
2015-04-29 22:55:24 	INFO 	[RSS] (nzb.su) 0 entries indexed.
2015-04-29 22:55:21 	INFO 	[RSS] Initiating RSS Feed Check for NZB Providers.
2015-04-29 22:55:21 	INFO 	RSS Feed Check was last run at : 2015-04-29 22:25:20
2015-04-29 22:54:51 	INFO 	delaying startup thread for 30 seconds to avoid locks.
2015-04-29 22:47:19 	INFO 	Finished checking for comics on my watchlist.
2015-04-29 22:47:12 	INFO 	Checking the Weekly Releases list for comics I'm watching...
2015-04-29 22:47:12 	INFO 	Weekly Pull List successfully loaded.
2015-04-29 22:47:06 	INFO 	Populating the NEW Weekly Pull list into Mylar.
2015-04-29 22:47:06 	INFO 	Preparing to update to the new listing.
2015-04-29 22:47:06 	INFO 	[PULL-LIST] Populating & Loading pull-list data from file
2015-04-29 22:47:06 	INFO 	Weekly pull list present - checking if it's up-to-date..
2015-04-29 22:47:06 	INFO 	Deleted existed pull-list data. Recreating Pull-list...
2015-04-29 22:47:06 	INFO 	Correcting Null entries that make the main page break on startup.
2015-04-29 22:47:06 	INFO 	Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
2015-04-29 22:47:06 	INFO 	Populating Custom Exception listings into Mylar....
2015-04-29 22:47:06 	INFO 	Populating Base Exception listings into Mylar....
2015-04-29 22:25:32 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using dognzb [RSS]
2015-04-29 22:25:32 	INFO 	Could not find Issue 40 of Batman(2011) using nzb.su
2015-04-29 22:25:32 	INFO 	Shhh be very quiet...I'm looking for Batman issue: 40 (2015) using nzb.su [RSS]
2015-04-29 22:25:32 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 22:25:32 	INFO 	Issue Title given as : endgame, part six
2015-04-29 22:25:32 	INFO 	Finished searching via :rss. Issue not found - status kept as Wanted.
2015-04-29 22:25:32 	INFO 	Could not find Issue 4 of Convergence(2015) using dognzb
2015-04-29 22:25:23 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using dognzb [RSS]
2015-04-29 22:25:23 	INFO 	Could not find Issue 4 of Convergence(2015) using nzb.su
2015-04-29 22:25:23 	INFO 	Shhh be very quiet...I'm looking for Convergence issue: 4 (2015) using nzb.su [RSS]
2015-04-29 22:25:23 	INFO 	search provider order is ['nzb.su', 'dognzb']
2015-04-29 22:25:23 	INFO 	Issue Title given as : None
2015-04-29 22:25:23 	INFO 	Initiating Search Scan at scheduled interval of 30 minutes.
2015-04-29 22:25:23 	INFO 	[RSS] Watchlist Check for new Releases
2015-04-29 22:25:23 	INFO 	[RSS] RSS Feed Check/Update Complete
2015-04-29 22:25:22 	INFO 	[RSS] 25 entries have been indexed and are now going to be stored for caching.
2015-04-29 22:25:22 	INFO 	[RSS] (dognzb) 25 entries indexed.
2015-04-29 22:25:22 	INFO 	[RSS] (nzb.su) 0 entries indexed.
2015-04-29 22:25:20 	INFO 	[RSS] Initiating RSS Feed Check for NZB Providers.

**Comment by wraith1385** [comment]
For some reason it wasn't logging in the actual log so I recreated the error:  

30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Entry: Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Cleantitle: batman 040 2015 2 covers digital zone-empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : detected invalid nzb filename - attempting to detect year to continue
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Cleantitle: batman 040 (2015)  2 covers digital zone-empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : 0. Bracket Word: batman 040 
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Comic: batman 040 
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : UseFuzzy is  : None
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : ComVersChk : 2
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : 1. Bracket Word: 2015
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : year detected: 2015
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : year looking for: 2015
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : 2015 - right years match baby!
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : 2. Bracket Word:   2 covers digital zone-empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : covers detected:   2 covers digital zone-empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Scanner detected:   2 covers digital zone-empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : original nzb comic and issue: batman 040 
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : adjusted nzb comic and issue: batman 040 
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : adjusting from: batman 040  to: 040
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : ['batman', '040'] nzb series word count: 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : ['batman'] watchlist word count: 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : splitst : 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : len-watchcomic : 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : length match..proceeding
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : search-length: 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : Watchlist-length: 1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : splitit: batman
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : scount : 0
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : 0 Comparing: batman .to. batman
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : word matched on : batman
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : scount:1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : splitit-len:1
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : we got 100.0 percent.
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : it's a go captain... - we matched 100.0%!
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : this should be a match!
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : issue we are looking for is : 40
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : integer value of issue we are looking for : 40000
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : issue we found for is : 040
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : integer value of issue we have found : 40000
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : [SEARCHER] entry[title]: Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (\s): Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : [SEARCHER] nzbname (space to .): Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : [SEARCHER] end nzbname: Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:30 - DEBUG   :: Thread-12 : nzbname used for post-processing:Batman.040.2015.2.covers.Digital.Zone-Empire
30-Apr-2015 06:35:31 - DEBUG   :: Thread-12 : nzo_info:{'length': 1420}
30-Apr-2015 06:35:31 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\search.py", line 1406, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "C:\Mylar\mylar\search.py", line 206, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Mylar\mylar\search.py", line 1285, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov)
  File "C:\Mylar\mylar\search.py", line 1679, in searcher
    filen = re.sub('.cbr', '', filen).strip()
  File "C:\Python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by ztaylor38** [comment]
I'm having the same issue. I verified that only sabnzbd is set up. 

Mylar isn't downloading any of this weeks comics and I'm getting the same error shown above. Things have been acting kind of hit or miss with mylar, in terms of getting books, the past week or two. 

my log is listed here: pastebin.com/g3mXxukw

**Comment by evilhero** [comment]
@ztaylor38: Actually your issue is different than OP. Your error message says that it can't write to your cache directory in order to save the file required by mylar to populate the weekly pull-list:

IOError: [Errno 13] Permission denied: u'/opt/Mylar/cache/newreleases.txt'

Make sure the perms are correct on that folder and/or the user running mylar has access to it.

**Comment by ztaylor38** [comment]
since my issues were different i started a new thread. sorry for accidentally hijacking this one.

https://github.com/evilhero/mylar/issues/999

**Comment by wraith1385** [comment]
I'm using nzb.su and dognzb.

**Comment by evilhero** [comment]
Seems to be the consensus, both are being really flakey from what I understand (I know dog is currently off line doing upgrades too). 

I have a fix going up later today that will address it, but in the meantime you can try to enable failed download handling, restart mylar and see if that fixes things (it just marks things it can't download as Failed and won't try to get that particular file from that specific provider in the future).

**Comment by wraith1385** [comment]
Is the failure for the one file causing it to not bother to look for the rest? There are several other items on my pull list but it stops trying when it gets to Batman.

**Comment by evilhero** [comment]
It's actually the traceback error that's causing the problem, but if you don't have failed handling enabled it won't bypass the traceback error and continue looking for issues. With it enabled, it passes it to the failed download handler which marks it as a bad download and then continues searching.

**Comment by wraith1385** [comment]
Far be it from me to ever question a dev.  That worked and it's currently downloading my other issues.  Thanks for your help.
